(in-package #:sgeo.editor)

(defun %command-object (editor designator)
  (let ((object (cond ((typep designator 'sgeo.scene:scene-object) designator)
                      (designator (sgeo.scene:find-object (editor-world editor) designator))
                      (t (sgeo.scene:world-selection (editor-world editor))))))
    (unless (and object (eq (sgeo.scene:scene-object-world object) (editor-world editor)))
      (error 'sgeo.core:validation-error :context "comando do editor" :message "Selecione um objeto da cena."))
    object))

(defun %command-mesh (object)
  (unless (and (typep object 'sgeo.scene:mesh-object)
               (typep (sgeo.scene:mesh-object-geometry object) 'sgeo.geometry:half-edge-mesh))
    (error 'sgeo.core:validation-error :context "modelagem" :message "A operação requer uma malha half-edge."))
  (sgeo.scene:mesh-object-geometry object))

(defun %command-handle (editor mesh kind index)
  (or (if index
          (find index (ecase kind
                        (:vertex (sgeo.geometry:mesh-vertices mesh))
                        (:edge (sgeo.geometry:mesh-edges mesh))
                        (:face (sgeo.geometry:mesh-faces mesh))) :key #'sgeo.geometry:handle-index)
          (find kind (editor-elements editor) :key #'sgeo.geometry:handle-kind))
      (error 'sgeo.core:validation-error :context "seleção geométrica" :message "Selecione um elemento compatível.")))

(defun %api-object-id (editor value accessor)
  (let ((object (find-if (lambda (object)
                           (and (typep object 'sgeo.scene:mesh-object) (eq value (funcall accessor object))))
                         (editor-objects editor))))
    (unless object (error "A referência não pertence à cena editada."))
    (sgeo.core:object-id object)))

(defun %encode-command-value (editor value)
  "Registra referências por identidades e índices, sem gravar handles transitórios."
  (typecase value
    (string (list :literal (copy-seq value)))
    (sgeo.scene:world (list :world))
    (sgeo.scene:scene-object (list :object (sgeo.core:object-id value)))
    ((or sgeo.geometry:half-edge-mesh sgeo.geometry:triangle-mesh)
     (list :geometry (%api-object-id editor value #'sgeo.scene:mesh-object-geometry)))
    (sgeo.scene:simple-material (list :material (%api-object-id editor value #'sgeo.scene:mesh-object-material)))
    (sgeo.geometry:mesh-handle
     (let* ((object (find-if (lambda (object)
                              (and (typep object 'sgeo.scene:mesh-object)
                                   (= (sgeo.core:object-id (sgeo.scene:mesh-object-geometry object))
                                      (sgeo.geometry:handle-mesh-id value)))) (editor-objects editor))))
       (unless object (error "O handle não pertence à cena editada."))
       (list :handle (sgeo.core:object-id object) (sgeo.geometry:handle-kind value) (sgeo.geometry:handle-index value))))
    (sgeo.math:quaternion (list :quaternion (coerce (sgeo.math::quaternion-data value) 'list)))
    (cons (list :list (mapcar (lambda (item) (%encode-command-value editor item)) value)))
    (vector (list :vector (map 'list (lambda (item) (%encode-command-value editor item)) value)))
    (otherwise (list :literal value))))

(defun %decode-command-value (editor encoded)
  (ecase (first encoded)
    (:world (editor-world editor))
    (:literal (second encoded))
    (:object (%command-object editor (second encoded)))
    (:geometry (sgeo.scene:mesh-object-geometry (%command-object editor (second encoded))))
    (:material (sgeo.scene:mesh-object-material (%command-object editor (second encoded))))
    (:quaternion (apply #'sgeo.math:make-quaternion (second encoded)))
    (:list (mapcar (lambda (item) (%decode-command-value editor item)) (second encoded)))
    (:vector (map 'vector (lambda (item) (%decode-command-value editor item)) (second encoded)))
    (:handle (%command-handle editor (%command-mesh (%command-object editor (second encoded)))
                              (third encoded) (fourth encoded)))))

(defun %api-history-step (editor function name arguments)
  (let ((encoded (mapcar (lambda (value) (%encode-command-value editor value)) arguments)))
    (call-with-edit-transaction editor (format nil "~S" name) (lambda () (apply function arguments))
       :name :api :arguments (list :function name :arguments encoded)
       :form `(sgeo.editor:execute-editor-command sgeo.editor:*editor* :api
                :function ',name :arguments ',encoded))))

(defun %execute-model-command (editor name arguments)
  (let* ((object (unless (member name '(:create :camera)) (%command-object editor (getf arguments :object))))
         (index (getf arguments :index))
         (value (or (getf arguments :value) (getf arguments :position))))
    (case name
      (:create
       (let* ((kind (or (getf arguments :kind) :box))
              (label (or (getf arguments :name) (format nil "~A ~D" kind (sgeo.core:make-object-id))))
              (parameters (copy-list (getf arguments :parameters)))
              (constructor (ecase kind (:box #'sgeo.geometry:make-half-edge-box) (:sphere #'sgeo.geometry:make-sphere)
                             (:cylinder #'sgeo.geometry:make-cylinder) (:grid #'sgeo.geometry:make-grid)
                             (:torus #'sgeo.geometry:make-torus)))
              (mesh (apply constructor :name label parameters))
              (created (sgeo.scene:make-mesh-object mesh :name label)))
         (sgeo.scene:add-to-world (editor-world editor) created)
         (editor-select editor created) created))
      (:delete (sgeo.scene:remove-from-world (editor-world editor) object)
               (editor-select editor nil))
      (:rename (setf (sgeo.core:object-name object) (getf arguments :name)))
      (:position (sgeo.scene:set-position object value))
      (:translate (sgeo.scene:translate object (getf arguments :delta)))
      (:rotate (sgeo.scene:rotate object (getf arguments :delta)))
      (:scale (sgeo.scene:set-scale object value))
      (:reparent (sgeo.scene:reparent object (if (getf arguments :parent)
                                                (%command-object editor (getf arguments :parent))
                                                (sgeo.scene:world-root (editor-world editor)))
                                           :keep-world-transform (getf arguments :keep-world)))
      (:material
       (let ((material (sgeo.scene:mesh-object-material object)))
         (when (getf arguments :color) (sgeo.scene:set-material-color material (getf arguments :color)))
         (when (member :wireframe-p arguments)
           (sgeo.scene:set-material-wireframe material (getf arguments :wireframe-p))) material))
      (:move-vertex (let ((mesh (%command-mesh object)))
                      (sgeo.geometry:set-vertex-position mesh (%command-handle editor mesh :vertex index)
                                                         (getf arguments :position))))
      (:split (let ((mesh (%command-mesh object)))
                (let ((vertex (sgeo.geometry:split-edge mesh (%command-handle editor mesh :edge index)
                                                      :parameter (getf arguments :parameter 0.5d0))))
                  (setf (editor-elements editor) (list vertex)
                        (editor-selection-mode editor) :vertex) vertex)))
      (:collapse (let ((mesh (%command-mesh object)))
                   (prog1 (sgeo.geometry:collapse-edge mesh (%command-handle editor mesh :edge index)
                            :keep (when (getf arguments :keep) (%command-handle editor mesh :vertex (getf arguments :keep)))
                            :position (getf arguments :position))
                     (setf (editor-elements editor) nil))))
      (:extrude
       (let* ((mesh (%command-mesh object))
              (indices (getf arguments :indices))
              (faces (if indices (mapcar (lambda (i) (%command-handle editor mesh :face i)) indices)
                         (if index (list (%command-handle editor mesh :face index))
                             (remove-if-not (lambda (handle) (eq :face (sgeo.geometry:handle-kind handle)))
                                            (editor-elements editor))))))
         (unless faces (error "Selecione uma face ou região antes da extrusão."))
         (setf (editor-elements editor)
               (sgeo.geometry:extrude-face-region mesh faces :distance (getf arguments :distance 0.3d0)
                                                     :offset (getf arguments :offset)))))
      (:camera
       (let ((camera (sgeo.scene:world-camera (editor-world editor))))
         (ecase (getf arguments :field)
           (:fov (setf (sgeo.scene:camera-fov camera) value))
           (:near (setf (sgeo.scene:camera-near camera) value))
           (:far (setf (sgeo.scene:camera-far camera) value))
           (:orthographic-height (sgeo.scene:set-camera-projection camera (sgeo.scene:camera-projection-mode camera) :height value)))))
      (otherwise (error "Comando de modelagem desconhecido: ~S" name)))))

(defun execute-editor-command (editor name &rest arguments)
  "Executa o mesmo comando usado por menus, inspector, gizmos e scripts."
  (call-in-editor editor
    (lambda ()
      (case name
        (:undo (undo-edit editor)) (:redo (redo-edit editor))
        (:play (%ensure-timeline-selection editor)
               (when (editor-animation-player editor)
                 (setf (sgeo.animation:player-playing-p (editor-animation-player editor)) t))
               (setf (editor-playing-p editor) t))
        (:pause (when (editor-animation-player editor)
                  (setf (sgeo.animation:player-playing-p (editor-animation-player editor)) nil))
                (setf (editor-playing-p editor) nil))
        (:animation-select (select-animation-clip editor (getf arguments :clip)))
        (:animation-seek (scrub-animation editor (getf arguments :time)))
        (:animation-create (apply #'create-editor-animation editor arguments))
        (:animation-record (apply #'add-animation-key editor arguments))
        (:animation-delete (apply #'delete-animation-key editor arguments))
        (:animation-move (move-animation-key editor (getf arguments :time)
                                            :index (or (getf arguments :index) (editor-animation-key editor))))
        (:import-gltf (import-editor-gltf editor (getf arguments :path)))
        (:export-gltf (export-editor-gltf editor (getf arguments :path) :binary (getf arguments :binary)))
        (:step (advance-editor-time editor (getf arguments :dt (/ 1d0 60d0)) :force t))
        (:time-scale (setf (editor-time-scale editor)
                           (%editor-time-number (getf arguments :value) t)))
        (:view (set-editor-view editor (getf arguments :view)))
        (:layout (set-editor-layout editor (getf arguments :layout)))
        (:tool (let ((tool (getf arguments :tool)))
                 (unless (member tool '(:translate :rotate :scale)) (error "Ferramenta desconhecida."))
                 (setf (editor-tool editor) tool)))
        (:selection-mode (let ((mode (getf arguments :mode)))
                           (unless (member mode '(:object :vertex :edge :face :region)) (error "Modo de seleção desconhecido."))
                           (setf (editor-selection-mode editor) mode (editor-elements editor) nil)))
        (:save (let ((path (or (getf arguments :path) (editor-scene-path editor))))
                 (sgeo.serialization:save-world (editor-world editor) path)
                 (setf (editor-scene-path editor) (namestring (pathname path))
                       (editor-status editor) (format nil "Saved: ~A" path))))
        (:open (let* ((path (or (getf arguments :path) (editor-scene-path editor)))
                      (loaded (sgeo.serialization:load-world path)))
                 (setf (sgeo.scene:world-running-p loaded)
                       (sgeo.scene:world-running-p (editor-world editor))
                       (sgeo.scene:world-running-p (editor-world editor)) nil)
                 (setf (editor-world editor) loaded (editor-scene-path editor) (namestring (pathname path))
                       (editor-undo-stack editor) nil (editor-redo-stack editor) nil
                       (editor-elements editor) nil (editor-selection-mode editor) :object
                       (editor-inspected editor) (sgeo.scene:world-root loaded)
                       (%inspect-stack editor) nil (editor-time editor) 0d0 (editor-playing-p editor) nil
                       (editor-animation-clip editor) nil (editor-animation-track editor) nil
                       (editor-animation-key editor) nil (editor-animation-player editor) nil
                       (editor-status editor) (format nil "Opened: ~A" path)
                       sgeo:*world* loaded sgeo:*selection* (sgeo.scene:world-selection loaded)) loaded))
        (:api (let ((function (getf arguments :function)))
                (call-with-edit-transaction editor (format nil "~S" function)
                  (lambda () (apply (fdefinition function)
                                     (mapcar (lambda (value) (%decode-command-value editor value))
                                             (getf arguments :arguments))))
                  :name name :arguments arguments)))
        (otherwise
         (let* ((arguments (copy-list arguments))
                (object (unless (member name '(:create :camera)) (%command-object editor (getf arguments :object)))))
           (when object (setf (getf arguments :object) (sgeo.core:object-id object)))
           (when (getf arguments :parent)
             (setf (getf arguments :parent) (sgeo.core:object-id (%command-object editor (getf arguments :parent)))))
           (when (and (member name '(:move-vertex :split :collapse :extrude))
                      (not (getf arguments :index)) (not (getf arguments :indices)) (editor-elements editor))
             (if (eq name :extrude)
                 (setf (getf arguments :indices) (mapcar #'sgeo.geometry:handle-index (editor-elements editor)))
                 (setf (getf arguments :index) (sgeo.geometry:handle-index (first (editor-elements editor))))))
           (call-with-edit-transaction editor (string-capitalize (symbol-name name))
             (lambda () (%execute-model-command editor name arguments))
             :name name :arguments arguments
             :form `(sgeo.editor:execute-editor-command sgeo.editor:*editor* ',name ,@(loop for (key value) on arguments by #'cddr
                                                                                        append (list key `(quote ,value)))))))))))

(defun replay-editor-command (editor command)
  "Reexecuta argumentos registrados contra os objetos atuais da cena."
  (unless (command-name command) (error "A transação manual não possui comando para replay."))
  (apply #'execute-editor-command editor (command-name command) (command-arguments command)))
