(in-package #:sgeo.editor)

(defstruct (%editor-view-frame (:constructor %make-editor-view-frame))
  mode eye target forward right up fov near far extent)

(defun %editor-world-meshes (world)
  (labels ((walk (object visible-enabled-p)
             (let ((active (and visible-enabled-p
                                (sgeo.scene:scene-object-visible-p object)
                                (sgeo.scene:scene-object-enabled-p object))))
               (append (when (and active (typep object 'sgeo.scene:mesh-object))
                         (list object))
                       (mapcan (lambda (child) (walk child active))
                       (sgeo.scene:scene-object-children object))))))
    (walk (sgeo.scene:world-root world) t)))

(defun %editor-visible-bounds (world)
  (let ((minimum nil) (maximum nil))
    (dolist (object (%editor-world-meshes world))
      (let* ((data (sgeo.scene:render-data-for-object object))
             (positions (sgeo.geometry:render-mesh-positions data))
             (matrix (sgeo.scene:world-transform object)))
        (loop for offset from 0 below (length positions) by 3
              for point = (sgeo.math:transform-point
                           matrix
                           (sgeo.math:make-vec3 (aref positions offset)
                                                (aref positions (1+ offset))
                                                (aref positions (+ offset 2))))
              do (unless minimum
                   (setf minimum (copy-seq point) maximum (copy-seq point)))
                 (dotimes (axis 3)
                   (setf (aref minimum axis) (min (aref minimum axis) (aref point axis))
                         (aref maximum axis) (max (aref maximum axis) (aref point axis)))))))
    (if minimum
        (let ((center (sgeo.math:v* 0.5d0 (sgeo.math:v+ minimum maximum)))
              (extent (loop for axis below 3 maximize (- (aref maximum axis) (aref minimum axis)))))
          (values center (max 1d-4 (* 1.2d0 extent))))
        (values (sgeo.scene:camera-target (sgeo.scene:world-camera world)) 6d0))))

(defun %canonical-view (view)
  (ecase view
    (:front (values (sgeo.math:make-vec3 0d0 0d0 -1d0)
                    (sgeo.math:make-vec3 0d0 1d0 0d0)))
    (:top (values (sgeo.math:make-vec3 0d0 -1d0 0d0)
                  (sgeo.math:make-vec3 0d0 0d0 -1d0)))
    (:side (values (sgeo.math:make-vec3 -1d0 0d0 0d0)
                   (sgeo.math:make-vec3 0d0 1d0 0d0)))) )

(defun editor-view-camera (world view &key extent)
  "Configura a câmera compartilhada do mundo para uma vista ortográfica ou perspectiva."
  (sgeo.scene:with-world-lock (world)
    (let ((camera (sgeo.scene:world-camera world)))
      (ecase view
        (:perspective
         (sgeo.scene:set-camera-projection camera :perspective))
        ((:front :top :side)
         (multiple-value-bind (center default-extent) (%editor-visible-bounds world)
           (let ((height (or extent default-extent)))
             (unless (and (realp height) (> height 0))
               (error 'sgeo.core:validation-error :context "extensão da vista"
                      :message "A extensão ortográfica precisa ser positiva."))
             (multiple-value-bind (forward up) (%canonical-view view)
               (let ((distance (max 10d0 (* 4d0 height))))
                 (sgeo.scene:set-camera-projection camera :orthographic :height height)
                 (sgeo.scene:set-camera-frame camera
                                              (sgeo.math:v- center (sgeo.math:v* distance forward))
                                              center up)))))))
      camera)))

(defun %editor-view-frame (world view extent)
  (let* ((camera (sgeo.scene:world-camera world))
         (mode (or view (sgeo.scene:camera-projection-mode camera)))
         (target (if (member view '(:front :top :side))
                     (nth-value 0 (%editor-visible-bounds world))
                     (sgeo.scene:camera-target camera))))
    (if (or (null view) (eq mode :perspective))
        (let* ((eye (sgeo.scene:camera-eye camera))
               (forward (sgeo.math:normalize (sgeo.math:v- target eye)))
               (up (sgeo.math:normalize
                    (sgeo.math:transform-direction (sgeo.scene:world-transform camera)
                                                   (sgeo.scene:camera-up camera))))
               (right (sgeo.math:normalize (sgeo.math:cross forward up)))
               (actual-up (sgeo.math:cross right forward)))
          (%make-editor-view-frame :mode mode :eye eye :target target
                                   :forward forward :right right :up actual-up
                                   :fov (sgeo.scene:camera-fov camera)
                                   :near (sgeo.scene:camera-near camera)
                                   :far (sgeo.scene:camera-far camera)
                                   :extent (sgeo.scene:camera-orthographic-height camera)))
        (let ((ortho-height (or extent
                                (if (eq mode :orthographic)
                                    (sgeo.scene:camera-orthographic-height camera)
                                    (nth-value 1 (%editor-visible-bounds world)))))
              (forward nil) (up nil))
          (multiple-value-setq (forward up) (%canonical-view mode))
          (let* ((right (sgeo.math:normalize (sgeo.math:cross forward up)))
                 (actual-up (sgeo.math:cross right forward))
                 (distance (max 10d0 (* 4d0 ortho-height)))
                 (eye (sgeo.math:v- target (sgeo.math:v* distance forward))))
            (%make-editor-view-frame :mode :orthographic :eye eye :target target
                                     :forward forward :right right :up actual-up
                                     :near (sgeo.scene:camera-near camera)
                                     :far (sgeo.scene:camera-far camera)
                                     :extent ortho-height))))))

(defun %project-with-frame (frame point width height)
  (unless (and (realp width) (realp height) (> width 0) (> height 0))
    (error 'sgeo.core:validation-error :context "projeção da viewport"
           :message "A largura e a altura precisam ser positivas."))
  (let* ((relative (sgeo.math:v- point (%editor-view-frame-eye frame)))
         (depth (sgeo.math:dot relative (%editor-view-frame-forward frame)))
         (aspect (/ width height)))
    (if (eq (%editor-view-frame-mode frame) :perspective)
        (if (or (<= depth (%editor-view-frame-near frame))
                (>= depth (%editor-view-frame-far frame)))
            (values nil nil nil)
            (let* ((tangent (tan (/ (%editor-view-frame-fov frame) 2d0)))
                   (nx (/ (sgeo.math:dot relative (%editor-view-frame-right frame))
                          (* depth tangent aspect)))
                   (ny (/ (sgeo.math:dot relative (%editor-view-frame-up frame))
                          (* depth tangent))))
              (if (or (< nx -1d0) (> nx 1d0) (< ny -1d0) (> ny 1d0))
                  (values nil nil nil)
                  (values (- (* (/ (+ nx 1d0) 2d0) width) 0.5d0)
                          (- (* (/ (- 1d0 ny) 2d0) height) 0.5d0)
                          depth))))
        (let* ((relative (sgeo.math:v- point (%editor-view-frame-target frame)))
               (half-height (/ (%editor-view-frame-extent frame) 2d0))
               (half-width (* half-height aspect))
               (nx (/ (sgeo.math:dot relative (%editor-view-frame-right frame)) half-width))
               (ny (/ (sgeo.math:dot relative (%editor-view-frame-up frame)) half-height)))
          (if (or (< depth (%editor-view-frame-near frame))
                  (> depth (%editor-view-frame-far frame))
                  (< nx -1d0) (> nx 1d0) (< ny -1d0) (> ny 1d0))
              (values nil nil nil)
              (values (- (* (/ (+ nx 1d0) 2d0) width) 0.5d0)
                      (- (* (/ (- 1d0 ny) 2d0) height) 0.5d0)
                      depth))))))

(defun projected-position (world point width height &key view)
  "Projeta um ponto mundial em coordenadas de pixel da viewport, ou retorna NIL fora da câmera."
  (unless (and (typep point 'array) (= (array-rank point) 1) (= (length point) 3)
               (every #'realp point))
    (error 'sgeo.core:validation-error :context "projeção da viewport"
           :message "O ponto precisa ter três componentes reais."))
  (sgeo.scene:with-world-lock (world)
    (%project-with-frame (%editor-view-frame world view nil) point width height)))

(defun %ray-from-view-frame (frame x y width height)
  (let* ((aspect (/ width height))
         (nx (- (* 2d0 (/ (+ x 0.5d0) width)) 1d0))
         (ny (- 1d0 (* 2d0 (/ (+ y 0.5d0) height))))
         (forward (%editor-view-frame-forward frame))
         (right (%editor-view-frame-right frame))
         (up (%editor-view-frame-up frame)))
    (if (eq (%editor-view-frame-mode frame) :perspective)
        (let* ((tangent (tan (/ (%editor-view-frame-fov frame) 2d0)))
               (direction (sgeo.math:v+ forward
                                        (sgeo.math:v+ (sgeo.math:v* (* nx tangent aspect) right)
                                                      (sgeo.math:v* (* ny tangent) up)))))
          (sgeo.math:make-ray (%editor-view-frame-eye frame) direction))
        (let* ((half-height (/ (%editor-view-frame-extent frame) 2d0))
               (half-width (* half-height aspect))
               (origin (sgeo.math:v+ (%editor-view-frame-eye frame)
                                     (sgeo.math:v+ (sgeo.math:v* (* nx half-width) right)
                                                   (sgeo.math:v* (* ny half-height) up)))))
          (sgeo.math:make-ray origin forward)))))

(defun %object-hit (object ray)
  (let* ((geometry (sgeo.scene:mesh-object-geometry object))
         (data (sgeo.core:compile-render-data geometry))
         (positions (sgeo.geometry:render-mesh-positions data))
         (indices (sgeo.geometry:render-mesh-indices data))
         (source-faces (sgeo.geometry:render-mesh-source-faces data))
         (matrix (sgeo.scene:world-transform object))
         (nearest nil) (nearest-face nil))
    (loop for offset from 0 below (length indices) by 3
          for a = (sgeo.math:transform-point matrix
                   (sgeo.math:make-vec3 (aref positions (* 3 (aref indices offset)))
                                        (aref positions (1+ (* 3 (aref indices offset))))
                                        (aref positions (+ 2 (* 3 (aref indices offset))))))
          for b = (sgeo.math:transform-point matrix
                   (sgeo.math:make-vec3 (aref positions (* 3 (aref indices (1+ offset))))
                                        (aref positions (1+ (* 3 (aref indices (1+ offset)))))
                                        (aref positions (+ 2 (* 3 (aref indices (1+ offset)))))))
          for c = (sgeo.math:transform-point matrix
                   (sgeo.math:make-vec3 (aref positions (* 3 (aref indices (+ offset 2))))
                                        (aref positions (1+ (* 3 (aref indices (+ offset 2)))))
                                        (aref positions (+ 2 (* 3 (aref indices (+ offset 2)))))))
          for distance = (sgeo.math:ray-triangle-intersection ray a b c)
          when (and distance (or (null nearest) (< distance nearest)))
            do (setf nearest distance
                     nearest-face (when (< (floor offset 3) (length source-faces))
                                    (aref source-faces (floor offset 3)))))
    (values nearest nearest-face)))

(defun %projected-feature-distance (frame point x y width height)
  (multiple-value-bind (px py depth) (%project-with-frame frame point width height)
    (if px (values (sqrt (+ (expt (- px x) 2) (expt (- py y) 2))) depth)
        (values nil nil))))

(defun %nearest-visible-hit (world ray object-filter frame x y width height)
  (let ((nearest-object nil) (nearest-depth nil) (nearest-face nil))
    (dolist (object (%editor-world-meshes world))
      (multiple-value-bind (distance face) (%object-hit object ray)
        (when distance
          (let ((point (sgeo.math:v+ (sgeo.math:ray-origin ray)
                                     (sgeo.math:v* distance (sgeo.math:ray-direction ray)))))
            (multiple-value-bind (px py depth) (%project-with-frame frame point width height)
              (when (and px (< (abs (- px x)) 1d0) (< (abs (- py y)) 1d0)
                         (or (null nearest-depth) (< depth nearest-depth)))
                (setf nearest-object object nearest-depth depth nearest-face face)))))))
    (if (and object-filter (not (eq object-filter nearest-object)))
        (values nil nil nil)
        (values nearest-object nearest-depth nearest-face))))

(defun %nearest-vertex-or-edge (object geometry frame x y width height radius hit-distance mode)
  (let ((best-distance nil) (best-element nil)
        (matrix (sgeo.scene:world-transform object)))
    (labels ((consider (element local-point)
               (let ((world-point (sgeo.math:transform-point matrix local-point)))
                 (multiple-value-bind (pixel-distance depth)
                     (%projected-feature-distance frame world-point x y width height)
                   (when (and pixel-distance (<= pixel-distance radius)
                              (or (null hit-distance)
                                  (<= depth (+ hit-distance 1d-7)))
                              (or (null best-distance) (< pixel-distance best-distance)))
                     (setf best-distance pixel-distance best-element element)))))
      )
      (ecase mode
        (:vertex
         (dolist (vertex (sgeo.geometry:mesh-vertices geometry))
           (consider vertex (sgeo.geometry:vertex-position geometry vertex))))
        (:edge
         (dolist (edge (sgeo.geometry:mesh-edges geometry))
           (let* ((vertices (sgeo.geometry:edge-vertices geometry edge))
                  (a (sgeo.geometry:vertex-position geometry (first vertices)))
                  (b (sgeo.geometry:vertex-position geometry (second vertices)))
                  (wa (sgeo.math:transform-point matrix a))
                  (wb (sgeo.math:transform-point matrix b)))
             (multiple-value-bind (ax ay ad) (%project-with-frame frame wa width height)
               (multiple-value-bind (bx by bd) (%project-with-frame frame wb width height)
                 (when (and ax bx)
                   (let* ((dx (- bx ax)) (dy (- by ay))
                          (length-squared (+ (* dx dx) (* dy dy)))
                          (parameter (if (zerop length-squared) 0d0
                                         (max 0d0 (min 1d0
                                                       (/ (+ (* (- x ax) dx) (* (- y ay) dy))
                                                          length-squared)))))
                          (px (+ ax (* parameter dx)))
                          (py (+ ay (* parameter dy)))
                          (distance (sqrt (+ (expt (- px x) 2) (expt (- py y) 2))))
                          (depth (+ ad (* parameter (- bd ad)))))
                     (when (and (<= distance radius)
                                (or (null hit-distance) (<= depth (+ hit-distance 1d-7)))
                                (or (null best-distance) (< distance best-distance)))
                       (setf best-distance distance best-element edge)))))))))))
    (values best-element best-distance)))

(defun pick-element (world mode x y width height &key view object (radius 8d0))
  "Seleciona objeto ou elemento visível mais próximo dentro do raio em pixels."
  (unless (member mode '(:object :vertex :edge :face :region))
    (error 'sgeo.core:validation-error :context "modo de seleção"
           :message "O modo precisa ser :OBJECT, :VERTEX, :EDGE, :FACE ou :REGION."))
  (unless (and (realp x) (realp y) (realp width) (realp height)
               (> width 0) (> height 0) (<= 0 x) (< x width) (<= 0 y) (< y height)
               (realp radius) (>= radius 0))
    (error 'sgeo.core:validation-error :context "seleção da viewport"
           :message "Coordenadas, dimensões e raio precisam ser reais válidos."))
  (sgeo.scene:with-world-lock (world)
    (let* ((frame (%editor-view-frame world view nil))
           (ray (%ray-from-view-frame frame x y width height)))
      (multiple-value-bind (hit-object hit-distance hit-face)
          (%nearest-visible-hit world ray object frame x y width height)
        (when hit-object
          (case mode
            (:object (values hit-object nil))
            ((:face :region)
             (let ((geometry (sgeo.scene:mesh-object-geometry hit-object)))
               (when (and hit-face (typep geometry 'sgeo.geometry:half-edge-mesh))
                 (values hit-object
                         (if (eq mode :face) (list hit-face)
                             (sgeo.geometry:connected-face-region geometry hit-face))))))
            ((:vertex :edge)
             (let ((geometry (sgeo.scene:mesh-object-geometry hit-object)))
               (when (typep geometry 'sgeo.geometry:half-edge-mesh)
                 (multiple-value-bind (element unused-distance)
                     (%nearest-vertex-or-edge hit-object geometry frame x y width height radius
                                              hit-distance mode)
                   (declare (ignore unused-distance))
                   (when element (values hit-object (list element)))))))))))))
