(in-package #:sgeo.simulation)

(defstruct scheduled-task due interval function cancelled-p)
(defclass simulation-state ()
  ((world :initarg :world :reader %simulation-world)
   (input :initarg :input :reader simulation-input)
   (physics :initarg :physics :reader simulation-physics)
   (audio :initarg :audio :reader simulation-audio)
   (events :initform (make-event-bus) :reader simulation-events)
   (spatial-index :initarg :spatial-index :reader simulation-spatial-index)
   (spatial-bounds :initform (make-hash-table :test 'eq) :reader %spatial-bounds)
   (fixed-dt :initarg :fixed-dt :reader simulation-fixed-dt)
   (max-steps :initarg :max-steps :reader simulation-max-steps)
   (time :initform 0d0 :reader simulation-time)
   (frame-time :initform 0d0 :reader simulation-frame-time)
   (accumulator :initform 0d0 :reader simulation-accumulator)
   (step-count :initform 0 :reader simulation-step-count)
   (paused-p :initform nil :accessor simulation-paused-p)
   (audio-fraction :initform 0d0 :accessor %audio-fraction)
   (audio-samples :initform #() :reader simulation-audio-samples)
   (hooks :initform (make-hash-table :test 'eq) :reader %phase-hooks)
   (tasks :initform nil :accessor %tasks)
   (old-contact-handler :initform nil :accessor %old-contact-handler)))

(defun %positive-time (value &optional zero-p)
  (unless (and (realp value) (<= (if zero-p 0d0 1d-12) value most-positive-double-float))
    (error "Intervalo de simulação precisa ser finito e não negativo."))
  (coerce value 'double-float))

(defun attach-simulation (world &key input physics audio (fixed-dt (/ 1d0 60d0))
                                    (max-steps 8) spatial-index)
  "Anexa sistemas opcionais ao mundo; a cena original continua sendo a fonte de dados."
  (unless (and (integerp max-steps) (plusp max-steps)) (error "Limite de passos inválido."))
  (sgeo.scene:with-world-lock (world)
    (when (sgeo.scene:world-simulation-state world) (error "O mundo já possui uma simulação."))
    (let ((state (make-instance 'simulation-state :world world
                  :input (or input (sgeo.input:make-input-state)) :physics physics :audio audio
                  :fixed-dt (%positive-time fixed-dt) :max-steps max-steps
                  :spatial-index (or spatial-index (make-uniform-grid)))))
      (when physics
        (setf (%old-contact-handler state) (sgeo.physics:physics-contact-handler physics)
              (sgeo.physics:physics-contact-handler physics)
              (lambda (physics-world kind contact)
                (when (%old-contact-handler state)
                  (funcall (%old-contact-handler state) physics-world kind contact))
                (emit-event (simulation-events state) kind :source physics-world :payload contact
                            :time (simulation-time state)))))
      (setf (sgeo.scene:world-simulation-state world) state) state)))

(defun detach-simulation (world &key close-audio)
  "Desanexa os serviços e devolve o estado; recursos de áudio são encerrados opcionalmente."
  (sgeo.scene:with-world-lock (world)
    (let ((state (sgeo.scene:world-simulation-state world)))
      (when state
        (when (simulation-physics state)
          (setf (sgeo.physics:physics-contact-handler (simulation-physics state)) (%old-contact-handler state)))
        (sgeo.input:clear-input-state (simulation-input state))
        (when (and close-audio (simulation-audio state))
          (sgeo.audio:close-audio-mixer (simulation-audio state)))
        (setf (sgeo.scene:world-simulation-state world) nil)) state)))

(defparameter +simulation-phases+
  '(:input :pre-update :fixed-update :post-physics :variable-update :animation
    :transforms :spatial :audio :post-update))
(defun add-phase-hook (state phase function)
  "Registra um hook (WORLD STATE DT); retorna a função usada para remoção."
  (unless (and (member phase +simulation-phases+) (functionp function))
    (error "Fase ou função de simulação inválida."))
  (setf (gethash phase (%phase-hooks state))
        (append (gethash phase (%phase-hooks state)) (list function))) function)
(defun remove-phase-hook (state phase function)
  (setf (gethash phase (%phase-hooks state))
        (remove function (gethash phase (%phase-hooks state)) :test #'eq)) function)
(defgeneric run-simulation-phase (world state phase dt)
  (:documentation "Ponto de extensão das fases ordenadas de um quadro."))
(defmethod run-simulation-phase (world (state simulation-state) phase dt)
  (dolist (hook (copy-list (gethash phase (%phase-hooks state)))) (funcall hook world state dt)))
(defgeneric fixed-update-object (object world dt)
  (:documentation "Atualização de jogo em passos fixos; métodos permanecem redefiníveis."))
(defmethod fixed-update-object ((object sgeo.scene:scene-object) world dt)
  (declare (ignore object world dt)) nil)

(defun schedule-task (state delay function &key interval)
  "Agenda uma função (WORLD STATE) no relógio fixo, com repetição opcional."
  (unless (functionp function) (error "Tarefa precisa de uma função."))
  (let ((task (make-scheduled-task :due (+ (simulation-time state) (%positive-time delay t))
                                  :interval (when interval (%positive-time interval)) :function function)))
    (setf (%tasks state) (append (%tasks state) (list task))) task))
(defun task-cancelled-p (task) (scheduled-task-cancelled-p task))
(defun cancel-task (task) (setf (scheduled-task-cancelled-p task) t) task)
(defun %run-tasks (world state)
  (dolist (task (copy-list (%tasks state)))
    (when (and (not (task-cancelled-p task)) (<= (scheduled-task-due task) (+ (simulation-time state) 1d-12)))
      ;; A agenda avança antes do callback: uma tarefa com erro não se repete infinitamente.
      (if (scheduled-task-interval task)
          (incf (scheduled-task-due task) (scheduled-task-interval task))
          (cancel-task task))
      (funcall (scheduled-task-function task) world state)))
  (setf (%tasks state) (remove-if #'task-cancelled-p (%tasks state))))
(defun %enabled-objects (world)
  (let ((objects nil))
    (labels ((visit (object enabled)
               (let ((active (and enabled (sgeo.scene:scene-object-enabled-p object))))
                 (when active (push object objects))
                 (dolist (child (sgeo.scene:scene-object-children object)) (visit child active)))))
      (visit (sgeo.scene:world-root world) t))
    (nreverse objects)))
(defun %scene-bounds (object)
  "Usa posições deformadas, quando houver malha, para atualizar o índice espacial."
  (let* ((matrix (sgeo.scene:world-transform object))
         (positions (when (typep object 'sgeo.scene:mesh-object)
                      (sgeo.geometry:render-mesh-positions (sgeo.scene:render-data-for-object object)))))
    (if (and positions (plusp (length positions)))
        (let ((minimum (sgeo.math:make-vec3 most-positive-double-float most-positive-double-float most-positive-double-float))
              (maximum (sgeo.math:make-vec3 (- most-positive-double-float) (- most-positive-double-float) (- most-positive-double-float))))
          (loop for offset from 0 below (length positions) by 3
                for point = (sgeo.math:transform-point matrix
                              (sgeo.math:make-vec3 (aref positions offset) (aref positions (+ offset 1)) (aref positions (+ offset 2)))) do
            (dotimes (axis 3)
              (setf (aref minimum axis) (min (aref minimum axis) (aref point axis))
                    (aref maximum axis) (max (aref maximum axis) (aref point axis)))))
          (sgeo.math:make-aabb minimum maximum))
        (let ((point (sgeo.math:transform-point matrix #(0d0 0d0 0d0)))) (sgeo.math:make-aabb point point)))))
(defun %update-spatial (world state)
  (let ((index (simulation-spatial-index state)) (known (%spatial-bounds state))
        (objects (%enabled-objects world)) (removed nil))
    (maphash (lambda (old bounds) (declare (ignore bounds))
               (unless (member old objects :test #'eq) (push old removed))) known)
    (dolist (old removed) (spatial-remove index old) (remhash old known))
    (dolist (object objects)
      (let ((bounds (%scene-bounds object)) (previous (gethash object known)))
        (if previous (spatial-update index object previous bounds) (spatial-insert index object bounds))
        (setf (gethash object known) bounds)))))

(defmethod sgeo.scene:advance-scene-frame ((world sgeo.scene:world) (state simulation-state) dt)
  "Mapeia entrada, simula passos fixos, atualiza objetos/animação e extrai índices."
  (let ((dt (%positive-time dt t)))
    (sgeo.input:begin-input-frame (simulation-input state))
    (unwind-protect
         (progn
           (run-simulation-phase world state :input dt)
           (dispatch-events (simulation-events state))
           (run-simulation-phase world state :pre-update dt)
           (incf (slot-value state 'frame-time) dt)
           (unless (simulation-paused-p state) (incf (slot-value state 'accumulator) dt))
           (let ((step (simulation-fixed-dt state)))
             (loop repeat (simulation-max-steps state)
                   while (and (not (simulation-paused-p state))
                              (>= (+ (simulation-accumulator state) 1d-12) step)) do
               (%run-tasks world state)
               (run-simulation-phase world state :fixed-update step)
               (dolist (object (%enabled-objects world)) (fixed-update-object object world step))
               (when (simulation-physics state) (sgeo.physics:step-physics (simulation-physics state) step))
               (incf (slot-value state 'time) step)
               (incf (slot-value state 'step-count))
               (setf (slot-value state 'accumulator) (max 0d0 (- (simulation-accumulator state) step)))
               (run-simulation-phase world state :post-physics step)
               (dispatch-events (simulation-events state))))
           (run-simulation-phase world state :variable-update dt)
           (sgeo.scene:update-scene-objects world dt)
           (run-simulation-phase world state :animation dt)
           (sgeo.scene:update-world-animations world (if (simulation-paused-p state) 0d0 dt))
           (run-simulation-phase world state :transforms dt)
           (%update-spatial world state)
           (run-simulation-phase world state :spatial dt)
           (when (simulation-audio state)
             (let* ((frames (+ (%audio-fraction state) (* dt (sgeo.audio:mixer-sample-rate (simulation-audio state)))))
                    (whole (floor frames)))
               (setf (%audio-fraction state) (- frames whole)
                     (slot-value state 'audio-samples) (sgeo.audio:mixer-render (simulation-audio state) whole))))
           (run-simulation-phase world state :audio dt)
           (run-simulation-phase world state :post-update dt))
      (sgeo.input:end-input-frame (simulation-input state))))
  world)
