(in-package #:sgeo.simulation)

(defclass spatial-index () ())
(defgeneric spatial-insert (index object bounds))
(defgeneric spatial-remove (index object))
(defgeneric spatial-update (index object old-bounds new-bounds))
(defgeneric spatial-query-aabb (index bounds))
(defgeneric spatial-ray-query (index ray))
(defclass uniform-grid (spatial-index)
  ((cell-size :initarg :cell-size :reader %cell-size)
   (cells :initform (make-hash-table :test 'equal) :reader %cells)
   (bounds :initform (make-hash-table :test 'eq) :reader %bounds)
   (keys :initform (make-hash-table :test 'eq) :reader %object-cell-keys)
   (order :initform nil :accessor %spatial-order)
   (overflow :initform nil :accessor %overflow)))
(defun make-uniform-grid (&key (cell-size 2d0))
  "Cria um índice por células; volumes enormes usam a lista de transbordamento."
  (unless (and (realp cell-size) (<= 1d-9 cell-size most-positive-double-float))
    (error "Tamanho de célula inválido."))
  (make-instance 'uniform-grid :cell-size (coerce cell-size 'double-float)))
(defun %validate-bounds (bounds)
  (loop for a across (sgeo.math:aabb-min bounds) for b across (sgeo.math:aabb-max bounds)
        unless (and (realp a) (realp b) (<= (- most-positive-double-float) a b most-positive-double-float))
        do (error "Limites espaciais inválidos.")) bounds)
(defun %bounds-intersect-p (a b)
  (loop for i below 3 always (and (<= (aref (sgeo.math:aabb-min a) i) (aref (sgeo.math:aabb-max b) i))
                                (<= (aref (sgeo.math:aabb-min b) i) (aref (sgeo.math:aabb-max a) i)))))
(defun %grid-keys (index bounds)
  (%validate-bounds bounds)
  (let* ((lo (map 'vector (lambda (x) (floor x (%cell-size index))) (sgeo.math:aabb-min bounds)))
         (hi (map 'vector (lambda (x) (floor x (%cell-size index))) (sgeo.math:aabb-max bounds))))
    (when (<= (loop for i below 3 for n = (1+ (- (aref hi i) (aref lo i))) for p = n then (* p n)
                    finally (return p)) 4096)
      (loop for x from (aref lo 0) to (aref hi 0) append
        (loop for y from (aref lo 1) to (aref hi 1) append
          (loop for z from (aref lo 2) to (aref hi 2) collect (list x y z)))))))
(defmethod spatial-remove ((index uniform-grid) object)
  (dolist (key (gethash object (%object-cell-keys index)))
    (let ((items (remove object (gethash key (%cells index)) :test #'eq)))
      (if items (setf (gethash key (%cells index)) items) (remhash key (%cells index)))))
  (remhash object (%object-cell-keys index)) (remhash object (%bounds index))
  (setf (%overflow index) (remove object (%overflow index) :test #'eq)
        (%spatial-order index) (remove object (%spatial-order index) :test #'eq)) object)
(defmethod spatial-insert ((index uniform-grid) object bounds)
  (%validate-bounds bounds)
  (let ((keys (%grid-keys index bounds)))
    (spatial-remove index object)
    (setf (gethash object (%bounds index))
          (sgeo.math:make-aabb (copy-seq (sgeo.math:aabb-min bounds)) (copy-seq (sgeo.math:aabb-max bounds)))
          (gethash object (%object-cell-keys index)) keys
          (%spatial-order index) (append (%spatial-order index) (list object)))
    (if keys (dolist (key keys) (push object (gethash key (%cells index))))
        (push object (%overflow index)))) object)
(defmethod spatial-update ((index uniform-grid) object old-bounds new-bounds)
  (declare (ignore old-bounds)) (spatial-insert index object new-bounds))
(defmethod spatial-query-aabb ((index uniform-grid) bounds)
  (let* ((keys (%grid-keys index bounds)) (found (make-hash-table :test 'eq)))
    (if keys
        (progn (dolist (key keys) (dolist (obj (gethash key (%cells index))) (setf (gethash obj found) t)))
               (dolist (obj (%overflow index)) (setf (gethash obj found) t)))
        (dolist (obj (%spatial-order index)) (setf (gethash obj found) t)))
    (remove-if-not (lambda (obj) (and (gethash obj found) (%bounds-intersect-p bounds (gethash obj (%bounds index)))))
                   (%spatial-order index))))
(defmethod spatial-ray-query ((index uniform-grid) ray)
  (sort (loop for obj in (%spatial-order index)
              for distance = (sgeo.math:ray-aabb-intersection ray (gethash obj (%bounds index)))
              when distance collect (cons obj distance)) #'< :key #'cdr))
