(in-package #:sgeo.geometry)

(define-condition geometry-error (validation-error) ()
  (:documentation "Erro-base para estados geométricos inválidos."))
(define-condition topology-error (geometry-error) ()
  (:documentation "Erro de conectividade ou topologia de uma malha."))
(define-condition stale-handle-error (topology-error) ()
  (:documentation "Indica que um identificador não corresponde mais a um elemento ativo."))
(define-condition geometry-edit-error (topology-error) ()
  (:documentation "Indica que uma edição candidata não pôde ser validada."))

(defstruct (mesh-handle (:constructor %make-mesh-handle (mesh-id kind index generation)))
  "Identificador de um elemento de malha vinculado à malha e geração do slot."
  (mesh-id 0 :type integer :read-only t)
  (kind :vertex :type symbol :read-only t)
  (index 0 :type integer :read-only t)
  (generation 0 :type integer :read-only t))
(defun handle-kind (handle) (mesh-handle-kind handle))
(defun handle-index (handle) (mesh-handle-index handle))
(defun handle-generation (handle) (mesh-handle-generation handle))
(defun handle-mesh-id (handle) (mesh-handle-mesh-id handle))

(defstruct (mesh-arena (:constructor %make-mesh-arena ()))
  (items (make-array 0 :adjustable t :fill-pointer 0) :type vector)
  (generations (make-array 0 :adjustable t :fill-pointer 0) :type vector))
(defstruct vertex-record position (outgoing nil))
(defstruct face-record vertices (half-edge nil))
(defstruct edge-record half-edge)
(defstruct half-edge-record origin face edge next previous twin)
(defstruct (mesh-state (:constructor %make-mesh-state ()))
  (vertices (%make-mesh-arena)) (faces (%make-mesh-arena))
  (edges (%make-mesh-arena)) (half-edges (%make-mesh-arena))
  (edge-identities (make-hash-table :test #'equal))
  (half-edge-identities (make-hash-table :test #'equal)))

(defclass half-edge-mesh (sgeo-object)
  ((state :initarg :state :accessor %mesh-state)
   (kernel-lock :initform (bt:make-recursive-lock "sgeo half-edge mesh") :reader %kernel-lock))
  (:documentation "Malha poligonal indexada com topologia half-edge explícita."))

(defun %arena-items (arena) (mesh-arena-items arena))
(defun %arena-generations (arena) (mesh-arena-generations arena))
(defun %state-vertices (state) (mesh-state-vertices state))
(defun %state-faces (state) (mesh-state-faces state))
(defun %state-edges (state) (mesh-state-edges state))
(defun %state-half-edges (state) (mesh-state-half-edges state))

(defun %arena-active-indices (arena)
  (loop for item across (%arena-items arena) for i from 0 when item collect i))
(defun %arena-allocate (arena record)
  (let* ((items (%arena-items arena)) (index (position nil items)))
    (if index
        (setf (aref items index) record)
        (let ((generation (%arena-generations arena)))
          (vector-push-extend record items)
          (vector-push-extend 0 generation)
          (setf index (1- (length items)))))
    index))
(defun %arena-retire (arena index)
  (let ((items (%arena-items arena)))
    (unless (and (integerp index) (<= 0 index) (< index (length items)) (aref items index))
      (error 'stale-handle-error :context "edição de malha" :message "O slot a remover não está ativo."))
    (setf (aref items index) nil)
    (incf (aref (%arena-generations arena) index))
    index))

(defun %with-kernel-lock-fn (mesh function)
  (bt:with-recursive-lock-held ((%kernel-lock mesh)) (funcall function)))
(defmacro %with-kernel-lock ((mesh) &body body)
  `(%with-kernel-lock-fn ,mesh (lambda () ,@body)))

(defun %clone-arena (arena)
  (let* ((out (%make-mesh-arena)) (items (%arena-items arena)) (gens (%arena-generations arena)))
    (dotimes (i (length items))
      (vector-push-extend
       (let ((item (aref items i)))
         (typecase item
           (vertex-record (make-vertex-record :position (copy-seq (vertex-record-position item)) :outgoing (vertex-record-outgoing item)))
           (face-record (make-face-record :vertices (copy-list (face-record-vertices item)) :half-edge (face-record-half-edge item)))
           (edge-record (make-edge-record :half-edge (edge-record-half-edge item)))
           (half-edge-record (make-half-edge-record :origin (half-edge-record-origin item) :face (half-edge-record-face item) :edge (half-edge-record-edge item) :next (half-edge-record-next item) :previous (half-edge-record-previous item) :twin (half-edge-record-twin item)))
           (otherwise nil))) (%arena-items out))
      (vector-push-extend (aref gens i) (%arena-generations out)))
    out))
(defun %copy-hash (table)
  (let ((copy (make-hash-table :test (hash-table-test table)
                              :size (max 1 (hash-table-count table)))))
    (maphash (lambda (key value) (setf (gethash key copy) value)) table)
    copy))
(defun %clone-state (state)
  (let ((out (%make-mesh-state)))
    (setf (mesh-state-vertices out) (%clone-arena (%state-vertices state))
          (mesh-state-faces out) (%clone-arena (%state-faces state))
          (mesh-state-edges out) (%clone-arena (%state-edges state))
          (mesh-state-half-edges out) (%clone-arena (%state-half-edges state))
          (mesh-state-edge-identities out) (%copy-hash (mesh-state-edge-identities state))
          (mesh-state-half-edge-identities out) (%copy-hash (mesh-state-half-edge-identities state)))
    out))

(defun %resolve-handle (mesh handle kind &optional (state (%mesh-state mesh)))
  (unless (and (mesh-handle-p handle) (eq (mesh-handle-kind handle) kind)
               (= (mesh-handle-mesh-id handle) (sgeo.core:object-id mesh)))
    (error 'stale-handle-error :context "identificador de malha" :message "O identificador pertence a outra malha ou a outro tipo de elemento."))
  (let* ((arena (ecase kind (:vertex (%state-vertices state)) (:edge (%state-edges state)) (:face (%state-faces state)) (:half-edge (%state-half-edges state))))
         (index (mesh-handle-index handle)))
    (unless (and (<= 0 index) (< index (length (%arena-items arena)))
                 (aref (%arena-items arena) index)
                 (= (mesh-handle-generation handle) (aref (%arena-generations arena) index)))
      (error 'stale-handle-error :context "identificador de malha" :message "O elemento foi removido ou seu slot foi reutilizado."))
    (values (aref (%arena-items arena) index) index)))
(defun %make-handle (mesh kind index &optional (state (%mesh-state mesh)))
  (let* ((arena (ecase kind (:vertex (%state-vertices state)) (:edge (%state-edges state)) (:face (%state-faces state)) (:half-edge (%state-half-edges state)))))
    (%make-mesh-handle (sgeo.core:object-id mesh) kind index (aref (%arena-generations arena) index))))

(defun %with-mesh-edit-fn (mesh function)
  (%with-kernel-lock (mesh)
    (let* ((candidate (%clone-state (%mesh-state mesh)))
           (result (funcall function candidate)))
      (%rebuild-topology candidate)
      (%validate-state candidate)
      (setf (%mesh-state mesh) candidate)
      (touch-object mesh :topology-edited)
      result)))
(defmacro %with-mesh-edit ((mesh state) &body body)
  `(%with-mesh-edit-fn ,mesh (lambda (,state) ,@body)))

(defun %canonical-cycle (vertices)
  (let* ((v (coerce vertices 'vector)) (n (length v)) (best nil))
    (dotimes (offset n)
      (let ((candidate (loop for i below n collect (aref v (mod (+ offset i) n)))))
        (when (or (null best) (string< (prin1-to-string candidate) (prin1-to-string best))) (setf best candidate))))
    best))
(defun %canonical-face-cycle (vertices)
  (let ((forward (%canonical-cycle vertices))
        (reverse (%canonical-cycle (reverse vertices))))
    (if (string< (prin1-to-string forward) (prin1-to-string reverse)) forward reverse)))
(defun %vertex-identity (state vertex-index)
  (list vertex-index (aref (%arena-generations (%state-vertices state)) vertex-index)))
(defun %edge-key (a b)
  "Cria uma chave não direcionada para índices de vértice dentro de um estado."
  (if (< a b) (list a b) (list b a)))
(defun %state-edge-key (state a b)
  (let ((ka (%vertex-identity state a)) (kb (%vertex-identity state b)))
    (if (< a b) (list ka kb) (list kb ka))))
(defun %directed-key (face-identity origin destination)
  (list face-identity origin destination))
(defun %boundary-key (origin destination) (list :boundary origin destination))

(defun %rebuild-topology (state)
  "Reconstrói arestas, twins e ciclos de borda preservando slots por identidade."
  (let* ((faces (%state-faces state)) (edges (%state-edges state)) (hes (%state-half-edges state))
         (old-edge-ids (mesh-state-edge-identities state)) (old-he-ids (mesh-state-half-edge-identities state))
         (new-edge-ids (make-hash-table :test #'equal)) (new-he-ids (make-hash-table :test #'equal))
         (edge-directions (make-hash-table :test #'equal)) (face-keys (make-hash-table :test #'equal))
         (face-he-lists (make-hash-table)) (boundary-indices nil))
    (clrhash edge-directions)
    ;; Ciclos duplicados incluem as duas orientações e todas as rotações.
    (dolist (fi (%arena-active-indices faces))
      (let* ((loop-vertices (face-record-vertices (aref (%arena-items faces) fi)))
             (key (%canonical-face-cycle loop-vertices)))
        (when (gethash key face-keys)
          (error 'topology-error :context "polígonos da malha" :message "A malha contém dois polígonos com o mesmo ciclo de vértices."))
        (setf (gethash key face-keys) fi)))
    ;; Reutiliza slots de aresta pela identidade dos vértices extremos.
    (let ((desired-edges (make-hash-table :test #'equal)))
      (dolist (fi (%arena-active-indices faces))
        (let* ((loop-vertices (face-record-vertices (aref (%arena-items faces) fi))) (n (length loop-vertices)))
          (loop for j below n for a = (nth j loop-vertices) for b = (nth (mod (1+ j) n) loop-vertices)
                for key = (%state-edge-key state a b) for dirs = (gethash key edge-directions)
                do (when (= a b) (error 'topology-error :context "polígonos da malha" :message "Um polígono contém uma aresta degenerada."))
                   (when (and dirs (>= (length dirs) 2))
                     (error 'topology-error :context "arestas da malha" :message "Uma aresta pertence a mais de duas faces."))
                   (when (and dirs (equal (subseq (first dirs) 0 2) (list a b)))
                     (error 'topology-error :context "orientação da malha" :message "Duas faces adjacentes percorrem uma aresta na mesma direção."))
                   (push (list a b fi j) (gethash key edge-directions))
                   (setf (gethash key desired-edges) t))))
      (dolist (idx (%arena-active-indices edges))
        (unless (loop for key being the hash-keys of desired-edges
                      thereis (eql idx (gethash key old-edge-ids)))
          (%arena-retire edges idx)))
      (maphash (lambda (key ignored)
                 (declare (ignore ignored))
                 (let ((idx (gethash key old-edge-ids)))
                   (unless (and idx (aref (%arena-items edges) idx))
                     (setf idx (%arena-allocate edges (make-edge-record))))
                   (setf (gethash key new-edge-ids) idx))) desired-edges))
    ;; Recria half-edges conservando identidade do loop, vértices e direção.
    (let ((desired-he (make-hash-table :test #'equal)) (face-directed (make-hash-table :test #'equal)))
      (dolist (fi (%arena-active-indices faces))
        (let* ((vertices (face-record-vertices (aref (%arena-items faces) fi)))
               (n (length vertices)) (indices nil))
          (loop for j below n for a = (nth j vertices) for b = (nth (mod (1+ j) n) vertices)
                for key = (%directed-key (list fi (aref (%arena-generations faces) fi))
                                          (%vertex-identity state a) (%vertex-identity state b))
                for idx = (or (gethash key old-he-ids)
                              (%arena-allocate hes (make-half-edge-record :origin a :face fi)))
                do (setf (gethash key desired-he) idx (gethash (list a b) face-directed) idx)
                   (push idx indices))
          (setf (gethash fi face-he-lists) (nreverse indices))))
      ;; Twins internos e arestas de borda explícitas.
      (progn
        (maphash (lambda (key dirs)
                   (let* ((a (first (first dirs))) (b (second (first dirs)))
                          (inside (gethash (list a b) face-directed))
                          (outside (gethash (list b a) face-directed))
                          (edge-index (gethash key new-edge-ids)))
                     (if outside
                         (setf (half-edge-record-twin (aref (%arena-items hes) inside)) outside
                               (half-edge-record-twin (aref (%arena-items hes) outside)) inside
                               (half-edge-record-edge (aref (%arena-items hes) inside)) edge-index
                               (half-edge-record-edge (aref (%arena-items hes) outside)) edge-index)
                         (let* ((bk (%boundary-key (%vertex-identity state b)
                                                   (%vertex-identity state a)))
                                (bi (or (gethash bk old-he-ids)
                                        (%arena-allocate hes (make-half-edge-record :origin b :face nil)))))
                           (setf (gethash bk desired-he) bi
                                 (half-edge-record-origin (aref (%arena-items hes) bi)) b
                                 (half-edge-record-face (aref (%arena-items hes) bi)) nil
                                 (half-edge-record-edge (aref (%arena-items hes) bi)) edge-index
                                 (half-edge-record-twin (aref (%arena-items hes) inside)) bi
                                 (half-edge-record-twin (aref (%arena-items hes) bi)) inside)
                           (push bi boundary-indices))))) edge-directions)
        ;; Loops de faces, ponteiros outgoing e slots de identidade das HEs.
        (dolist (fi (%arena-active-indices faces))
          (let ((loop-ids (gethash fi face-he-lists)))
            (setf (face-record-half-edge (aref (%arena-items faces) fi)) (first loop-ids))
            (loop for idx in loop-ids for next in (append (rest loop-ids) (list (first loop-ids)))
                  for previous in (append (last loop-ids) (butlast loop-ids))
                  for he = (aref (%arena-items hes) idx)
                  do (setf (half-edge-record-origin he) (half-edge-record-origin he)
                           (half-edge-record-face he) fi
                           (half-edge-record-next he) next
                           (half-edge-record-previous he) previous
                           (half-edge-record-edge he) (gethash (%state-edge-key state (half-edge-record-origin he)
                                                                         (half-edge-record-origin (aref (%arena-items hes) next))) new-edge-ids)))))
        ;; As bordas seguem a face adjacente; manifoldidade torna o próximo único.
        (let ((outgoing-boundary (make-hash-table)))
          (dolist (bi boundary-indices)
            (let ((he (aref (%arena-items hes) bi)))
              (when (gethash (half-edge-record-origin he) outgoing-boundary)
                (error 'topology-error :context "ciclos de borda" :message "Há mais de uma meia-aresta de borda saindo de um vértice."))
              (setf (gethash (half-edge-record-origin he) outgoing-boundary) bi)))
          (dolist (bi boundary-indices)
            (let* ((he (aref (%arena-items hes) bi))
                   (destination (half-edge-record-origin (aref (%arena-items hes) (half-edge-record-twin he))))
                   (next (gethash destination outgoing-boundary)))
              (unless next (error 'topology-error :context "ciclos de borda" :message "A borda não fecha em um ciclo."))
              (setf (half-edge-record-next he) next
                    (half-edge-record-previous (aref (%arena-items hes) next)) bi))))
        ;; Retire apenas slots sem identidade presente; gerações mudam no candidato.
        (dolist (idx (%arena-active-indices hes))
          (unless (member idx (loop for v being the hash-values of desired-he collect v)) (%arena-retire hes idx)))
        (setf new-he-ids desired-he)
        ;; Escolha o arco de saída só depois que slots obsoletos forem aposentados.
        (dolist (vi (%arena-active-indices (%state-vertices state)))
          (setf (vertex-record-outgoing (aref (%arena-items (%state-vertices state)) vi))
                (loop for hi in (%arena-active-indices hes)
                      for he = (aref (%arena-items hes) hi)
                      when (= vi (half-edge-record-origin he)) return hi)))
        (dolist (edge-index (%arena-active-indices edges))
          (let ((representative
                  (loop for hi in (%arena-active-indices hes)
                        for he = (aref (%arena-items hes) hi)
                        when (and (eql edge-index (half-edge-record-edge he))
                                  (half-edge-record-face he)) return hi)))
            (setf (edge-record-half-edge (aref (%arena-items edges) edge-index)) representative)))
        (setf (mesh-state-edge-identities state) new-edge-ids
              (mesh-state-half-edge-identities state) new-he-ids)))))

(defun %active-slot-p (arena index)
  (and (integerp index) (<= 0 index) (< index (length (%arena-items arena)))
       (aref (%arena-items arena) index)))

(defun %validate-indexed-topology (state)
  "Valida os índices e as relações recíprocas armazenadas nos half-edges."
  (let* ((vertices (%state-vertices state)) (faces (%state-faces state))
         (edges (%state-edges state)) (half-edges (%state-half-edges state))
         (edge-incidence (make-hash-table)))
    (dolist (hi (%arena-active-indices half-edges))
      (let* ((he (aref (%arena-items half-edges) hi))
             (origin (half-edge-record-origin he))
             (face (half-edge-record-face he))
             (edge (half-edge-record-edge he))
             (next-index (half-edge-record-next he))
             (previous-index (half-edge-record-previous he))
             (twin-index (half-edge-record-twin he)))
        (unless (%active-slot-p vertices origin)
          (error 'topology-error :context "topologia half-edge" :message "Uma meia-aresta referencia uma origem inválida."))
        (unless (or (null face) (%active-slot-p faces face))
          (error 'topology-error :context "topologia half-edge" :message "Uma meia-aresta referencia uma face inválida."))
        (unless (%active-slot-p edges edge)
          (error 'topology-error :context "topologia half-edge" :message "Uma meia-aresta referencia uma aresta inválida."))
        (unless (and (%active-slot-p half-edges next-index)
                     (%active-slot-p half-edges previous-index)
                     (%active-slot-p half-edges twin-index))
          (error 'topology-error :context "topologia half-edge" :message "Uma meia-aresta possui next, previous ou twin inválido."))
        (let* ((next (aref (%arena-items half-edges) next-index))
               (previous (aref (%arena-items half-edges) previous-index))
               (twin (aref (%arena-items half-edges) twin-index))
               (twin-next (and (%active-slot-p half-edges (half-edge-record-next twin))
                               (aref (%arena-items half-edges) (half-edge-record-next twin)))))
          (unless (and (= (half-edge-record-previous next) hi)
                       (= (half-edge-record-next previous) hi)
                       (= (half-edge-record-twin twin) hi)
                       (eql (half-edge-record-edge twin) edge)
                       (= (half-edge-record-origin twin) (half-edge-record-origin next))
                       twin-next
                       (= origin (half-edge-record-origin twin-next)))
            (error 'topology-error :context "topologia half-edge" :message "A relação next, previous ou twin não é recíproca."))
          (when (null face)
            (unless (and (null (half-edge-record-face next))
                         (null (half-edge-record-face previous)))
              (error 'topology-error :context "ciclo de borda" :message "Um ciclo de borda atravessa uma meia-aresta de face.")))
          (push hi (gethash edge edge-incidence)))))
    (dolist (ei (%arena-active-indices edges))
      (let* ((edge (aref (%arena-items edges) ei))
             (representative (edge-record-half-edge edge))
             (incident (gethash ei edge-incidence)))
        (unless (and (= (length incident) 2)
                     (%active-slot-p half-edges representative)
                     (= ei (half-edge-record-edge (aref (%arena-items half-edges) representative))))
          (error 'topology-error :context "topologia half-edge" :message "Uma aresta precisa apontar para dois twins ativos."))))
    (dolist (fi (%arena-active-indices faces))
      (let* ((face (aref (%arena-items faces) fi))
             (vertices-in-loop (face-record-vertices face))
             (start (face-record-half-edge face))
             (index start))
        (unless (%active-slot-p half-edges start)
          (error 'topology-error :context "topologia half-edge" :message "Uma face não aponta para uma meia-aresta ativa."))
        (loop for expected-origin in vertices-in-loop
              for step from 0
              for he = (and (%active-slot-p half-edges index)
                            (aref (%arena-items half-edges) index))
              do (unless (and he (= fi (half-edge-record-face he))
                              (= expected-origin (half-edge-record-origin he)))
                   (error 'topology-error :context "topologia half-edge" :message "O ciclo half-edge não corresponde ao polígono armazenado."))
                 (setf index (half-edge-record-next he)))
        (unless (= index start)
          (error 'topology-error :context "topologia half-edge" :message "O ciclo half-edge da face não fecha no número esperado de passos."))))
    (dolist (vi (%arena-active-indices vertices))
      (let* ((vertex (aref (%arena-items vertices) vi))
             (outgoing (vertex-record-outgoing vertex))
             (has-outgoing (loop for hi in (%arena-active-indices half-edges)
                                 thereis (= vi (half-edge-record-origin (aref (%arena-items half-edges) hi))))))
        (if has-outgoing
            (unless (and (%active-slot-p half-edges outgoing)
                         (= vi (half-edge-record-origin (aref (%arena-items half-edges) outgoing))))
              (error 'topology-error :context "topologia half-edge" :message "A origem do vértice não aponta para uma meia-aresta ativa."))
            (when outgoing
              (error 'topology-error :context "topologia half-edge" :message "Um vértice isolado possui uma origem half-edge.")))))
    t))

(defun %validate-state (state)
  "Valida polígonos, incidências half-edge e leques de vértices do estado."
  (let* ((vertices (%state-vertices state)) (faces (%state-faces state)) (hes (%state-half-edges state))
         (incident (make-hash-table)) (face-graphs (make-hash-table)) (boundary-count (make-hash-table)))
    (unless (and (plusp (length (%arena-active-indices vertices))) (plusp (length (%arena-active-indices faces))))
      (error 'topology-error :context "malha" :message "A malha precisa de ao menos um vértice e uma face."))
    (dolist (fi (%arena-active-indices faces))
      (let ((vs (face-record-vertices (aref (%arena-items faces) fi))))
        (unless (and (listp vs) (>= (length vs) 3) (= (length vs) (length (remove-duplicates vs))))
          (error 'topology-error :context "polígono" :message "Cada face precisa de ao menos três vértices distintos."))
        (dolist (vi vs)
          (unless (and (integerp vi) (<= 0 vi) (< vi (length (%arena-items vertices))) (aref (%arena-items vertices) vi))
            (error 'topology-error :context "polígono" :message "Uma face referencia um vértice inválido."))
          (pushnew fi (gethash vi incident))
          (unless (gethash vi face-graphs)
            (setf (gethash vi face-graphs) (make-hash-table))))
        (loop for a in vs for b in (append (rest vs) (list (first vs)))
              do (when (= a b)
                   (error 'topology-error :context "polígono" :message "Um polígono contém uma aresta degenerada.")))))
    (%validate-indexed-topology state)
    ;; Constrói grafo de faces ao redor de cada vértice e conta arestas de borda.
    (dolist (hi (%arena-active-indices hes))
      (let* ((he (aref (%arena-items hes) hi))
             (origin (half-edge-record-origin he))
             (twin (and (half-edge-record-twin he) (aref (%arena-items hes) (half-edge-record-twin he)))))
        (when (and (half-edge-record-face he) (null (half-edge-record-face twin)))
          (incf (gethash origin boundary-count 0))
          (let ((dest (half-edge-record-origin twin))) (incf (gethash dest boundary-count 0))))
        (when (and (half-edge-record-face he) (half-edge-record-face twin)
                   (< hi (half-edge-record-twin he)))
          (loop for vi in (list origin (half-edge-record-origin twin))
                for graph = (or (gethash vi face-graphs)
                                (setf (gethash vi face-graphs) (make-hash-table)))
                do (push (half-edge-record-face twin)
                         (gethash (half-edge-record-face he) graph))
                   (push (half-edge-record-face he)
                         (gethash (half-edge-record-face twin) graph))))))
    (dolist (vi (%arena-active-indices vertices))
      (let* ((faces-at (gethash vi incident)) (boundary-edges (gethash vi boundary-count 0)))
        (when (and faces-at (not (member boundary-edges '(0 2))))
          (error 'topology-error :context "leque de vértices" :message "Um vértice precisa ter zero ou duas arestas de borda."))
        (when faces-at
          (let ((visited nil) (queue (list (first faces-at))))
            (loop while queue for fi = (pop queue) unless (member fi visited)
                  do (push fi visited) (setf queue (nconc (copy-list (gethash fi (gethash vi face-graphs))) queue)))
            (unless (= (length visited) (length faces-at))
              (error 'topology-error :context "leque de vértices" :message "As faces incidentes a um vértice formam leques desconectados.")))
          (let* ((degrees (mapcar (lambda (fi) (length (gethash fi (gethash vi face-graphs)))) faces-at))
                 (valid-fan
                   (if (zerop boundary-edges)
                       (every (lambda (degree) (= degree 2)) degrees)
                       (or (and (= (length degrees) 1) (zerop (first degrees)))
                           (and (= 2 (count 1 degrees))
                                (every (lambda (degree) (member degree '(1 2))) degrees))))))
            (unless valid-fan
              (error 'topology-error :context "leque de vértices"
                     :message "As faces incidentes a um vértice precisam formar um caminho de borda ou um ciclo interno."))))))
    (dolist (fi (%arena-active-indices faces))
      (%triangulate-face state fi))
    t))

(defun %finite-real-p (value)
  (and (realp value)
       (handler-case
           (let ((number (coerce value 'double-float)))
             (and (= number number)
                  (<= (- most-positive-double-float) number most-positive-double-float)))
         (error () nil))))
(defun %numeric-position (position)
  (unless (and (typep position 'sequence) (= (length position) 3)
               (every #'%finite-real-p position))
    (error 'geometry-error :context "posição do vértice" :message "Cada posição precisa conter três números reais."))
  (map 'vector (lambda (x) (coerce x 'double-float)) position))
(defun make-half-edge-mesh (&key positions faces (name "Malha poligonal") metadata)
  "Cria uma malha poligonal e valida seus leques e ciclos antes de publicá-la."
  (unless (and (typep positions 'sequence) (plusp (length positions)) (typep faces 'sequence) (plusp (length faces)))
    (error 'geometry-error :context "malha poligonal" :message "Informe ao menos uma posição e uma face."))
  (let ((state (%make-mesh-state)))
    (loop for position across (coerce positions 'vector)
          do (%arena-allocate (%state-vertices state) (make-vertex-record :position (%numeric-position position))))
    (loop for input-face across (coerce faces 'vector)
          for face = (if (typep input-face 'sequence)
                         (coerce input-face 'list)
                         (error 'geometry-error :context "polígono"
                                :message "Cada face precisa ser uma sequência de índices."))
          do (unless (and (>= (length face) 3)
                          (every (lambda (i)
                                   (and (integerp i) (<= 0 i)
                                        (< i (length (%arena-items (%state-vertices state))))))
                                 face)
                          (= (length face) (length (remove-duplicates face))))
               (error 'geometry-error :context "polígono" :message "A face possui índices inválidos ou vértices repetidos."))
             (%arena-allocate (%state-faces state) (make-face-record :vertices face)))
    (%rebuild-topology state)
    (%validate-state state)
    (make-instance 'half-edge-mesh :name name :metadata metadata :state state)))

(defun mesh-vertices (mesh) (%with-kernel-lock (mesh) (mapcar (lambda (i) (%make-handle mesh :vertex i)) (%arena-active-indices (%state-vertices (%mesh-state mesh))))))
(defun mesh-edges (mesh) (%with-kernel-lock (mesh) (mapcar (lambda (i) (%make-handle mesh :edge i)) (%arena-active-indices (%state-edges (%mesh-state mesh))))))
(defun mesh-faces (mesh) (%with-kernel-lock (mesh) (mapcar (lambda (i) (%make-handle mesh :face i)) (%arena-active-indices (%state-faces (%mesh-state mesh))))))
(defun mesh-half-edges (mesh) (%with-kernel-lock (mesh) (mapcar (lambda (i) (%make-handle mesh :half-edge i)) (%arena-active-indices (%state-half-edges (%mesh-state mesh))))))
(defun vertex-position (mesh vertex)
  (%with-kernel-lock (mesh) (copy-seq (vertex-record-position (nth-value 0 (%resolve-handle mesh vertex :vertex))))))
(defun face-vertices (mesh face)
  (%with-kernel-lock (mesh) (mapcar (lambda (i) (%make-handle mesh :vertex i)) (face-record-vertices (nth-value 0 (%resolve-handle mesh face :face))))))
(defun face-half-edges (mesh face)
  (%with-kernel-lock (mesh)
    (let* ((record (nth-value 0 (%resolve-handle mesh face :face))) (start (face-record-half-edge record)) (result nil) (idx start))
      (loop do (push (%make-handle mesh :half-edge idx) result)
            do (setf idx (half-edge-record-next (aref (%arena-items (%state-half-edges (%mesh-state mesh))) idx)))
            until (= idx start))
      (nreverse result))))
(defun edge-half-edges (mesh edge)
  (%with-kernel-lock (mesh)
    (let* ((record (nth-value 0 (%resolve-handle mesh edge :edge))) (first (edge-record-half-edge record))
           (twin (half-edge-record-twin (aref (%arena-items (%state-half-edges (%mesh-state mesh))) first))))
      (list (%make-handle mesh :half-edge first) (%make-handle mesh :half-edge twin)))))
(defun edge-vertices (mesh edge)
  (%with-kernel-lock (mesh)
    (let* ((record (nth-value 0 (%resolve-handle mesh edge :edge))) (hi (edge-record-half-edge record))
           (he (aref (%arena-items (%state-half-edges (%mesh-state mesh))) hi))
           (to (half-edge-record-origin (aref (%arena-items (%state-half-edges (%mesh-state mesh))) (half-edge-record-next he)))))
      (list (%make-handle mesh :vertex (half-edge-record-origin he)) (%make-handle mesh :vertex to)))))
(defun half-edge-origin (mesh half-edge)
  (%with-kernel-lock (mesh) (%make-handle mesh :vertex (half-edge-record-origin (nth-value 0 (%resolve-handle mesh half-edge :half-edge))))))
(defun half-edge-destination (mesh half-edge)
  (%with-kernel-lock (mesh)
    (let* ((he (nth-value 0 (%resolve-handle mesh half-edge :half-edge)))
           (target (half-edge-record-origin (aref (%arena-items (%state-half-edges (%mesh-state mesh))) (half-edge-record-next he)))))
      (%make-handle mesh :vertex target))))
(defun half-edge-next (mesh half-edge)
  (%with-kernel-lock (mesh) (let ((he (nth-value 0 (%resolve-handle mesh half-edge :half-edge)))) (%make-handle mesh :half-edge (half-edge-record-next he)))))
(defun half-edge-previous (mesh half-edge)
  (%with-kernel-lock (mesh) (let ((he (nth-value 0 (%resolve-handle mesh half-edge :half-edge)))) (%make-handle mesh :half-edge (half-edge-record-previous he)))))
(defun half-edge-twin (mesh half-edge)
  (%with-kernel-lock (mesh) (let* ((he (nth-value 0 (%resolve-handle mesh half-edge :half-edge))) (idx (half-edge-record-twin he))) (%make-handle mesh :half-edge idx))))
(defun half-edge-edge (mesh half-edge)
  (%with-kernel-lock (mesh) (let ((he (nth-value 0 (%resolve-handle mesh half-edge :half-edge)))) (%make-handle mesh :edge (half-edge-record-edge he)))))
(defun half-edge-face (mesh half-edge)
  (%with-kernel-lock (mesh) (let* ((he (nth-value 0 (%resolve-handle mesh half-edge :half-edge))) (fi (half-edge-record-face he))) (when fi (%make-handle mesh :face fi)))))
(defun boundary-half-edge-p (mesh half-edge)
  (%with-kernel-lock (mesh) (null (half-edge-record-face (nth-value 0 (%resolve-handle mesh half-edge :half-edge))))))
(defun boundary-edge-p (mesh edge)
  (some (lambda (he) (boundary-half-edge-p mesh he)) (edge-half-edges mesh edge)))

(defun %neighbors-of-vertex (mesh vertex kind)
  (%with-kernel-lock (mesh)
    (multiple-value-bind (record vi) (%resolve-handle mesh vertex :vertex)
      (declare (ignore record))
      (let ((found (make-hash-table)))
        (dolist (hi (%arena-active-indices (%state-half-edges (%mesh-state mesh))))
          (let* ((he (aref (%arena-items (%state-half-edges (%mesh-state mesh))) hi))
                 (dest (half-edge-record-origin (aref (%arena-items (%state-half-edges (%mesh-state mesh))) (half-edge-record-next he)))))
            (when (or (= vi (half-edge-record-origin he)) (= vi dest))
              (ecase kind
                (:vertex (setf (gethash (if (= vi (half-edge-record-origin he)) dest (half-edge-record-origin he)) found) t))
                (:edge (setf (gethash (half-edge-record-edge he) found) t))
                (:face (when (half-edge-record-face he) (setf (gethash (half-edge-record-face he) found) t)))))))
        (loop for idx being the hash-keys of found collect (%make-handle mesh kind idx))))))
(defun vertex-neighbors (mesh vertex) (%neighbors-of-vertex mesh vertex :vertex))
(defun vertex-edges (mesh vertex) (%neighbors-of-vertex mesh vertex :edge))
(defun vertex-faces (mesh vertex) (%neighbors-of-vertex mesh vertex :face))
(defun face-neighbors (mesh face)
  (%with-kernel-lock (mesh)
    (multiple-value-bind (record fi) (%resolve-handle mesh face :face)
      (declare (ignore record))
      (let ((found (make-hash-table)))
        (dolist (hi (%arena-active-indices (%state-half-edges (%mesh-state mesh))))
          (let ((he (aref (%arena-items (%state-half-edges (%mesh-state mesh))) hi)))
            (when (eql fi (half-edge-record-face he))
              (let* ((twin (aref (%arena-items (%state-half-edges (%mesh-state mesh))) (half-edge-record-twin he))) (other (half-edge-record-face twin)))
                (when other (setf (gethash other found) t))))))
        (loop for idx being the hash-keys of found collect (%make-handle mesh :face idx))))))
(defun connected-face-region (mesh seed &key predicate)
  (%with-kernel-lock (mesh)
    (multiple-value-bind (record start) (%resolve-handle mesh seed :face)
      (declare (ignore record))
      (let ((seen (make-hash-table)) (queue (list start)) (result nil))
        (loop while queue for fi = (pop queue) unless (gethash fi seen)
              do (setf (gethash fi seen) t)
                 (let ((handle (%make-handle mesh :face fi)))
                   (when (or (null predicate) (funcall predicate handle))
                     (push handle result)
                     (dolist (neighbor (face-neighbors mesh handle))
                       (push (mesh-handle-index neighbor) queue)))))
        (nreverse result)))))
(defun boundary-loops (mesh)
  (%with-kernel-lock (mesh)
    (let ((visited (make-hash-table)) (loops nil) (hes (%state-half-edges (%mesh-state mesh))))
      (dolist (start (%arena-active-indices hes))
        (let ((first-he (aref (%arena-items hes) start)))
          (when (and (null (half-edge-record-face first-he)) (not (gethash start visited)))
            (let ((cycle nil) (idx start))
              (loop while (not (gethash idx visited))
                    do (setf (gethash idx visited) t) (push (%make-handle mesh :half-edge idx) cycle)
                       (setf idx (half-edge-record-next (aref (%arena-items hes) idx)))
                    until (= idx start))
              (push (nreverse cycle) loops)))))
      (nreverse loops))))
(defun mesh-counts (mesh)
  (%with-kernel-lock (mesh)
    (let ((state (%mesh-state mesh)))
      (list :vertices (length (%arena-active-indices (%state-vertices state)))
            :edges (length (%arena-active-indices (%state-edges state)))
            :faces (length (%arena-active-indices (%state-faces state)))
            :half-edges (length (%arena-active-indices (%state-half-edges state)))
            :boundary-edges (count-if (lambda (e) (boundary-edge-p mesh e)) (mesh-edges mesh))))))
(defun validate-mesh (mesh)
  (%with-kernel-lock (mesh) (%validate-state (%mesh-state mesh))))
