(in-package #:sgeo.physics)

;; Física pequena e independente do ciclo de vida da cena.

(defun %finite-real (value context)
  (unless (and (realp value)
               (handler-case (<= (abs value) most-positive-double-float)
                 (error () nil)))
    (error "~A precisa ser um número real finito: ~S" context value))
  (coerce value 'double-float))

(defun %vec (value context)
  (unless (and (typep value 'array) (= (array-rank value) 1) (= (length value) 3))
    (error "~A precisa ser um vec3." context))
  (make-vec3 (%finite-real (aref value 0) context)
             (%finite-real (aref value 1) context)
             (%finite-real (aref value 2) context)))

(defstruct (sphere-shape (:constructor %sphere-shape (radius)))
  (radius 0.5d0 :type double-float))
(defun sphere-radius (shape) (sphere-shape-radius shape))
(defun make-sphere-shape (&key (radius 0.5d0))
  "Cria esfera com raio positivo, em unidades locais do objeto."
  (let ((r (%finite-real radius "raio da esfera")))
    (unless (> r 0d0) (error "O raio da esfera precisa ser positivo."))
    (%sphere-shape r)))

(defstruct (box-shape (:constructor %box-shape (half-extents)))
  (half-extents (make-vec3 0.5d0 0.5d0 0.5d0)))
(defun box-half-extents (shape) (copy-seq (box-shape-half-extents shape)))
(defun make-box-shape (&key (half-extents (make-vec3 0.5d0 0.5d0 0.5d0)))
  "Cria uma caixa orientada com semieixos positivos em unidades locais."
  (let ((h (%vec half-extents "half-extents da caixa")))
    (unless (every #'plusp h) (error "As semiextensões da caixa precisam ser positivas."))
    (%box-shape h)))

(defstruct (capsule-shape (:constructor %capsule-shape (radius half-height)))
  (radius 0.5d0 :type double-float)
  (half-height 0.5d0 :type double-float))
(defun capsule-radius (shape) (capsule-shape-radius shape))
(defun capsule-half-height (shape) (capsule-shape-half-height shape))
(defun make-capsule-shape (&key (radius 0.5d0) (half-height 0.5d0))
  "Cria cápsula no eixo Y, half-height é a meia altura do trecho cilíndrico."
  (let ((r (%finite-real radius "raio da cápsula"))
        (h (%finite-real half-height "meia altura da cápsula")))
    (unless (and (> r 0d0) (>= h 0d0))
      (error "O raio precisa ser positivo e a meia altura não negativa."))
    (%capsule-shape r h)))

(defstruct (rigid-body (:constructor %rigid-body))
  object shape (motion-type :dynamic) (mass 1d0 :type double-float)
  (velocity (make-vec3) :type (simple-array double-float (3)))
  (force (make-vec3) :type (simple-array double-float (3)))
  (restitution 0d0 :type double-float) (friction 0.6d0 :type double-float)
  sensor-p)
(defun make-rigid-body (&key object shape (mass 1d0) (motion-type :dynamic)
                             (velocity (make-vec3)) (restitution 0d0)
                             (friction 0.6d0) sensor-p trigger-p)
  "Associa um colisor a um objeto de cena. motion-type é :STATIC, :DYNAMIC ou :KINEMATIC."
  (unless (typep object 'scene-object) (error "object precisa ser um sgeo.scene:scene-object."))
  (unless (or (sphere-shape-p shape) (box-shape-p shape) (capsule-shape-p shape))
    (error "shape precisa ser esfera, caixa ou cápsula."))
  (unless (member motion-type '(:static :dynamic :kinematic))
    (error "motion-type precisa ser :STATIC, :DYNAMIC ou :KINEMATIC."))
  (let ((m (%finite-real mass "massa")) (e (%finite-real restitution "restituição"))
        (f (%finite-real friction "atrito")))
    (unless (and (> m 0d0) (<= 0d0 e 1d0) (>= f 0d0))
      (error "Massa positiva, restituição entre 0 e 1 e atrito não negativo são exigidos."))
    (%rigid-body :object object :shape shape :motion-type motion-type :mass m
                 :velocity (%vec velocity "velocidade") :restitution e :friction f
                 :sensor-p (or (not (null sensor-p)) (not (null trigger-p))))))

(defstruct (contact (:constructor %contact (body-a body-b normal depth point &optional event)))
  body-a body-b normal (depth 0d0 :type double-float) point event-slot)
(defstruct (physics-world (:constructor %physics-world))
  (gravity (make-vec3 0d0 -9.81d0 0d0)) (bodies nil) (contacts nil)
  contact-handler (previous-pairs nil))
(defun make-physics-world (&key (gravity (make-vec3 0d0 -9.81d0 0d0)) contact-handler)
  "Cria mundo independente. contact-handler recebe world, evento e contato."
  (%physics-world :gravity (%vec gravity "gravidade") :contact-handler contact-handler))
(defun physics-contact-handler (world) (physics-world-contact-handler world))
(defun (setf physics-contact-handler) (handler world)
  (unless (or (null handler) (functionp handler)) (error "contact-handler precisa ser função ou NIL."))
  (setf (physics-world-contact-handler world) handler))

(defun body-inverse-mass (body)
  (if (and (eq (rigid-body-motion-type body) :dynamic)
           (> (rigid-body-mass body) 0d0))
      (/ 1d0 (rigid-body-mass body)) 0d0))
(defun body-angular-velocity (body) (declare (ignore body)) (make-vec3))
(defun body-velocity (body) (copy-seq (rigid-body-velocity body)))
(defun (setf body-velocity) (value body)
  (setf (rigid-body-velocity body) (%vec value "velocidade")))
(defun body-object (body) (rigid-body-object body))
(defun body-shape (body) (rigid-body-shape body))
(defun body-motion-type (body) (rigid-body-motion-type body))
(defun body-mass (body) (rigid-body-mass body))
(defun body-restitution (body) (rigid-body-restitution body))
(defun body-friction (body) (rigid-body-friction body))
(defun body-sensor-p (body) (rigid-body-sensor-p body))
(defun body-trigger-p (body) (body-sensor-p body))
(defun physics-contacts (world) (copy-list (physics-world-contacts world)))
(defun contact-event (contact) (contact-event-slot contact))

(defun add-body (world body)
  "Anexa um corpo ao mundo; o mesmo corpo não pode aparecer duas vezes."
  (unless (and (physics-world-p world) (rigid-body-p body)) (error "Mundo ou corpo inválido."))
  (when (member body (physics-world-bodies world) :test #'eq) (error "Corpo já anexado a este mundo."))
  (setf (physics-world-bodies world) (append (physics-world-bodies world) (list body)))
  body)
(defun remove-body (world body)
  "Remove corpo e contatos associados; retorna NIL se não estava anexado."
  (let ((present (member body (physics-world-bodies world) :test #'eq)))
    (when present
      (let ((handler (physics-world-contact-handler world)))
        (when handler
          (dolist (contact (physics-world-contacts world))
            (when (or (eq body (contact-body-a contact)) (eq body (contact-body-b contact)))
              (setf (contact-event-slot contact) :end)
              (funcall handler world :end contact)))))
      (setf (physics-world-bodies world) (delete body (physics-world-bodies world) :test #'eq)
            (physics-world-contacts world)
            (remove-if (lambda (c) (or (eq body (contact-body-a c)) (eq body (contact-body-b c))))
                       (physics-world-contacts world))
            (physics-world-previous-pairs world)
            (remove-if (lambda (pair) (member body pair :test #'eq))
                       (physics-world-previous-pairs world))))
    (not (null present))))
(defun physics-bodies (world) (copy-list (physics-world-bodies world)))

(defun %position (body)
  (transform-point (world-transform (body-object body)) (make-vec3)))
(defun body-position (body) (copy-seq (%position body)))
(defun %write-world-position (body position)
  (let* ((object (body-object body)) (parent (scene-object-parent object))
         (local (if parent (world->local parent position) position)))
    (set-position object local)))
(defun move-body (body position)
  "Define posição mundial de corpo cinemático e atualiza imediatamente o objeto."
  (unless (eq (body-motion-type body) :kinematic)
    (error "move-body só aceita corpos :KINEMATIC."))
  (%write-world-position body (%vec position "posição mundial"))
  body)
(defun sync-body-from-object (body)
  "Sincroniza o estado do corpo após alterações externas na hierarquia da cena."
  (%position body)
  body)
(defun apply-force (body force)
  "Acumula força mundial; só tem efeito em corpos dinâmicos."
  (let ((v (%vec force "força")))
    (when (eq (body-motion-type body) :dynamic)
      (setf (rigid-body-force body) (v+ (rigid-body-force body) v))))
  body)
(defun apply-impulse (body impulse)
  "Aplica impulso linear instantâneo, sem simular torque."
  (when (plusp (body-inverse-mass body))
    (setf (rigid-body-velocity body)
          (v+ (rigid-body-velocity body) (v* (body-inverse-mass body) (%vec impulse "impulso")))))
  body)

;; A matriz mundial pode incluir pais; colisores aceitam apenas bases ortogonais.
(defun %frame (body)
  (let* ((m (world-transform (body-object body)))
         (raw (list (make-vec3 (aref m 0) (aref m 1) (aref m 2))
                    (make-vec3 (aref m 4) (aref m 5) (aref m 6))
                    (make-vec3 (aref m 8) (aref m 9) (aref m 10))))
         (scales (mapcar #'vector-length raw)))
    (when (some (lambda (s) (<= s 1d-12)) scales) (error "Transformação de corpo singular."))
    (let ((axes (mapcar #'normalize raw)))
      (unless (and (< (abs (dot (first axes) (second axes))) 1d-6)
                   (< (abs (dot (first axes) (third axes))) 1d-6)
                   (< (abs (dot (second axes) (third axes))) 1d-6))
        (error "Colisores físicos exigem escala sem cisalhamento no transform mundial."))
      (values (%position body) axes scales))))
(defun %uniform-scale (scales body)
  (declare (ignore body))
  (let ((s (first scales)))
    (unless (and (< (abs (- s (second scales))) (* 1d-6 (max 1d0 s)))
                 (< (abs (- s (third scales))) (* 1d-6 (max 1d0 s))))
      (error "Esferas e cápsulas exigem escala mundial uniforme."))
    s))
(defun %box-data (body)
  (multiple-value-bind (center axes scales) (%frame body)
    (unless (box-shape-p (body-shape body)) (error "Shape não é caixa."))
    (values center axes (loop for i below 3 collect (* (aref (box-half-extents (body-shape body)) i)
                                                         (nth i scales))))))
(defun %capsule-data (body)
  (multiple-value-bind (center axes scales) (%frame body)
    (unless (capsule-shape-p (body-shape body)) (error "Shape não é cápsula."))
    (let ((s (%uniform-scale scales body)) (shape (body-shape body)))
      (values center (v* (nth 1 axes) (* s (capsule-half-height shape)))
              (* s (capsule-radius shape))))))
(defun %sphere-data (body)
  (multiple-value-bind (center axes scales) (%frame body)
    (declare (ignore axes))
    (unless (sphere-shape-p (body-shape body)) (error "Shape não é esfera."))
    (values center (* (%uniform-scale scales body) (sphere-radius (body-shape body))))))

(defun %aabb-for-body (body)
  (let ((shape (body-shape body)))
    (cond
      ((sphere-shape-p shape)
       (multiple-value-bind (p r) (%sphere-data body)
         (make-aabb (v- p (make-vec3 r r r)) (v+ p (make-vec3 r r r)))))
      ((box-shape-p shape)
       (multiple-value-bind (p axes hs) (%box-data body)
         (let ((extent (make-vec3)))
           (dotimes (i 3) (setf (aref extent i)
                                 (loop for axis in axes for h in hs sum (* h (abs (aref axis i))))))
           (make-aabb (v- p extent) (v+ p extent)))))
      (t (multiple-value-bind (p segment r) (%capsule-data body)
           (let ((e (v+ (make-vec3 r r r)
                        (make-vec3 (abs (vx segment)) (abs (vy segment)) (abs (vz segment))))))
             (make-aabb (v- p e) (v+ p e))))))))
(defun body-bounds (body) (%aabb-for-body body))
(defun %aabb-overlap-p (a b)
  (loop for i below 3 always (and (<= (aref (aabb-min a) i) (aref (aabb-max b) i))
                                   (<= (aref (aabb-min b) i) (aref (aabb-max a) i)))))
(defun query-aabb (world bounds)
  "Consulta corpos por AABB via lista ordenada pelo mínimo X (broad phase sweep)."
  (unless (and (typep bounds 'aabb) (physics-world-p world)) (error "query-aabb requer mundo e AABB."))
  (let ((entries (sort (mapcar (lambda (body) (cons body (%aabb-for-body body)))
                               (copy-list (physics-world-bodies world)))
                       #'< :key (lambda (entry) (vx (aabb-min (cdr entry))))))
        (query-max (vx (aabb-max bounds))))
    (loop for entry in entries
          while (<= (vx (aabb-min (cdr entry))) query-max)
          when (and (>= (vx (aabb-max (cdr entry))) (vx (aabb-min bounds)))
                    (%aabb-overlap-p (cdr entry) bounds)) collect (car entry))))

(defun %closest-segments (p1 q1 p2 q2)
  (let* ((d1 (v- q1 p1)) (d2 (v- q2 p2)) (r (v- p1 p2))
         (a (dot d1 d1)) (e (dot d2 d2)) (f (dot d2 r)) (s 0d0) (tvalue 0d0))
    (cond
      ((and (<= a 1d-15) (<= e 1d-15)) (values p1 p2))
      ((<= a 1d-15) (setf tvalue (max 0d0 (min 1d0 (/ f e)))))
      (t
       (let ((c (dot d1 r)))
         (if (<= e 1d-15)
             (setf s (max 0d0 (min 1d0 (/ (- c) a))))
             (let* ((b (dot d1 d2)) (denom (- (* a e) (* b b))))
               (when (> denom 1d-15)
                 (setf s (max 0d0 (min 1d0 (/ (- (* b f) (* c e)) denom)))))
               (setf tvalue (/ (+ (* b s) f) e))
               (cond ((< tvalue 0d0)
                      (setf tvalue 0d0 s (max 0d0 (min 1d0 (/ (- c) a)))))
                     ((> tvalue 1d0)
                      (setf tvalue 1d0 s (max 0d0 (min 1d0 (/ (- b c) a)))))))))))
    (values (v+ p1 (v* s d1)) (v+ p2 (v* tvalue d2)))))

(defun %sphere-sphere (a b)
  (multiple-value-bind (pa ra) (%sphere-data a)
    (multiple-value-bind (pb rb) (%sphere-data b)
      (let* ((delta (v- pb pa)) (distance (vector-length delta)) (depth (- (+ ra rb) distance)))
        (when (>= depth 0d0)
          (let ((normal (if (> distance 1d-12) (v* (/ 1d0 distance) delta) (make-vec3 1d0 0d0 0d0))))
            (%contact a b normal depth (v+ pa (v* (- ra (/ depth 2d0)) normal)))))))))

(defun %closest-on-box (point center axes hs)
  (let ((result (copy-seq center)) (offset (v- point center)))
    (loop for axis in axes for h in hs do
      (let ((d (max (- h) (min h (dot offset axis)))))
        (setf result (v+ result (v* d axis)))))
    result))
(defun %sphere-box (sphere box flip)
  (multiple-value-bind (p radius) (%sphere-data sphere)
    (multiple-value-bind (center axes hs) (%box-data box)
      (let* ((closest (%closest-on-box p center axes hs))
             (delta (v- closest p)) (distance (vector-length delta)))
        (when (<= distance radius)
          (let* ((offset (v- p center))
                 (axis-index (loop with best = 0 with value = most-positive-double-float
                                   for axis in axes for h in hs for i from 0
                                   for gap = (- h (abs (dot offset axis)))
                                   when (< gap value) do (setf best i value gap)
                                   finally (return best)))
                 (axis (nth axis-index axes))
                 (normal (if (> distance 1d-12)
                             (v* (/ 1d0 distance) delta)
                             (v* (if (minusp (dot offset axis)) -1d0 1d0) axis)))
                 (depth (if (> distance 1d-12)
                            (- radius distance)
                            (+ radius (- (nth axis-index hs) (abs (dot offset axis)))))))
            ;; O contato interno empurra a esfera até a face mais próxima.
            (if flip (%contact box sphere (v* -1d0 normal) depth closest)
                (%contact sphere box normal depth closest))))))))

(defun %capsule-sphere (capsule sphere flip)
  (multiple-value-bind (center segment rc) (%capsule-data capsule)
    (multiple-value-bind (ps rs) (%sphere-data sphere)
      (let* ((a (v- center segment)) (b (v+ center segment))
             (axis (v- b a)) (tvalue (if (> (dot axis axis) 1d-15)
                                         (max 0d0 (min 1d0 (/ (dot (v- ps a) axis) (dot axis axis)))) 0d0))
             (closest (v+ a (v* tvalue axis))) (delta (v- ps closest))
             (distance (vector-length delta)) (depth (- (+ rc rs) distance)))
        (when (>= depth 0d0)
          (let ((n (if (> distance 1d-12) (v* (/ 1d0 distance) delta) (make-vec3 1d0 0d0 0d0))))
            (if flip (%contact sphere capsule (v* -1d0 n) depth closest)
                (%contact capsule sphere n depth closest))))))))

(defun %capsule-capsule (a b)
  (multiple-value-bind (ca sa ra) (%capsule-data a)
    (multiple-value-bind (cb sb rb) (%capsule-data b)
      (multiple-value-bind (pa pb) (%closest-segments (v- ca sa) (v+ ca sa) (v- cb sb) (v+ cb sb))
        (let* ((delta (v- pb pa)) (distance (vector-length delta)) (depth (- (+ ra rb) distance)))
          (when (>= depth 0d0)
            (let ((n (if (> distance 1d-12) (v* (/ 1d0 distance) delta) (make-vec3 1d0 0d0 0d0))))
              (%contact a b n depth (v+ pa (v* (- ra (/ depth 2d0)) n))))))))))

(defun %capsule-box (capsule box flip)
  (multiple-value-bind (center segment radius) (%capsule-data capsule)
    (multiple-value-bind (bc axes hs) (%box-data box)
      (let* ((p0 (v- center segment)) (p1 (v+ center segment))
             (lo 0d0) (hi 1d0))
        (labels ((point-at (u) (v+ p0 (v* u (v- p1 p0))))
                 (distance-squared (u)
                   (let* ((p (point-at u)) (q (%closest-on-box p bc axes hs)))
                     (dot (v- q p) (v- q p)))))
          ;; Minimização convexa do eixo da cápsula contra a caixa OBB.
          (loop repeat 48 do
            (let ((m1 (/ (+ (* 2d0 lo) hi) 3d0))
                  (m2 (/ (+ lo (* 2d0 hi)) 3d0)))
              (if (< (distance-squared m1) (distance-squared m2))
                  (setf hi m2) (setf lo m1))))
          (let* ((p (point-at (/ (+ lo hi) 2d0)))
                 (q (%closest-on-box p bc axes hs))
                 (delta (v- q p)) (distance (vector-length delta)))
            (when (<= distance radius)
              (let* ((offset (v- p bc))
                     (index (loop with best = 0 with value = most-positive-double-float
                                  for axis in axes for h in hs for i from 0
                                  for gap = (- h (abs (dot offset axis)))
                                  when (< gap value) do (setf best i value gap)
                                  finally (return best)))
                     (axis (nth index axes))
                     (normal (if (> distance 1d-12)
                                 (v* (/ 1d0 distance) delta)
                                 (v* (if (minusp (dot offset axis)) -1d0 1d0) axis)))
                     (depth (if (> distance 1d-12)
                                (- radius distance)
                                (+ radius (- (nth index hs) (abs (dot offset axis)))))))
                (if flip (%contact box capsule (v* -1d0 normal) depth q)
                    (%contact capsule box normal depth q))))))))))

(defun %box-box (a b)
  ;; Separating-axis theorem para OBB: três eixos de cada caixa e nove cruzamentos.
  (multiple-value-bind (pa aa ah) (%box-data a)
    (multiple-value-bind (pb ba bh) (%box-data b)
      (let ((delta (v- pb pa)) (best-depth most-positive-double-float) (best-axis nil))
        (dolist (axis (append aa ba (loop for x in aa append (loop for y in ba collect (cross x y)))))
          (let ((length (vector-length axis)))
            (when (> length 1d-10)
              (let* ((n (v* (/ 1d0 length) axis))
                     (ra (loop for x in aa for h in ah sum (* h (abs (dot n x)))))
                     (rb (loop for x in ba for h in bh sum (* h (abs (dot n x)))))
                     (d (abs (dot delta n))) (depth (- (+ ra rb) d)))
                (when (< depth 0d0) (return-from %box-box nil))
                (when (< depth best-depth)
                  (setf best-depth depth best-axis (if (minusp (dot delta n)) (v* -1d0 n) n)))))))
        (%contact a b best-axis best-depth (v* 0.5d0 (v+ pa pb)))))))

(defun overlap-bodies (a b)
  "Retorna contato ou NIL; normal sempre aponta do corpo A para B."
  (unless (and (rigid-body-p a) (rigid-body-p b)) (error "Esperava dois rigid-body."))
  (unless (%aabb-overlap-p (%aabb-for-body a) (%aabb-for-body b)) (return-from overlap-bodies nil))
  (let ((sa (body-shape a)) (sb (body-shape b)))
    (cond ((and (sphere-shape-p sa) (sphere-shape-p sb)) (%sphere-sphere a b))
          ((and (sphere-shape-p sa) (box-shape-p sb)) (%sphere-box a b nil))
          ((and (box-shape-p sa) (sphere-shape-p sb)) (%sphere-box b a t))
          ((and (capsule-shape-p sa) (sphere-shape-p sb)) (%capsule-sphere a b nil))
          ((and (sphere-shape-p sa) (capsule-shape-p sb)) (%capsule-sphere b a t))
          ((and (capsule-shape-p sa) (capsule-shape-p sb)) (%capsule-capsule a b))
          ((and (capsule-shape-p sa) (box-shape-p sb)) (%capsule-box a b nil))
          ((and (box-shape-p sa) (capsule-shape-p sb)) (%capsule-box b a t))
          (t (%box-box a b)))))

(defun %ray-sphere (ray center radius)
  (let* ((o (ray-origin ray)) (d (ray-direction ray)) (offset (v- o center))
         (b (dot offset d)) (c (- (dot offset offset) (* radius radius)))
         (disc (- (* b b) c)))
    (when (>= disc 0d0)
      (let* ((root (sqrt disc)) (near (- (- b) root)) (far (+ (- b) root))
             (distance (if (>= near 0d0) near (if (>= far 0d0) far nil))))
        (when distance
          (let* ((point (v+ o (v* distance d)))
                 (normal (if (> (vector-length (v- point center)) 1d-12)
                             (normalize (v- point center)) (v* -1d0 d))))
            (values distance normal)))))))

(defun %ray-box (ray center axes hs)
  ;; Preserva a entrada negativa para distinguir um raio que começou dentro
  ;; da caixa de um raio que tocou a face exatamente na origem.
  (let ((near (- most-positive-double-float))
        (far most-positive-double-float)
        (near-normal nil) (far-normal nil))
    (loop for axis in axes for h in hs do
      (let ((origin (dot (v- (ray-origin ray) center) axis))
            (direction (dot (ray-direction ray) axis)))
        (if (<= (abs direction) 1d-15)
            (when (or (< origin (- h)) (> origin h)) (return-from %ray-box nil))
            (let* ((a (/ (- (- h) origin) direction))
                   (b (/ (- h origin) direction))
                   (entry (min a b)) (exit (max a b))
                   (entry-normal (v* (if (< a b) -1d0 1d0) axis))
                   (exit-normal (v* (if (< a b) 1d0 -1d0) axis)))
              (when (> entry near) (setf near entry near-normal entry-normal))
              (when (< exit far) (setf far exit far-normal exit-normal))
              (when (> near far) (return-from %ray-box nil))))))
    (when (and far-normal (>= far 0d0))
      (if (and near-normal (>= near 0d0))
          (values near near-normal)
          (values far far-normal)))))

(defun %ray-capsule (ray center segment radius)
  (let* ((a (v- center segment)) (b (v+ center segment))
         (ba (v- b a)) (oa (v- (ray-origin ray) a)) (rd (ray-direction ray))
         (baba (dot ba ba)) (bard (dot ba rd)) (baoa (dot ba oa))
         (rdoa (dot rd oa)) (oaoa (dot oa oa))
         (aa (- baba (* bard bard))) (bb (- (* baba rdoa) (* baoa bard)))
         (cc (- (* baba oaoa) (* baoa baoa) (* radius radius baba)))
         (disc (- (* bb bb) (* aa cc))) (best nil))
    (when (and (> aa 1d-15) (>= disc 0d0))
      (let ((root (sqrt disc)))
        (dolist (tvalue (list (/ (- (- bb) root) aa) (/ (+ (- bb) root) aa)))
          (let ((y (+ baoa (* tvalue bard))))
            (when (and (>= tvalue 0d0) (>= y 0d0) (<= y baba)
                       (or (null best) (< tvalue best)))
              (setf best tvalue))))))
    (dolist (endpoint (list a b))
      (multiple-value-bind (distance normal) (%ray-sphere ray endpoint radius)
        (declare (ignore normal))
        (when (and distance (or (null best) (< distance best))) (setf best distance))))
    (when best
      (let* ((point (v+ (ray-origin ray) (v* best rd)))
             (u (if (> baba 1d-15) (max 0d0 (min 1d0 (/ (dot (v- point a) ba) baba))) 0d0))
             (closest (v+ a (v* u ba)))
             (normal (if (> (vector-length (v- point closest)) 1d-12)
                         (normalize (v- point closest)) (v* -1d0 rd))))
        (values best normal)))))

(defun %ray-body (ray body)
  (case (type-of (body-shape body))
    (sphere-shape (multiple-value-bind (center radius) (%sphere-data body)
                    (%ray-sphere ray center radius)))
    (box-shape (multiple-value-bind (center axes hs) (%box-data body)
                 (%ray-box ray center axes hs)))
    (capsule-shape (multiple-value-bind (center segment radius) (%capsule-data body)
                     (%ray-capsule ray center segment radius)))))

(defun physics-ray-cast (world ray &key (max-distance most-positive-double-float))
  "Retorna valores corpo, distância, ponto e normal do primeiro colisor atingido."
  (unless (and (physics-world-p world) (typep ray 'sgeo.math:ray))
    (error "physics-ray-cast requer mundo e raio."))
  (let ((limit (%finite-real max-distance "distância máxima")) (best-distance nil) (best-body nil) (best-normal nil))
    (unless (>= limit 0d0) (error "max-distance precisa ser não negativo."))
    (dolist (body (physics-world-bodies world))
      (when (sgeo.math:ray-aabb-intersection ray (%aabb-for-body body))
        (multiple-value-bind (distance normal) (%ray-body ray body)
          (when (and distance (<= distance limit) (or (null best-distance) (< distance best-distance)))
            (setf best-distance distance best-body body best-normal normal)))))
    (when best-body
      (values best-body best-distance
              (v+ (ray-origin ray) (v* best-distance (ray-direction ray)))
              best-normal))))

(defun %inverse-sum (a b) (+ (body-inverse-mass a) (body-inverse-mass b)))
(defun %move-world (body delta)
  (when (plusp (body-inverse-mass body)) (%write-world-position body (v+ (%position body) delta))))
(defun %resolve-contact (contact)
  (let* ((a (contact-body-a contact)) (b (contact-body-b contact))
         (inv-a (body-inverse-mass a)) (inv-b (body-inverse-mass b)) (sum (+ inv-a inv-b)))
    (when (and (> sum 0d0) (not (or (body-sensor-p a) (body-sensor-p b))))
      (let* ((n (contact-normal contact)) (relative (v- (body-velocity b) (body-velocity a)))
             (along (dot relative n)))
        (when (< along 0d0)
          (let* ((e (max (body-restitution a) (body-restitution b)))
                 (j (/ (* (- (+ 1d0 e)) along) sum)) (impulse (v* j n)))
            (when (> inv-a 0d0) (setf (rigid-body-velocity a) (v- (rigid-body-velocity a) (v* inv-a impulse))))
            (when (> inv-b 0d0) (setf (rigid-body-velocity b) (v+ (rigid-body-velocity b) (v* inv-b impulse))))
            (let* ((rv (v- (body-velocity b) (body-velocity a)))
                   (tangent-raw (v- rv (v* (dot rv n) n)))
                   (tl (vector-length tangent-raw)))
              (when (> tl 1d-12)
                (let* ((tangent (v* (/ 1d0 tl) tangent-raw))
                       (jt (/ (- (dot rv tangent)) sum))
                       (mu (sqrt (* (body-friction a) (body-friction b))))
                       (jt (max (- (* j mu)) (min (* j mu) jt))) (friction (v* jt tangent)))
                  (when (> inv-a 0d0) (setf (rigid-body-velocity a) (v- (rigid-body-velocity a) (v* inv-a friction))))
                  (when (> inv-b 0d0) (setf (rigid-body-velocity b) (v+ (rigid-body-velocity b) (v* inv-b friction))))))))
      (let ((correction (v* (/ (* 0.8d0 (max 0d0 (- (contact-depth contact) 0.001d0))) sum)
                            (contact-normal contact))))
        (%move-world a (v* (- inv-a) correction))
        (%move-world b (v* inv-b correction))))))))

(defun step-physics (world dt)
  "Integra um passo determinístico de duração DT, detecta contatos e resolve colisões."
  (let ((delta (%finite-real dt "dt")))
    (unless (and (physics-world-p world) (> delta 0d0)) (error "step-physics requer mundo e dt positivo."))
    (dolist (body (physics-world-bodies world))
      (when (eq (body-motion-type body) :dynamic)
        (setf (rigid-body-velocity body)
              (v+ (rigid-body-velocity body)
                  (v* delta (v+ (physics-world-gravity world)
                                (v* (body-inverse-mass body) (rigid-body-force body))))))
        (%write-world-position body (v+ (%position body) (v* delta (rigid-body-velocity body)))))
      (setf (rigid-body-force body) (make-vec3)))
    (let* ((bodies (physics-world-bodies world)) (pairs nil) (contacts nil))
      (loop for tail on bodies for a = (car tail) do
        (dolist (b (cdr tail))
          (unless (and (eq (body-motion-type a) :static) (eq (body-motion-type b) :static))
            (let ((contact (overlap-bodies a b)))
              (when contact (push (list a b) pairs) (push contact contacts))))))
      (setf pairs (nreverse pairs) contacts (nreverse contacts))
      (loop repeat 8 do
        (dolist (contact contacts) (%resolve-contact contact)))
      (setf (physics-world-contacts world) contacts)
      (dolist (contact contacts)
        (let ((pair (list (contact-body-a contact) (contact-body-b contact))))
          (setf (contact-event-slot contact)
                (if (member pair (physics-world-previous-pairs world) :test #'equal) :stay :begin))))
      (let ((handler (physics-world-contact-handler world)))
        (when handler
          (dolist (contact contacts)
            (funcall handler world (contact-event contact) contact))
          (dolist (old (physics-world-previous-pairs world))
            (unless (member old pairs :test #'equal)
              (funcall handler world :end (%contact (first old) (second old) (make-vec3) 0d0
                                                   (make-vec3) :end)))))
      (setf (physics-world-previous-pairs world) pairs))
    world)))
