(in-package #:sgeo.tests)
(in-suite sgeo-suite)

(defun %timeline-test-scene ()
  "Cria um editor com uma pista viva para verificar cursor e histórico."
  (let* ((world (sg:make-world)) (node (sg:make-scene-object :name "Mover"))
         (editor (sgeo.editor:make-editor :world world)))
    (sg:add-to-world world node)
    (sgeo.editor:editor-select editor node)
    (let ((clip (sgeo.editor:create-editor-animation editor)))
      (values editor node clip (first (sg:clip-tracks clip))))))

(test timeline-samples-live-tracks-and-pauses
  (multiple-value-bind (editor node clip track) (%timeline-test-scene)
    (sg:set-track-keys track '((0d0 #(0d0 0d0 0d0)) (2d0 #(2d0 0d0 0d0))))
    (is (eq clip (getf (sgeo.editor:timeline-data editor) :clip)))
    (is (eq track (first (getf (sgeo.editor:timeline-data editor) :tracks))))
    (sgeo.editor:scrub-animation editor 1d0)
    (is (not (sgeo.editor:editor-playing-p editor)))
    (is (approximately= 1d0 (sg:vx (sg:transform-position (sg:scene-object-local-transform node)))))
    (sgeo.editor:execute-editor-command editor :step :dt 0.25d0)
    (is (approximately= 1.25d0 (sgeo.editor:editor-time editor)))
    (sgeo.editor:advance-editor-time editor 0.25d0)
    (is (approximately= 1.25d0 (sgeo.editor:editor-time editor)))
    (sgeo.editor:execute-editor-command editor :play)
    (sgeo.editor:advance-editor-time editor 0.25d0)
    (is (approximately= 1.5d0 (sgeo.editor:editor-time editor)))
    (sgeo.editor:execute-editor-command editor :pause)
    (sgeo.editor:scrub-animation editor 2d0)
    (is (approximately= 2d0 (sg:vx (sg:transform-position (sg:scene-object-local-transform node)))))))

(test timeline-key-edit-undo-redo-and-failure
  (multiple-value-bind (editor node clip track) (%timeline-test-scene)
    (sgeo.editor:scrub-animation editor 1d0)
    (sg:set-position node #(7d0 2d0 0d0))
    (sgeo.editor:add-animation-key editor :time 1d0)
    (is (= 3 (length (sg:track-keys track))))
    (is (vector-approximately= #(7d0 2d0 0d0) (second (nth 1 (sg:track-keys track)))))
    (sgeo.editor:undo-edit editor)
    (is (= 2 (length (sg:track-keys track))))
    (is (eq track (first (sg:clip-tracks clip))))
    (sgeo.editor:redo-edit editor)
    (is (= 3 (length (sg:track-keys track))))
    (sgeo.editor:move-animation-key editor 1.25d0 :index 1)
    (is (approximately= 1.25d0 (first (nth 1 (sg:track-keys track)))))
    (signals error (sgeo.editor:move-animation-key editor 2d0 :index 1))
    (is (approximately= 1.25d0 (first (nth 1 (sg:track-keys track)))))
    (sgeo.editor:delete-animation-key editor :index 1)
    (is (= 2 (length (sg:track-keys track))))
    (sgeo.editor:undo-edit editor)
    (is (= 3 (length (sg:track-keys track))))
    (signals error
      (sgeo.editor:with-edit-transaction (editor "Failed key edit")
        (sg:set-track-keys track '((0d0 #(9d0 0d0 0d0)) (4d0 #(8d0 0d0 0d0))))
        (setf (sg:clip-duration clip) 4d0)
        (error "Rollback exigido.")))
    (is (= 3 (length (sg:track-keys track))))
    (is (approximately= 2d0 (sg:clip-duration clip)))))

(test timeline-deleting-last-key-restores-base-and-undo-redo-track-identity
  (let* ((world (sg:make-world))
         (node (sg:make-scene-object :name "Base"))
         (editor (sgeo.editor:make-editor :world world)))
    (sg:add-to-world world node)
    (sg:set-position node #(5d0 0d0 0d0))
    (sgeo.editor:editor-select editor node)
    (let* ((clip (sgeo.editor:create-editor-animation editor))
           (track (first (sg:clip-tracks clip))))
      (sg:set-track-keys track '((0d0 #(5d0 0d0 0d0)) (2d0 #(15d0 0d0 0d0))))
      (sgeo.editor:scrub-animation editor 2d0)
      (is (approximately= 15d0 (sg:vx (sg:transform-position
                                       (sg:scene-object-local-transform node)))))
      (sgeo.editor:delete-animation-key editor :track track :index 1)
      (sgeo.editor:delete-animation-key editor :track track :index 0)
      (is (null (sg:clip-tracks clip)))
      (is (approximately= 5d0 (sg:vx (sg:transform-position
                                      (sg:scene-object-local-transform node)))))
      (sgeo.editor:undo-edit editor)
      (is (eq track (first (sg:clip-tracks clip))))
      (is (approximately= 5d0 (sg:vx (sg:transform-position
                                      (sg:scene-object-local-transform node)))))
      (sgeo.editor:redo-edit editor)
      (is (null (sg:clip-tracks clip)))
      (is (approximately= 5d0 (sg:vx (sg:transform-position
                                      (sg:scene-object-local-transform node))))))))

(test timeline-created-clip-is-undoable
  (multiple-value-bind (editor node clip track) (%timeline-test-scene)
    (declare (ignore node track))
    (is (member clip (getf (sgeo.editor:timeline-data editor) :clips)))
    (sgeo.editor:undo-edit editor)
    (is (null (getf (sgeo.editor:timeline-data editor) :clips)))
    (sgeo.editor:redo-edit editor)
    (is (eq clip (getf (sgeo.editor:timeline-data editor) :clip)))))

(test timeline-nonlooping-player-stops-at-clip-end
  (multiple-value-bind (editor node clip track) (%timeline-test-scene)
    (declare (ignore node clip track))
    (let ((player (sgeo.editor:editor-animation-player editor)))
      (setf (sg:player-looping-p player) nil)
      (sgeo.editor:execute-editor-command editor :play)
      (sgeo.editor:advance-editor-time editor 3d0)
      (is (approximately= 2d0 (sg:player-time player)))
      (is (not (sg:player-playing-p player)))
      (sgeo.editor:advance-editor-time editor 1d0)
      (is (approximately= 2d0 (sg:player-time player))))))

(test editor-orthographic-fit-follows-the-deformed-pose
  (let* ((world (sg:make-world))
         (mesh (sg:make-triangle-mesh
                :positions #(0d0 0d0 0d0 1d0 0d0 0d0 0d0 1d0 0d0) :indices #(0 1 2)))
         (morph (sg:make-morph-target
                 :positions #(0d0 4d0 0d0 0d0 4d0 0d0 0d0 4d0 0d0)))
         (object (sg:make-deformable-mesh-object :geometry mesh :skeleton nil
                   :morph-targets (vector morph) :morph-weights #(1d0))))
    (sg:add-to-world world object)
    (sgeo.editor:editor-view-camera world :front)
    (is (approximately= 4.5d0 (sg:vy (sg:camera-target (sg:world-camera world)))))
    (sg:set-morph-weights object #(0d0))
    (sgeo.editor:editor-view-camera world :front)
    (is (approximately= 0.5d0 (sg:vy (sg:camera-target (sg:world-camera world)))))))
