(in-package #:sgeo.tests)
(in-suite sgeo-suite)

(defun %animation-persistence-world ()
  "Constrói uma cena com bind compartilhado, morphs e uma camada parcial."
  (let* ((world (sg:make-world)) (joint (sg:make-scene-object :name "Joint"))
         (skeleton (sg:make-skeleton :joints (vector joint)))
         (mesh (sg:make-triangle-mesh :positions #(0d0 0d0 0d0 1d0 0d0 0d0 0d0 1d0 0d0) :indices #(0 1 2)))
         (target (sg:make-morph-target :positions #(0d0 0d0 1d0 0d0 0d0 0d0 0d0 0d0 0d0)))
         (a (sg:make-deformable-mesh-object :name "Skin A" :geometry mesh :skeleton skeleton
               :morph-targets (vector target) :morph-weights #(0.4d0)))
         (b (sg:make-deformable-mesh-object :name "Skin B" :geometry mesh :skeleton skeleton))
         (track (sg:make-property-track joint '(:position) '((0d0 #(0d0 0d0 0d0)) (2d0 #(2d0 0d0 0d0)))))
         (clip (sg:make-animation-clip :name "Walk" :tracks (list track)))
         (player nil))
    (mapc (lambda (object) (sg:add-to-world world object)) (list joint a b))
    (setf player (sg:play-animation world clip :weight 0.5d0 :looping-p nil))
    (sg:seek-animation player 1d0)
    (setf (sg:player-playing-p player) nil)
    (values world a b player)))

(test animation-scene-roundtrip-retains-editable-authority
  (multiple-value-bind (world a b player) (%animation-persistence-world)
    (declare (ignore b player))
    (let* ((data (sgeo.serialization:scene-data world))
           (loaded (sgeo.serialization:world-from-data data))
           (new-a (sg:find-object loaded "Skin A")) (new-b (sg:find-object loaded "Skin B"))
           (state (sg:world-animation-state loaded))
           (new-player (first (sg:animation-state-players state))))
      (is (= 2 (getf (rest data) :version)))
      (is (typep new-a 'sg:deformable-mesh-object))
      (is (eq (sg:mesh-skeleton new-a) (sg:mesh-skeleton new-b)))
      (is (eq (sg:mesh-object-geometry new-a) (sg:mesh-object-geometry new-b)))
      (is (not (eq new-a a)))
      (is (vector-approximately= (sg:render-mesh-positions (sg:deformed-render-data a))
                                 (sg:render-mesh-positions (sg:deformed-render-data new-a))))
      (is (approximately= 1d0 (sg:player-time new-player)))
      (is (not (sg:player-playing-p new-player)))
      (sg:seek-animation new-player 2d0)
      (is (approximately= 1d0 (sg:vx (sg:transform-position
                                     (sg:scene-object-local-transform (sg:find-object loaded "Joint"))))))
      (sg:set-mesh-position (sg:mesh-object-geometry new-a) 0 #(0d0 0.2d0 0d0))
      (is (approximately= 0.2d0 (aref (sg:render-mesh-positions (sg:deformed-render-data new-a)) 1))))))

(test animation-scene-rejects-invalid-references-and-code-paths
  (multiple-value-bind (world a b player) (%animation-persistence-world)
    (declare (ignore a b player))
    (let* ((data (sgeo.serialization:scene-data world))
           (animation (getf (rest data) :animation)))
      (setf (getf (first (getf animation :deformations)) :object-id) 9999999)
      (signals sg:validation-error (sgeo.serialization:world-from-data data)))
    (let ((track (sg:make-property-track (sg:find-object world "Joint")
                  (list (list 'funcall (lambda (object) (declare (ignore object)) 0d0)
                                      (lambda (object value) (declare (ignore object value)))))
                  '((0d0 0d0) (1d0 1d0)))))
      (sg:add-animation-clip world (sg:make-animation-clip :tracks (list track)))
      (signals sg:validation-error (sgeo.serialization:scene-data world)))))

(test animation-scene-prevalidates-deformation-arities-and-types
  (multiple-value-bind (world a b player) (%animation-persistence-world)
    (declare (ignore a b player))
    (dolist (mutate
             (list
              (lambda (data record) (setf (getf record :object-id) (getf (rest data) :root-id)))
              (lambda (data record) (declare (ignore data)) (setf (getf record :joint-indices) '((0))))
              (lambda (data record) (declare (ignore data)) (setf (first (first (getf record :joint-indices))) 500))
              (lambda (data record) (declare (ignore data)) (setf (getf record :morph-weights) '(0d0 1d0)))
              (lambda (data record) (declare (ignore data))
                (when (getf record :morph-targets)
                  (setf (getf (first (getf record :morph-targets)) :positions) '(0d0 0d0 0d0))))))
      (let* ((data (sgeo.serialization:scene-data world))
             (records (getf (getf (rest data) :animation) :deformations))
             (record (or (find-if (lambda (r) (getf r :morph-targets)) records) (first records))))
        (funcall mutate data record)
        (signals sg:validation-error (sgeo.serialization:world-from-data data))))))
