(in-package #:sgeo.tests)
(in-suite sgeo-suite)

(test editor-orthographic-zoom-changes-visible-scale
  (let* ((camera (sg:make-camera :eye #(0d0 0d0 5d0) :target #(0d0 0d0 0d0)
                                :projection-mode :orthographic :orthographic-height 4d0))
         (world (sg:make-world :camera camera))
         (eye (sg:camera-eye camera))
         (point #(1d0 0d0 0d0))
         (before (sgeo.editor:projected-position world point 200d0 200d0)))
    (sg:zoom-camera camera (log 0.5d0))
    (is (vector-approximately= eye (sg:camera-eye camera)))
    (is (approximately= (* 2d0 (- before 99.5d0))
                        (- (sgeo.editor:projected-position world point 200d0 200d0) 99.5d0)))))
(in-suite sgeo-suite)

(defun %editor-test-world (&optional (view :front))
  (let* ((world (sgeo.scene:make-world))
         (geometry (sgeo.geometry:make-half-edge-box))
         (object (sgeo.scene:make-mesh-object geometry :name "Caixa de seleção")))
    (sgeo.scene:add-to-world world object)
    (sgeo.editor:editor-view-camera world view :extent 4d0)
    (values world object geometry)))

(test editor-orthographic-views-project-and-pick
  (multiple-value-bind (world object geometry) (%editor-test-world :front)
    (declare (ignore geometry))
    (multiple-value-bind (x y depth)
        (sgeo.editor:projected-position world #(0d0 0d0 0d0) 100d0 100d0)
      (is (approximately= 49.5d0 x))
      (is (approximately= 49.5d0 y))
      (is (plusp depth)))
    (multiple-value-bind (picked elements)
        (sgeo.editor:pick-element world :object 49.5d0 49.5d0 100d0 100d0)
      (is (eq object picked))
      (is (null elements)))
    (multiple-value-bind (picked faces)
        (sgeo.editor:pick-element world :face 49.5d0 49.5d0 100d0 100d0)
      (is (eq object picked))
      (is (= 1 (length faces)))
      (is (eq :face (sgeo.geometry:handle-kind (first faces)))))
    (multiple-value-bind (picked region)
        (sgeo.editor:pick-element world :region 49.5d0 49.5d0 100d0 100d0)
      (is (eq object picked))
      (is (= 6 (length region))))
    (sgeo.editor:editor-view-camera world :top :extent 4d0)
    (multiple-value-bind (x y depth)
        (sgeo.editor:projected-position world #(0d0 0d0 0d0) 100d0 100d0)
      (is (approximately= 49.5d0 x))
      (is (approximately= 49.5d0 y))
      (is (plusp depth)))
    (sgeo.editor:editor-view-camera world :side :extent 4d0)
    (multiple-value-bind (x y depth)
        (sgeo.editor:projected-position world #(0d0 0d0 0d0) 100d0 100d0)
      (is (approximately= 49.5d0 x))
      (is (approximately= 49.5d0 y))
      (is (plusp depth)))
    (let ((eye-before (sgeo.scene:camera-eye (sgeo.scene:world-camera world))))
      (multiple-value-bind (x y depth)
          (sgeo.editor:projected-position world #(0d0 0d0 0d0) 100d0 100d0 :view :front)
        (is (approximately= 49.5d0 x))
        (is (approximately= 49.5d0 y))
        (is (plusp depth)))
      (multiple-value-bind (picked elements)
          (sgeo.editor:pick-element world :object 49.5d0 49.5d0 100d0 100d0 :view :front)
        (is (eq object picked))
        (is (null elements)))
      (is (equalp eye-before (sgeo.scene:camera-eye (sgeo.scene:world-camera world)))))))

(test editor-element-picking-respects-projection-and-pixel-radius
  (multiple-value-bind (world object geometry) (%editor-test-world :front)
    (let* ((front-vertex (find-if (lambda (vertex)
                                    (let ((point (sgeo.geometry:vertex-position geometry vertex)))
                                      (and (plusp (sgeo.math:vy point))
                                           (plusp (sgeo.math:vz point)))))
                                  (sgeo.geometry:mesh-vertices geometry)))
           (front-position (sgeo.geometry:vertex-position geometry front-vertex)))
      (multiple-value-bind (x y depth)
          (sgeo.editor:projected-position world front-position 100d0 100d0)
        (declare (ignore depth))
        (multiple-value-bind (picked elements)
            (sgeo.editor:pick-element world :vertex x y 100d0 100d0 :radius 2d0)
          (is (eq object picked))
          (is (equalp front-vertex (first elements))))
        (multiple-value-bind (picked elements)
            (sgeo.editor:pick-element world :vertex 49.5d0 49.5d0 100d0 100d0 :radius 1d0)
          (is (null picked))
          (is (null elements))))
      (multiple-value-bind (x y depth)
          (sgeo.editor:projected-position world #(0d0 0.5d0 0.5d0) 100d0 100d0)
        (declare (ignore depth))
        (multiple-value-bind (picked elements)
            (sgeo.editor:pick-element world :edge x y 100d0 100d0 :radius 2d0)
          (is (eq object picked))
          (is (= 1 (length elements)))
          (is (eq :edge (sgeo.geometry:handle-kind (first elements)))))))))

(test editor-selection-applies-world-transforms-and-occlusion
  (let* ((world (sgeo.scene:make-world))
         (front (sgeo.scene:make-mesh-object (sgeo.geometry:make-half-edge-box)
                                             :name "Frente" :position #(0d0 0d0 1d0)
                                             :scale #(0.5d0 0.5d0 0.5d0)))
         (back (sgeo.scene:make-mesh-object (sgeo.geometry:make-half-edge-box)
                                            :name "Fundo" :position #(0d0 0d0 -1d0))))
    (sgeo.scene:add-to-world world front)
    (sgeo.scene:add-to-world world back)
    (sgeo.editor:editor-view-camera world :front :extent 4d0)
    (multiple-value-bind (picked elements)
        (sgeo.editor:pick-element world :object 49.5d0 49.5d0 100d0 100d0)
      (is (eq front picked))
      (is (null elements)))
    (multiple-value-bind (picked elements)
        (sgeo.editor:pick-element world :object 49.5d0 49.5d0 100d0 100d0 :object back)
      (is (null picked))
      (is (null elements)))
    (setf (sgeo.scene:scene-object-visible-p front) nil)
    (multiple-value-bind (picked elements)
        (sgeo.editor:pick-element world :object 49.5d0 49.5d0 100d0 100d0)
      (is (eq back picked))
      (is (null elements)))
    (setf (sgeo.scene:scene-object-visible-p front) t
          (sgeo.scene:scene-object-enabled-p front) nil)
    (multiple-value-bind (picked elements)
        (sgeo.editor:pick-element world :object 49.5d0 49.5d0 100d0 100d0)
      (is (eq back picked))
      (is (null elements)))))

(test editor-perspective-camera-rays-and-clipping
  (let* ((world (sgeo.scene:make-world))
         (object (sgeo.scene:make-mesh-object (sgeo.geometry:make-half-edge-box)))
         (camera (sgeo.scene:world-camera world)))
    (sgeo.scene:add-to-world world object)
    (sgeo.scene:set-camera-frame camera #(0d0 0d0 5d0) #(0d0 0d0 0d0) #(0d0 1d0 0d0))
    (sgeo.scene:set-camera-projection camera :perspective)
    (multiple-value-bind (picked faces)
        (sgeo.editor:pick-element world :face 49.5d0 49.5d0 100d0 100d0)
      (is (eq object picked))
      (is (= 1 (length faces))))
    (multiple-value-bind (x y depth)
        (sgeo.editor:projected-position world #(0d0 0d0 0d0) 100d0 100d0)
      (is (approximately= 49.5d0 x))
      (is (approximately= 49.5d0 y))
      (is (approximately= 5d0 depth)))
    (let ((near-object (sgeo.scene:make-mesh-object (sgeo.geometry:make-half-edge-box)
                                                    :position #(0d0 0d0 4.998d0)
                                                    :scale #(0.001d0 0.001d0 0.001d0))))
      (sgeo.scene:add-to-world world near-object)
      (multiple-value-bind (picked elements)
          (sgeo.editor:pick-element world :object 49.5d0 49.5d0 100d0 100d0)
        (is (eq object picked))
        (is (null elements))))
    (let ((far-object (sgeo.scene:make-mesh-object (sgeo.geometry:make-half-edge-box)
                                                   :position #(0d0 0d0 -2000d0))))
      (sgeo.scene:add-to-world world far-object)
      (multiple-value-bind (picked elements)
          (sgeo.editor:pick-element world :object 49.5d0 49.5d0 100d0 100d0)
        (is (eq object picked))
        (is (null elements))))))

(test editor-orthographic-projection-and-camera-rays
  (let* ((camera (sgeo.scene:make-camera :projection-mode :orthographic
                                         :orthographic-height 4d0
                                         :eye #(0d0 0d0 5d0) :target #(0d0 0d0 0d0)))
         (center (sgeo.scene:camera-ray camera 49.5d0 49.5d0 100d0 100d0))
         (corner (sgeo.scene:camera-ray camera 0d0 0d0 100d0 100d0)))
    (is (eq :orthographic (sgeo.scene:camera-projection-mode camera)))
    (is (approximately= 4d0 (sgeo.scene:camera-orthographic-height camera)))
    (is (approximately= 0d0 (sgeo.math:vx (sgeo.math:ray-origin center))))
    (is (approximately= 0d0 (sgeo.math:vy (sgeo.math:ray-origin center))))
    (is (approximately= (* 1.98d0 (sqrt 2d0)) (sgeo.math:vector-length
                               (sgeo.math:v- (sgeo.math:ray-origin corner)
                                             (sgeo.math:ray-origin center)))
                          1d-6))
    (is (approximately= 1d0 (sgeo.math:vector-length (sgeo.math:ray-direction center))))
    (is (approximately= 0d0 (sgeo.math:vx (sgeo.math:ray-direction center))))
    (is (approximately= -1d0 (sgeo.math:vz (sgeo.math:ray-direction center))))))

(test orthographic-camera-setters-validate-and-touch-revisions
  (let* ((camera (sgeo.scene:make-camera))
         (revision (sgeo.core:object-revision camera)))
    (signals sgeo.core:validation-error
      (sgeo.scene:make-camera :projection-mode :orthographic :orthographic-height 0d0))
    (sgeo.scene:set-camera-projection camera :orthographic :height 8d0)
    (is (eq :orthographic (sgeo.scene:camera-projection-mode camera)))
    (is (approximately= 8d0 (sgeo.scene:camera-orthographic-height camera)))
    (is (= (1+ revision) (sgeo.core:object-revision camera)))
    (let ((revision (sgeo.core:object-revision camera)))
      (signals sgeo.core:validation-error
        (sgeo.scene:set-camera-projection camera :diagonal :height 2d0))
      (signals sgeo.core:validation-error
        (sgeo.scene:set-camera-projection camera :orthographic :height 0d0))
      (is (= revision (sgeo.core:object-revision camera)))
      (is (eq :orthographic (sgeo.scene:camera-projection-mode camera)))
      (is (approximately= 8d0 (sgeo.scene:camera-orthographic-height camera)))))
  (let* ((matrix (sgeo.math:orthographic-mat4 -2d0 2d0 -1d0 1d0 0.1d0 100d0))
         (near-center (sgeo.math:transform-point matrix #(0d0 0d0 -0.1d0)))
         (far-center (sgeo.math:transform-point matrix #(0d0 0d0 -100d0))))
    (is (approximately= 0d0 (sgeo.math:vx near-center)))
    (is (approximately= 0d0 (sgeo.math:vy near-center)))
    (is (approximately= -1d0 (sgeo.math:vz near-center)))
    (is (approximately= 1d0 (sgeo.math:vz far-center)))))

(test editor-view-switch-uses-valid-atomic-camera-frames
  (multiple-value-bind (world object) (%editor-test-world :front)
    (declare (ignore object))
    (let* ((camera (sgeo.scene:world-camera world))
           (revision (sgeo.core:object-revision camera)))
      (sgeo.editor:editor-view-camera world :top :extent 3d0)
      (is (eq :orthographic (sgeo.scene:camera-projection-mode camera)))
      (is (= (+ revision 2) (sgeo.core:object-revision camera)))
      (is (approximately= 3d0 (sgeo.scene:camera-orthographic-height camera)))
      (multiple-value-bind (x y depth)
          (sgeo.editor:projected-position world #(0d0 0d0 0d0) 100d0 100d0)
        (is (approximately= 49.5d0 x))
        (is (approximately= 49.5d0 y))
        (is (plusp depth))))))
