(in-package #:sgeo.tests)
(in-suite sgeo-suite)

(defun %count-value (mesh key)
  (getf (sgeo.geometry:mesh-counts mesh) key))

(defun %triangle-area-from-handles (mesh triangle)
  (let* ((a (sgeo.geometry:vertex-position mesh (first triangle)))
         (b (sgeo.geometry:vertex-position mesh (second triangle)))
         (c (sgeo.geometry:vertex-position mesh (third triangle))))
    (/ (sgeo.math:vector-length (sgeo.math:cross (sgeo.math:v- b a) (sgeo.math:v- c a))) 2d0)))

(defun %face-centroid (mesh face)
  (let* ((vertices (sgeo.geometry:face-vertices mesh face))
         (sum (loop with sum = (sgeo.math:make-vec3)
                    for vertex in vertices
                    do (setf sum (sgeo.math:v+ sum (sgeo.geometry:vertex-position mesh vertex)))
                    finally (return sum))))
    (sgeo.math:v* (/ 1d0 (length vertices)) sum)))

(test half-edge-primitives-counts-and-euler-characteristics
  (let* ((box (sgeo.geometry:make-half-edge-box))
         (sphere (sgeo.geometry:make-sphere :segments 12 :rings 6))
         (cylinder (sgeo.geometry:make-cylinder :segments 12))
         (open-cylinder (sgeo.geometry:make-cylinder :segments 8 :capped-p nil))
         (grid (sgeo.geometry:make-grid :columns 4 :rows 3))
         (torus (sgeo.geometry:make-torus :segments 12 :sides 8)))
    (is (= 8 (%count-value box :vertices)))
    (is (= 12 (%count-value box :edges)))
    (is (= 6 (%count-value box :faces)))
    (is (= 2 (- (+ (%count-value box :vertices) (%count-value box :faces)) (%count-value box :edges))))
    (is (= 62 (%count-value sphere :vertices)))
    (is (= 132 (%count-value sphere :edges)))
    (is (= 72 (%count-value sphere :faces)))
    (is (= 2 (- (+ (%count-value sphere :vertices) (%count-value sphere :faces)) (%count-value sphere :edges))))
    (is (zerop (%count-value cylinder :boundary-edges)))
    (is (= 2 (length (sgeo.geometry:boundary-loops open-cylinder))))
    (is (= 10 (%count-value grid :boundary-edges)))
    (is (= 0 (- (+ (%count-value torus :vertices) (%count-value torus :faces)) (%count-value torus :edges))))
    (is (zerop (%count-value torus :boundary-edges))))
  (let ((sphere (sgeo.geometry:make-sphere :segments 8 :rings 4))
        (cylinder (sgeo.geometry:make-cylinder :segments 8))
        (grid (sgeo.geometry:make-grid :columns 3 :rows 3))
        (torus (sgeo.geometry:make-torus :segments 8 :sides 6)))
    (dolist (face (sgeo.geometry:mesh-faces sphere))
      (is (plusp (sgeo.math:dot (sgeo.geometry:face-normal sphere face) (%face-centroid sphere face)))))
    (dolist (face (sgeo.geometry:mesh-faces cylinder))
      (let* ((normal (sgeo.geometry:face-normal cylinder face))
             (center (%face-centroid cylinder face)))
        (if (> (abs (sgeo.math:vy normal)) 0.9d0)
            (is (plusp (* (sgeo.math:vy normal) (sgeo.math:vy center))))
            (is (plusp (+ (* (sgeo.math:vx normal) (sgeo.math:vx center))
                          (* (sgeo.math:vz normal) (sgeo.math:vz center)))))))
    (dolist (face (sgeo.geometry:mesh-faces grid))
      (is (plusp (sgeo.math:vy (sgeo.geometry:face-normal grid face)))))
    (dolist (face (sgeo.geometry:mesh-faces torus))
      (let* ((center (%face-centroid torus face))
             (radius (sqrt (+ (* (sgeo.math:vx center) (sgeo.math:vx center))
                              (* (sgeo.math:vz center) (sgeo.math:vz center)))))
             (ring-center (sgeo.math:make-vec3 (* 2d0 (/ (sgeo.math:vx center) radius)) 0d0
                                               (* 2d0 (/ (sgeo.math:vz center) radius)))))
        (is (plusp (sgeo.math:dot (sgeo.geometry:face-normal torus face)
                                  (sgeo.math:v- center ring-center)))))))
  (let* ((box (sgeo.geometry:make-half-edge-box))
         (faces (sgeo.geometry:mesh-faces box)))
    (dolist (face faces)
      (let* ((normal (sgeo.geometry:face-normal box face))
             (center (loop with sum = (sgeo.math:make-vec3)
                           for vertex in (sgeo.geometry:face-vertices box face)
                           for position = (sgeo.geometry:vertex-position box vertex)
                           do (setf sum (sgeo.math:v+ sum position))
                           finally (return (sgeo.math:v* (/ 1d0 (length (sgeo.geometry:face-vertices box face))) sum)))))
        (is (> (sgeo.math:dot normal center) 0d0)))))))

(test polygon-ear-clipping-preserves-area-and-winding
  (let* ((mesh (sgeo.geometry:make-half-edge-mesh
                :positions #((0d0 0d0 0d0) (2d0 0d0 0d0) (2d0 0d0 2d0)
                             (1d0 0d0 1d0) (0d0 0d0 2d0))
                :faces '((0 1 2 3 4))))
         (face (first (sgeo.geometry:mesh-faces mesh)))
         (triangles (sgeo.geometry:triangulate-face mesh face))
         (again (sgeo.geometry:triangulate-face mesh face)))
    (is (= 3 (length triangles)))
    (is (equal (mapcar (lambda (triangle) (mapcar #'sgeo.geometry:handle-index triangle)) triangles)
               (mapcar (lambda (triangle) (mapcar #'sgeo.geometry:handle-index triangle)) again)))
    (is (approximately= 3d0 (loop for triangle in triangles sum (%triangle-area-from-handles mesh triangle))))
    (dolist (triangle triangles)
      (let* ((a (sgeo.geometry:vertex-position mesh (first triangle)))
             (b (sgeo.geometry:vertex-position mesh (second triangle)))
             (c (sgeo.geometry:vertex-position mesh (third triangle))))
        (is (minusp (sgeo.math:vy (sgeo.math:cross (sgeo.math:v- b a) (sgeo.math:v- c a))))))
    (let* ((data (sgeo.core:compile-render-data mesh))
           (source-faces (sgeo.geometry:render-mesh-source-faces data)))
      (is (= 3 (length source-faces)))
      (is (every (lambda (source) (eq (sgeo.geometry:handle-kind source) :face)) source-faces)))
    (let ((translated (sgeo.geometry:make-half-edge-mesh
                       :positions #((1000000000d0 0d0 1000000000d0)
                                    (1000000002d0 0d0 1000000000d0)
                                    (1000000002d0 0d0 1000000002d0)
                                    (1000000001d0 0d0 1000000001d0)
                                    (1000000000d0 0d0 1000000002d0))
                       :faces '((0 1 2 3 4)))))
      (is (approximately= 3d0 (sgeo.geometry:mesh-surface-area translated)))))
  (let* ((mesh (sgeo.geometry:make-half-edge-mesh
                :positions #((0d0 0d0 0d0) (1d0 0d0 0d0) (2d0 0d0 0d0)
                             (2d0 0d0 1d0) (0d0 0d0 1d0))
                :faces '((0 1 2 3 4))))
         (triangles (sgeo.geometry:triangulate-face mesh (first (sgeo.geometry:mesh-faces mesh))))
           (data (sgeo.core:compile-render-data mesh)))
    (is (= 3 (length triangles)))
    (is (approximately= 2d0 (sgeo.geometry:face-area mesh (first (sgeo.geometry:mesh-faces mesh)))))
    (is (= 15 (length (sgeo.geometry:render-mesh-positions data))))
    (is (= 9 (length (sgeo.geometry:render-mesh-indices data))))
    (is (every (lambda (index) (< index 5)) (sgeo.geometry:render-mesh-indices data)))
    (is (= 3 (length (sgeo.geometry:render-mesh-source-faces data))))
    (is (approximately= -1d0 (sgeo.math:vy (sgeo.math:make-vec3
                                             (aref (sgeo.geometry:render-mesh-normals data) 0)
                                             (aref (sgeo.geometry:render-mesh-normals data) 1)
                                             (aref (sgeo.geometry:render-mesh-normals data) 2))))))))

(test polygon-geometry-rejects-invalid-faces
  (signals sgeo.geometry:topology-error
    (sgeo.geometry:make-half-edge-mesh
     :positions #((0d0 0d0 0d0) (1d0 0d0 1d0) (0d0 0d0 1d0) (1d0 0d0 0d0))
     :faces '((0 1 2 3))))
  (signals sgeo.geometry:topology-error
    (sgeo.geometry:make-half-edge-mesh
     :positions #((0d0 0d0 0d0) (1d0 0d0 0d0) (2d0 0d0 0d0)) :faces '((0 1 2))))
  (signals sgeo.core:validation-error (sgeo.geometry:make-sphere :radius 0d0))
  (signals sgeo.core:validation-error (sgeo.geometry:make-torus :major-radius 1d0 :minor-radius 1d0))
  (let* ((tiny (sgeo.geometry:make-half-edge-box :size 1d-8))
         (normal (sgeo.geometry:face-normal tiny (first (sgeo.geometry:mesh-faces tiny))))
         (data (sgeo.core:compile-render-data tiny)))
    (is (= 6 (%count-value tiny :faces)))
    (is (approximately= 1d0 (sgeo.math:vector-length normal)))
    (is (= 36 (length (sgeo.geometry:render-mesh-indices data))))
    (multiple-value-bind (distance face point)
        (sgeo.geometry:mesh-ray-intersection
         tiny (sgeo.math:make-ray #(0d0 0d0 5d-8) #(0d0 0d0 -1d0)))
      (is (approximately= 4.5d-8 distance 1d-14))
      (is (sgeo.geometry:mesh-handle-p face))
      (is (approximately= 5d-9 (sgeo.math:vz point) 1d-14)))))

(test polygon-queries-preserve-microscopic-scale
  (let* ((mesh (sgeo.geometry:make-half-edge-box :size 1d-16))
         (vertex (first (sgeo.geometry:mesh-vertices mesh)))
         (normal (sgeo.geometry:vertex-normal mesh vertex)))
    (is (approximately= 1d0 (sgeo.math:vector-length normal)))
    (multiple-value-bind (point distance face)
        (sgeo.geometry:closest-point-on-mesh mesh #(8d-17 8d-17 0d0))
      (is (sgeo.geometry:mesh-handle-p face))
      (is (< (abs (- (sgeo.math:vx point) 5d-17)) 1d-30))
      (is (< (abs (- (sgeo.math:vy point) 5d-17)) 1d-30))
      (is (< (abs (sgeo.math:vz point)) 1d-30))
      (is (< (abs (- distance (* (sqrt 2d0) 3d-17))) 1d-30)))))

(test concave-vertex-normal-uses-reflex-corner-angle
  (let* ((mesh (sg:make-half-edge-mesh
                :positions #((0 0 0) (2 0 0) (2 2 0) (1 1 0) (0 2 0) (1 1 1))
                :faces '((0 1 2 3 4) (3 2 5))))
         (corner (fourth (sg:mesh-vertices mesh)))
         (normal (sg:vertex-normal mesh corner))
         (expected (sg:normalize (sg:vec3 (/ 1d0 (sqrt 2d0)) (/ -1d0 (sqrt 2d0)) 3d0))))
    ;; O ângulo de 270 graus da face côncava pesa três vezes o canto de 90 graus.
    (is (vector-approximately= normal expected))))

(test polygon-surface-queries-and-read-copies
  (let* ((mesh (sgeo.geometry:make-half-edge-box))
         (ray (sgeo.math:make-ray #(0d0 0d0 2d0) #(0d0 0d0 -1d0))))
    (multiple-value-bind (distance face point) (sgeo.geometry:mesh-ray-intersection mesh ray)
      (is (approximately= 1.5d0 distance))
      (is (sgeo.geometry:mesh-handle-p face))
      (is (approximately= 0.5d0 (sgeo.math:vz point))))
    (multiple-value-bind (point distance face) (sgeo.geometry:closest-point-on-mesh mesh #(0d0 0d0 0d0))
      (is (approximately= 0.5d0 distance))
      (is (sgeo.geometry:mesh-handle-p face))
      (is (approximately= 0.5d0 (abs (sgeo.math:vz point)))))
    (is (approximately= 6d0 (sgeo.geometry:mesh-surface-area mesh)))
    (let* ((vertex (first (sgeo.geometry:mesh-vertices mesh)))
           (normal (sgeo.geometry:vertex-normal mesh vertex)))
      (is (approximately= 1d0 (sgeo.math:vector-length normal))))
    (multiple-value-bind (point distance face) (sgeo.geometry:closest-point-on-mesh mesh #(0.8d0 0.8d0 0.8d0))
      (is (approximately= (sqrt 0.27d0) distance))
      (is (sgeo.geometry:mesh-handle-p face))
      (is (and (approximately= 0.5d0 (sgeo.math:vx point))
               (approximately= 0.5d0 (sgeo.math:vy point))
               (approximately= 0.5d0 (sgeo.math:vz point))))
      (multiple-value-bind (edge-point edge-distance edge-face)
          (sgeo.geometry:closest-point-on-mesh mesh #(0.8d0 0.8d0 0d0))
        (is (approximately= (sqrt 0.18d0) edge-distance))
        (is (sgeo.geometry:mesh-handle-p edge-face))
        (is (and (approximately= 0.5d0 (sgeo.math:vx edge-point))
                 (approximately= 0.5d0 (sgeo.math:vy edge-point))
                 (approximately= 0d0 (sgeo.math:vz edge-point))))))
    (signals sgeo.core:validation-error (sgeo.geometry:closest-point-on-mesh mesh #(0d0 1d0)))
    (signals sgeo.core:validation-error
      (sgeo.geometry:closest-point-on-mesh mesh #2A((0d0 0d0 0d0))))
    (multiple-value-bind (distance face point)
        (sgeo.geometry:mesh-ray-intersection mesh (sgeo.math:make-ray #(2d0 2d0 2d0) #(0d0 0d0 -1d0)))
      (is (null distance))
      (is (null face))
      (is (null point)))
    (let* ((vertex (first (sgeo.geometry:mesh-vertices mesh)))
           (position (sgeo.geometry:vertex-position mesh vertex)))
      (setf (aref position 0) 1000d0)
      (is (< (abs (sgeo.math:vx (sgeo.geometry:vertex-position mesh vertex))) 1d0)))
    (let* ((data (sgeo.core:compile-render-data mesh))
           (bounds (sgeo.core:bounds mesh)))
      (is (= 72 (length (sgeo.geometry:render-mesh-positions data))))
      (is (= 36 (length (sgeo.geometry:render-mesh-indices data))))
      (is (= 12 (length (sgeo.geometry:render-mesh-source-faces data))))
      (is (= (sgeo.core:object-revision mesh) (sgeo.geometry:render-mesh-revision data)))
      (is (approximately= -0.5d0 (sgeo.math:vx (sgeo.math:aabb-min bounds)))))))
