(in-package #:sgeo.tests)
(in-suite sgeo-suite)

(defun %same-handle-p (a b)
  (and (sg:mesh-handle-p a) (sg:mesh-handle-p b)
       (eq (sg:handle-kind a) (sg:handle-kind b))
       (= (sg:handle-index a) (sg:handle-index b))
       (= (sg:handle-generation a) (sg:handle-generation b))
       (= (sg:handle-mesh-id a) (sg:handle-mesh-id b))))

(defun %edge-between (mesh a b)
  (find-if (lambda (edge)
             (let ((ends (sg:edge-vertices mesh edge)))
               (or (and (%same-handle-p (first ends) a) (%same-handle-p (second ends) b))
                   (and (%same-handle-p (first ends) b) (%same-handle-p (second ends) a)))))
           (sg:mesh-edges mesh)))

(test kernel-edit-revision-and-rollback
  (let* ((mesh (sg:make-half-edge-mesh
                :positions (vector (sg:vec3 0 0 0) (sg:vec3 1 0 0) (sg:vec3 0 1 0))
                :faces '((0 1 2))))
         (vertex (first (sg:mesh-vertices mesh)))
         (before (mapcar (lambda (v) (sg:vertex-position mesh v)) (sg:mesh-vertices mesh)))
         (revision (sg:object-revision mesh)))
    (signals sg:geometry-error (sg:set-vertex-position mesh vertex (sg:vec3 1d0 0 0)))
    (is (= revision (sg:object-revision mesh)))
    (is (equalp before (mapcar (lambda (v) (sg:vertex-position mesh v)) (sg:mesh-vertices mesh))))
    (sg:set-vertex-position mesh vertex (sg:vec3 -1 0 0))
    (is (= (1+ revision) (sg:object-revision mesh)))
    (is (vector-approximately= #(-1 0 0) (sg:vertex-position mesh vertex)))))

(test split-boundary-edge-and-collapse-round-trip
  (let* ((mesh (sg:make-half-edge-mesh
                :positions (vector (sg:vec3 0 0 0) (sg:vec3 2 0 0)
                                   (sg:vec3 2 2 0) (sg:vec3 0 2 0))
                :faces '((0 1 2 3))))
         (vertices (sg:mesh-vertices mesh))
         (edge (%edge-between mesh (first vertices) (second vertices)))
         (new-vertex (sg:split-edge mesh edge :parameter 0.25d0)))
    (is (= 5 (getf (sg:mesh-counts mesh) :vertices)))
    (is (= 5 (length (sg:face-vertices mesh (first (sg:mesh-faces mesh))))))
    (is (vector-approximately= #(0.5d0 0 0) (sg:vertex-position mesh new-vertex)))
    (signals sg:stale-handle-error (sg:edge-vertices mesh edge))
    (let ((half-edge (%edge-between mesh (first vertices) new-vertex)))
      (sg:collapse-edge mesh half-edge :keep (first vertices) :position (sg:vec3 0 0 0)))
    (is (= 4 (getf (sg:mesh-counts mesh) :vertices)))
    (is (= 4 (length (sg:face-vertices mesh (first (sg:mesh-faces mesh))))))
    (signals sg:stale-handle-error (sg:vertex-position mesh new-vertex))))

(test face-region-extrusion-shares-topology-and-preserves-top-faces
  (let* ((mesh (sg:make-half-edge-mesh
                :positions (vector (sg:vec3 0 0 0) (sg:vec3 1 0 0) (sg:vec3 2 0 0)
                                   (sg:vec3 0 1 0) (sg:vec3 1 1 0) (sg:vec3 2 1 1))
                :faces '((0 1 4 3) (1 2 5 4))))
         (faces (sg:mesh-faces mesh))
         (tops (sg:extrude-face-region mesh faces :distance 0.5d0)))
    (is (= 2 (length tops)))
    (is (every (lambda (old new) (%same-handle-p old new)) faces tops))
    ;; Seis arestas de contorno geram seis paredes; a aresta interna não ganha parede duplicada.
    (is (= 8 (getf (sg:mesh-counts mesh) :faces)))
    (is (= 12 (getf (sg:mesh-counts mesh) :vertices)))
    (is (eq t (sg:validate-mesh mesh)))
    (signals sg:geometry-error (sg:extrude-face-region mesh (list (first (sg:mesh-faces mesh))
                                                                  (car (last (sg:mesh-faces mesh))))
                                                     :distance 0d0))))

(test single-face-extrusion-on-closed-box
  (let* ((mesh (sg:make-half-edge-box :size 2))
         (face (first (sg:mesh-faces mesh)))
         (faces-before (copy-list (sg:mesh-faces mesh)))
         (top (sg:extrude-face mesh face :distance 0.25d0)))
    (is (sg:mesh-handle-p top))
    (is (%same-handle-p face top))
    (is (= 10 (getf (sg:mesh-counts mesh) :faces)))
    (is (= 12 (getf (sg:mesh-counts mesh) :vertices)))
    (is (every (lambda (old) (member old (sg:mesh-faces mesh) :test #'%same-handle-p))
               faces-before))
    (is (eq t (sg:validate-mesh mesh)))))

(test interior-edge-split-and-collapse-preserve-solid
  (let* ((mesh (sg:make-half-edge-box))
         (edge (first (sg:mesh-edges mesh)))
         (endpoint (first (sg:edge-vertices mesh edge)))
         (position (sg:vertex-position mesh endpoint))
         (faces (sg:mesh-faces mesh))
         (revision (sg:object-revision mesh))
         (inserted (sg:split-edge mesh edge)))
    (is (= 9 (getf (sg:mesh-counts mesh) :vertices)))
    (is (= 13 (getf (sg:mesh-counts mesh) :edges)))
    (is (= 2 (count 5 faces :key (lambda (face) (length (sg:face-vertices mesh face))))))
    (is (null (sg:boundary-loops mesh)))
    (sg:collapse-edge mesh (%edge-between mesh endpoint inserted) :keep endpoint :position position)
    (is (= (+ revision 2) (sg:object-revision mesh)))
    (is (= 8 (getf (sg:mesh-counts mesh) :vertices)))
    (is (= 12 (getf (sg:mesh-counts mesh) :edges)))
    (is (every (lambda (face) (= 4 (length (sg:face-vertices mesh face)))) faces))
    (is (sg:validate-mesh mesh))))

(test collapse-invalid-solid-preserves-identities-and-render-data
  (let* ((mesh (sg:make-half-edge-mesh
                :positions #((0 0 0) (1 0 0) (0 1 0) (0 0 1))
                :faces '((0 2 1) (0 1 3) (1 2 3) (2 0 3))))
         (vertices (sg:mesh-vertices mesh)) (edges (sg:mesh-edges mesh))
         (faces (sg:mesh-faces mesh)) (half-edges (sg:mesh-half-edges mesh))
         (revision (sg:object-revision mesh))
         (data (sg:compile-render-data mesh)))
    ;; A contração de um tetraedro produziria duas faces com o mesmo ciclo.
    (signals sg:geometry-error (sg:collapse-edge mesh (first edges)))
    (is (= revision (sg:object-revision mesh)))
    (is (equalp vertices (sg:mesh-vertices mesh)))
    (is (equalp edges (sg:mesh-edges mesh)))
    (is (equalp faces (sg:mesh-faces mesh)))
    (is (equalp half-edges (sg:mesh-half-edges mesh)))
    (is (equalp (sg:render-mesh-positions data)
                (sg:render-mesh-positions (sg:compile-render-data mesh))))
    (is (sg:validate-mesh mesh))))

(test modeling-parameters-and-disconnected-region-are-atomic
  (let* ((mesh (sg:make-half-edge-box))
         (edge (first (sg:mesh-edges mesh)))
         (face (first (sg:mesh-faces mesh)))
         (opposite (second (sg:mesh-faces mesh)))
         (foreign-endpoint (find-if (lambda (vertex)
                                     (not (member vertex (sg:edge-vertices mesh edge) :test #'equalp)))
                                   (sg:mesh-vertices mesh)))
         (revision (sg:object-revision mesh))
         (counts (sg:mesh-counts mesh)))
    (signals sg:geometry-error (sg:split-edge mesh edge :parameter 0))
    (signals sg:geometry-error (sg:split-edge mesh edge :parameter 1))
    (signals sg:geometry-error (sg:collapse-edge mesh edge :keep foreign-endpoint))
    (signals sg:geometry-error (sg:extrude-face-region mesh nil))
    (signals sg:geometry-error (sg:extrude-face-region mesh (list face face)))
    (signals sg:geometry-error (sg:extrude-face-region mesh (list face opposite)))
    (signals sg:geometry-error (sg:extrude-face mesh face :offset '(0 0 0)))
    (signals sg:geometry-error (sg:extrude-face mesh face :offset '(1 0 0)))
    (signals sg:geometry-error (sg:extrude-face mesh face :distance (expt 10 1000)))
    (signals sg:geometry-error
      (sg:set-vertex-position mesh (first (sg:mesh-vertices mesh)) (list (expt 10 1000) 0 0)))
    (is (= revision (sg:object-revision mesh)))
    (is (equal counts (sg:mesh-counts mesh)))
    (is (sg:validate-mesh mesh))))

(test coplanar-grid-region-extrusion-retires-only-interior-vertices
  (let* ((mesh (sg:make-grid :columns 3 :rows 3))
         (old-vertices (sg:mesh-vertices mesh))
         (center (fifth old-vertices))
         (faces (sg:mesh-faces mesh))
         (tops (sg:extrude-face-region mesh faces :offset '(0 0.5d0 0))))
    (is (equalp faces tops))
    (is (= 17 (getf (sg:mesh-counts mesh) :vertices)))
    (is (= 12 (getf (sg:mesh-counts mesh) :faces)))
    (is (= 8 (length (first (sg:boundary-loops mesh)))))
    (signals sg:stale-handle-error (sg:vertex-position mesh center))
    (is (every (lambda (vertex) (sg:vertex-position mesh vertex))
               (remove center old-vertices :test #'equalp)))
    (is (sg:validate-mesh mesh))))

(test complete-closed-region-extrusion-retains-face-handles
  (let* ((mesh (sg:make-half-edge-box))
         (vertices (sg:mesh-vertices mesh))
         (faces (sg:mesh-faces mesh))
         (tops (sg:extrude-face-region mesh faces :distance 0.2d0)))
    (is (equalp faces tops))
    (is (= 8 (getf (sg:mesh-counts mesh) :vertices)))
    (is (= 6 (getf (sg:mesh-counts mesh) :faces)))
    (is (null (sg:boundary-loops mesh)))
    (dolist (vertex vertices)
      (signals sg:stale-handle-error (sg:vertex-position mesh vertex)))
    (is (sg:validate-mesh mesh))))

(test editable-mesh-render-snapshots-retain-captured-revision
  (let* ((mesh (sg:make-half-edge-box))
         (vertex (first (sg:mesh-vertices mesh)))
         (first-data (sg:compile-render-data mesh))
         (old-positions (copy-seq (sg:render-mesh-positions first-data))))
    (sg:set-vertex-position mesh vertex (sg:v+ (sg:vertex-position mesh vertex) (sg:vec3 -0.1d0 0 0)))
    (let ((second-data (sg:compile-render-data mesh)))
      (is (= (1+ (sg:render-mesh-revision first-data)) (sg:render-mesh-revision second-data)))
      (is (equalp old-positions (sg:render-mesh-positions first-data)))
      (is (not (equalp old-positions (sg:render-mesh-positions second-data))))
      (is (= 6 (length (sg:mesh-faces mesh))))
      (is (= 12 (length (sg:render-mesh-source-faces second-data)))))))

(test committed-edit-survives-invalidation-observer-failure
  (let* ((mesh (sg:make-half-edge-box))
         (vertex (first (sg:mesh-vertices mesh)))
         (position (sg:v+ (sg:vertex-position mesh vertex) (sg:vec3 -0.1d0 0 0)))
         (notified nil) (diagnosed nil))
    (sg:add-invalidation-observer mesh (lambda (object reason revision)
                                        (declare (ignore object reason))
                                        (setf notified revision)))
    (sg:add-invalidation-observer mesh (lambda (object reason revision)
                                        (declare (ignore object reason revision))
                                        (error "Falha intencional na notificação.")))
    (handler-bind ((warning (lambda (condition)
                             (setf diagnosed t)
                             (muffle-warning condition))))
      (sg:set-vertex-position mesh vertex position))
    (is (not (null diagnosed)))
    (is (= 1 notified))
    (is (= 1 (sg:object-revision mesh)))
    (is (vector-approximately= position (sg:vertex-position mesh vertex)))
    (is (sg:validate-mesh mesh))))
