(in-package #:sgeo.tests)
(in-suite sgeo-suite)

(test pbr-material-validates-entire-edit-before-publishing
  (let* ((material (sg:make-pbr-material :base-color #(0.8d0 0.2d0 0.1d0 1d0)
                                         :metallic 0.7d0 :roughness 0.25d0))
         (before (sg:pbr-material-data material)) (revision (sg:object-revision material)))
    (signals sg:validation-error
      (sg:set-pbr-material material :metallic 0.2d0 :roughness 1.1d0))
    (is (= revision (sg:object-revision material)))
    (is (equalp before (sg:pbr-material-data material)))
    (signals sg:validation-error (sg:set-pbr-material material :casts-shadow-p :yes))
    (let ((copy (sg:pbr-material-base-color material)))
      (setf (aref copy 0) 0d0)
      (is (= 0.8d0 (aref (sg:pbr-material-base-color material) 0))))
    (sg:set-pbr-material material :roughness 0d0 :emissive #(4d0 2d0 1d0))
    (is (> (sg:object-revision material) revision))
    (is (= 0d0 (sg:pbr-material-roughness material)))
    (is (equalp #(4d0 2d0 1d0) (sg:pbr-material-emissive material)))))

(test pbr-rgb-operation-preserves-alpha-and-validation
  (let* ((material (sg:make-pbr-material :base-color #(0.4d0 0.5d0 0.6d0 0.7d0)))
         (revision (sg:object-revision material)))
    (signals sg:validation-error (sg:set-material-color material #(2d0 0d0 0d0)))
    (is (= revision (sg:object-revision material)))
    (is (equalp #(0.4d0 0.5d0 0.6d0 0.7d0) (sg:pbr-material-base-color material)))
    (sg:set-material-color material #(0.2d0 0.3d0 0.4d0))
    (is (equalp #(0.2d0 0.3d0 0.4d0 0.7d0) (sg:pbr-material-base-color material)))))

(test pbr-scenes-roundtrip-materials-shared-resources-and-light
  (let* ((world (sg:make-world))
         (material (sg:make-pbr-material :name "Copper" :metallic 0.9d0 :roughness 0.2d0
                                        :emissive #(0.2d0 0.1d0 0d0) :casts-shadow-p nil))
         (geometry (sg:make-half-edge-box))
         (a (sg:make-mesh-object geometry :name "A" :material material))
         (b (sg:make-mesh-object geometry :name "B" :material material))
         (sun (sg:make-directional-light :name "Sun" :intensity 8d0 :shadow-extent 12d0)))
    (sg:add-to-world world a) (sg:add-to-world world b) (sg:add-to-world world sun)
    (let* ((data (sgeo.serialization:scene-data world))
           (copy (sgeo.serialization:world-from-data data))
           (ca (sg:find-object copy "A")) (cb (sg:find-object copy "B"))
           (cm (sg:mesh-object-material ca)))
      (is (typep cm 'sg:pbr-material))
      (is (eq cm (sg:mesh-object-material cb)))
      (is (eq (sg:mesh-object-geometry ca) (sg:mesh-object-geometry cb)))
      (is (equalp (sg:pbr-material-data material) (sg:pbr-material-data cm)))
      (let ((original (sg:directional-light-data sun))
            (reopened (sg:directional-light-data (sg:find-object copy "Sun"))))
        (is (vector-approximately= (getf original :direction) (getf reopened :direction)))
        (remf original :direction) (remf reopened :direction)
        (is (equalp original reopened))))
    (let ((data (sgeo.serialization:scene-data world)))
      (setf (getf (getf (first (getf (rest data) :materials)) :pbr) :metallic) 2d0)
      (signals sg:validation-error (sgeo.serialization:world-from-data data)))
    (let ((data (sgeo.serialization:scene-data world)))
      (setf (getf (first (getf (rest data) :materials)) :color) '(0d0 0d0 0d0))
      (signals sg:validation-error (sgeo.serialization:world-from-data data)))))

(test modern-scene-uniform-layout-and-normal-transform
  (let* ((world (sg:make-world))
         (object (sg:make-mesh-object (sg:make-half-edge-box)
                                     :material (sg:make-pbr-material :metallic 0.75d0 :roughness 0.4d0)
                                     :scale #(2d0 3d0 4d0)))
         (sun (sg:make-directional-light :intensity 5d0 :direction #(0d0 -1d0 0d0))))
    (sg:add-to-world world object) (sg:add-to-world world sun)
    (let* ((snapshot (sgeo.render:modern-scene-snapshot world :aspect 1.5d0 :shadow-size 512 :exposure 2d0))
           (entry (first (getf snapshot :objects)))
           (uniforms (sgeo.render:pack-frame-uniforms snapshot entry))
           (vertices (sgeo.render:interleave-render-mesh entry)))
      (is (= 96 (length uniforms)))
      (is (= 2f0 (aref uniforms 0)))
      (is (= 0.5f0 (aref uniforms 16)))
      (is (approximately= (/ 1d0 3d0) (aref uniforms 21) 1d-6))
      (is (= 0.25f0 (aref uniforms 26)))
      (is (= 5f0 (aref uniforms 71)))
      (is (= 0.75f0 (aref uniforms 80)))
      (is (approximately= 0.4d0 (aref uniforms 81) 1d-6))
      (is (= 2f0 (aref uniforms 92)))
      (is (= (/ 1f0 512f0) (aref uniforms 94)))
      (is (= (* 2 (length (getf entry :positions))) (length vertices)))
      (is (typep vertices '(simple-array single-float (*)))))
    (let* ((projection (sgeo.render:vulkan-projection (sg:perspective-mat4 (/ pi 3) 1d0 0.1d0 100d0)))
           (near (sg:mat* projection (sg:make-vec4 0d0 0d0 -0.1d0 1d0)))
           (far (sg:mat* projection (sg:make-vec4 0d0 0d0 -100d0 1d0))))
      (is (approximately= 0d0 (/ (sg:vz near) (sg:vw near))))
      (is (approximately= 1d0 (/ (sg:vz far) (sg:vw far)))))))

(test pbr-inspector-edits-replay-and-undo-on-live-materials
  (let* ((material (sg:make-pbr-material :roughness 0.4d0))
         (object (sg:make-mesh-object (sg:make-half-edge-box) :material material))
         (world (sg:make-world :root object)) (light (sg:make-directional-light :intensity 2d0))
         (editor (sgeo.editor:make-editor :world world)))
    (sg:add-to-world world light)
    (unwind-protect
         (progn
           (sgeo.editor:inspect-editor editor material)
           (sgeo.editor:set-inspector-number editor :roughness 0.2d0)
           (is (= 0.2d0 (sg:pbr-material-roughness material)))
           (let ((command (first (sgeo.editor:editor-history editor))))
             (sgeo.editor:undo-edit editor)
             (is (= 0.4d0 (sg:pbr-material-roughness material)))
             (sgeo.editor:replay-editor-command editor command)
             (is (= 0.2d0 (sg:pbr-material-roughness material))))
           (sgeo.editor:inspect-editor editor material)
           (sgeo.editor:set-inspector-number editor :emissive 3d0 :axis 1)
           (is (= 3d0 (aref (sg:pbr-material-emissive material) 1)))
           (sgeo.editor:undo-edit editor)
           (is (= 0d0 (aref (sg:pbr-material-emissive material) 1)))
           (sgeo.editor:inspect-editor editor material)
           (signals sg:validation-error (sgeo.editor:set-inspector-number editor :roughness -1d0))
           (is (= 0.2d0 (sg:pbr-material-roughness material)))
           (sgeo.editor:inspect-editor editor light)
           (sgeo.editor:set-inspector-number editor :light-intensity 6d0)
           (is (= 6d0 (getf (sg:directional-light-data light) :intensity)))
           (sgeo.editor:undo-edit editor)
           (is (= 2d0 (getf (sg:directional-light-data light) :intensity))))
      (sgeo.editor:close-editor editor))))

(test render-graph-dependencies-barriers-and-lifetimes
  (is (every (lambda (resource) (not (sgeo.render:render-resource-transient-p resource)))
             (sgeo.render:compiled-graph-resources (sgeo.render:make-pbr-render-graph))))
  (let* ((graph (sgeo.render:make-pbr-render-graph :transient-p t)) (events nil)
         (transitions nil))
    (is (equal '(:shadow :pbr :tone :output)
               (mapcar #'sgeo.render:render-pass-name (sgeo.render:compiled-graph-passes graph))))
    (is (equal '(0 1) (gethash :shadow (sgeo.render:compiled-graph-lifetimes graph))))
    (is (equal '(1 2) (gethash :hdr (sgeo.render:compiled-graph-lifetimes graph))))
    (is (find-if (lambda (barrier) (and (eq :shadow (getf barrier :resource))
                                       (eq :depth-write (getf barrier :from))
                                       (eq :sampled-read (getf barrier :to))))
                 (sgeo.render:compiled-graph-barriers graph)))
      (sgeo.render:execute-render-graph graph
        (lambda (pass) (push (list :pass (sgeo.render:render-pass-name pass)) events))
        :transition (lambda (barrier)
                      (push barrier transitions)
                      (push (list :transition (getf barrier :pass)
                                  (getf barrier :resource) (getf barrier :from)
                                  (getf barrier :to)) events))
        :acquire (lambda (resource) (push (list :acquire (sgeo.render:render-resource-name resource)) events))
        :release (lambda (resource) (push (list :release (sgeo.render:render-resource-name resource)) events)))
      (setf events (nreverse events))
      (is (equal (sgeo.render:compiled-graph-barriers graph) (nreverse transitions)))
      (dolist (pass-name '(:shadow :pbr :tone :output))
        (let ((pass-position (position (list :pass pass-name) events :test #'equal))
              (transition-position (position-if
                                    (lambda (event)
                                      (and (eq (first event) :transition)
                                           (eq (second event) pass-name)))
                                    events)))
          (is (not (null transition-position)))
          (is (< transition-position pass-position))))
      (is (< (position '(:acquire :shadow) events :test #'equal)
             (position '(:pass :shadow) events :test #'equal)))
    (is (< (position '(:pass :pbr) events :test #'equal)
           (position '(:release :shadow) events :test #'equal)))
    (let ((released nil))
      (signals error
        (sgeo.render:execute-render-graph graph (lambda (pass) (declare (ignore pass)) (error "Pass falhou."))
          :release (lambda (resource) (push (sgeo.render:render-resource-name resource) released))))
      (is (equal '(:shadow) released)))))

(test render-graph-releases-multiple-live-transients-after-later-pass-failure
  (let* ((graph
           (sgeo.render:compile-render-graph
            (sgeo.render:make-render-graph
             :resources (list (sgeo.render:make-render-resource :name :early)
                              (sgeo.render:make-render-resource :name :middle)
                              (sgeo.render:make-render-resource :name :late))
             :passes (list (sgeo.render:make-render-pass
                            :name :first :writes '((:early :color-write)))
                           (sgeo.render:make-render-pass
                            :name :second :reads '((:early :sampled-read))
                            :writes '((:middle :color-write)))
                           (sgeo.render:make-render-pass
                            :name :failing :reads '((:early :sampled-read)
                                                    (:middle :sampled-read))
                            :writes '((:late :color-write)))))))
         (acquired nil) (released nil))
    (signals error
      (sgeo.render:execute-render-graph
       graph
       (lambda (pass)
         (when (eq :failing (sgeo.render:render-pass-name pass))
           (error "Falha no último pass.")))
       :acquire (lambda (resource)
                  (push (sgeo.render:render-resource-name resource) acquired))
       :release (lambda (resource)
                  (push (sgeo.render:render-resource-name resource) released))))
    (is (equal '(:early :middle :late) (reverse acquired)))
    (is (equal '(:early :middle :late) released))
    (is (= (length acquired) (length released)))
    (is (= (length (remove-duplicates released)) (length released)))))

(test render-graph-rejects-missing-producers-and-cycles
  (signals sg:render-error
    (sgeo.render:compile-render-graph
     (sgeo.render:make-render-graph
      :resources (list (sgeo.render:make-render-resource :name :missing))
      :passes (list (sgeo.render:make-render-pass :name :read :reads '((:missing :sampled-read)))))))
  (signals sg:render-error
    (sgeo.render:compile-render-graph
     (sgeo.render:make-render-graph
      :passes (list (sgeo.render:make-render-pass :name :a :depends-on '(:b))
                    (sgeo.render:make-render-pass :name :b :depends-on '(:a)))))))

(defun %finish-test-shader-compiles (program)
  (dolist (thread (sgeo.render::%program-workers program)) (bt:join-thread thread)))

(test shader-reload-preserves-working-program-through-failures
  (let* ((owner (bt:current-thread)) (compile-threads nil) (destroyed nil)
         (program (sgeo.render:make-shader-program
                   :test (lambda (source)
                           (push (bt:current-thread) compile-threads)
                           (when (eq source :bad-source) (error "Compilação rejeitada.")) source)
                   (lambda (compiled)
                     (assert (eq owner (bt:current-thread)))
                     (when (eq compiled :bad-pipeline) (error "Pipeline rejeitado."))
                     (unless (eq compiled :nil-pipeline) (list :gpu compiled)))
                   (lambda (pipeline) (push pipeline destroyed)) :initial)))
    (unwind-protect
         (let ((initial (sgeo.render:shader-program-active program)))
           (sgeo.render:request-shader-reload program :bad-source)
           (%finish-test-shader-compiles program)
           (is (null (sgeo.render:install-pending-shader program 1)))
           (is (eq initial (sgeo.render:shader-program-active program)))
           (is (typep (sgeo.render:shader-program-last-error program) 'error))
           (sgeo.render:request-shader-reload program :bad-pipeline)
           (%finish-test-shader-compiles program)
           (is (null (sgeo.render:install-pending-shader program 2)))
           (is (eq initial (sgeo.render:shader-program-active program)))
           (sgeo.render:request-shader-reload program :nil-pipeline)
           (%finish-test-shader-compiles program)
           (is (null (sgeo.render:install-pending-shader program 3)))
           (is (eq initial (sgeo.render:shader-program-active program)))
           (is (typep (sgeo.render:shader-program-last-error program) 'error))
           (sgeo.render:request-shader-reload program :updated)
           (%finish-test-shader-compiles program)
           (is (sgeo.render:install-pending-shader program 4))
           (is (equal '(:gpu :updated) (sgeo.render:shader-program-active program)))
           (is (null destroyed))
           (is (= 0 (sgeo.render:collect-retired-shaders program 3)))
           (is (= 1 (sgeo.render:collect-retired-shaders program 4)))
           (is (eq initial (first destroyed)))
           (is (null (sgeo.render:shader-program-last-error program)))
           (is (some (lambda (thread) (not (eq owner thread))) compile-threads)))
      (sgeo.render:destroy-shader-program program))
    (is (= 2 (length destroyed)))
    (is (null (sgeo.render:destroy-shader-program program)))))

(test shared-fresnel-function-runs-on-cpu-and-remains-in-shader-sgir
  (is (vector-approximately= #(0.04d0 0.2d0 0.8d0)
                             (sgeo.render:fresnel-schlick 1d0 #(0.04d0 0.2d0 0.8d0)) 1d-6))
  (is (vector-approximately= #(1d0 1d0 1d0)
                             (sgeo.render:fresnel-schlick 0d0 #(0.04d0 0.2d0 0.8d0)) 1d-6))
  (let* ((fragment (getf (sgeo.render:standard-shader-sources :pbr) :fragment))
         (functions (sgeo.shader:sgir-module-functions (sgeo.shader:shader-definition-sgir fragment))))
    (is (find 'sgeo.render:fresnel-schlick functions :key #'sgeo.shader:sgir-function-name))))

(sgeo.shader:defgpu-function reload-helper ((value :float)) (* value 0.5))

(test shader-recompile-uses-redefined-helper-on-existing-source
  (let* ((fragment (sgeo.shader:compile-shader-form
                    'helper-reload-fragment :fragment nil
                    '((:color (vec4 (reload-helper 1.0) 0.0 0.0 1.0)))))
         (source (list :vertex (getf (sgeo.render:standard-shader-sources :pbr) :vertex)
                       :fragment fragment))
         (before (sgeo.render:compile-graphics-program source)))
    (unwind-protect
         (progn
           (eval '(sgeo.shader:defgpu-function reload-helper ((value :float)) (* value 0.8)))
           (let ((after (sgeo.render:compile-graphics-program source)))
             (is (not (equalp (getf before :fragment) (getf after :fragment)))))
           (is (approximately= 0.8d0 (reload-helper 1d0) 1d-6)))
      (eval '(sgeo.shader:defgpu-function reload-helper ((value :float)) (* value 0.5))))))

(test shader-reload-discards-stale-candidate-after-newer-request
  (let* ((owner (bt:current-thread))
         (candidate-started (bt:make-semaphore))
         (release-candidate (bt:make-semaphore))
         (destroyed nil) (pending-observations nil) (program nil))
    (setf program (sgeo.render:make-shader-program
                   :latest-wins #'identity
                   (lambda (compiled)
                     (assert (eq owner (bt:current-thread)))
                     (when (eq compiled :stale)
                       (bt:signal-semaphore candidate-started)
                       (bt:wait-on-semaphore release-candidate))
                     (list :gpu compiled))
                   (lambda (pipeline)
                     (push (sgeo.render:shader-program-pending-p program) pending-observations)
                     (push pipeline destroyed)) :initial))
    (unwind-protect
         (let ((initial (sgeo.render:shader-program-active program)))
           (sgeo.render:request-shader-reload program :stale)
           (%finish-test-shader-compiles program)
           (let ((newer-request
                   (bt:make-thread
                    (lambda ()
                      (bt:wait-on-semaphore candidate-started)
                      (sgeo.render:request-shader-reload program :newest)
                      (bt:signal-semaphore release-candidate)))))
             ;; A nova solicitação acontece enquanto o candidato antigo é construído.
             (is (null (sgeo.render:install-pending-shader program 10)))
             (bt:join-thread newer-request))
           (is (equal (list :gpu :stale) (first destroyed)))
           (is (= 1 (length pending-observations)))
           (is (eq initial (sgeo.render:shader-program-active program)))
           (%finish-test-shader-compiles program)
           (is (sgeo.render:install-pending-shader program 11))
           (is (equal '(:gpu :newest) (sgeo.render:shader-program-active program)))
           (is (= 0 (sgeo.render:collect-retired-shaders program 10)))
           (is (= 1 (sgeo.render:collect-retired-shaders program 11)))
           (is (member initial destroyed :test #'eq))
           (is (null (sgeo.render:shader-program-last-error program))))
      (sgeo.render:destroy-shader-program program))))
