(in-package #:sgeo.tests)
(in-suite sgeo-suite)

(test physics-contact-shapes-and-query
  (let* ((world (sgeo.physics:make-physics-world :gravity (sg:vec3)))
         (sphere-object (sg:make-scene-object :position (sg:vec3 0.8d0 0 0)))
         (box-object (sg:make-scene-object))
         (sphere (sgeo.physics:make-rigid-body :object sphere-object :shape (sgeo.physics:make-sphere-shape :radius 0.5d0)
                                     :motion-type :static))
         (box (sgeo.physics:make-rigid-body :object box-object :shape (sgeo.physics:make-box-shape
                                                              :half-extents (sg:vec3 0.5d0 0.5d0 0.5d0))
                                  :motion-type :static)))
    (is (sgeo.physics:overlap-bodies sphere box))
    (is (null (sgeo.physics:overlap-bodies
               sphere (sgeo.physics:make-rigid-body :object (sg:make-scene-object :position (sg:vec3 3 0 0))
                                          :shape (sgeo.physics:make-sphere-shape) :motion-type :static))))
    (sgeo.physics:add-body world sphere)
    (sgeo.physics:add-body world box)
    (is (= 2 (length (sgeo.physics:query-aabb world (sg:make-aabb (sg:vec3 -1 -1 -1) (sg:vec3 1 1 1))))))
    (multiple-value-bind (hit distance point normal)
        (sgeo.physics:physics-ray-cast world (sg:make-ray (sg:vec3 -2 0 0) (sg:vec3 1 0 0)))
      (is (eq hit box))
      (is (approximately= 1.5d0 distance))
      (is (vector-approximately= #(-0.5d0 0 0) point))
      (is (vector-approximately= #(-1d0 0 0) normal)))))

(test physics-box-raycast-boundary-interior-and-outside
  (let* ((world (sgeo.physics:make-physics-world :gravity (sg:vec3)))
         (body (sgeo.physics:make-rigid-body
                :object (sg:make-scene-object)
                :shape (sgeo.physics:make-box-shape
                        :half-extents (sg:vec3 1d0 1d0 1d0))
                :motion-type :static)))
    (sgeo.physics:add-body world body)
    (flet ((check-hit (origin direction expected-distance expected-point expected-normal)
             (multiple-value-bind (hit distance point normal)
                 (sgeo.physics:physics-ray-cast world
                   (sg:make-ray (sg:vec3 (first origin) (second origin) (third origin))
                                (sg:vec3 (first direction) (second direction) (third direction))))
               (is (eq hit body))
               (is (approximately= expected-distance distance))
               (is (vector-approximately= expected-point point))
               (is (vector-approximately= expected-normal normal)))))
      ;; Outside and inward: report the entry face.
      (check-hit '(-2d0 0d0 0d0) '(1d0 0d0 0d0) 1d0 #(-1d0 0d0 0d0) #(-1d0 0d0 0d0))
      ;; At the surface and inward: the hit is immediate, not the far face.
      (check-hit '(-1d0 0d0 0d0) '(1d0 0d0 0d0) 0d0 #(-1d0 0d0 0d0) #(-1d0 0d0 0d0))
      ;; Inside: the first positive hit is the exit face.
      (check-hit '(0d0 0d0 0d0) '(1d0 0d0 0d0) 1d0 #(1d0 0d0 0d0) #(1d0 0d0 0d0))
      ;; At the surface and outward: report the same immediate surface hit.
      (check-hit '(-1d0 0d0 0d0) '(-1d0 0d0 0d0) 0d0 #(-1d0 0d0 0d0) #(-1d0 0d0 0d0)))))

(test physics-fixed-step-resting-bounce-friction-and-events
  (let* ((events nil)
         (world (sgeo.physics:make-physics-world
                 :gravity (sg:vec3 0 -9.81d0 0)
                 :contact-handler (lambda (w event contact)
                                    (declare (ignore w contact)) (push event events))))
         (floor (sgeo.physics:make-rigid-body :object (sg:make-scene-object :position (sg:vec3 0 -0.5d0 0))
                                    :shape (sgeo.physics:make-box-shape :half-extents (sg:vec3 5 0.5d0 5))
                                    :motion-type :static :friction 0.9d0))
         (ball (sgeo.physics:make-rigid-body :object (sg:make-scene-object :position (sg:vec3 0 2 0))
                                   :shape (sgeo.physics:make-sphere-shape :radius 0.5d0)
                                   :mass 1 :friction 0.9d0)))
    (sgeo.physics:add-body world floor)
    (sgeo.physics:add-body world ball)
    (dotimes (i 220) (declare (ignore i)) (sgeo.physics:step-physics world 0.01d0))
    (is (<= 0.49d0 (sg:vy (sgeo.physics:body-position ball)) 0.52d0))
    (is (<= (abs (sg:vy (sgeo.physics:body-velocity ball))) 0.03d0))
    (is (member :begin events))
    (is (member :stay events))
    (setf (sgeo.physics:body-velocity ball) (sg:vec3 2 0 0))
    (dotimes (i 30) (declare (ignore i)) (sgeo.physics:step-physics world 0.01d0))
    (is (< (sg:vx (sgeo.physics:body-velocity ball)) 2d0))
    (is (plusp (length (sgeo.physics:physics-contacts world)))))
  (let* ((events nil)
         (world (sgeo.physics:make-physics-world :gravity (sg:vec3)
                                       :contact-handler (lambda (w event contact)
                                                          (declare (ignore w contact)) (push event events))))
         (a (sgeo.physics:make-rigid-body :object (sg:make-scene-object)
                                :shape (sgeo.physics:make-sphere-shape) :motion-type :static))
         (b (sgeo.physics:make-rigid-body :object (sg:make-scene-object :position (sg:vec3 0.5d0 0 0))
                                :shape (sgeo.physics:make-sphere-shape) :motion-type :kinematic)))
    (sgeo.physics:add-body world a) (sgeo.physics:add-body world b)
    (sgeo.physics:step-physics world 0.01d0)
    (sgeo.physics:move-body b (sg:vec3 4 0 0))
    (sgeo.physics:step-physics world 0.01d0)
    (is (member :end events)))
  (let* ((world (sgeo.physics:make-physics-world :gravity (sg:vec3 0 -9.81d0 0)))
         (floor (sgeo.physics:make-rigid-body
                 :object (sg:make-scene-object :position (sg:vec3 0 -0.5d0 0))
                 :shape (sgeo.physics:make-box-shape :half-extents (sg:vec3 4 0.5d0 4))
                 :motion-type :static :restitution 1d0))
         (ball (sgeo.physics:make-rigid-body
                :object (sg:make-scene-object :position (sg:vec3 0 0.7d0 0))
                :shape (sgeo.physics:make-sphere-shape) :velocity (sg:vec3 0 -3 0)
                :restitution 1d0)))
    (sgeo.physics:add-body world floor) (sgeo.physics:add-body world ball)
    (sgeo.physics:apply-impulse ball (sg:vec3 0 1 0))
    (is (approximately= -2d0 (sg:vy (sgeo.physics:body-velocity ball))))
    (dotimes (i 20) (declare (ignore i)) (sgeo.physics:step-physics world 0.01d0))
    (is (plusp (sg:vy (sgeo.physics:body-velocity ball))))))

(test physics-parent-transform-and-detach
  (let* ((world (sgeo.physics:make-physics-world :gravity (sg:vec3)))
         (parent (sg:make-scene-object :position (sg:vec3 10 1 0)
                                       :scale (sg:vec3 2 2 2)))
         (object (sg:make-scene-object :position (sg:vec3 0 1 0)))
         (body (sgeo.physics:make-rigid-body :object object :shape (sgeo.physics:make-sphere-shape)
                                   :motion-type :kinematic)))
    (sg:add-child parent object)
    (is (vector-approximately= #(10 3 0) (sgeo.physics:body-position body)))
    (sgeo.physics:add-body world body)
    (sgeo.physics:move-body body (sg:vec3 12 5 0))
    (is (vector-approximately= #(12 5 0) (sgeo.physics:body-position body)))
    (is (sgeo.physics:remove-body world body))
    (is (null (sgeo.physics:physics-bodies world)))
    (is (not (sgeo.physics:remove-body world body)))))

(test physics-capsule-combinations-and-invalid-input
  (let* ((objects (loop repeat 3 collect (sg:make-scene-object)))
         (sphere (sgeo.physics:make-rigid-body :object (first objects) :shape (sgeo.physics:make-sphere-shape) :motion-type :static))
         (box (sgeo.physics:make-rigid-body :object (second objects) :shape (sgeo.physics:make-box-shape) :motion-type :static))
         (capsule (sgeo.physics:make-rigid-body :object (third objects) :shape (sgeo.physics:make-capsule-shape) :motion-type :static)))
    (is (sgeo.physics:overlap-bodies capsule sphere))
    (is (sgeo.physics:overlap-bodies capsule box))
    (is (sgeo.physics:overlap-bodies box capsule))
    (is (sgeo.physics:overlap-bodies sphere box))
    (is (sgeo.physics:overlap-bodies sphere capsule))
    (is (sgeo.physics:overlap-bodies box sphere))
    (is (sgeo.physics:overlap-bodies box box))
    (is (sgeo.physics:overlap-bodies sphere sphere))
    (is (sgeo.physics:body-trigger-p
         (sgeo.physics:make-rigid-body :object (sg:make-scene-object)
                                       :shape (sgeo.physics:make-sphere-shape) :trigger-p t)))
    (signals error (sgeo.physics:make-sphere-shape :radius 0))
    (signals error (sgeo.physics:make-capsule-shape :radius -1))
    (signals error (sgeo.physics:make-box-shape :half-extents (sg:vec3 1 0 1)))))
