(in-package #:sgeo.tests)
(in-suite sgeo-suite)

(defclass m6-gamepad-window (sgeo.platform:platform-window)
  ((state :initform nil :accessor m6-gamepad-state)))
(defmethod sgeo.platform:window-gamepad-state ((window m6-gamepad-window))
  (m6-gamepad-state window))

(test runtime-gamepad-trigger-axes-buttons-and-disconnection
  (let ((window (make-instance 'm6-gamepad-window))
        (input (sgeo.input:make-input-state)))
    (sgeo.input:push-input-context input :gamepad-test :bindings nil)
    (sgeo.input:bind-action input :fire '((:gamepad-button :right-trigger)))
    (sgeo.input:bind-action input :pressure '((:gamepad-axis :right-trigger :positive)))
    (sgeo.input:bind-action input :jump '((:gamepad-button :a)))
    (setf (m6-gamepad-state window) '(:buttons (:a) :axes ((:right-trigger . 0.8d0))))
    (sgeo.runtime::%poll-gamepad-input window input)
    (sgeo.input:begin-input-frame input)
    (is (sgeo.input:action-pressed-p input :fire))
    (is (sgeo.input:action-pressed-p input :jump))
    (is (plusp (sgeo.input:action-value input :pressure)))
    (sgeo.input:end-input-frame input)
    (sgeo.runtime::%poll-gamepad-input window input)
    (sgeo.input:begin-input-frame input)
    (is (sgeo.input:action-down-p input :fire))
    (is (not (sgeo.input:action-pressed-p input :fire)))
    (sgeo.input:end-input-frame input)
    (setf (m6-gamepad-state window) nil)
    (sgeo.runtime::%poll-gamepad-input window input)
    (sgeo.input:begin-input-frame input)
    (is (sgeo.input:action-released-p input :fire))
    (is (sgeo.input:action-released-p input :jump))
    (is (= 0d0 (sgeo.input:action-value input :pressure)))))
