(in-package #:sgeo.tests)
(in-suite sgeo-suite)

(test simulation-phases-fixed-clock-debt-and-detachment
  (let* ((world (sg:make-world))
         (state (sg:attach-simulation world :fixed-dt 0.1d0 :max-steps 2))
         (phases nil))
    (dolist (phase '(:input :pre-update :fixed-update :post-physics :variable-update :animation :transforms :spatial :audio :post-update))
      (let ((name phase))
        (sg:add-phase-hook state phase (lambda (w s dt) (declare (ignore w s dt)) (push name phases)))))
    (sg:update-world world 0.25d0)
    (is (equal '(:input :pre-update :fixed-update :post-physics :fixed-update :post-physics
                 :variable-update :animation :transforms :spatial :audio :post-update) (nreverse phases)))
    (is (approximately= 0.2d0 (sg:simulation-time state)))
    (is (approximately= 0.05d0 (sg:simulation-accumulator state)))
    (is (= 2 (sg:simulation-step-count state)))
    (sg:update-world world 0.5d0)
    (is (approximately= 0.35d0 (sg:simulation-accumulator state)))
    (sg:update-world world 0d0)
    (is (approximately= 0.15d0 (sg:simulation-accumulator state)))
    (setf (sg:simulation-paused-p state) t)
    (let ((time (sg:simulation-time state)))
      (sg:update-world world 0.5d0)
      (is (= time (sg:simulation-time state)))
      (is (approximately= 0.15d0 (sg:simulation-accumulator state))))
    (signals error (sg:update-world world -1d0))
    (is (eq state (sg:detach-simulation world)))
    (is (null (sg:world-simulation-state world)))
    (sg:update-world world 0.1d0)))

(test simulation-scheduler-events-failure-and-reentrant-hooks
  (let* ((world (sg:make-world)) (state (sg:attach-simulation world :fixed-dt 0.1d0))
         (seen nil) (bus (sg:simulation-events state)) (hook nil))
    (sg:on-event bus :hit (lambda (event) (push (sg:event-payload event) seen)) :priority 10 :once-p t)
    (sg:on-event bus :hit (lambda (event) (declare (ignore event)) (error "Erro esperado.")))
    (sg:on-event bus :hit (lambda (event) (push (list :last (sg:event-payload event)) seen)))
    (sg:emit-event bus :hit :payload :first)
    (sg:emit-event bus :hit :payload :second)
    (is (= 2 (sg:dispatch-events bus)))
    (is (equal '(:first (:last :first) (:last :second)) (nreverse seen)))
    (is (= 2 (length (sg:event-bus-errors bus))))
    (sg:clear-event-errors bus)
    (is (null (sg:event-bus-errors bus)))
    (setf seen nil)
    (sg:schedule-task state 0d0 (lambda (w s) (declare (ignore w s)) (push :task seen)))
    (let ((cancelled (sg:schedule-task state 0d0 (lambda (&rest args) (declare (ignore args)) (error "Cancelada.")))))
      (sg:cancel-task cancelled)
      (is (sg:task-cancelled-p cancelled)))
    (setf hook (sg:add-phase-hook state :fixed-update
                  (lambda (w s dt) (declare (ignore w dt))
                    (push :hook seen) (sg:remove-phase-hook s :fixed-update hook))))
    (sg:update-world world 0.2d0)
    (is (equal '(:task :hook) (nreverse seen)))
    (let ((count 0))
      (sg:schedule-task state 0d0 (lambda (w s) (declare (ignore w s)) (incf count)) :interval 0.1d0)
      (sg:update-world world 0.3d0)
      (is (= 3 count)))))

(test simulation-spatial-index-updates-and-audio-clock
  (let* ((world (sg:make-world)) (node (sg:make-scene-object))
         (mixer (sg:make-audio-mixer :sample-rate 1000))
         (state (sg:attach-simulation world :audio mixer))
         (grid (sg:simulation-spatial-index state)))
    (sg:add-to-world world node)
    (sg:set-position node #(5d0 0d0 0d0))
    (sg:update-world world 0.0105d0)
    (is (= 20 (length (sg:simulation-audio-samples state))))
    (sg:update-world world 0.0105d0)
    (is (= 22 (length (sg:simulation-audio-samples state))))
    (is (member node (sg:spatial-query-aabb grid (sg:make-aabb #(4.9d0 -0.1d0 -0.1d0) #(5.1d0 0.1d0 0.1d0)))))
    (sg:set-position node #(8d0 0d0 0d0))
    (sg:update-world world 0d0)
    (is (not (member node (sg:spatial-query-aabb grid (sg:make-aabb #(4.9d0 -0.1d0 -0.1d0) #(5.1d0 0.1d0 0.1d0))))))
    (sg:remove-from-world world node)
    (sg:update-world world 0d0)
    (is (not (member node (sg:spatial-query-aabb grid (sg:make-aabb #(-10d0 -10d0 -10d0) #(10d0 10d0 10d0))))))
    (sg:detach-simulation world :close-audio t)))

(test spatial-grid-overflow-removal-and-ray-distance
  (let ((grid (sg:make-uniform-grid :cell-size 1d0)))
    (sg:spatial-insert grid :near (sg:make-aabb #(1d0 -1d0 -1d0) #(2d0 1d0 1d0)))
    (sg:spatial-insert grid :far (sg:make-aabb #(4d0 -1d0 -1d0) #(5d0 1d0 1d0)))
    (sg:spatial-insert grid :huge (sg:make-aabb #(-100d0 -100d0 -100d0) #(100d0 100d0 100d0)))
    (is (equal '(:near :huge) (sg:spatial-query-aabb grid (sg:make-aabb #(1d0 0d0 0d0) #(1d0 0d0 0d0)))))
    (let ((hits (sg:spatial-ray-query grid (sg:make-ray #(0d0 0d0 0d0) #(1d0 0d0 0d0)))))
      (is (equal '(:huge :near :far) (mapcar #'car hits)))
      (is (equal '(0d0 1d0 4d0) (mapcar #'cdr hits))))
    (sg:spatial-remove grid :huge)
    (is (equal '(:near :far) (sg:spatial-query-aabb grid (sg:make-aabb #(-100d0 -100d0 -100d0) #(100d0 100d0 100d0)))))))
