(in-package #:sgeo.debug)

(defstruct (debug-command (:constructor %make-debug-command))
  kind data color width duration remaining)

(defstruct (debug-batch (:constructor %make-debug-batch))
  object positions indices)

(defstruct (debug-state (:constructor %make-debug-state))
  (commands nil)
  (batches (make-hash-table :test #'equalp)))

(defstruct (mesh-builder (:constructor %make-mesh-builder))
  (positions nil)
  (indices nil)
  (vertex-count 0))

(defun %finite-real-p (value)
  (and (realp value)
       (handler-case
           (let ((number (coerce value 'double-float)))
             (and (<= (- most-positive-double-float) number)
                  (<= number most-positive-double-float)))
         (error () nil))))

(defun %vector3 (value context)
  (unless (and (typep value 'sequence) (= (length value) 3)
               (every #'%finite-real-p value))
    (error "~A precisa ter três componentes reais e finitos." context))
  (map 'vector (lambda (part) (coerce part 'double-float)) value))

(defun %color (value)
  (let ((copy (%vector3 value "A cor")))
    (unless (every (lambda (component) (<= 0d0 component 1d0)) copy)
      (error "A cor precisa estar no intervalo RGB [0, 1]."))
    copy))

(defun %duration (value)
  (unless (and (%finite-real-p value) (or (= value -1) (>= value 0)))
    (error "A duração precisa ser zero, positiva ou -1 para persistir."))
  (coerce value 'double-float))

(defun %positive-width (value)
  (unless (and (%finite-real-p value) (> value 0))
    (error "A largura precisa ser um número real positivo e finito."))
  (coerce value 'double-float))

(defun %ensure-state (world)
  (or (sgeo.scene:world-debug-state world)
      (setf (sgeo.scene:world-debug-state world) (%make-debug-state))))

(defun %queue-command (world kind data color width duration)
  (sgeo.scene:with-world-lock (world)
    (let ((command (%make-debug-command :kind kind :data data :color (%color color)
                                        :width (%positive-width width)
                                        :duration (%duration duration)
                                        :remaining (%duration duration))))
      (push command (debug-state-commands (%ensure-state world)))))
  world)

(defun debug-line (world a b &key (color #(1d0 0.35d0 0.08d0))
                                  (width 0.01d0) (duration 0d0))
  "Enfileira uma linha de depuração como cópias imutáveis dos pontos."
  (let ((from (%vector3 a "O início da linha"))
        (to (%vector3 b "O fim da linha")))
    (%queue-command world :line (list :a from :b to) color width duration)))

(defun debug-ray (world ray &key (length 1d0) (color #(0.15d0 0.85d0 1d0))
                               (width 0.01d0) (duration 0d0))
  "Desenha um raio até LENGTH unidades a partir de sua origem."
  (unless (typep ray 'sgeo.math:ray)
    (error "DEBUG-RAY precisa receber um raio de Sgeo.Math."))
  (unless (and (%finite-real-p length) (> length 0))
    (error "O comprimento do raio precisa ser positivo e finito."))
  (let* ((origin (%vector3 (sgeo.math:ray-origin ray) "A origem do raio"))
         (direction (sgeo.math:normalize (sgeo.math:ray-direction ray)))
         (finish (sgeo.math:v+ origin (sgeo.math:v* direction (coerce length 'double-float)))))
    (debug-line world origin finish :color color :width width :duration duration)))

(defun debug-aabb (world bounds &key (color #(0.15d0 1d0 0.35d0))
                                    (width 0.01d0) (duration 0d0))
  "Enfileira as doze arestas de uma caixa alinhada aos eixos."
  (unless (typep bounds 'sgeo.math:aabb)
    (error "DEBUG-AABB precisa receber uma caixa AABB."))
  (%queue-command world :aabb
                  (list :minimum (%vector3 (sgeo.math:aabb-min bounds) "O mínimo da caixa")
                        :maximum (%vector3 (sgeo.math:aabb-max bounds) "O máximo da caixa"))
                  color width duration))

(defun debug-sphere (world center radius &key (color #(1d0 0.9d0 0.15d0))
                                          (width 0.01d0) (duration 0d0))
  "Enfileira uma esfera representada por três grandes círculos."
  (unless (and (%finite-real-p radius) (> radius 0))
    (error "O raio da esfera precisa ser positivo e finito."))
  (%queue-command world :sphere
                  (list :center (%vector3 center "O centro da esfera")
                        :radius (coerce radius 'double-float))
                  color width duration))

(defun debug-text (world position text &key (color #(1d0 1d0 1d0))
                                           (height 0.14d0) (duration 0d0))
  "Desenha texto com uma fonte bitmap 5x7 incorporada ao pacote."
  (unless (stringp text) (error "O texto de depuração precisa ser uma string."))
  (unless (and (%finite-real-p height) (> height 0))
    (error "A altura do texto precisa ser positiva e finita."))
  (%queue-command world :text
                  (list :position (%vector3 position "A posição do texto")
                        :text (copy-seq text) :height (coerce height 'double-float))
                  color 0.01d0 duration))

(defun clear-debug-draw (world)
  "Apaga comandos e lotes transitórios do mundo."
  (sgeo.scene:with-world-lock (world)
    (when (sgeo.scene:world-debug-state world)
      (let ((state (sgeo.scene:world-debug-state world)))
        (setf (debug-state-commands state) nil)
        (clrhash (debug-state-batches state)))))
  world)

(defun debug-command-count (world)
  "Devolve quantos comandos ainda aguardam expiração ou limpeza."
  (sgeo.scene:with-world-lock (world)
    (if (sgeo.scene:world-debug-state world)
        (length (debug-state-commands (sgeo.scene:world-debug-state world)))
        0)))

(defmethod sgeo.scene:advance-scene-frame :before
    ((world sgeo.scene:world) state dt)
  (declare (ignore state))
  (sgeo.scene:with-world-lock (world)
    (let ((debug-state (sgeo.scene:world-debug-state world)))
      (when debug-state
        (setf (debug-state-commands debug-state)
              (loop for command in (debug-state-commands debug-state)
                    for remaining = (debug-command-remaining command)
                    for next = (if (plusp remaining)
                                   (- remaining (coerce dt 'double-float))
                                   remaining)
                    unless (and (not (= (debug-command-duration command) -1d0))
                                (<= next 0d0))
                      collect (let ((copy (copy-debug-command command)))
                                (setf (debug-command-remaining copy) next)
                                copy)))))))

(defparameter *bitmap-font-5x7*
  '((#\A "01110" "10001" "10001" "11111" "10001" "10001" "10001")
    (#\B "11110" "10001" "10001" "11110" "10001" "10001" "11110")
    (#\C "01111" "10000" "10000" "10000" "10000" "10000" "01111")
    (#\D "11110" "10001" "10001" "10001" "10001" "10001" "11110")
    (#\E "11111" "10000" "10000" "11110" "10000" "10000" "11111")
    (#\F "11111" "10000" "10000" "11110" "10000" "10000" "10000")
    (#\G "01111" "10000" "10000" "10111" "10001" "10001" "01111")
    (#\H "10001" "10001" "10001" "11111" "10001" "10001" "10001")
    (#\I "11111" "00100" "00100" "00100" "00100" "00100" "11111")
    (#\J "00111" "00010" "00010" "00010" "10010" "10010" "01100")
    (#\K "10001" "10010" "10100" "11000" "10100" "10010" "10001")
    (#\L "10000" "10000" "10000" "10000" "10000" "10000" "11111")
    (#\M "10001" "11011" "10101" "10101" "10001" "10001" "10001")
    (#\N "10001" "11001" "10101" "10011" "10001" "10001" "10001")
    (#\O "01110" "10001" "10001" "10001" "10001" "10001" "01110")
    (#\P "11110" "10001" "10001" "11110" "10000" "10000" "10000")
    (#\Q "01110" "10001" "10001" "10001" "10101" "10010" "01101")
    (#\R "11110" "10001" "10001" "11110" "10100" "10010" "10001")
    (#\S "01111" "10000" "10000" "01110" "00001" "00001" "11110")
    (#\T "11111" "00100" "00100" "00100" "00100" "00100" "00100")
    (#\U "10001" "10001" "10001" "10001" "10001" "10001" "01110")
    (#\V "10001" "10001" "10001" "10001" "10001" "01010" "00100")
    (#\W "10001" "10001" "10001" "10101" "10101" "10101" "01010")
    (#\X "10001" "10001" "01010" "00100" "01010" "10001" "10001")
    (#\Y "10001" "10001" "01010" "00100" "00100" "00100" "00100")
    (#\Z "11111" "00001" "00010" "00100" "01000" "10000" "11111")
    (#\0 "01110" "10001" "10011" "10101" "11001" "10001" "01110")
    (#\1 "00100" "01100" "00100" "00100" "00100" "00100" "01110")
    (#\2 "01110" "10001" "00001" "00010" "00100" "01000" "11111")
    (#\3 "11110" "00001" "00001" "01110" "00001" "00001" "11110")
    (#\4 "00010" "00110" "01010" "10010" "11111" "00010" "00010")
    (#\5 "11111" "10000" "10000" "11110" "00001" "00001" "11110")
    (#\6 "01110" "10000" "10000" "11110" "10001" "10001" "01110")
    (#\7 "11111" "00001" "00010" "00100" "01000" "01000" "01000")
    (#\8 "01110" "10001" "10001" "01110" "10001" "10001" "01110")
    (#\9 "01110" "10001" "10001" "01111" "00001" "00001" "01110")
    (#\Space "00000" "00000" "00000" "00000" "00000" "00000" "00000")
    (#\. "00000" "00000" "00000" "00000" "00000" "00100" "00100")
    (#\, "00000" "00000" "00000" "00000" "00100" "00100" "01000")
    (#\: "00000" "00100" "00100" "00000" "00100" "00100" "00000")
    (#\- "00000" "00000" "00000" "11111" "00000" "00000" "00000")
    (#\+ "00000" "00100" "00100" "11111" "00100" "00100" "00000")
    (#\/ "00001" "00010" "00010" "00100" "01000" "01000" "10000")
    (#\_ "00000" "00000" "00000" "00000" "00000" "00000" "11111")
    (#\! "00100" "00100" "00100" "00100" "00100" "00000" "00100")
    (#\? "01110" "10001" "00001" "00010" "00100" "00000" "00100")))

(defun %glyph-rows (character)
  (or (rest (assoc (char-upcase character) *bitmap-font-5x7* :test #'char=))
      (rest (assoc #\? *bitmap-font-5x7* :test #'char=))))

(defun %camera-basis (world)
  (let* ((camera (sgeo.scene:world-camera world))
         (forward (sgeo.math:normalize
                   (sgeo.math:v- (sgeo.scene:camera-target camera)
                                 (sgeo.scene:camera-eye camera))))
         (given-up (sgeo.scene:camera-up camera))
         (right (sgeo.math:cross forward given-up)))
    (when (< (sgeo.math:vector-length right) 1d-12)
      (setf right (sgeo.math:cross forward #(0d0 0d0 1d0)))
      (when (< (sgeo.math:vector-length right) 1d-12)
        (setf right (sgeo.math:cross forward #(1d0 0d0 0d0)))))
    (setf right (sgeo.math:normalize right))
    (values forward right (sgeo.math:normalize (sgeo.math:cross right forward)))))

(defun %builder-for (builders color)
  (or (gethash color builders)
      (setf (gethash (copy-seq color) builders) (%make-mesh-builder))))

(defun %append-quad (builder a b c d)
  (let ((base (mesh-builder-vertex-count builder)))
    (dolist (point (list a b c d))
      (loop for component across point
            do (push component (mesh-builder-positions builder))))
    (dolist (index (list base (+ base 2) (+ base 1)
                         base (+ base 3) (+ base 2)))
      (push index (mesh-builder-indices builder)))
    (incf (mesh-builder-vertex-count builder) 4)))

(defun %line-quad (a b width camera-forward camera-right)
  (let* ((direction (sgeo.math:v- b a))
         (length (sgeo.math:vector-length direction)))
    (when (> length 1d-12)
      (let* ((unit (sgeo.math:v* direction (/ 1d0 length)))
             (offset-direction (sgeo.math:cross unit camera-forward)))
        (when (< (sgeo.math:vector-length offset-direction) 1d-12)
          (setf offset-direction camera-right))
        (let ((offset (sgeo.math:v* (sgeo.math:normalize offset-direction) (/ width 2d0))))
          (list (sgeo.math:v+ a offset) (sgeo.math:v+ b offset)
                (sgeo.math:v- b offset) (sgeo.math:v- a offset)))))))

(defun %add-line (builders command a b forward right)
  (let ((quad (%line-quad a b (debug-command-width command) forward right)))
    (when quad (%append-quad (%builder-for builders (debug-command-color command))
                             (first quad) (second quad) (third quad) (fourth quad)))))

(defun %sphere-lines (command builders forward right)
  (let* ((center (getf (debug-command-data command) :center))
         (radius (getf (debug-command-data command) :radius))
         (segments 32))
    (dolist (plane '((0 1) (0 2) (1 2)))
      (loop for index below segments
            for angle = (* 2d0 pi (/ index segments))
            for next-angle = (* 2d0 pi (/ (1+ index) segments))
            for from = (copy-seq center)
            for to = (copy-seq center)
            do (setf (aref from (first plane)) (+ (aref center (first plane))
                                                   (* radius (cos angle)))
                     (aref from (second plane)) (+ (aref center (second plane))
                                                    (* radius (sin angle)))
                     (aref to (first plane)) (+ (aref center (first plane))
                                                 (* radius (cos next-angle)))
                     (aref to (second plane)) (+ (aref center (second plane))
                                                  (* radius (sin next-angle))))
               (%add-line builders command from to forward right)))))

(defun %aabb-lines (command builders forward right)
  (let* ((minimum (getf (debug-command-data command) :minimum))
         (maximum (getf (debug-command-data command) :maximum))
         (corners (loop for mask below 8
                        collect (vector (if (logbitp 0 mask) (aref maximum 0) (aref minimum 0))
                                        (if (logbitp 1 mask) (aref maximum 1) (aref minimum 1))
                                        (if (logbitp 2 mask) (aref maximum 2) (aref minimum 2))))))
    (loop for index below 8 do
      (loop for bit in '(1 2 4) when (zerop (logand index bit)) do
        (%add-line builders command (nth index corners)
                   (nth (logior index bit) corners) forward right)))))

(defun %text-geometry (command builders right up)
  (let* ((data (debug-command-data command))
         (origin (getf data :position))
         (text (getf data :text))
         (cell (/ (getf data :height) 7d0))
         (builder (%builder-for builders (debug-command-color command))))
    (loop for character across text
          for glyph-index from 0
          for rows = (%glyph-rows character)
          do (loop for row in rows for y from 0 do
               (loop for x below 5
                     when (char= (char row x) #\1) do
                       (let* ((base (sgeo.math:v+
                                     origin
                                     (sgeo.math:v+
                                      (sgeo.math:v* right (* cell (+ (* glyph-index 6) x)))
                                      (sgeo.math:v* up (* cell (- 6 y))))))
                              (next (sgeo.math:v+ base (sgeo.math:v* right cell)))
                              (top-next (sgeo.math:v+ next (sgeo.math:v* up cell)))
                              (top (sgeo.math:v+ base (sgeo.math:v* up cell))))
                         (%append-quad builder base next top-next top)))))))

(defun %collect-geometry (world commands)
  (multiple-value-bind (forward right up) (%camera-basis world)
    (let ((builders (make-hash-table :test #'equalp)))
      (dolist (command commands)
        (case (debug-command-kind command)
          (:line
           (%add-line builders command (getf (debug-command-data command) :a)
                      (getf (debug-command-data command) :b) forward right))
          (:aabb (%aabb-lines command builders forward right))
          (:sphere (%sphere-lines command builders forward right))
          (:text (%text-geometry command builders right up))))
      (let ((result nil))
        (maphash (lambda (color builder)
                   (when (mesh-builder-indices builder)
                     (push (list color
                                 (coerce (nreverse (mesh-builder-positions builder))
                                         '(simple-array double-float (*)))
                                 (coerce (nreverse (mesh-builder-indices builder))
                                         '(simple-array (unsigned-byte 32) (*))))
                           result)))
                 builders)
        result))))

(defun %batch-object (color positions indices)
  (let* ((geometry (sgeo.geometry:make-triangle-mesh
                   :positions positions :indices indices :name "Geometria de depuração"))
         (material (sgeo.scene:make-material :color color :name "Material de depuração"))
         (object (sgeo.scene:make-mesh-object geometry :name "Lote de depuração"
                                               :material material)))
    (%make-debug-batch :object object :positions (copy-seq positions)
                       :indices (copy-seq indices))))

(defun %ensure-batch (state color positions indices)
  (let* ((batches (debug-state-batches state))
         (batch (gethash color batches)))
    (cond
      ((null batch)
       (setf batch (%batch-object color positions indices)
             (gethash (copy-seq color) batches) batch))
      ((or (not (equalp positions (debug-batch-positions batch)))
           (not (equalp indices (debug-batch-indices batch))))
       (sgeo.geometry:set-mesh-data (sgeo.scene:mesh-object-geometry
                                     (debug-batch-object batch))
                                    positions indices)
       (setf (debug-batch-positions batch) (copy-seq positions)
             (debug-batch-indices batch) (copy-seq indices))))
    batch))

(defun %batch-entry (batch)
  (let* ((object (debug-batch-object batch))
         (geometry (sgeo.scene:mesh-object-geometry object))
         (material (sgeo.scene:mesh-object-material object))
         (data (sgeo.scene:render-data-for-object object)))
    (list :object object :object-id (sgeo.core:object-id object)
          :geometry geometry :render-key geometry
          :revision (sgeo.geometry:render-mesh-revision data)
          :positions (sgeo.geometry:render-mesh-positions data)
          :normals (sgeo.geometry:render-mesh-normals data)
          :indices (sgeo.geometry:render-mesh-indices data)
          :model-matrix (sgeo.scene:world-transform object)
          :material material :color (sgeo.scene:simple-material-color material)
          :wireframe-p (sgeo.scene:simple-material-wireframe-p material)
          :visible-p t)))

(defmethod sgeo.scene:additional-render-entries ((world sgeo.scene:world))
  (sgeo.scene:with-world-lock (world)
    (let ((state (sgeo.scene:world-debug-state world)))
      (when state
        (mapcar (lambda (geometry)
                  (destructuring-bind (color positions indices) geometry
                    (%batch-entry (%ensure-batch state color positions indices))))
                (%collect-geometry world (debug-state-commands state)))))))
