(in-package #:sgeo.shader)

;;; A linguagem SGL guarda formas Lisp originais e também uma árvore tipada. O
;;; front-end não avalia código do usuário durante a compilação.
(define-condition shader-error (error)
  ((message :initarg :message :reader shader-error-message)
   (form :initarg :form :initform nil :reader shader-error-form))
  (:report (lambda (c s) (format s "Shader Lisp: ~A~@[ (em ~S)~]"
                                 (shader-error-message c) (shader-error-form c))))
  (:documentation "Erro recuperável ao validar ou compilar Shader Lisp."))
(define-condition shader-type-error (shader-error) ()
  (:documentation "Erro de tipo em uma expressão de shader."))
(define-condition shader-interface-error (shader-error) ()
  (:documentation "Erro em uma interface ou recurso de shader."))

(defstruct shader-expression opcode type operands value attributes)
(defstruct shader-statement opcode data)
(defstruct shader-output name type expression)
(defstruct shader-parameter name type storage location set binding decorations)
(defstruct shader-definition name stage declarations parameters outputs ast sgir source)
(defstruct gpu-function-definition name arguments return-type ast source)
(defstruct sgir-module name stage entry-point functions interfaces)
(defstruct sgir-function name return-type parameters blocks)
(defstruct sgir-parameter name type storage decorations)
(defstruct sgir-block name instructions terminator)
(defstruct sgir-instruction opcode result type operands attributes)
(defstruct sgir-terminator opcode operands targets)
(defstruct sgir-interface name type storage location set binding decorations)

(defvar *shader-registry-lock* (bt:make-lock "sgeo shader registry")
  "Serializa a leitura do registro enquanto o compilador constrói um módulo.")
(defvar *shader-definitions* (make-hash-table :test #'eq)
  "Definições compiladas indexadas pelo símbolo Lisp do shader.")
(defvar *gpu-function-definitions* (make-hash-table :test #'eq)
  "Definições tipadas de funções compartilhadas CPU/GPU.")

(defun shader-definition-by-name (name) (gethash name *shader-definitions*))
(defun all-shader-definitions ()
  "Devolve uma cópia da lista de shaders compilados na imagem atual."
  (loop for value being the hash-values of *shader-definitions* collect value))

(defun %shader-error (condition message form)
  (error condition :message message :form form))

(defun %type (type &optional form)
  (let ((result
          (case type
            ((:void :bool :int :uint :float) type)
            (:vec2 '(:vector :float 2)) (:vec3 '(:vector :float 3))
            (:vec4 '(:vector :float 4))
            (:ivec2 '(:vector :int 2)) (:ivec3 '(:vector :int 3))
            (:ivec4 '(:vector :int 4))
            (:uvec2 '(:vector :uint 2)) (:uvec3 '(:vector :uint 3))
            (:uvec4 '(:vector :uint 4))
            (:mat2 '(:matrix 2 2)) (:mat3 '(:matrix 3 3)) (:mat4 '(:matrix 4 4))
            (:sampler2d '(:sampled-image (:image :2d :float)))
            (:struct '(:struct))
            (otherwise nil))))
    (or result
        (cond
          ((and (consp type) (eq (first type) :vector)
                (= (length type) 3) (member (second type) '(:float :int :uint) :test #'eq)
                (typep (third type) '(integer 2 4))) type)
          ((and (consp type) (eq (first type) :matrix)
                (= (length type) 3)
                (= (second type) (third type))
                (typep (second type) '(integer 2 4))) type)
          ((and (consp type) (eq (first type) :array)
                (= (length type) 3) (typep (third type) '(integer 1 *))) type)
          ((and (consp type) (eq (first type) :image) (>= (length type) 3)) type)
          ((and (consp type) (eq (first type) :sampled-image)
                (= (length type) 2) (consp (second type)) (eq (first (second type)) :image)) type)
          ((and (consp type) (eq (first type) :struct)) type)
          (t (%shader-error 'shader-type-error
                            (format nil "Tipo SGL desconhecido ou malformado: ~S." type) form))))))

(defun %declared-type (type name form)
  (if (and (consp type) (eq (first type) :struct))
      (let* ((fields (rest type))
             (members (mapcar (lambda (field)
                                (unless (and (consp field) (= (length field) 2) (symbolp (first field)))
                                  (%shader-error 'shader-type-error "Campo de struct inválido." field))
                                (list (first field) (%type (second field) field))) fields)))
        (when (null fields) (%shader-error 'shader-type-error "Struct uniforme precisa ter campos." form))
        (unless (= (length members) (length (remove-duplicates (mapcar #'first members) :test #'eq)))
          (%shader-error 'shader-type-error "Campo de struct duplicado." form))
        (list :struct name members))
      (%type type form)))

(defun shader-type-p (type)
  (or (member type '(:void :bool :int :uint :float) :test #'eq)
      (and (consp type) (member (first type) '(:vector :matrix :array :struct :image :sampled-image) :test #'eq))))
(defun shader-type-kind (type) (if (consp type) (first type) type))
(defun shader-type-width (type)
  (case (shader-type-kind type)
    (:vector (third type)) (:matrix (second type)) (otherwise 1)))
(defun %scalar-type (type)
  (case (shader-type-kind type)
    (:vector (second type)) (:matrix :float) (otherwise type)))
(defun %numeric-type-p (type)
  (member (%scalar-type type) '(:float :int :uint) :test #'eq))
(defun %vector-type (base width) (if (= width 1) base (list :vector base width)))
(defun %same-shape-type (a b)
  (and (equal (cdr (if (consp a) a (list a)))
              (cdr (if (consp b) b (list b))))))

(defstruct (%binding (:constructor %make-binding (type storage))) type storage)

(defun %copy-env (env) (let ((copy (make-hash-table :test #'eq)))
                         (maphash (lambda (k v) (setf (gethash k copy) v)) env) copy))
(defun %lookup (name env form)
  (or (gethash name env)
      (%shader-error 'shader-type-error (format nil "Variável não declarada: ~S." name) form)))

(defun %literal-type (value)
  (cond ((eq value t) :bool) ((integerp value) :int)
        ((floatp value) :float) (t nil)))

(defun %infer-binary (op left right form)
  (let ((lt (shader-expression-type left)) (rt (shader-expression-type right)))
    (unless (and (%numeric-type-p lt) (%numeric-type-p rt))
      (%shader-error 'shader-type-error (format nil "~S requer operandos numéricos, recebeu ~S e ~S." op lt rt) form))
    (cond
      ((and (eq op '*) (eq (shader-type-kind lt) :matrix) (eq (shader-type-kind rt) :vector)
            (= (second lt) (third rt))) (%vector-type :float (third lt)))
      ((and (eq op '*) (eq (shader-type-kind lt) :matrix) (eq (shader-type-kind rt) :matrix)
            (= (second lt) (third rt))) (list :matrix (second rt) (third lt)))
      ((and (eq op '*) (eq (shader-type-kind lt) :vector) (eq (shader-type-kind rt) :matrix)
            (= (third lt) (third rt))) (%vector-type :float (second rt)))
      ((or (eq (shader-type-kind lt) :matrix) (eq (shader-type-kind rt) :matrix))
       (%shader-error 'shader-type-error
                      (format nil "Operação ~S não é suportada para matrizes; use multiplicação matricial compatível." op)
                      form))
      ((equal lt rt) lt)
      ((and (eq (%scalar-type lt) (%scalar-type rt))
            (= (shader-type-width lt) 1)) rt)
      ((and (eq (%scalar-type lt) (%scalar-type rt))
            (= (shader-type-width rt) 1)) lt)
      ((and (eq (%scalar-type lt) :float) (eq (%scalar-type rt) :float)
            (= (shader-type-width lt) (shader-type-width rt))) lt)
      (t (%shader-error 'shader-type-error
                        (format nil "Tipos incompatíveis para ~S: ~S e ~S." op lt rt) form)))))

(defun %parse-expression (form env)
  (let ((literal (%literal-type form)))
    (when literal (return-from %parse-expression
                    (make-shader-expression :opcode :constant :type literal :value form)))
    (when (symbolp form)
      (let ((binding (%lookup form env form)))
        (return-from %parse-expression
          (make-shader-expression :opcode :variable :type (%binding-type binding) :value form
                                 :attributes (list :storage (%binding-storage binding))))))
    (unless (consp form)
      (%shader-error 'shader-type-error (format nil "Expressão inválida: ~S." form) form))
    (let* ((op (first form)) (op-name (and (symbolp op) (string-upcase (symbol-name op))))
           (args (rest form)))
      (cond
        ((member op '(+ - * /) :test #'eq)
         (unless (>= (length args) (if (eq op '-) 1 2))
           (%shader-error 'shader-type-error (format nil "Aridade inválida para ~S." op) form))
         (let* ((parsed (mapcar (lambda (arg) (%parse-expression arg env)) args))
                (opcode (case op (+ :add) (- :subtract) (* :multiply) (/ :divide))))
           (if (and (eq op '-) (= (length parsed) 1))
               (progn
                 (when (eq (shader-type-kind (shader-expression-type (first parsed))) :matrix)
                   (%shader-error 'shader-type-error "Negação unária de matriz não é suportada." form))
                 (make-shader-expression :opcode opcode :type (shader-expression-type (first parsed))
                                        :operands parsed))
               (reduce (lambda (left right)
                         (make-shader-expression :opcode opcode
                                                :type (%infer-binary op left right form)
                                                :operands (list left right)))
                       (rest parsed) :initial-value (first parsed)))))
        ((member op '(= < > <= >=) :test #'eq)
         (unless (= (length args) 2) (%shader-error 'shader-type-error "Comparação exige dois operandos." form))
         (let ((a (%parse-expression (first args) env)) (b (%parse-expression (second args) env)))
           (unless (equal (shader-expression-type a) (shader-expression-type b))
             (%shader-error 'shader-type-error "Os operandos da comparação têm tipos diferentes." form))
           (unless (member (shader-type-kind (shader-expression-type a)) '(:float :int :uint) :test #'eq)
             (%shader-error 'shader-type-error "Comparações SGL nesta versão aceitam apenas operandos escalares." form))
           (make-shader-expression :opcode (case op (= :equal) (< :less-than) (> :greater-than) (<= :less-equal) (>= :greater-equal))
                                  :type :bool :operands (list a b))))
        ((eq op 'if)
         (unless (= (length args) 3) (%shader-error 'shader-type-error "if exige condição e dois ramos." form))
         (let ((condition (%parse-expression (first args) env))
               (yes (%parse-expression (second args) env))
               (no (%parse-expression (third args) env)))
           (unless (eq (shader-expression-type condition) :bool)
             (%shader-error 'shader-type-error "A condição de if precisa ser :bool." (first args)))
           (unless (equal (shader-expression-type yes) (shader-expression-type no))
             (%shader-error 'shader-type-error "Os ramos de if precisam ter o mesmo tipo." form))
           (make-shader-expression :opcode :select :type (shader-expression-type yes)
                                  :operands (list condition yes no))))
        ((eq op 'let) (%parse-let args env form nil))
        ((eq op 'let*) (%parse-let args env form t))
        ((equal op-name "SELECT")
         (unless (= (length args) 3) (%shader-error 'shader-type-error "select exige condição, verdadeiro e falso." form))
         (%parse-expression (cons 'if args) env))
        ((equal op-name "SWIZZLE")
         (unless (and (= (length args) 2) (symbolp (second args)))
           (%shader-error 'shader-type-error "swizzle exige vetor e uma máscara como xyz." form))
         (%parse-swizzle (first args) (second args) env form))
        ((member op-name '("VEC2" "VEC3" "VEC4" "IVEC2" "IVEC3" "IVEC4"
                           "UVEC2" "UVEC3" "UVEC4" "MAT2" "MAT3" "MAT4") :test #'string=)
         (%parse-constructor op args env form))
        ((member op-name '("NORMALIZE" "DOT" "CROSS" "MIN" "MAX" "POW" "CLAMP" "MIX" "REFLECT") :test #'string=)
         (%parse-builtin op args env form))
        ((equal op-name "TEXTURE")
         (unless (= (length args) 2) (%shader-error 'shader-type-error "texture exige sampler e coordenada UV." form))
         (let* ((sampler (%parse-expression (first args) env)) (uv (%parse-expression (second args) env)))
           (unless (eq (shader-type-kind (shader-expression-type sampler)) :sampled-image)
             (%shader-error 'shader-type-error "texture exige um sampler2d." (first args)))
           (unless (equal (shader-expression-type uv) '(:vector :float 2))
             (%shader-error 'shader-type-error "Coordenadas de texture precisam ser :vec2." (second args)))
           (make-shader-expression :opcode :texture-sample :type '(:vector :float 4) :operands (list sampler uv))))
        ((equal op-name "FIELD")
         (unless (and (= (length args) 2) (symbolp (second args)))
           (%shader-error 'shader-type-error "field exige uma estrutura e o nome do campo." form))
         (let* ((base (%parse-expression (first args) env))
                (base-type (shader-expression-type base)))
           (unless (and (consp base-type) (eq (first base-type) :struct))
             (%shader-error 'shader-type-error "field exige um valor struct." form))
           (let ((member (find (second args) (third base-type)
                               :key #'first :test (lambda (a b)
                                                    (and (symbolp a) (symbolp b)
                                                         (string-equal (symbol-name a) (symbol-name b)))))))
             (unless member (%shader-error 'shader-type-error "Campo inexistente na estrutura." form))
             (make-shader-expression :opcode :field :type (second member) :operands (list base)
                                    :attributes (list :member (second args))))))
        ((%find-gpu-function-unlocked op)
         (let* ((function (%find-gpu-function-unlocked op))
                (arguments (mapcar (lambda (arg) (%parse-expression arg env)) args))
                (expected (gpu-function-definition-arguments function)))
           (unless (= (length arguments) (length expected))
             (%shader-error 'shader-type-error (format nil "Aridade inválida para função GPU ~S." op) form))
           (loop for actual in arguments for formal in expected do
             (unless (equal (shader-expression-type actual) (second formal))
               (%shader-error 'shader-type-error (format nil "Tipo incompatível para argumento ~S de ~S: esperado ~S, recebido ~S."
                                                         (first formal) op (second formal)
                                                         (shader-expression-type actual)) form)))
           (make-shader-expression :opcode :call :type (gpu-function-definition-return-type function)
                                  :operands arguments :attributes (list :function (gpu-function-definition-name function)))))
        (t (%parse-swizzle-or-call op args env form))))))

(defun %find-gpu-function-unlocked (name)
  (loop for function being the hash-values of *gpu-function-definitions*
        when (string-equal (symbol-name name)
                           (symbol-name (gpu-function-definition-name function))) return function))

(defun %find-gpu-function (name)
  (bt:with-lock-held (*shader-registry-lock*)
    (%find-gpu-function-unlocked name)))

(defun %parse-let (args env form sequential)
  (unless (and (>= (length args) 2) (listp (first args)))
    (%shader-error 'shader-type-error "let/let* exige bindings e uma expressão." form))
  (let ((inner (%copy-env env)) (names nil) (initializers nil))
    (dolist (binding (first args))
      (unless (and (consp binding) (= (length binding) 2) (symbolp (first binding)))
        (%shader-error 'shader-type-error "Binding inválido em let/let*." binding))
      (let ((expr (%parse-expression (second binding) (if sequential inner env))))
        (push (first binding) names)
        (push expr initializers)
        (setf (gethash (first binding) inner)
              (%make-binding (shader-expression-type expr) :local))))
    (let* ((body (mapcar (lambda (f) (%parse-expression f inner)) (rest args)))
           (binding-count (length names)))
      (make-shader-expression :opcode :let :type (shader-expression-type (car (last body)))
                             :operands (append (nreverse initializers) body)
                             :attributes (list :names (nreverse names)
                                               :initializer-count binding-count
                                               :body-count (length body)
                                               :sequential sequential)))))

(defun %parse-constructor (op args env form)
  (let* ((type (%type (intern (string-upcase (symbol-name op)) :keyword) form))
         (parsed (mapcar (lambda (x) (%parse-expression x env)) args))
         (required (shader-type-width type))
         (component-count (reduce #'+ parsed :key (lambda (e) (shader-type-width (shader-expression-type e))) :initial-value 0)))
    (unless (and parsed (every #'%numeric-type-p (mapcar #'shader-expression-type parsed)))
      (%shader-error 'shader-type-error "Construtor vetorial/matricial exige componentes numéricos." form))
    (let ((base (%scalar-type type)))
      (unless (every (lambda (expression)
                       (eq (%scalar-type (shader-expression-type expression)) base)) parsed)
        (%shader-error 'shader-type-error "Componentes do construtor precisam usar o mesmo tipo escalar do resultado." form)))
    (case (shader-type-kind type)
      (:vector
       (unless (or (and (= (length parsed) 1)
                        (= (shader-type-width (shader-expression-type (first parsed))) 1))
                   (= component-count required))
         (%shader-error 'shader-type-error
                        (format nil "Construtor ~S exige um escalar para broadcast ou exatamente ~D componentes." op required) form)))
      (:matrix
       (unless (and (= (length parsed) required)
                    (every (lambda (expression)
                             (equal (shader-expression-type expression)
                                    (list :vector :float required))) parsed))
         (%shader-error 'shader-type-error
                        (format nil "Construtor ~S exige ~D colunas :vec~D." op required required) form))))
    (make-shader-expression :opcode :construct :type type :operands parsed
                           :attributes (list :constructor op))))

(defun %parse-builtin (op args env form)
  (setf op (or (find-symbol (string-upcase (symbol-name op)) :sgeo.shader) op))
  (let* ((parsed (mapcar (lambda (x) (%parse-expression x env)) args))
         (types (mapcar #'shader-expression-type parsed))
         (arity (case op ((normalize) 1) ((dot cross reflect) 2) ((clamp mix) 3) (otherwise 2)))
         (type (or (find-if (lambda (item) (> (shader-type-width item) 1)) types)
                   (first types))))
    (unless (= (length parsed) arity)
      (%shader-error 'shader-type-error (format nil "Aridade inválida para ~S." op) form))
    (unless (every (lambda (item)
                     (and (%numeric-type-p item)
                          (member (shader-type-kind item) '(:float :int :uint :vector) :test #'eq)))
                   types)
      (%shader-error 'shader-type-error (format nil "~S exige escalares ou vetores numéricos." op) form))
    (case op
      ((dot)
       (unless (and (equal (first types) (second types))
                    (eq (shader-type-kind (first types)) :vector)
                    (eq (%scalar-type (first types)) :float))
         (%shader-error 'shader-type-error "dot exige vetores float do mesmo tipo." form))
       (setf type (%scalar-type (first types))))
      ((cross)
       (unless (equal types (list '(:vector :float 3) '(:vector :float 3)))
         (%shader-error 'shader-type-error "cross exige dois :vec3." form)))
      ((normalize)
       (unless (and (eq (shader-type-kind type) :vector) (eq (%scalar-type type) :float))
         (%shader-error 'shader-type-error "normalize exige um vetor de floats." form)))
      ((pow reflect)
       (unless (and (eq (%scalar-type (first types)) :float)
                    (eq (%scalar-type (second types)) :float)
                    (equal (first types) (second types)))
         (%shader-error 'shader-type-error (format nil "~S exige operandos float com formas compatíveis." op) form)))
      ((clamp mix)
       (unless (every (lambda (item) (eq (%scalar-type item) :float)) types)
         (%shader-error 'shader-type-error (format nil "~S exige valores float." op) form)))
      (otherwise
       (unless (every (lambda (item)
                        (or (equal item type)
                            (and (= (shader-type-width item) 1)
                                 (eq (%scalar-type item) (%scalar-type type)))))
                      types)
         (%shader-error 'shader-type-error (format nil "Tipos incompatíveis para ~S." op) form))))
    (make-shader-expression :opcode (case op (normalize :normalize) (dot :dot) (cross :cross)
                            (min :min) (max :max) (pow :pow) (clamp :clamp) (mix :mix) (reflect :reflect))
                           :type type :operands parsed)))

(defun %parse-swizzle-or-call (op args env form)
  (when (and (gethash op env) args)
      (return-from %parse-swizzle-or-call
       (%parse-swizzle op (first args) env form)))
  (%shader-error 'shader-type-error (format nil "Operação ou função não suportada: ~S." op) form))

(defun %parse-swizzle (vector mask env form)
  (unless (symbolp mask) (%shader-error 'shader-type-error "Máscara de swizzle precisa ser símbolo." mask))
  (let* ((base (%parse-expression vector env)) (components (string-downcase (symbol-name mask)))
         (indices (loop for ch across components collect (position ch "xyzw"))))
    (unless (and (consp (shader-expression-type base))
                 (eq (shader-type-kind (shader-expression-type base)) :vector)
                 (<= 1 (length components) 4) (every #'identity indices)
                 (every (lambda (index) (< index (shader-type-width (shader-expression-type base)))) indices))
      (%shader-error 'shader-type-error "Swizzle inválido; use componentes x/y/z/w disponíveis." form))
    (make-shader-expression :opcode :swizzle
                           :type (%vector-type (%scalar-type (shader-expression-type base)) (length indices))
                           :operands (list base) :attributes (list :indices indices))))

(defun %parse-declaration (declaration stage)
  (unless (and (consp declaration) (>= (length declaration) 2) (symbolp (first declaration)))
    (%shader-error 'shader-interface-error "Declaração de parâmetro inválida." declaration))
  (let* ((name (first declaration)) (type (%declared-type (second declaration) name declaration))
         (options (cddr declaration)) (storage (if (member :uniform options) :uniform
                                                   (if (member :storage-buffer options) :storage-buffer
                                                       (if (member :output options) :output :input))))
         (location (%option-value options :location))
         (set (%option-value options :set)) (binding (%option-value options :binding)))
    (when (> (count-if (lambda (qualifier) (member qualifier options :test #'eq))
                       '(:uniform :storage-buffer :input :output))
             1)
      (%shader-error 'shader-interface-error "Declaração possui qualificadores de armazenamento incompatíveis." declaration))
    (let ((cursor options))
      (loop while cursor do
        (let ((key (pop cursor)))
          (cond ((member key '(:uniform :storage-buffer :input :output :std140) :test #'eq))
                ((member key '(:location :set :binding) :test #'eq)
                 (unless cursor (%shader-error 'shader-interface-error "Decoração sem valor." declaration))
                 (pop cursor))
                (t (%shader-error 'shader-interface-error "Qualificador ou decoração desconhecida." declaration)))))
      (when (and (eq (%type-kind-safe type) :struct) (not (member :uniform options)))
        (%shader-error 'shader-interface-error "Estrutura SGL só pode ser declarada como :uniform nesta versão." declaration))
      (when (and (member :std140 options) (not (member :uniform options)))
        (%shader-error 'shader-interface-error ":std140 exige armazenamento :uniform." declaration))
      (when (and (member :std140 options) (not (eq (%type-kind-safe type) :struct)))
        (%shader-error 'shader-interface-error ":std140 exige um bloco struct." declaration)))
    (when (and (member storage '(:uniform :storage-buffer)) (eq (shader-type-kind type) :sampled-image))
      (unless (eq storage :uniform) (%shader-error 'shader-interface-error "Sampler precisa usar :uniform." declaration)))
    (when (eq storage :storage-buffer)
      (%shader-error 'shader-interface-error "Storage buffers ainda não são suportados pelo frontend SGL." declaration))
    (when (member storage '(:uniform :storage-buffer) :test #'eq)
      (unless binding (%shader-error 'shader-interface-error "Descritor exige :binding explícito." declaration))
      (unless set (setf set 0)))
    (dolist (decoration (list (cons :location location) (cons :set set) (cons :binding binding)))
      (let ((key (car decoration)) (value (cdr decoration)))
        (when (and value (not (typep value '(integer 0 *))))
          (%shader-error 'shader-interface-error (format nil "~S precisa ser inteiro não negativo." key) declaration))))
    (when (and (member storage '(:input :output) :test #'eq) (or set binding))
      (%shader-error 'shader-interface-error "Entradas e saídas não podem declarar set/binding." declaration))
    (when (and (member storage '(:uniform :storage-buffer) :test #'eq) location)
      (%shader-error 'shader-interface-error "Descritores não podem declarar location." declaration))
    (when (eq storage :input)
      (unless (member stage '(:vertex :fragment))
        (%shader-error 'shader-interface-error "Stage sem entradas suportadas." declaration))
      (when (null location)
        (%shader-error 'shader-interface-error "Entrada de shader exige :location explícito." declaration)))
    (when (and (member storage '(:input :output)) location (not (typep location '(integer 0 *))))
      (%shader-error 'shader-interface-error ":location precisa ser inteiro não negativo." declaration))
    (make-shader-parameter :name name :type type :storage storage :location location :set set :binding binding
                           :decorations (append
                                         (when (and (eq storage :input) (member stage '(:vertex :fragment)))
                                           (list :stage stage))
                                         (when (and (eq (%type-kind-safe type) :struct) (member :std140 options))
                                           (list :block :std140 :member-offsets (%std140-member-offsets type)))))))

(defun %type-kind-safe (type) (if (consp type) (first type) type))

(defun %round-up (value alignment)
  (* alignment (ceiling value alignment)))

(defun %std140-layout (type)
  (case (%type-kind-safe type)
    ((:bool :int :uint :float) (values 4 4))
    (:vector (case (third type) (2 (values 8 8)) (otherwise (values 16 16))))
    (:matrix (values 16 (* 16 (second type))))
    (otherwise (%shader-error 'shader-type-error "Tipo não suportado em bloco std140." type))))

(defun %std140-member-offsets (type)
  (let ((offset 0) (result nil))
    (dolist (member (third type))
      (multiple-value-bind (alignment size) (%std140-layout (second member))
        (setf offset (%round-up offset alignment))
        (push (list (first member) offset) result)
        (incf offset size)))
    (nreverse result)))

(defun %option-value (options key)
  (loop with cursor = options
        while cursor for candidate = (pop cursor) do
          (cond ((eq candidate key) (return (pop cursor)))
                ((member candidate '(:uniform :storage-buffer :input :output :std140) :test #'eq))
                (t (when cursor (pop cursor))))))

(defun %flatten-output-form (form)
  (cond
    ((and (consp form) (member (first form) '(let let*) :test #'eq))
     (unless (and (>= (length form) 3) (listp (second form)))
       (%shader-error 'shader-interface-error "let/let* de shader precisa conter bindings e saídas." form))
     (mapcar (lambda (pair)
               (list (first pair) (list (first form) (second form) (second pair))))
             (mapcan #'%flatten-output-form (cddr form))))
    ((and (consp form) (eq (first form) 'values)) (mapcan #'%flatten-output-form (rest form)))
    (t (list form))))

(defun %parse-output-form (form env)
  (let ((pairs (%flatten-output-form form)))
    (unless pairs (%shader-error 'shader-interface-error "Shader precisa produzir ao menos uma saída." form))
    (mapcar (lambda (pair)
              (unless (and (consp pair) (= (length pair) 2) (keywordp (first pair)))
                (%shader-error 'shader-interface-error "Saída deve ter a forma (:nome expressão)." pair))
              (let ((expr (%parse-expression (second pair) env)))
                (make-shader-output :name (first pair) :type (shader-expression-type expr) :expression expr)))
            pairs)))

(defun %validate-stage-interfaces (parameters stage)
  (let ((locations (make-hash-table :test #'equal))
        (descriptors (make-hash-table :test #'equal)))
    (dolist (parameter parameters)
      (let ((storage (shader-parameter-storage parameter)))
        (when (member storage '(:input :output) :test #'eq)
          (let* ((location (shader-parameter-location parameter))
                 (key (cons storage location)))
            (when (gethash key locations)
              (%shader-error 'shader-interface-error
                             (format nil "Location ~D duplicada para ~S no stage ~S." location storage stage)
                             parameter))
            (setf (gethash key locations) parameter)))
        (when (member storage '(:uniform :storage-buffer) :test #'eq)
          (let ((key (list (shader-parameter-set parameter) (shader-parameter-binding parameter))))
            (when (gethash key descriptors)
              (%shader-error 'shader-interface-error
                             (format nil "Descritor set ~D/binding ~D duplicado no stage ~S."
                                     (first key) (second key) stage)
                             parameter))
            (setf (gethash key descriptors) parameter)))))))

(defun %shader-output-location (outputs index)
  (let ((name (shader-output-name (nth index outputs))))
    (cond ((eq name :position) nil)
          ((eq name :color) 0)
          (t (- index (if (member :position
                                  (mapcar #'shader-output-name (subseq outputs 0 index)))
                          1 0))))))

(defun %validate-output-locations (outputs)
  (let ((locations (make-hash-table :test #'eql)))
    (loop for output in outputs for index from 0
          for location = (%shader-output-location outputs index)
          when location do
            (when (gethash location locations)
              (%shader-error 'shader-interface-error
                             (format nil "Location de saída ~D duplicada." location) output))
            (setf (gethash location locations) output))))

(defun %descriptor-type-signature (type)
  (if (and (consp type) (eq (first type) :struct) (= (length type) 3))
      (list :struct
            (mapcar (lambda (member)
                      (list (first member) (%descriptor-type-signature (second member))))
                    (third type)))
      type))

(defun %descriptor-signature (parameter)
  (list (shader-parameter-storage parameter)
        (%descriptor-type-signature (shader-parameter-type parameter))
        (remove-if-not (lambda (decoration)
                         (member (if (consp decoration) (first decoration) decoration)
                                 '(:block :std140 :member-offsets)))
                       (shader-parameter-decorations parameter))))

(defun %compile-definition (name stage declarations body)
  (unless (member stage '(:vertex :fragment) :test #'eq)
    (%shader-error 'shader-interface-error
                   "Nesta versão, SGL aceita apenas stages :vertex e :fragment; compute ainda não é executável."
                   stage))
  (unless body (%shader-error 'shader-interface-error "Shader sem corpo." body))
  (let* ((parameters (mapcar (lambda (decl) (%parse-declaration decl stage)) declarations))
         (names (mapcar #'shader-parameter-name parameters))
         (env (make-hash-table :test #'eq)))
    (unless (= (length names) (length (remove-duplicates names :test #'eq)))
      (%shader-error 'shader-interface-error "Nome de parâmetro duplicado." declarations))
    (dolist (param parameters)
      (setf (gethash (shader-parameter-name param) env)
            (%make-binding (shader-parameter-type param) (shader-parameter-storage param))))
    (%validate-stage-interfaces parameters stage)
    (let* ((outputs (%parse-output-form (if (= (length body) 1) (first body) (cons 'values body)) env))
           (output-names (mapcar #'shader-output-name outputs)))
      (unless (= (length output-names) (length (remove-duplicates output-names :test #'eq)))
        (%shader-error 'shader-interface-error "Nome de saída duplicado." body))
      (when (and (eq stage :vertex) (not (member :position output-names)))
        (%shader-error 'shader-interface-error "Shader de vértice precisa produzir :position." body))
      (when (and (eq stage :vertex)
                 (not (equal (shader-output-type (find :position outputs :key #'shader-output-name))
                             '(:vector :float 4))))
        (%shader-error 'shader-interface-error "A saída :position do vertex shader precisa ser :vec4." body))
      (when (and (member :position output-names) (not (eq stage :vertex)))
        (%shader-error 'shader-interface-error ":position só pode ser saída de vertex shader." body))
      (when (and (eq stage :fragment) (not (member :color output-names)))
        (%shader-error 'shader-interface-error "Shader de fragment precisa produzir :color." body))
      (when (and (eq stage :fragment)
                 (not (equal (shader-output-type (find :color outputs :key #'shader-output-name))
                             '(:vector :float 4))))
        (%shader-error 'shader-interface-error "A saída :color do fragment shader precisa ser :vec4." body))
      (%validate-output-locations outputs)
      (let* ((ast (make-shader-statement :opcode :return-outputs :data outputs))
             (sgir (%lower-shader name stage parameters outputs)))
        (make-shader-definition :name name :stage stage :declarations (copy-tree declarations)
                                :parameters parameters :outputs outputs :ast ast :sgir sgir
                                :source (copy-tree body))))))

(defun compile-shader-form (name stage declarations body)
  "Compila formas Lisp SGL em AST tipada e SGIR, sinalizando condições recuperáveis."
  (bt:with-lock-held (*shader-registry-lock*)
    (%compile-definition name stage declarations body)))

(defun compile-shader (&rest args)
  "Alias funcional para COMPILE-SHADER-FORM, útil em ferramentas e REPL."
  (apply #'compile-shader-form args))

(defmacro defshader (stage name declarations &body body)
  "Define um shader Lisp e registra sua AST e SGIR sem inicializar gráficos."
  `(setf (gethash ',name *shader-definitions*)
         (compile-shader-form ',name ',stage ',declarations ',body)))

(defmacro defgpu-function (name arguments &body body)
  "Define uma função CPU avaliada pela AST tipada e também compilável para GPU."
  `(progn
     (bt:with-lock-held (*shader-registry-lock*)
       (setf (gethash ',name *gpu-function-definitions*)
             (%compile-gpu-function-form ',name ',arguments ',body)))
     (defun ,name ,(mapcar #'first arguments)
       (%evaluate-gpu-function (gethash ',name *gpu-function-definitions*)
                               (list ,@(mapcar #'first arguments))))))

(defun compile-gpu-function-form (name arguments body)
  "Analisa e infere os tipos de uma função SGL pura compartilhada com a CPU."
  (bt:with-lock-held (*shader-registry-lock*)
    (%compile-gpu-function-form name arguments body)))

(defun %compile-gpu-function-form (name arguments body)
  (let ((env (make-hash-table :test #'eq)) (names (mapcar #'first arguments)))
    (unless (= (length names) (length (remove-duplicates names :test #'eq)))
      (%shader-error 'shader-interface-error "Parâmetro de função GPU duplicado." arguments))
    (dolist (argument arguments)
      (unless (and (consp argument) (= (length argument) 2) (symbolp (first argument)))
        (%shader-error 'shader-interface-error "Parâmetro de função GPU inválido." argument))
      (setf (gethash (first argument) env)
            (%make-binding (%type (second argument) argument) :local)))
    (unless (= (length body) 1)
      (%shader-error 'shader-type-error "Função GPU precisa ter uma expressão de retorno." body))
    (let ((ast (%parse-expression (first body) env)))
      (make-gpu-function-definition :name name
                                    :arguments (mapcar (lambda (argument)
                                                         (list (first argument) (%type (second argument) argument)))
                                                       arguments)
                                    :return-type (shader-expression-type ast)
                                    :ast ast :source body))))

(defun %vector-value-p (value)
  (and (or (listp value) (and (vectorp value) (not (stringp value)))
           (and (arrayp value) (> (array-rank value) 1)))
       (not (stringp value))))

(defun %components (value)
  (cond ((and (arrayp value) (> (array-rank value) 1))
         (loop for i below (array-dimension value 0) collect (aref value i)))
        ((and (vectorp value) (not (stringp value))) (coerce value 'list))
        ((listp value) value)
        (t nil)))

(defun %componentwise (function &rest values)
  (let* ((vectors (mapcar #'%components values))
         (width (loop for components in vectors when components return (length components))))
    (if (null width)
        (apply function values)
        (progn
          (unless (every (lambda (components)
                           (or (null components) (= (length components) width) (= (length components) 1)))
                         vectors)
            (%shader-error 'shader-type-error "Comprimentos vetoriais incompatíveis na avaliação CPU." values))
          (loop for index below width collect
            (apply function
                   (loop for value in values for components in vectors collect
                     (if components (nth (if (= (length components) 1) 0 index) components) value))))))))

(defun %evaluate-gpu-function (function arguments)
  (unless (and function (= (length arguments) (length (gpu-function-definition-arguments function))))
    (%shader-error 'shader-type-error "Chamada CPU de função GPU com aridade incorreta." function))
  (let ((env (make-hash-table :test #'eq)))
    (loop for formal in (gpu-function-definition-arguments function)
          for value in arguments do (setf (gethash (first formal) env) value))
    (%evaluate-expression (gpu-function-definition-ast function) env)))

(defun %evaluate-expression (expr env)
  (let ((op (shader-expression-opcode expr)) (args (shader-expression-operands expr)))
    (labels ((eval-arg (arg) (%evaluate-expression arg env)))
      (case op
        (:constant (shader-expression-value expr))
        (:variable (gethash (shader-expression-value expr) env))
        (:sequence (let ((value nil)) (dolist (arg args) (setf value (eval-arg arg))) value))
        (:let
         (let* ((names (getf (shader-expression-attributes expr) :names))
                (count (getf (shader-expression-attributes expr) :initializer-count))
                (sequential (getf (shader-expression-attributes expr) :sequential))
                (inner (make-hash-table :test #'eq)) (initializers (subseq args 0 count)) (result nil))
           (maphash (lambda (key value) (setf (gethash key inner) value)) env)
           (loop for name in names for initializer in initializers do
             (let ((value (%evaluate-expression initializer (if sequential inner env))))
               (setf (gethash name inner) value)))
           (dolist (body (nthcdr count args)) (setf result (%evaluate-expression body inner)))
           result))
        (:select (if (eval-arg (first args)) (eval-arg (second args)) (eval-arg (third args))))
        (:construct (%evaluate-constructor (shader-expression-type expr) (mapcar #'eval-arg args)))
        (:swizzle
         (let* ((value (%components (eval-arg (first args))))
                (selected (mapcar (lambda (index) (nth index value))
                                  (getf (shader-expression-attributes expr) :indices))))
           (if (= (length selected) 1) (first selected) selected)))
        (:field (%cpu-field (eval-arg (first args)) (getf (shader-expression-attributes expr) :member)))
        ((:add :subtract :multiply :divide)
         (let* ((values (mapcar #'eval-arg args))
                (fn (case op (:add #'+) (:subtract #'-) (:multiply #'*) (:divide #'/))))
           (if (= (length values) 1) (%componentwise fn (first values))
               (reduce (lambda (left right) (%componentwise fn left right)) (rest values)
                       :initial-value (first values)))))
        ((:equal :less-than :greater-than :less-equal :greater-equal)
         (let ((left (eval-arg (first args))) (right (eval-arg (second args))))
           (funcall (case op (:equal #'=) (:less-than #'<) (:greater-than #'>)
                          (:less-equal #'<=) (:greater-equal #'>=)) left right)))
        ((:normalize :dot :cross :min :max :pow :clamp :mix :reflect)
         (%evaluate-builtin op (mapcar #'eval-arg args)))
        (:call
         (let* ((callee (%find-gpu-function (getf (shader-expression-attributes expr) :function)))
                (values (mapcar #'eval-arg args)))
           (%evaluate-gpu-function callee values)))
        (:texture-sample
         (let ((sampler (eval-arg (first args))) (uv (eval-arg (second args))))
           (if (functionp sampler) (funcall sampler uv)
               (%shader-error 'shader-error "texture só pode ser avaliada na CPU quando o sampler é uma função." expr))))
        (otherwise (%shader-error 'shader-error (format nil "Opcode não avaliável na CPU: ~S." op) expr))))))

(defun %evaluate-constructor (type values)
  (case (shader-type-kind type)
    (:vector
     (let* ((width (third type)) (flat (mapcan (lambda (value)
                                                 (if (%vector-value-p value) (%components value) (list value))) values)))
       (cond ((= (length flat) 1) (make-list width :initial-element (first flat)))
             ((= (length flat) width) flat)
             (t (%shader-error 'shader-type-error "Quantidade de componentes inválida em construtor CPU." values)))))
    (:matrix
     (let* ((width (second type)) (flat (mapcan (lambda (value)
                                                  (if (%vector-value-p value) (%components value) (list value))) values)))
       (cond ((= (length flat) 1)
              (loop for row below width collect
                (loop for column below width collect (if (= row column) (first flat) 0.0))))
             ((= (length flat) (* width width))
              (loop for row below width collect (subseq flat (* row width) (* (1+ row) width))))
             (t (%shader-error 'shader-type-error "Quantidade de componentes inválida em construtor CPU." values)))))
    (otherwise (%shader-error 'shader-type-error "Tipo inválido para construtor CPU." type))))

(defun %cpu-field (object name)
  (cond ((hash-table-p object) (gethash name object))
        ((and (listp object) (assoc name object :test #'eq)) (cdr (assoc name object :test #'eq)))
        ((and (listp object) (getf object name)) (getf object name))
        ((symbolp name) (or (ignore-errors (slot-value object name))
                            (%shader-error 'shader-error (format nil "Campo CPU inexistente: ~S." name) object)))
        (t (%shader-error 'shader-error (format nil "Campo CPU inexistente: ~S." name) object))))

(defun %dot (a b)
  (reduce #'+ (mapcar #'* (%components a) (%components b)) :initial-value 0.0))

(defun %evaluate-builtin (op values)
  (case op
    (:normalize (let* ((v (first values)) (length (sqrt (%dot v v))))
                  (if (zerop length) v (%componentwise (lambda (x) (/ x length)) v))))
    (:dot (%dot (first values) (second values)))
    (:cross (destructuring-bind (ax ay az) (%components (first values))
              (destructuring-bind (bx by bz) (%components (second values))
                (list (- (* ay bz) (* az by)) (- (* az bx) (* ax bz)) (- (* ax by) (* ay bx))))))
    (:min (%componentwise #'min (first values) (second values)))
    (:max (%componentwise #'max (first values) (second values)))
    (:pow (%componentwise #'expt (first values) (second values)))
    (:clamp (%componentwise (lambda (x low high) (max low (min high x)))
                            (first values) (second values) (third values)))
    (:mix (let ((a (first values)) (b (second values)) (amount (third values)))
            (%componentwise (lambda (x y t-value) (+ x (* (- y x) t-value))) a b amount)))
    (:reflect (let ((incident (first values)) (normal (second values)))
                (%componentwise (lambda (i n) (- i (* 2 (%dot incident normal) n))) incident normal)))))
