(in-package #:sgeo.shader)

(defun %glsl-type (type)
  (cond
    ((eq type :void) "void") ((eq type :bool) "bool") ((eq type :int) "int")
    ((eq type :uint) "uint") ((eq type :float) "float")
    ((and (consp type) (eq (first type) :vector))
     (format nil "~Avec~D" (case (second type) (:int "i") (:uint "u") (otherwise "")) (third type)))
    ((and (consp type) (eq (first type) :matrix)) (format nil "mat~D" (second type)))
    ((and (consp type) (eq (first type) :sampled-image)) "sampler2D")
    (t (string-downcase (symbol-name (if (consp type) (second type) type))))))

(defun %glsl-name (value)
  (string-downcase (if (symbolp value) (symbol-name value) (princ-to-string value))))

(defun %glsl-expression (expr)
  (let ((op (shader-expression-opcode expr)) (args (shader-expression-operands expr)))
    (case op
      (:constant (let ((value (shader-expression-value expr)))
                   (cond ((eq value t) "true") ((floatp value) (format nil "~F" value))
                         (t (princ-to-string value)))))
      (:variable (%glsl-name (shader-expression-value expr)))
      (:field (format nil "~A.~A" (%glsl-expression (first args))
                      (%glsl-name (getf (shader-expression-attributes expr) :member))))
      (:swizzle (format nil "~A.~A" (%glsl-expression (first args))
                        (coerce (map 'vector (lambda (i) (char "xyzw" i))
                                     (getf (shader-expression-attributes expr) :indices)) 'string)))
      (:construct (format nil "~A(~{~A~^, ~})" (%glsl-type (shader-expression-type expr))
                          (mapcar #'%glsl-expression args)))
      (:select (format nil "(~A ? ~A : ~A)" (%glsl-expression (first args))
                       (%glsl-expression (second args)) (%glsl-expression (third args))))
      (:sequence (format nil "(~{~A~^, ~})" (mapcar #'%glsl-expression args)))
      (:let (let* ((attrs (shader-expression-attributes expr))
                   (names (getf attrs :names)) (count (getf attrs :initializer-count))
                   (inits (subseq args 0 count)) (body (nthcdr count args)))
              (declare (ignore inits))
              (format nil "(/* let ~{~A~^, ~} */ ~A)" names (%glsl-expression (car (last body))))))
      (:texture-sample (format nil "texture(~A, ~A)" (%glsl-expression (first args)) (%glsl-expression (second args))))
      ((:add :subtract :multiply :divide :equal :less-than :greater-than :less-equal :greater-equal)
       (let ((symbol (case op (:add "+") (:subtract "-") (:multiply "*") (:divide "/")
                        (:equal "==") (:less-than "<") (:greater-than ">") (:less-equal "<=") (:greater-equal ">="))))
         (if (and (eq op :subtract) (= (length args) 1))
             (format nil "(-~A)" (%glsl-expression (first args)))
             (format nil "(~A)"
                     (reduce (lambda (left right) (format nil "~A ~A ~A" left symbol right))
                             (mapcar #'%glsl-expression args))))))
      ((:normalize :dot :cross :min :max :pow :clamp :mix :reflect)
       (format nil "~A(~{~A~^, ~})" (string-downcase (symbol-name op)) (mapcar #'%glsl-expression args)))
      (otherwise (format nil "/* unsupported ~A */ 0" op)))))

(defun %std140-glsl (param stream)
  (let ((type (shader-parameter-type param)) (name (shader-parameter-name param)))
    (when (and (consp type) (eq (first type) :struct))
      (format stream "layout(std140, set = ~D, binding = ~D) uniform ~A_block {~%"
              (shader-parameter-set param) (shader-parameter-binding param) (%glsl-name name))
      (dolist (member (third type))
        (format stream "  ~A ~A;~%" (%glsl-type (second member)) (%glsl-name (first member))))
      (format stream "} ~A;~%" (%glsl-name name)))))

(defun emit-glsl (definition &optional (stream nil))
  "Emite GLSL 450 legível para depuração de uma definição SGL."
  (let ((out (or stream (make-string-output-stream))) (stage (shader-definition-stage definition)))
    (format out "#version 450~%")
    (dolist (param (shader-definition-parameters definition))
      (case (shader-parameter-storage param)
        (:uniform
         (if (eq (shader-type-kind (shader-parameter-type param)) :struct)
             (%std140-glsl param out)
             (format out "layout(set = ~D, binding = ~D) uniform ~A ~A;~%"
                     (shader-parameter-set param) (shader-parameter-binding param)
                     (%glsl-type (shader-parameter-type param)) (%glsl-name (shader-parameter-name param)))))
        (:input (format out "layout(location = ~D) in ~A ~A;~%"
                        (or (shader-parameter-location param) 0) (%glsl-type (shader-parameter-type param))
                        (%glsl-name (shader-parameter-name param))))))
    (loop for output in (shader-definition-outputs definition) for index from 0 do
      (unless (eq (shader-output-name output) :position)
        (format out "layout(location = ~D) out ~A ~A;~%"
                (%shader-output-location (shader-definition-outputs definition) index)
                (%glsl-type (shader-output-type output)) (%glsl-name (shader-output-name output)))))
    (format out "void main() {~%")
    (dolist (output (shader-definition-outputs definition))
      (format out "  ~A = ~A;~%"
              (if (eq (shader-output-name output) :position) "gl_Position" (%glsl-name (shader-output-name output)))
              (%glsl-expression (shader-output-expression output))))
    (format out "}~%")
    (if stream definition (get-output-stream-string out))))

(defun link-shaders (vertex fragment)
  "Valida varyings e descritores compartilhados entre vertex e fragment."
  (unless (and (eq (shader-definition-stage vertex) :vertex)
               (eq (shader-definition-stage fragment) :fragment))
    (%shader-error 'shader-interface-error "link-shaders exige vertex e fragment nessa ordem." (list vertex fragment)))
  (let ((vertex-descriptors (make-hash-table :test #'equal))
        (outputs (shader-definition-outputs vertex)))
    (dolist (parameter (shader-definition-parameters vertex))
      (when (member (shader-parameter-storage parameter) '(:uniform :storage-buffer) :test #'eq)
        (setf (gethash (list (shader-parameter-set parameter)
                             (shader-parameter-binding parameter)) vertex-descriptors)
              parameter)))
    (dolist (parameter (shader-definition-parameters fragment))
      (when (member (shader-parameter-storage parameter) '(:uniform :storage-buffer) :test #'eq)
        (let* ((key (list (shader-parameter-set parameter) (shader-parameter-binding parameter)))
               (other (gethash key vertex-descriptors)))
          (when (and other
                     (not (equal (%descriptor-signature parameter)
                                 (%descriptor-signature other))))
            (%shader-error 'shader-interface-error
                           (format nil "Descritor set ~D/binding ~D tem tipo/layout incompatível entre vertex e fragment."
                                   (first key) (second key))
                           (list other parameter))))))
    (dolist (input (remove-if-not (lambda (param) (eq (shader-parameter-storage param) :input))
                                  (shader-definition-parameters fragment)))
      (let* ((location (shader-parameter-location input))
             (matched (loop for output in outputs for index from 0
                            when (and (not (eq (shader-output-name output) :position))
                                      (= (%shader-output-location outputs index) location))
                              return output)))
        (unless (and matched (equal (shader-output-type matched) (shader-parameter-type input)))
          (%shader-error 'shader-interface-error "Entrada fragment sem saída vertex compatível." input))))
    t))
