(in-package #:sgeo.shader)

(defun %sgir-type (type)
  (cond ((member type '(:void :bool :int :uint :float) :test #'eq) type)
        ((and (consp type) (eq (first type) :vector)) type)
        ((and (consp type) (eq (first type) :matrix)) type)
        ((and (consp type) (eq (first type) :sampled-image)) type)
        ((and (consp type) (eq (first type) :image)) type)
        (t type)))

(defun %opcode-for-arithmetic (opcode type)
  (let* ((base (%scalar-type type))
         (prefix (if (eq base :float) :f (if (eq base :uint) :u :s))))
    (case opcode
      (:add (intern (format nil "~AADD" prefix) :keyword))
      (:subtract (intern (format nil "~ASUB" prefix) :keyword))
      (:multiply (intern (format nil "~AMUL" prefix) :keyword))
      (:divide (intern (format nil "~ADIV" prefix) :keyword)))))

(defun %lower-shader (name stage parameters outputs)
  "Baixa a AST tipada para SGIR SSA com interfaces Vulkan explícitas."
  (let ((interfaces nil) (instructions nil) (next-id 0) (locals (make-hash-table :test #'eq)))
    (labels ((new-id () (incf next-id))
             (emit (opcode type operands &optional attributes)
               (let ((result (new-id)))
                 (push (make-sgir-instruction :opcode opcode :result result :type (%sgir-type type)
                                              :operands operands :attributes attributes)
                       instructions)
                 result))
             (interface-for (param)
               (let* ((storage (shader-parameter-storage param))
                      (iface (make-sgir-interface
                              :name (shader-parameter-name param) :type (%sgir-type (shader-parameter-type param))
                              :storage (if (eq storage :storage-buffer) :storage-buffer storage)
                              :location (shader-parameter-location param)
                              :set (shader-parameter-set param) :binding (shader-parameter-binding param)
                              :decorations (shader-parameter-decorations param))))
                 (push iface interfaces)))
             (lower (expr)
               (let* ((opcode (shader-expression-opcode expr))
                      (type (shader-expression-type expr))
                      (args (shader-expression-operands expr)))
                 (case opcode
                   (:constant (emit :constant type nil (list :value (shader-expression-value expr))))
                   (:variable
                    (let ((name (shader-expression-value expr)))
                      (let ((local (gethash name locals)))
                        (cond ((integerp local) local)
                              ((and (consp local) (eq (first local) :parameter))
                               (emit :load type nil (list :parameter name)))
                              (t (emit :load type nil (list :interface name
                                                           :storage (getf (shader-expression-attributes expr) :storage))))))))
                   (:sequence (let ((id nil)) (dolist (child args) (setf id (lower child))) id))
                   (:let
                    (let* ((names (getf (shader-expression-attributes expr) :names))
                           (count (getf (shader-expression-attributes expr) :initializer-count))
                           (sequential (getf (shader-expression-attributes expr) :sequential))
                           (old (make-hash-table :test #'eq)) (missing (gensym "MISSING"))
                           (inits (subseq args 0 count)) (body (nthcdr count args)) (result nil))
                      (dolist (name names) (setf (gethash name old) (gethash name locals missing)))
                      (loop for name in names for init in inits do
                        (let ((value (lower init)))
                          (if sequential (setf (gethash name locals) value)
                              (setf (gethash name old) (cons (gethash name old) value)))))
                      (unless sequential
                        (loop for name in names for pair = (gethash name old) do
                          (setf (gethash name locals) (cdr pair))))
                      (dolist (child body) (setf result (lower child)))
                      (dolist (name names)
                        (let ((previous (gethash name old)))
                          (cond ((consp previous)
                                 (if (eq (car previous) missing) (remhash name locals)
                                     (setf (gethash name locals) (car previous))))
                                ((eq previous missing) (remhash name locals))
                                (t (setf (gethash name locals) previous)))))
                      result))
                   (:select (emit :select type (mapcar #'lower args)))
                   (:construct (emit :construct type (mapcar #'lower args)
                                     (shader-expression-attributes expr)))
                   (:swizzle (emit :swizzle type (list (lower (first args)))
                                   (shader-expression-attributes expr)))
                   (:texture-sample (emit :texture-sample type (mapcar #'lower args)))
                   (:call (emit :call type (mapcar #'lower args)
                                (list :function (getf (shader-expression-attributes expr) :function))))
                   (:field
                    (let* ((base (first args)) (base-op (shader-expression-opcode base))
                           (name (shader-expression-value base)))
                      (unless (eq base-op :variable)
                        (%shader-error 'shader-error "Acesso a campo exige interface uniforme nomeada." expr))
                      (emit :load type nil (list :interface name :storage :uniform
                                                 :member (getf (shader-expression-attributes expr) :member)))))
                   ((:add :subtract :multiply :divide)
                    (let* ((ids (mapcar #'lower args))
                           (left-type (shader-expression-type (first args)))
                           (right-type (and (second args) (shader-expression-type (second args)))))
                      (cond ((and (eq opcode :multiply) (eq (shader-type-kind left-type) :matrix)
                                  (eq (shader-type-kind right-type) :vector))
                             (emit :matrix-times-vector type ids))
                            ((and (eq opcode :multiply) (eq (shader-type-kind left-type) :matrix)
                                  (eq (shader-type-kind right-type) :matrix))
                             (emit :matrix-times-matrix type ids))
                            ((and (eq opcode :multiply) (eq (shader-type-kind left-type) :vector)
                                  (eq (shader-type-kind right-type) :matrix))
                             (emit :vector-times-matrix type ids))
                            ((and (eq opcode :subtract) (= (length ids) 1)) (emit :fneg type ids))
                            (t (emit (%opcode-for-arithmetic opcode type) type ids)))))
                   ((:equal :less-than :greater-than :less-equal :greater-equal)
                    (let* ((base (%scalar-type (shader-expression-type (first args))))
                           (signed (not (eq base :uint)))
                           (prefix (if (eq base :float) :f (if signed :s :u)))
                           (suffix (case opcode (:equal :equal) (:less-than :less-than)
                                     (:greater-than :greater-than) (:less-equal :less-equal) (:greater-equal :greater-equal))))
                      (emit (intern (format nil "~A~A" prefix suffix) :keyword) :bool (mapcar #'lower args))))
                   (otherwise
                    (let ((ids (mapcar #'lower args)))
                      (case opcode
                        (:dot (emit :dot type ids))
                        (:cross (emit :cross type ids))
                        (:min (emit :min type ids)) (:max (emit :max type ids))
                        (:pow (emit :extinst type ids (list :instruction-set :glsl-std-450 :instruction :pow)))
                        (:normalize (emit :extinst type ids (list :instruction-set :glsl-std-450 :instruction :normalize)))
                        (:clamp (emit :extinst type ids (list :instruction-set :glsl-std-450 :instruction :clamp)))
                        (:mix (emit :extinst type ids (list :instruction-set :glsl-std-450 :instruction :mix)))
                        (:reflect (emit :extinst type ids (list :instruction-set :glsl-std-450 :instruction :reflect)))
                        (otherwise (%shader-error 'shader-error (format nil "Opcode sem lower SGIR: ~S." opcode) expr)))))))))
      (dolist (parameter parameters) (interface-for parameter))
      (let ((stores nil))
        (dolist (output outputs)
          (let* ((name (shader-output-name output))
                 (builtin (eq name :position))
                 (location (unless builtin
                            (%shader-output-location outputs
                                                     (position output outputs :test #'eq))))
                 (interface (make-sgir-interface :name name :type (%sgir-type (shader-output-type output))
                                                 :storage :output :location location
                                                 :decorations (when builtin (list :builtin :position)))))
            (push interface interfaces)
            (let ((value (lower (shader-output-expression output))))
              (push (make-sgir-instruction :opcode :store :result nil :type :void :operands (list value)
                                           :attributes (list :interface name :storage :output)) stores))))
        (make-sgir-module
         :name name :stage stage :entry-point name
         :interfaces (nreverse interfaces)
         :functions (append
                     (list (make-sgir-function
                            :name name :return-type :void :parameters nil
                            :blocks (list (make-sgir-block :name 'entry
                                                           :instructions (append (nreverse instructions) (nreverse stores))
                                                           :terminator (make-sgir-terminator :opcode :return :operands nil :targets nil)))))
                     (mapcar #'%lower-gpu-function
                             (loop for function being the hash-values of *gpu-function-definitions* collect function))))))))

(defun %lower-gpu-function (function)
  (let ((instructions nil) (next-id 0) (locals (make-hash-table :test #'eq)))
    (labels ((emit (opcode type operands &optional attributes)
               (let ((result (incf next-id)))
                 (push (make-sgir-instruction :opcode opcode :result result :type (%sgir-type type)
                                              :operands operands :attributes attributes) instructions)
                 result)))
      (dolist (argument (gpu-function-definition-arguments function))
        (setf (gethash (first argument) locals) (list :parameter (first argument))))
      (let* ((value (%lower-function-expression (gpu-function-definition-ast function) locals #'emit))
             (parameters (mapcar (lambda (argument)
                                   (make-sgir-parameter :name (first argument) :type (%sgir-type (second argument))
                                                        :storage :function :decorations nil))
                                 (gpu-function-definition-arguments function))))
        (make-sgir-function :name (gpu-function-definition-name function)
                            :return-type (%sgir-type (gpu-function-definition-return-type function))
                            :parameters parameters
                            :blocks (list (make-sgir-block :name 'entry :instructions (nreverse instructions)
                                                           :terminator (make-sgir-terminator :opcode :return-value
                                                                                            :operands (list value) :targets nil))))))))

(defun %lower-function-expression (expr locals emit)
  (let ((op (shader-expression-opcode expr))
        (type (shader-expression-type expr))
        (args (shader-expression-operands expr)))
    (labels ((lower (child)
               (%lower-function-expression child locals emit))
             (arith-opcode (left right)
               (cond ((and (eq op :multiply)
                           (eq (shader-type-kind left) :matrix)
                           (eq (shader-type-kind right) :vector))
                      :matrix-times-vector)
                     ((and (eq op :multiply)
                           (eq (shader-type-kind left) :matrix)
                           (eq (shader-type-kind right) :matrix))
                      :matrix-times-matrix)
                     ((and (eq op :multiply)
                           (eq (shader-type-kind left) :vector)
                           (eq (shader-type-kind right) :matrix))
                      :vector-times-matrix)
                     (t (%opcode-for-arithmetic op type))))
             (emit-extinst (ids instruction)
               (funcall emit :extinst type ids
                        (list :instruction-set :glsl-std-450 :instruction instruction))))
      (case op
        (:constant
         (funcall emit :constant type nil (list :value (shader-expression-value expr))))
        (:variable
         (let ((value (gethash (shader-expression-value expr) locals)))
           (if (and (consp value) (eq (first value) :parameter))
               (funcall emit :load type nil (list :parameter (second value)))
               value)))
        (:sequence
         (let ((value nil))
           (dolist (arg args value) (setf value (lower arg)))))
        (:let
         (let* ((attributes (shader-expression-attributes expr))
                (names (getf attributes :names))
                (count (getf attributes :initializer-count))
                (sequential (getf attributes :sequential))
                (initializers (subseq args 0 count))
                (old (make-hash-table :test #'eq))
                (missing (gensym "MISSING"))
                (result nil))
           (dolist (name names)
             (setf (gethash name old) (gethash name locals missing)))
           (if sequential
               (loop for name in names for initializer in initializers do
                 (setf (gethash name locals) (lower initializer)))
               (loop for name in names for value in (mapcar #'lower initializers) do
                 (setf (gethash name locals) value)))
           (dolist (arg (nthcdr count args)) (setf result (lower arg)))
           (dolist (name names)
             (let ((previous (gethash name old)))
               (if (eq previous missing)
                   (remhash name locals)
                   (setf (gethash name locals) previous))))
           result))
        ((:add :subtract :multiply :divide)
         (let* ((left-type (shader-expression-type (first args)))
                (right-type (and (second args) (shader-expression-type (second args))))
                (opcode (if (and left-type right-type)
                            (arith-opcode left-type right-type)
                            (%opcode-for-arithmetic op type))))
           (funcall emit opcode type (mapcar #'lower args))))
        (:call
         (funcall emit :call type (mapcar #'lower args)
                  (list :function (getf (shader-expression-attributes expr) :function))))
        (otherwise
         (let ((ids (mapcar #'lower args)))
           (case op
             (:construct (funcall emit :construct type ids (shader-expression-attributes expr)))
             (:normalize (emit-extinst ids :normalize))
             (:dot (funcall emit :dot type ids))
             (:cross (funcall emit :cross type ids))
             (:min (funcall emit :min type ids))
             (:max (funcall emit :max type ids))
             (:pow (emit-extinst ids :pow))
             (:clamp (emit-extinst ids :clamp))
             (:mix (emit-extinst ids :mix))
             (:reflect (emit-extinst ids :reflect))
             (otherwise
              (%shader-error 'shader-error "Opcode não suportado em função GPU." expr)))))))))
