(in-package #:sgeo.serialization)

(defun %animation-value-data (value)
  "Codifica valores numéricos sem depender de estruturas do leitor Lisp."
  (cond ((%finite-real-p value) (list :scalar value))
        ((typep value 'sgeo.math:quaternion)
         (list :quaternion (%vector-values (sgeo.math::quaternion-data value))))
        ((and (vectorp value) (not (stringp value)) (every #'%finite-real-p value))
         (list :vector (%vector-values value)))
        (t (%fail "animação" "A persistência de pistas aceita valores numéricos finitos."))))

(defun %animation-value-from-data (data)
  (%plist-pairs data "valor de animação" nil '(:scalar :quaternion :vector))
  (unless (= (length data) 2) (%fail "animação" "Valor de animação ambíguo."))
  (case (first data)
    (:scalar (unless (%finite-real-p (second data)) (%fail "animação" "Escalar não finito.")) (second data))
    (:vector (unless (and (%proper-list-p (second data)) (every #'%finite-real-p (second data)))
               (%fail "animação" "Vetor não finito."))
             (coerce (second data) 'vector))
    (:quaternion (%vec-list (second data) 4 "quaternion de animação")
                 (apply #'sgeo.math:make-quaternion (second data)))))

(defun %animation-symbol-data (symbol)
  (unless (and (symbolp symbol) (symbol-package symbol))
    (%fail "animação" "Caminhos persistentes precisam de símbolos nomeados."))
  (list (package-name (symbol-package symbol)) (symbol-name symbol)))

(defun %animation-symbol-from-data (data)
  (unless (and (%proper-list-p data) (= (length data) 2) (every #'stringp data))
    (%fail "animação" "Referência de símbolo inválida."))
  (or (let ((package (find-package (first data))))
        (when package (find-symbol (second data) package)))
      (%fail "animação" "Símbolo persistente não está definido nesta sessão.")))

(defun %animation-path-data (path)
  "Persiste caminhos de dados; funções arbitrárias permanecem apenas na sessão viva."
  (unless (and (%proper-list-p path) path) (%fail "animação" "Caminho vazio ou circular."))
  (mapcar (lambda (segment)
            (cond ((symbolp segment) (list :symbol (%animation-symbol-data segment)))
                  ((and (consp segment) (symbolp (first segment))
                        (member (symbol-name (first segment)) '("SLOT" "AREF" "NTH" "CAR" "CDR") :test #'string=))
                   (list :segment (mapcar (lambda (value)
                                            (if (symbolp value) (list :symbol (%animation-symbol-data value)) value)) segment)))
                  (t (%fail "animação" "Caminho com função não pode ser salvo.")))) path))

(defun %animation-path-from-data (data)
  (unless (and (%proper-list-p data) data) (%fail "animação" "Caminho inválido."))
  (mapcar (lambda (segment)
            (%plist-pairs segment "segmento de caminho" nil '(:symbol :segment))
            (unless (= (length segment) 2) (%fail "animação" "Segmento ambíguo."))
            (case (first segment)
              (:symbol (%animation-symbol-from-data (second segment)))
              (:segment (let ((values (second segment)))
                          (unless (%proper-list-p values) (%fail "animação" "Segmento inválido."))
                          (let ((decoded (mapcar (lambda (value)
                                                 (if (consp value)
                                                     (progn
                                                       (%plist-pairs value "símbolo de segmento" '(:symbol) nil)
                                                       (%animation-symbol-from-data (second value))) value)) values)))
                            (unless (and (symbolp (first decoded))
                                         (member (symbol-name (first decoded)) '("SLOT" "AREF" "NTH" "CAR" "CDR") :test #'string=))
                              (%fail "animação" "Operação de caminho não permitida.")) decoded))))) data))

(defun %animation-key-data (key)
  (cons (first key) (mapcar (lambda (value) (when value (%animation-value-data value))) (rest key))))

(defun %animation-key-from-data (key)
  (unless (and (%proper-list-p key) (<= 2 (length key) 4) (%finite-real-p (first key))
               (>= (first key) 0)) (%fail "animação" "Chave inválida."))
  (cons (first key) (mapcar (lambda (value) (when value (%animation-value-from-data value))) (rest key))))

(defun %animation-track-data (track ids)
  (typecase track
    (sgeo.animation:property-track
     (let ((id (gethash (sgeo.animation:track-target track) ids)))
       (unless id (%fail "animação" "A pista referencia um alvo fora da cena."))
       (list :type :property :target-id id :path (%animation-path-data (sgeo.animation:track-path track))
             :interpolation (sgeo.animation:track-interpolation track)
             :easings (copy-list (sgeo.animation:track-easings track))
             :keys (mapcar #'%animation-key-data (sgeo.animation:track-keys track)))))
    (sgeo.animation:event-track
     (let ((handler (slot-value track 'sgeo.animation::handler)))
       (unless (or (null handler) (and (symbolp handler) (fboundp handler)))
         (%fail "animação" "O handler de evento precisa ser uma função nomeada para salvar."))
       (list :type :event :events (%copy-metadata-value (slot-value track 'sgeo.animation::events))
             :handler (when handler (%animation-symbol-data handler)))))
    (t (%fail "animação" "Tipo de pista não persistente."))))

(defun %animation-data (world objects geometries materials)
  (declare (ignore geometries materials))
  (let* ((state (sgeo.scene:world-animation-state world))
         (deformables (remove-if-not (lambda (object) (typep object 'sgeo.animation:deformable-mesh-object)) objects))
         (skeletons (remove-duplicates (remove nil (mapcar #'sgeo.animation:mesh-skeleton deformables)) :test #'eq))
         (clips (when state (sgeo.animation:animation-state-clips state)))
         (ids (make-hash-table :test #'eq)))
    (dolist (object objects)
      (setf (gethash object ids) (object-id object))
      (when (typep object 'mesh-object)
        (dolist (item (list (mesh-object-geometry object) (mesh-object-material object)))
          (setf (gethash item ids) (object-id item)))))
    (when (or state deformables)
      (labels ((id (object)
                 (and object (or (gethash object ids) (%fail "animação" "Referência fora da cena."))))
               (mask-data (mask)
                 (cond ((null mask) nil)
                       ((%proper-list-p mask)
                        (mapcar (lambda (entry) (if (symbolp entry) (list :symbol (%animation-symbol-data entry))
                                                   (list :path (%animation-path-data entry)))) mask))
                       (t (%fail "animação" "Máscaras persistentes devem ser listas de caminhos.")))))
        (list :time (if state (sgeo.animation:animation-state-time state) 0d0)
              :skeletons
              (mapcar (lambda (skeleton)
                        (list :name (slot-value skeleton 'sgeo.animation::name)
                              :joints (map 'list #'id (sgeo.animation:skeleton-joints skeleton))
                              :root-id (id (sgeo.animation:skeleton-root skeleton))
                              :inverse-bind-matrices (map 'list #'%vector-values (sgeo.animation:skeleton-inverse-bind-matrices skeleton)))) skeletons)
              :deformations
              (mapcar (lambda (object)
                        (list :object-id (id object) :skeleton (position (sgeo.animation:mesh-skeleton object) skeletons :test #'eq)
                              :joint-indices (map 'list (lambda (x) (coerce x 'list)) (sgeo.animation:mesh-joint-indices object))
                              :joint-weights (map 'list (lambda (x) (coerce x 'list)) (sgeo.animation:mesh-joint-weights object))
                              :morph-weights (%vector-values (sgeo.animation:mesh-morph-weights object))
                              :morph-targets (map 'list (lambda (target)
                                                        (list :positions (%vector-values (sgeo.animation:morph-target-positions target))
                                                              :normals (%vector-values (sgeo.animation:morph-target-normals target))))
                                                  (sgeo.animation:mesh-morph-targets object)))) deformables)
              :references (when state
                            (let ((records nil))
                              (maphash (lambda (key value)
                                         (push (list :target-id (id (first key))
                                                     :path (%animation-path-data (second key))
                                                     :value (%animation-value-data value)) records))
                                       (slot-value state 'sgeo.animation::references))
                              (sort records #'string< :key (lambda (entry) (prin1-to-string entry)))))
              :clips (mapcar (lambda (clip)
                               (list :name (slot-value clip 'sgeo.animation::name) :duration (sgeo.animation:clip-duration clip)
                                     :tracks (mapcar (lambda (track) (%animation-track-data track ids)) (sgeo.animation:clip-tracks clip)))) clips)
              :players (when state
                         (mapcar (lambda (player)
                                   (list :clip (or (position (sgeo.animation:player-clip player) clips)
                                                   (%fail "animação" "Player fora da biblioteca de clipes."))
                                         :time (sgeo.animation:player-time player) :weight (sgeo.animation:player-weight player)
                                         :speed (sgeo.animation:player-speed player) :looping-p (sgeo.animation:player-looping-p player)
                                         :playing-p (sgeo.animation:player-playing-p player)
                                         :enabled-p (slot-value player 'sgeo.animation::enabled-p)
                                         :additive-p (sgeo.animation:player-additive-p player) :mask (mask-data (sgeo.animation:player-mask player))
                                         :root-target-id (id (slot-value player 'sgeo.animation::root-motion-target))
                                         :root-joint-id (id (slot-value player 'sgeo.animation::root-motion-joint))))
                                 (sgeo.animation:animation-state-players state))))))))

(defun %validate-animation-data (data objects geometries materials &optional scene)
  "Valida coleções e referências antes de construir ou publicar a cena."
  (%plist-pairs data "animação" '(:time :skeletons :deformations :clips :players :references) nil)
  (unless (and (%finite-real-p (getf data :time)) (>= (getf data :time) 0)) (%fail "animação" "Tempo inválido."))
  (dolist (key '(:skeletons :deformations :clips :players :references))
    (unless (%proper-list-p (getf data key)) (%fail "animação" "Coleção inválida.")))
  (labels ((ref (id &optional any)
             (unless (and (integerp id) (or (gethash id objects)
                                            (and any (or (gethash id geometries) (gethash id materials)))))
               (%fail "animação" "Referência inexistente.")))
           (index (value collection)
             (unless (and (integerp value) (<= 0 value) (< value (length collection)))
               (%fail "animação" "Índice de coleção inválido.")))
           (numbers (values)
             (unless (and (%proper-list-p values) (every #'%finite-real-p values))
               (%fail "animação" "Lista numérica inválida."))))
    (dolist (reference (getf data :references))
      (%plist-pairs reference "pose de referência" '(:target-id :path :value) nil)
      (ref (getf reference :target-id) t)
      (%animation-path-from-data (getf reference :path))
      (%animation-value-from-data (getf reference :value)))
    (dolist (skeleton (getf data :skeletons))
      (%plist-pairs skeleton "esqueleto" '(:name :joints :root-id :inverse-bind-matrices) nil)
      (unless (stringp (getf skeleton :name)) (%fail "animação" "Nome de esqueleto inválido."))
      (unless (and (%proper-list-p (getf skeleton :joints)) (getf skeleton :joints)) (%fail "animação" "Esqueleto vazio."))
      (mapc #'ref (getf skeleton :joints))
      (when (getf skeleton :root-id) (ref (getf skeleton :root-id)))
      (unless (= (length (getf skeleton :joints)) (length (getf skeleton :inverse-bind-matrices)))
        (%fail "animação" "Número de matrizes de bind incorreto."))
      (dolist (matrix (getf skeleton :inverse-bind-matrices)) (%vec-list matrix 16 "matriz de bind")))
    (let ((seen nil))
      (dolist (record (getf data :deformations))
        (%plist-pairs record "deformação" '(:object-id :skeleton :joint-indices :joint-weights :morph-weights :morph-targets) nil)
        (ref (getf record :object-id))
        (when (member (getf record :object-id) seen) (%fail "animação" "Deformação repetida."))
        (push (getf record :object-id) seen)
        (when (getf record :skeleton) (index (getf record :skeleton) (getf data :skeletons)))
        (dolist (key '(:joint-indices :joint-weights :morph-targets))
          (unless (%proper-list-p (getf record key)) (%fail "animação" "Dados de deformação inválidos.")))
        (dolist (indices (getf record :joint-indices))
          (unless (and (%proper-list-p indices) (every (lambda (x) (and (integerp x) (>= x 0))) indices))
            (%fail "animação" "Índices de juntas inválidos.")))
        (dolist (weights (getf record :joint-weights)) (numbers weights))
        (numbers (getf record :morph-weights))
        (dolist (target (getf record :morph-targets))
          (%plist-pairs target "morph target" '(:positions :normals) nil)
          (numbers (getf target :positions)) (numbers (getf target :normals)))
        (when scene
          (let* ((object (find (getf record :object-id) (getf (rest scene) :objects)
                               :key (lambda (item) (getf item :id))))
                 (geometry (find (getf object :geometry-id) (getf (rest scene) :geometries)
                                 :key (lambda (item) (getf item :id))))
                 (skeleton (when (getf record :skeleton) (nth (getf record :skeleton) (getf data :skeletons))))
                 (joint-count (length (getf skeleton :joints)))
                 (vertex-count
                   (when geometry
                     (if (eq (getf geometry :type) :triangle-mesh)
                         (length (getf geometry :positions))
                         (/ (length (sgeo.geometry:render-mesh-positions
                                     (sgeo.core:compile-render-data
                                      (sgeo.geometry:make-half-edge-mesh
                                       :positions (mapcar (lambda (p) (apply #'make-vec3 p)) (getf geometry :positions))
                                       :faces (getf geometry :faces))))) 3)))))
            (unless (and (eq (getf object :type) :mesh-object) vertex-count)
              (%fail "animação" "Somente objetos de malha podem ter deformação."))
            (unless (and (= vertex-count (length (getf record :joint-indices)))
                         (= vertex-count (length (getf record :joint-weights))))
              (%fail "animação" "Influências precisam corresponder aos vértices renderizáveis."))
            (loop for indices in (getf record :joint-indices) for weights in (getf record :joint-weights) do
              (unless (and (= (length indices) (length weights))
                           (every (lambda (index) (< index joint-count)) indices)
                           (every (lambda (weight) (>= weight 0)) weights)
                           (or (null skeleton) (plusp (reduce #'+ weights :initial-value 0d0))))
                (%fail "animação" "Influência de junta inválida.")))
            (unless (= (length (getf record :morph-targets)) (length (getf record :morph-weights)))
              (%fail "animação" "Número de pesos morfológicos incorreto."))
            (dolist (target (getf record :morph-targets))
              (unless (and (= (* 3 vertex-count) (length (getf target :positions)))
                           (or (null (getf target :normals)) (= (* 3 vertex-count) (length (getf target :normals)))))
                (%fail "animação" "Alvo morfológico incompatível com a malha.")))))))
    (dolist (clip (getf data :clips))
      (%plist-pairs clip "clipe" '(:name :duration :tracks) nil)
      (unless (or (null (getf clip :name)) (stringp (getf clip :name))) (%fail "animação" "Nome de clipe inválido."))
      (unless (and (%finite-real-p (getf clip :duration)) (>= (getf clip :duration) 0)) (%fail "animação" "Duração inválida."))
      (unless (%proper-list-p (getf clip :tracks)) (%fail "animação" "Pistas inválidas."))
      (dolist (track (getf clip :tracks))
        (case (getf track :type)
          (:property
           (%plist-pairs track "pista" '(:type :target-id :path :interpolation :keys :easings) nil)
           (ref (getf track :target-id) t) (%animation-path-from-data (getf track :path))
           (unless (member (getf track :interpolation) '(:step :linear :cubic-spline)) (%fail "animação" "Interpolação inválida."))
           (unless (and (%proper-list-p (getf track :easings))
                        (or (null (getf track :easings)) (= (length (getf track :easings)) (length (getf track :keys))))
                        (every (lambda (x) (member x '(nil :linear :in :out :in-out))) (getf track :easings)))
             (%fail "animação" "Curva de easing inválida."))
           (unless (and (%proper-list-p (getf track :keys)) (getf track :keys)) (%fail "animação" "Pista sem chaves."))
           (mapc #'%animation-key-from-data (getf track :keys)))
          (:event
           (%plist-pairs track "pista de evento" '(:type :events :handler) nil)
           (%copy-metadata-value (getf track :events))
           (when (getf track :handler)
             (let ((handler (%animation-symbol-from-data (getf track :handler))))
               (unless (fboundp handler) (%fail "animação" "Handler de evento ausente.")))))
          (t (%fail "animação" "Tipo de pista desconhecido.")))))
    (dolist (player (getf data :players))
      (%plist-pairs player "player" '(:clip :time :weight :speed :looping-p :playing-p :enabled-p :additive-p :mask :root-target-id :root-joint-id) nil)
      (index (getf player :clip) (getf data :clips))
      (dolist (key '(:time :weight :speed))
        (unless (%finite-real-p (getf player key)) (%fail "animação" "Parâmetro de player não finito.")))
      (when (or (< (getf player :time) 0) (< (getf player :weight) 0)) (%fail "animação" "Tempo/peso negativo."))
      (dolist (key '(:looping-p :playing-p :enabled-p :additive-p))
        (unless (member (getf player key) '(nil t)) (%fail "animação" "Estado booleano inválido.")))
      (dolist (key '(:root-target-id :root-joint-id)) (when (getf player key) (ref (getf player key))))
      (unless (%proper-list-p (getf player :mask)) (%fail "animação" "Máscara inválida."))
      (dolist (entry (getf player :mask))
        (%plist-pairs entry "máscara" nil '(:symbol :path))
        (unless (= (length entry) 2) (%fail "animação" "Máscara ambígua."))
        (if (eq (first entry) :symbol) (%animation-symbol-from-data (second entry))
            (%animation-path-from-data (second entry))))))
  data)

(defun %restore-animation-data (world data objects geometries materials)
  "Reconstrói os alvos e camadas em um mundo ainda privado, sem executar handlers."
  (let* ((skeletons (mapcar (lambda (record)
                            (sgeo.animation:make-skeleton :name (getf record :name)
                             :joints (map 'vector (lambda (id) (gethash id objects)) (getf record :joints))
                             :root (gethash (getf record :root-id) objects)
                             :inverse-bind-matrices (map 'vector (lambda (m) (sgeo.math:make-mat4 (coerce m 'vector)))
                                                        (getf record :inverse-bind-matrices)))) (getf data :skeletons)))
         (state (sgeo.animation:ensure-animation-state world)))
    (dolist (record (getf data :deformations))
      (let* ((object (gethash (getf record :object-id) objects))
             (targets (map 'vector (lambda (target)
                                    (sgeo.animation:make-morph-target :positions (coerce (getf target :positions) 'vector)
                                                                     :normals (when (getf target :normals) (coerce (getf target :normals) 'vector))))
                           (getf record :morph-targets)))
             (arguments (list :geometry (mesh-object-geometry object) :material (mesh-object-material object)
                              :skeleton (when (getf record :skeleton) (nth (getf record :skeleton) skeletons))
                              :joint-indices (map 'vector (lambda (x) (coerce x 'vector)) (getf record :joint-indices))
                              :joint-weights (map 'vector (lambda (x) (coerce x 'vector)) (getf record :joint-weights))
                              :morph-targets targets :morph-weights (coerce (getf record :morph-weights) 'vector)))
             (validated (apply #'sgeo.animation:make-deformable-mesh-object arguments)))
        ;; O construtor validou comprimentos e influências antes de trocar a classe.
        (change-class object 'sgeo.animation:deformable-mesh-object
                      :skeleton (sgeo.animation:mesh-skeleton validated)
                      :joint-indices (sgeo.animation:mesh-joint-indices validated)
                      :joint-weights (sgeo.animation:mesh-joint-weights validated)
                      :morph-targets targets :morph-weights (sgeo.animation:mesh-morph-weights validated))))
    (let ((clips nil))
      (dolist (record (getf data :clips))
        (let* ((tracks (mapcar (lambda (track)
                                (case (getf track :type)
                                  (:event (sgeo.animation:make-event-track (getf track :events)
                                            :handler (when (getf track :handler) (%animation-symbol-from-data (getf track :handler)))))
                                  (:property (sgeo.animation:make-property-track
                                              (or (gethash (getf track :target-id) objects) (gethash (getf track :target-id) geometries)
                                                  (gethash (getf track :target-id) materials))
                                              (%animation-path-from-data (getf track :path))
                                              (mapcar #'%animation-key-from-data (getf track :keys))
                                              :easings (getf track :easings)
                                              :interpolation (getf track :interpolation))))) (getf record :tracks)))
               (clip (sgeo.animation:make-animation-clip :name (getf record :name) :tracks tracks :duration (getf record :duration))))
          (sgeo.animation:add-animation-clip world clip) (push clip clips)))
      (setf clips (nreverse clips)
            (sgeo.animation:animation-state-clips state) clips)
      (dolist (record (reverse (getf data :players)))
        (let* ((mask (mapcar (lambda (entry) (if (eq (first entry) :symbol) (%animation-symbol-from-data (second entry))
                                                  (%animation-path-from-data (second entry)))) (getf record :mask)))
               (player (sgeo.animation:play-animation world (nth (getf record :clip) clips)
                         :weight (getf record :weight) :speed (getf record :speed) :looping-p (getf record :looping-p)
                         :additive-p (getf record :additive-p) :mask mask
                         :evaluate-p nil
                         :root-motion-target (gethash (getf record :root-target-id) objects)
                         :root-motion-joint (gethash (getf record :root-joint-id) objects))))
          (setf (sgeo.animation:player-time player) (getf record :time)
                (sgeo.animation:player-playing-p player) (getf record :playing-p)
                (slot-value player 'sgeo.animation::enabled-p) (getf record :enabled-p)))))
    (dolist (reference (getf data :references))
      (let ((target (or (gethash (getf reference :target-id) objects)
                        (gethash (getf reference :target-id) geometries)
                        (gethash (getf reference :target-id) materials))))
        (setf (gethash (list target (%animation-path-from-data (getf reference :path)))
                      (slot-value state 'sgeo.animation::references))
              (%animation-value-from-data (getf reference :value)))))
    (setf (sgeo.animation:animation-state-time state) (getf data :time))
    world))
