(in-package #:sgeo.serialization)

(defun %fail (context message)
  (error 'validation-error :context context :message message))

(defun %finite-real-p (value)
  (and (realp value)
       (handler-case
           (let ((number (coerce value 'double-float)))
             (and (= number number) (< (abs number) most-positive-double-float)))
         (error () nil))))

(defun %proper-list-p (value)
  (let ((seen (make-hash-table :test #'eq)) (tail value))
    (loop while (consp tail)
          do (when (gethash tail seen) (return-from %proper-list-p nil))
             (setf (gethash tail seen) t
                   tail (cdr tail)))
    (null tail)))

(defun %plist-pairs (plist context required optional)
  (unless (and (%proper-list-p plist) (evenp (length plist)))
    (%fail context "Esperava uma lista de propriedades válida."))
  (let ((seen nil))
    (loop for tail on plist by #'cddr
          for key = (car tail)
          do
             (unless (and (keywordp key) (member key (append required optional)))
               (%fail context (format nil "Propriedade desconhecida: ~S." key)))
             (when (member key seen)
               (%fail context (format nil "Propriedade repetida: ~S." key)))
             (push key seen))
    (dolist (key required)
      (unless (member key seen)
        (%fail context (format nil "Propriedade obrigatória ausente: ~S." key))))
    plist))

(defun %prop (plist key)
  (getf (if (and (consp plist) (eq (first plist) :sgeo-scene)) (rest plist) plist) key))

(defun %has-property-p (plist key)
  (loop for tail on plist by #'cddr thereis (eq (car tail) key)))

(defun %vec-list (value count context)
  (unless (and (%proper-list-p value) (= (length value) count)
               (every #'%finite-real-p value))
    (%fail context (format nil "Esperava uma lista de ~D números reais finitos." count)))
  value)

(defun %schema-string (value)
  "Retorna uma string geral, sem preservar especialização de array de caracteres."
  (make-array (length value) :element-type 'character :initial-contents value))

(defun %copy-metadata-value (value &optional (seen (make-hash-table :test #'eq)))
  "Copia somente valores de metadados que podem ser representados com segurança."
  (cond ((stringp value) (%schema-string value))
        ((or (null value) (eq value t) (keywordp value)) value)
        ((numberp value)
         (if (%finite-real-p value) value (%fail "metadados" "Número não finito nos metadados.")))
        ((consp value)
         (when (gethash value seen) (%fail "metadados" "Lista circular nos metadados."))
         (setf (gethash value seen) t)
         (let ((result (cons (%copy-metadata-value (car value) seen)
                             (%copy-metadata-value (cdr value) seen))))
           (remhash value seen)
           result))
        (t (%fail "metadados" "Metadados aceitam apenas listas, strings, palavras-chave, booleanos e números finitos."))))

(defun %metadata-data (object)
  (let ((pairs nil))
    (maphash (lambda (key value)
               (unless (or (stringp key) (keywordp key))
                 (%fail "metadados" "As chaves precisam ser strings ou palavras-chave."))
               (push (list (%copy-metadata-value key) (%copy-metadata-value value)) pairs))
             (object-metadata object))
    (sort pairs #'string< :key (lambda (pair) (prin1-to-string (first pair))))))

(defun %metadata-from-data (data)
  (unless (%proper-list-p data) (%fail "metadados" "Esperava uma lista de pares de metadados."))
  (let ((table (make-hash-table :test #'equal)) (seen nil))
    (dolist (pair data table)
      (unless (and (%proper-list-p pair) (= (length pair) 2)
                   (or (stringp (first pair)) (keywordp (first pair))))
        (%fail "metadados" "Cada item precisa ser um par (chave valor) com chave textual."))
      (when (member (first pair) seen :test #'equal)
        (%fail "metadados" "Chave repetida nos metadados."))
      (push (first pair) seen)
      (%copy-metadata-value (second pair))
      (setf (gethash (first pair) table) (second pair)))))

(defun %vector-values (vector)
  (when vector (loop for value across vector collect value)))

(defun %vector3-lists (flat)
  (loop for offset from 0 below (length flat) by 3
        collect (list (aref flat offset) (aref flat (1+ offset))
                      (aref flat (+ offset 2)))))

(defun %object-record (object)
  (let* ((transform (scene-object-local-transform object))
         (rotation (sgeo.math::quaternion-data (transform-rotation transform)))
         (base (list :id (object-id object)
                     :name (%schema-string (object-name object))
                     :metadata (%metadata-data object)
                     :enabled-p (scene-object-enabled-p object)
                     :visible-p (scene-object-visible-p object)
                     :parent-id (and (scene-object-parent object)
                                     (object-id (scene-object-parent object)))
                     :transform (list :position (%vector-values (transform-position transform))
                                      :rotation (%vector-values rotation)
                                      :scale (%vector-values (transform-scale transform))))))
    (cond
      ((typep object 'camera)
       (unless (eq (class-of object) (find-class 'camera))
         (%fail "serialização" "Subclasses de câmera não são suportadas."))
       (append (list :type :camera)
               base
               (list :camera (list :target (%vector-values (camera-target object))
                                   :up (%vector-values (camera-up object))
                                   :fov (camera-fov object) :near (camera-near object)
                                   :far (camera-far object)
                                   :projection-mode (camera-projection-mode object)
                                   :orthographic-height (camera-orthographic-height object)))))
      ((typep object 'mesh-object)
       (unless (or (eq (class-of object) (find-class 'mesh-object))
                   (eq (class-of object) (find-class 'sgeo.animation:deformable-mesh-object)))
         (%fail "serialização" "Subclasses de objetos de malha não são suportadas."))
       (append (list :type :mesh-object) base
               (list :geometry-id (object-id (mesh-object-geometry object))
                     :material-id (object-id (mesh-object-material object)))))
      ((typep object 'sgeo.scene:directional-light)
       (unless (eq (class-of object) (find-class 'sgeo.scene:directional-light))
         (%fail "serialização" "Subclasses de luz não são suportadas."))
       (append (list :type :directional-light) base
               (list :light (list :direction (%vector-values (slot-value object 'sgeo.scene::direction))
                                  :color (%vector-values (slot-value object 'sgeo.scene::color))
                                  :intensity (slot-value object 'sgeo.scene::intensity)
                                  :shadow-extent (slot-value object 'sgeo.scene::shadow-extent)
                                  :shadow-bias (slot-value object 'sgeo.scene::shadow-bias)))))
      ((typep object 'scene-object)
       (when (not (eq (class-of object) (find-class 'scene-object)))
         (%fail "serialização" "Subclasses de objetos de cena não são suportadas."))
       (append (list :type :scene-object) base))
      (t (%fail "serialização" "Tipo de objeto de cena não suportado.")))))

(defun %geometry-record (geometry)
  (let ((metadata (%metadata-data geometry)))
    (cond
      ((typep geometry 'triangle-mesh)
       (unless (eq (class-of geometry) (find-class 'triangle-mesh))
         (%fail "serialização" "Subclasses de malha triangular não são suportadas."))
       (bt:with-recursive-lock-held ((sgeo.geometry::%mesh-data-lock geometry))
         (let ((positions (copy-seq (sgeo.geometry::%mesh-raw-positions geometry)))
               (normals (copy-seq (sgeo.geometry::%mesh-raw-normals geometry)))
               (indices (copy-seq (sgeo.geometry::%mesh-raw-indices geometry))))
           (list :id (object-id geometry) :type :triangle-mesh
                 :name (%schema-string (object-name geometry)) :metadata metadata
                 :positions (%vector3-lists positions) :normals (%vector3-lists normals)
                 :indices (%vector-values indices)))))
      ((typep geometry 'half-edge-mesh)
       (unless (eq (class-of geometry) (find-class 'half-edge-mesh))
         (%fail "serialização" "Subclasses de malha half-edge não são suportadas."))
       (sgeo.geometry::%with-kernel-lock (geometry)
         (let* ((state (sgeo.geometry::%mesh-state geometry))
                (vertices (sgeo.geometry::%state-vertices state))
                (faces (sgeo.geometry::%state-faces state))
                (active-vertices (sgeo.geometry::%arena-active-indices vertices))
                (remap (make-hash-table)))
           (loop for old-index in active-vertices for new-index from 0
                 do (setf (gethash old-index remap) new-index))
           (list :id (object-id geometry) :type :half-edge-mesh
                 :name (%schema-string (object-name geometry)) :metadata metadata
                 :positions
                 (mapcar (lambda (i)
                           (%vector-values
                            (sgeo.geometry::vertex-record-position
                             (aref (sgeo.geometry::%arena-items vertices) i))))
                         active-vertices)
                 :faces
                 (mapcar (lambda (i)
                           (mapcar (lambda (vertex)
                                     (or (gethash vertex remap)
                                         (%fail "geometria" "Face aponta para vértice inativo.")))
                                   (sgeo.geometry::face-record-vertices
                                    (aref (sgeo.geometry::%arena-items faces) i))))
                         (sgeo.geometry::%arena-active-indices faces))))))
      (t (%fail "serialização" "Tipo de geometria não suportado.")))))

(defun %material-record (material)
  (unless (typep material 'simple-material)
    (%fail "serialização" "Tipo de material não suportado."))
  (unless (member (class-of material) (list (find-class 'simple-material)
                                         (find-class 'sgeo.scene:pbr-material)))
    (%fail "serialização" "Subclasses de material não são suportadas."))
  (append
   (list :id (object-id material)
        :type (if (typep material 'sgeo.scene:pbr-material) :pbr-material :simple-material)
        :name (%schema-string (object-name material))
        :metadata (%metadata-data material)
        :color (%vector-values (simple-material-color material))
        :wireframe-p (simple-material-wireframe-p material))
   (when (typep material 'sgeo.scene:pbr-material)
     (list :pbr (loop for (key value) on (sgeo.scene:pbr-material-data material) by #'cddr
                     append (list key (if (vectorp value) (%vector-values value) value)))))))

(defun scene-data (world)
  "Retorna um snapshot plist legível, independente das instâncias vivas da cena."
  (with-world-lock (world)
    (let* ((root (world-root world))
           (objects (append (sgeo.scene::%descendants root) (list (world-camera world))))
           (geometries nil) (materials nil) (seen-geometry (make-hash-table))
           (seen-material (make-hash-table)))
      (dolist (object objects)
        (when (typep object 'mesh-object)
          (let ((geometry (mesh-object-geometry object))
                (material (mesh-object-material object)))
            (unless (gethash geometry seen-geometry)
              (setf (gethash geometry seen-geometry) t)
              (push (%geometry-record geometry) geometries))
            (unless (gethash material seen-material)
              (setf (gethash material seen-material) t)
              (push (%material-record material) materials)))))
      (let ((animation (%copy-metadata-value (%animation-data world objects geometries materials))))
      (append (list :sgeo-scene :version (if animation 2 1)
            :root-id (object-id root) :camera-id (object-id (world-camera world))
            :selection-id (and (world-selection world) (object-id (world-selection world)))
            :objects (mapcar #'%object-record objects)
            :geometries (nreverse geometries) :materials (nreverse materials))
              (when animation (list :animation animation)))))))

(defun %safe-tree (form &optional (seen (make-hash-table :test #'eq)))
  "Converte uma forma lida em dados seguros e rejeita símbolos e ciclos."
  (cond ((or (null form) (eq form t) (stringp form) (keywordp form)) form)
        ((numberp form)
         (if (%finite-real-p form) form (%fail "leitura" "Número não finito no arquivo.")))
        ((consp form)
         (when (gethash form seen) (%fail "leitura" "Forma circular no arquivo."))
         (setf (gethash form seen) t)
         (let ((result (cons (%safe-tree (car form) seen)
                             (%safe-tree (cdr form) seen))))
           (remhash form seen)
           result))
        (t (%fail "leitura" "O arquivo contém um objeto de leitura não permitido."))))

(defun %reject-dispatch-syntax (stream character)
  (declare (ignore stream character))
  (%fail "leitura" "Sintaxe de leitor # não é permitida nos arquivos de cena."))

(defun %read-one-form (stream)
  (let* ((package-name (format nil "SGEO-SERIALIZATION-READER-~D" (gensym)))
         (package (make-package package-name :use '(:cl)))
         (readtable (copy-readtable nil)))
    (unwind-protect
         (let ((*package* package) (*readtable* readtable) (*read-eval* nil)
               (eof (gensym "EOF")))
           (set-macro-character #\# #'%reject-dispatch-syntax nil readtable)
           (let* ((first-form (read stream nil eof))
                  (second-form (and (not (eq first-form eof)) (read stream nil eof))))
             (when (eq first-form eof) (%fail "leitura" "O arquivo está vazio."))
             (unless (eq second-form eof) (%fail "leitura" "O arquivo precisa conter exatamente uma forma."))
             (%safe-tree first-form)))
      (delete-package package))))

(defun %validate-data (data)
  "Valida integralmente o esquema e todas as referências antes de construir objetos."
  (unless (and (%proper-list-p data) (eq (first data) :sgeo-scene))
    (%fail "cena" "Assinatura de cena desconhecida."))
  (%plist-pairs (rest data) "cena"
                '(:version :root-id :camera-id :selection-id :objects :geometries :materials) '(:animation))
  (unless (eq (first data) :sgeo-scene) (%fail "cena" "Assinatura de cena desconhecida."))
  (unless (member (%prop data :version) '(1 2)) (%fail "cena" "Versão de cena desconhecida."))
  (when (and (= (%prop data :version) 1) (%has-property-p (rest data) :animation))
    (%fail "cena" "A versão 1 não aceita estado de animação."))
  (dolist (key '(:root-id :camera-id))
    (unless (and (integerp (%prop data key)) (plusp (%prop data key)))
      (%fail "cena" "Identificador de raiz ou câmera inválido.")))
  (unless (or (null (%prop data :selection-id))
              (and (integerp (%prop data :selection-id)) (plusp (%prop data :selection-id))))
    (%fail "cena" "Identificador de seleção inválido."))
  (dolist (key '(:objects :geometries :materials))
    (unless (%proper-list-p (%prop data key)) (%fail "cena" "Coleção do esquema precisa ser uma lista.")))
  (let ((object-table (make-hash-table)) (geometry-table (make-hash-table))
        (material-table (make-hash-table)) (all-ids (make-hash-table)))
    (labels ((unique-id (id table context)
               (unless (and (integerp id) (plusp id)) (%fail context "Identificador inválido."))
               (when (gethash id all-ids) (%fail context "Identificador duplicado na cena."))
               (setf (gethash id all-ids) t (gethash id table) t))
             (check-meta (meta)
               (unless (%proper-list-p meta) (%fail "metadados" "Esperava uma lista."))
               (%metadata-from-data meta))
             (check-transform (transform)
               (%plist-pairs transform "transformação" '(:position :rotation :scale) nil)
               (%vec-list (%prop transform :position) 3 "posição")
               (let ((rotation (%vec-list (%prop transform :rotation) 4 "rotação")))
                 (when (<= (reduce #'+ rotation :key (lambda (x) (* x x))) 1d-30)
                   (%fail "rotação" "Quaternion nulo não representa uma rotação.")))
               (%vec-list (%prop transform :scale) 3 "escala"))
             (check-bool (value context)
               (unless (member value '(nil t)) (%fail context "Esperava T ou NIL."))))
      (dolist (record (%prop data :objects))
        (%plist-pairs record "objeto" '(:id :type :name :metadata :enabled-p :visible-p :parent-id :transform)
                      '(:geometry-id :material-id :camera :light))
        (unique-id (%prop record :id) object-table "objeto")
        (unless (stringp (%prop record :name)) (%fail "objeto" "Nome precisa ser string."))
        (check-meta (%prop record :metadata))
        (check-bool (%prop record :enabled-p) "estado habilitado")
        (check-bool (%prop record :visible-p) "estado visível")
        (unless (or (null (%prop record :parent-id))
                    (and (integerp (%prop record :parent-id)) (plusp (%prop record :parent-id))))
          (%fail "hierarquia" "Referência de pai inválida."))
        (check-transform (%prop record :transform))
        (case (%prop record :type)
          (:scene-object
           (when (some (lambda (key) (%has-property-p record key))
                       '(:geometry-id :material-id :camera :light))
             (%fail "objeto" "Campos de tipo incorreto no objeto simples.")))
          (:mesh-object
           (when (or (%has-property-p record :camera) (%has-property-p record :light))
             (%fail "objeto" "Campo de câmera em objeto de malha."))
           (unless (and (integerp (%prop record :geometry-id))
                        (integerp (%prop record :material-id)))
             (%fail "objeto" "Referência de geometria ou material inválida.")))
          (:camera
           (when (some (lambda (key) (%has-property-p record key))
                       '(:geometry-id :material-id :light))
             (%fail "câmera" "Referência de malha/material em objeto de câmera."))
           (%plist-pairs (%prop record :camera) "câmera"
                         '(:target :up :fov :near :far :projection-mode :orthographic-height) nil)
           (%vec-list (getf (%prop record :camera) :target) 3 "alvo da câmera")
           (%vec-list (getf (%prop record :camera) :up) 3 "vetor para cima")
           (dolist (field '(:fov :near :far :orthographic-height))
             (unless (%finite-real-p (getf (%prop record :camera) field))
               (%fail "câmera" "Parâmetro óptico não finito.")))
           (unless (member (getf (%prop record :camera) :projection-mode)
                           '(:perspective :orthographic))
             (%fail "câmera" "Modo de projeção desconhecido."))
           (let* ((cam (%prop record :camera))
                  (fov (getf cam :fov)) (near (getf cam :near))
                  (far (getf cam :far)) (height (getf cam :orthographic-height))
                  (eye (getf (%prop record :transform) :position))
                  (target (getf cam :target)) (up (getf cam :up)))
             (unless (and (< 0 fov pi) (plusp near) (> far near) (plusp height))
               (%fail "câmera" "Parâmetros ópticos da câmera inválidos."))
             (let* ((forward (mapcar #'- target eye))
                    (cross (list (- (* (second forward) (third up))
                                    (* (third forward) (second up)))
                                 (- (* (third forward) (first up))
                                    (* (first forward) (third up)))
                                 (- (* (first forward) (second up))
                                    (* (second forward) (first up)))))
                    (length-squared (lambda (vector)
                                      (reduce #'+ vector :key (lambda (x) (* x x))))))
               (when (or (<= (funcall length-squared forward) 1d-24)
                         (<= (funcall length-squared up) 1d-24)
                         (<= (funcall length-squared cross)
                             (* 1d-24 (funcall length-squared forward)
                                (funcall length-squared up))))
                 (%fail "câmera" "A orientação da câmera é degenerada.")))))
          (:directional-light
           (when (some (lambda (key) (%has-property-p record key)) '(:geometry-id :material-id :camera))
             (%fail "luz" "Campos de outro tipo em luz direcional."))
           (let ((light (%prop record :light)))
             (%plist-pairs light "luz" '(:direction :color :intensity :shadow-extent :shadow-bias) nil)
             (%vec-list (getf light :direction) 3 "direção da luz")
             (%vec-list (getf light :color) 3 "cor da luz")
             (apply #'sgeo.scene:make-directional-light light)))
          (otherwise (%fail "objeto" "Tipo de objeto desconhecido."))))
      (dolist (record (%prop data :geometries))
        (unless (member (%prop record :type) '(:triangle-mesh :half-edge-mesh))
          (%fail "geometria" "Tipo de geometria desconhecido."))
        (%plist-pairs record "geometria"
                      (if (eq (%prop record :type) :triangle-mesh)
                          '(:id :type :name :metadata :positions :normals :indices)
                          '(:id :type :name :metadata :positions :faces)) nil)
        (unique-id (%prop record :id) geometry-table "geometria")
        (unless (stringp (%prop record :name)) (%fail "geometria" "Nome precisa ser string."))
        (check-meta (%prop record :metadata))
        (unless (%proper-list-p (%prop record :positions)) (%fail "geometria" "Posições precisam ser lista."))
        (dolist (point (%prop record :positions)) (%vec-list point 3 "posição de vértice"))
        (if (eq (%prop record :type) :triangle-mesh)
            (progn
              (unless (%proper-list-p (%prop record :normals)) (%fail "geometria" "Normais precisam ser lista."))
              (dolist (normal (%prop record :normals)) (%vec-list normal 3 "normal"))
              (unless (and (%proper-list-p (%prop record :indices))
                           (every (lambda (index) (and (integerp index) (<= 0 index #xffffffff)))
                                  (%prop record :indices)))
                (%fail "geometria" "Índices triangulares inválidos.")))
            (progn
              (unless (%proper-list-p (%prop record :faces)) (%fail "geometria" "Faces precisam ser lista."))
              (dolist (face (%prop record :faces))
                (unless (and (%proper-list-p face) (every (lambda (index) (and (integerp index) (>= index 0))) face))
                  (%fail "geometria" "Loop poligonal inválido."))))))
      (dolist (record (%prop data :materials))
        (%plist-pairs record "material" '(:id :type :name :metadata :color :wireframe-p) '(:pbr))
        (unless (member (%prop record :type) '(:simple-material :pbr-material))
          (%fail "material" "Tipo de material desconhecido."))
        (when (eq (%prop record :type) :simple-material)
          (when (%has-property-p record :pbr) (%fail "material" "Parâmetros PBR em material simples.")))
        (when (eq (%prop record :type) :pbr-material)
          (let ((pbr (%prop record :pbr)))
            (%plist-pairs pbr "PBR" '(:base-color :metallic :roughness :occlusion :emissive
                                      :casts-shadow-p :receives-shadow-p) nil)
            (%vec-list (getf pbr :base-color) 4 "cor PBR")
            (%vec-list (getf pbr :emissive) 3 "emissão PBR")
            (%vec-list (%prop record :color) 3 "cor do material")
            (unless (every #'= (%prop record :color) (subseq (getf pbr :base-color) 0 3))
              (%fail "material PBR" "As representações RGB e RGBA precisam ter a mesma cor."))
            (apply #'sgeo.scene:make-pbr-material pbr)))
        (unique-id (%prop record :id) material-table "material")
        (unless (stringp (%prop record :name)) (%fail "material" "Nome precisa ser string."))
        (check-meta (%prop record :metadata))
        (%vec-list (%prop record :color) 3 "cor do material")
        (check-bool (%prop record :wireframe-p) "modo de arame"))
      (unless (and (gethash (%prop data :root-id) object-table)
                   (gethash (%prop data :camera-id) object-table))
        (%fail "cena" "Raiz ou câmera não está presente na coleção de objetos."))
      (unless (member (getf (find (%prop data :root-id) (%prop data :objects)
                                  :key (lambda (record) (getf record :id))) :type)
                      '(:scene-object :mesh-object))
        (%fail "hierarquia" "A raiz precisa ser um objeto de cena, não uma câmera."))
      (unless (eq (getf (find (%prop data :camera-id) (%prop data :objects)
                             :key (lambda (record) (getf record :id))) :type)
                  :camera)
        (%fail "cena" "O objeto de câmera não é uma câmera."))
      (when (%prop data :selection-id)
        (unless (gethash (%prop data :selection-id) object-table)
          (%fail "cena" "A seleção aponta para objeto inexistente.")))
      (dolist (record (%prop data :objects))
        (let ((type (%prop record :type)) (parent (%prop record :parent-id)))
          (case type
            (:camera (unless (and (= (%prop record :id) (%prop data :camera-id)) (null parent))
                        (%fail "hierarquia" "A câmera deve ser a câmera única e ficar fora da hierarquia.")))
            (otherwise
             (when (= (%prop record :id) (%prop data :root-id))
               (when parent (%fail "hierarquia" "A raiz não pode ter pai.")))
             (unless (or (= (%prop record :id) (%prop data :root-id))
                         (and parent (gethash parent object-table)))
               (%fail "hierarquia" "Objeto fora da hierarquia da raiz."))))
          (when (and parent (not (gethash parent object-table)))
            (%fail "hierarquia" "Referência de pai inexistente."))
          (when (eq type :mesh-object)
            (unless (and (gethash (%prop record :geometry-id) geometry-table)
                         (gethash (%prop record :material-id) material-table))
              (%fail "objeto" "Referência de geometria/material inexistente.")))))
      ;; Cada cadeia de pais precisa terminar na raiz e não pode conter ciclos.
      (let ((parents (make-hash-table)))
        (dolist (record (%prop data :objects))
          (setf (gethash (%prop record :id) parents) (%prop record :parent-id)))
        (dolist (record (%prop data :objects))
          (unless (= (%prop record :id) (%prop data :camera-id))
            (let ((seen (make-hash-table)) (id (%prop record :id)))
              (loop while id do
                (when (gethash id seen) (%fail "hierarquia" "Ciclo detectado na hierarquia."))
                (setf (gethash id seen) t)
                (when (= id (%prop data :root-id)) (return))
                (setf id (gethash id parents)))
              (unless (or (= (%prop record :id) (%prop data :root-id))
                          (gethash (%prop data :root-id) seen))
                (%fail "hierarquia" "Objeto não é descendente da raiz.")))))
        )
      (when (%prop data :animation)
        (%validate-animation-data (%prop data :animation) object-table geometry-table material-table data))
      (values data object-table geometry-table material-table))))

(defun %restore-object-metadata (object metadata)
  (setf (sgeo.core:object-metadata object) (%metadata-from-data metadata))
  object)

(defun %apply-transform (object transform-data)
  (let* ((rotation (apply #'make-quaternion (getf transform-data :rotation)))
         (transform (make-transform :position (apply #'make-vec3 (getf transform-data :position))
                                    :rotation rotation
                                    :scale (apply #'make-vec3 (getf transform-data :scale)))))
    (setf (sgeo.scene::%scene-object-local-transform object) transform)))

(defun world-from-data (data)
  "Valida DATA por completo e cria um mundo novo, sem reutilizar objetos vivos."
  (multiple-value-bind (data objects geometries materials) (%validate-data data)
    (declare (ignore objects geometries materials))
    (let ((geometry-map (make-hash-table)) (material-map (make-hash-table))
          (object-map (make-hash-table)))
      ;; As malhas e os materiais são criados depois de a estrutura inteira passar na validação.
      (dolist (record (%prop data :geometries))
        (let ((geometry
                (case (getf record :type)
                  (:triangle-mesh
                   (make-triangle-mesh-from-data
                    (mapcan #'identity (getf record :positions)) (getf record :indices)
                    :normals (mapcan #'identity (getf record :normals))
                    :name (getf record :name) :metadata (%metadata-from-data (getf record :metadata))))
                  (:half-edge-mesh
                   (make-half-edge-mesh :positions (mapcar (lambda (p) (apply #'make-vec3 p))
                                                          (getf record :positions))
                                        :faces (getf record :faces)
                                        :name (getf record :name)
                                        :metadata (%metadata-from-data (getf record :metadata)))))))
          (setf (gethash (getf record :id) geometry-map) geometry)))
      (dolist (record (%prop data :materials))
        (let ((material (if (eq (getf record :type) :pbr-material)
                            (apply #'sgeo.scene:make-pbr-material :name (getf record :name) (getf record :pbr))
                            (make-material :name (getf record :name)
                                           :color (apply #'make-vec3 (getf record :color))
                                           :wireframe-p (getf record :wireframe-p)))))
          (when (typep material 'sgeo.scene:pbr-material)
            (sgeo.scene:set-material-color material (getf record :color))
            (sgeo.scene:set-material-wireframe material (getf record :wireframe-p)))
          (%restore-object-metadata material (getf record :metadata))
          (setf (gethash (getf record :id) material-map) material)))
      (dolist (record (%prop data :objects))
        (let* ((type (getf record :type))
               (object (case type
                         (:scene-object (make-scene-object :name (getf record :name)))
                         (:directional-light (apply #'sgeo.scene:make-directional-light
                                                    :name (getf record :name) (getf record :light)))
                         (:mesh-object (make-mesh-object (gethash (getf record :geometry-id) geometry-map)
                                                         :name (getf record :name)
                                                         :material (gethash (getf record :material-id) material-map)))
                         (:camera (let ((cam (getf record :camera)))
                                    (make-camera :name (getf record :name)
                                                 :eye (apply #'make-vec3 (getf (getf record :transform) :position))
                                                 :target (apply #'make-vec3 (getf cam :target))
                                                 :up (apply #'make-vec3 (getf cam :up))
                                                 :fov (getf cam :fov) :near (getf cam :near) :far (getf cam :far)
                                                 :projection-mode (getf cam :projection-mode)
                                                 :orthographic-height (getf cam :orthographic-height)))))))
          (%apply-transform object (getf record :transform))
          (setf (slot-value object 'sgeo.scene::visible-p) (getf record :visible-p)
                (slot-value object 'sgeo.scene::enabled-p) (getf record :enabled-p))
          (%restore-object-metadata object (getf record :metadata))
          (setf (gethash (getf record :id) object-map) object)))
      (let* ((root (gethash (%prop data :root-id) object-map))
             (camera (gethash (%prop data :camera-id) object-map))
             (world (make-world :root root :camera camera)))
        ;; ADD-CHILD acrescenta no início; ligue irmãos do último para o primeiro.
        (dolist (record (reverse (%prop data :objects)))
          (let ((parent-id (getf record :parent-id)))
            (when parent-id
              (add-child (gethash parent-id object-map)
                         (gethash (getf record :id) object-map)))))
        (when (%prop data :selection-id)
          (setf (world-selection world) (gethash (%prop data :selection-id) object-map)))
        (when (%prop data :animation)
          (%restore-animation-data world (%prop data :animation) object-map geometry-map material-map))
        world))))

(defvar *temporary-file-counter* 0)
(defvar *temporary-file-lock* (bt:make-lock "sgeo serialization temporary files"))

(defun %temporary-pathname (pathname)
  (let ((counter (bt:with-lock-held (*temporary-file-lock*) (incf *temporary-file-counter*))))
    (make-pathname :name (format nil ".~A.sgeo-~D-~D"
                                 (or (pathname-name pathname) "scene")
                                 counter (get-universal-time))
                   :type (pathname-type pathname)
                   :defaults pathname)))

(defun save-world (world path)
  "Grava um mundo num arquivo irmão temporário e só publica após a escrita completa."
  (let ((*print-readably* t) (*print-escape* t) (*print-array* nil)
        (*print-base* 10) (*print-radix* nil) (*print-circle* nil)
        (*print-gensym* t) (*print-pretty* nil) (*print-case* :upcase)
        (*print-level* nil) (*print-length* nil) (*print-lines* nil)
        (*package* (find-package :keyword)))
    (let* ((target (pathname path)) (temporary (%temporary-pathname target))
           (data (scene-data world)))
      (unwind-protect
           (progn
             (with-open-file (stream temporary :direction :output :if-exists :error
                                     :if-does-not-exist :create :external-format :utf-8)
               (prin1 data stream)
               (terpri stream)
               (finish-output stream))
             (uiop:rename-file-overwriting-target temporary target)
             target)
        (when (probe-file temporary)
          (ignore-errors (delete-file temporary)))))))

(defun load-world (path)
  "Lê uma única forma de dados sem avaliação e retorna um mundo validado novo."
  (with-open-file (stream path :direction :input :external-format :utf-8)
    (world-from-data (%read-one-form stream))))
