(in-package #:sgeo.render)

(defstruct render-resource name format (transient-p t) (external-p nil))
(defstruct render-pass name reads writes depends-on)
(defstruct render-graph resources passes)
(defstruct compiled-graph passes resources barriers lifetimes)

(defun %graph-error (message)
  (error 'sgeo.core:render-error :context "grafo de renderização" :message message))

(defun compile-render-graph (graph)
  "Ordena passes, valida produtores e calcula transições e vidas úteis."
  (let ((resources (make-hash-table :test #'equal)) (passes (make-hash-table :test #'equal))
        (writers (make-hash-table :test #'equal)) (dependencies (make-hash-table :test #'equal))
        (ordered nil))
    (dolist (resource (render-graph-resources graph))
      (let ((name (render-resource-name resource)))
        (when (gethash name resources) (%graph-error "Recurso repetido."))
        (setf (gethash name resources) resource)))
    (dolist (pass (render-graph-passes graph))
      (let ((name (render-pass-name pass)))
        (when (gethash name passes) (%graph-error "Pass repetido."))
        (setf (gethash name passes) pass)
        (dolist (access (append (render-pass-reads pass) (render-pass-writes pass)))
          (unless (and (listp access) (= (length access) 2)
                       (gethash (first access) resources)
                       (member (second access) '(:sampled-read :color-write :depth-write
                                                 :transfer-read :transfer-write :present)))
            (%graph-error "Acesso inválido ou recurso não declarado.")))
        (dolist (access (render-pass-writes pass))
          (when (gethash (first access) writers) (%graph-error "Um recurso possui mais de um produtor."))
          (setf (gethash (first access) writers) name))))
    (dolist (pass (render-graph-passes graph))
      (let ((deps (copy-list (render-pass-depends-on pass))) (name (render-pass-name pass)))
        (dolist (access (render-pass-reads pass))
          (let ((writer (gethash (first access) writers)))
            (cond ((and writer (equal writer name)) (%graph-error "Leitura e escrita simultâneas exigem recursos distintos."))
                  (writer (pushnew writer deps :test #'equal))
                  ((not (render-resource-external-p (gethash (first access) resources)))
                   (%graph-error "Leitura sem produtor ou entrada externa.")))))
        (dolist (dep deps)
          (unless (gethash dep passes) (%graph-error "Dependência de pass inexistente.")))
        (setf (gethash name dependencies) deps)))
    (let ((remaining (copy-list (render-graph-passes graph))) (done nil))
      (loop while remaining do
        (let ((ready (find-if (lambda (pass)
                               (every (lambda (dep) (member dep done :test #'equal))
                                      (gethash (render-pass-name pass) dependencies))) remaining)))
          (unless ready (%graph-error "Dependências contêm um ciclo."))
          (push ready ordered) (push (render-pass-name ready) done)
          (setf remaining (remove ready remaining :test #'eq)))))
    (setf ordered (nreverse ordered))
    (let ((states (make-hash-table :test #'equal)) (barriers nil)
          (lifetimes (make-hash-table :test #'equal)))
      (loop for pass in ordered for index from 0 do
        (dolist (access (append (render-pass-reads pass) (render-pass-writes pass)))
          (destructuring-bind (name state) access
            (let ((before (gethash name states :undefined)) (life (gethash name lifetimes)))
              (unless (eq before state)
                (push (list :pass (render-pass-name pass) :resource name :from before :to state) barriers))
              (setf (gethash name states) state
                    (gethash name lifetimes) (list (if life (first life) index) index))))))
      (make-compiled-graph :passes ordered :resources (copy-list (render-graph-resources graph))
                           :barriers (nreverse barriers) :lifetimes lifetimes))))

(defun execute-render-graph (graph execute-pass &key transition acquire release)
  "Aplica o plano compilado; o backend controla alocação, barreiras e comandos."
  (let ((compiled (if (typep graph 'compiled-graph) graph (compile-render-graph graph)))
        (live nil))
    (unwind-protect
         (loop for pass in (compiled-graph-passes compiled) for index from 0 do
           (dolist (resource (compiled-graph-resources compiled))
             (let ((life (gethash (render-resource-name resource) (compiled-graph-lifetimes compiled))))
               (when (and life (= index (first life)) (render-resource-transient-p resource)
                          (not (render-resource-external-p resource)))
                 (when acquire (funcall acquire resource)) (push resource live))))
           (when transition
             (dolist (barrier (compiled-graph-barriers compiled))
               (when (equal (getf barrier :pass) (render-pass-name pass))
                 (funcall transition barrier))))
           (funcall execute-pass pass)
           (dolist (resource (copy-list live))
             (when (= index (second (gethash (render-resource-name resource)
                                           (compiled-graph-lifetimes compiled))))
               (when release (funcall release resource))
               (setf live (remove resource live :test #'eq)))))
      (dolist (resource live) (when release (funcall release resource))))
    compiled))

(defun make-pbr-render-graph (&key transient-p)
  "Grafo HDR; por padrão, o backend mantém os alvos entre quadros."
  (compile-render-graph
   (make-render-graph
    :resources (list (make-render-resource :name :shadow :format :d32-sfloat :transient-p transient-p)
                     (make-render-resource :name :hdr :format :r16g16b16a16-sfloat :transient-p transient-p)
                     (make-render-resource :name :depth :format :d32-sfloat :transient-p transient-p)
                     (make-render-resource :name :output :format :r8g8b8a8-unorm :transient-p transient-p))
    :passes (list (make-render-pass :name :shadow :writes '((:shadow :depth-write)))
                  (make-render-pass :name :pbr :reads '((:shadow :sampled-read))
                                    :writes '((:hdr :color-write) (:depth :depth-write)))
                  (make-render-pass :name :tone :reads '((:hdr :sampled-read))
                                    :writes '((:output :color-write)))
                  (make-render-pass :name :output :reads '((:output :transfer-read)))))))
