(in-package #:sgeo.render)

(defun vulkan-projection (projection)
  "Converte a projeção GL para profundidade [0,1] e o eixo Y do Vulkan."
  (let ((conversion (sgeo.math:identity-mat4)))
    (setf (aref conversion 5) -1d0 (aref conversion 10) 0.5d0 (aref conversion 14) 0.5d0)
    (sgeo.math:mat* conversion projection)))

(defun %normal-matrix (matrix)
  (let ((inverse (sgeo.math:inverse-mat4 matrix)) (normal (sgeo.math:make-mat4)))
    (dotimes (column 4)
      (dotimes (row 4) (setf (aref normal (+ row (* column 4)))
                           (aref inverse (+ column (* row 4))))))
    normal))

(defun %entry-material (entry)
  (let ((material (getf entry :material)))
    (if (typep material 'sgeo.scene:pbr-material)
        (sgeo.scene:pbr-material-data material)
        (list :base-color (concatenate 'vector (getf entry :color) #(1d0))
              :metallic 0d0 :roughness 0.65d0 :occlusion 1d0 :emissive #(0d0 0d0 0d0)
              :casts-shadow-p t :receives-shadow-p t))))

(defun modern-scene-snapshot (world &key (aspect 1d0) (shadow-size 1024) (exposure 1d0)
                                       (environment #(0.16d0 0.19d0 0.24d0 1d0)))
  "Prepara o quadro a partir de um instantâneo CPU consistente e independente do backend."
  (unless (and (realp aspect) (plusp aspect) (integerp shadow-size) (plusp shadow-size))
    (error 'sgeo.core:validation-error :context "instantâneo de renderização"
           :message "Aspecto e resolução da sombra precisam ser positivos."))
  (sgeo.scene:with-world-lock (world)
    (let* ((snapshot (sgeo.scene:render-snapshot world aspect))
           (light (find-if (lambda (object)
                             (and (typep object 'sgeo.scene:directional-light)
                                  (sgeo.scene::%visible-enabled-p object)))
                           (sgeo.scene::%descendants (sgeo.scene:world-root world))))
           (lighting (if light (sgeo.scene:directional-light-data light)
                         (list :direction #(-0.4d0 -1d0 -0.3d0) :color #(1d0 1d0 1d0)
                               :intensity 0d0 :shadow-extent 8d0 :shadow-bias 0.002d0)))
           (direction (sgeo.math:normalize (getf lighting :direction)))
           (extent (getf lighting :shadow-extent))
           (center (sgeo.math:make-vec3))
           (eye (sgeo.math:v- center (sgeo.math:v* direction (* extent 2d0))))
           (up (if (> (abs (sgeo.math:vy direction)) 0.99d0)
                   (sgeo.math:make-vec3 0d0 0d0 1d0) (sgeo.math:make-vec3 0d0 1d0 0d0)))
           (shadow-view (sgeo.math:look-at-mat4 eye center up))
           (shadow-projection (vulkan-projection
                               (sgeo.math:orthographic-mat4 (- extent) extent (- extent) extent
                                                          0.01d0 (* extent 4d0)))))
      (setf (getf snapshot :view-projection)
            (sgeo.math:mat* (vulkan-projection (getf snapshot :projection-matrix))
                           (getf snapshot :view-matrix))
            (getf snapshot :light-view-projection) (sgeo.math:mat* shadow-projection shadow-view)
            (getf snapshot :light) lighting
            (getf snapshot :shadow-size) shadow-size
            (getf snapshot :exposure) (sgeo.scene::%material-number exposure "exposição" 0.001d0)
            (getf snapshot :environment) (sgeo.scene::%material-vector environment 4 "ambiente HDR"))
      (setf (getf snapshot :objects)
            (mapcar (lambda (entry)
                      (append (list :pbr (%entry-material entry)
                                    :normal-matrix (%normal-matrix (getf entry :model-matrix)))
                              entry))
                    (getf snapshot :objects)))
      snapshot)))

(defun pack-frame-uniforms (snapshot &optional entry)
  "Retorna os 96 floats do bloco std140 de 384 bytes, em ordem coluna-major."
  (let* ((result (make-array 96 :element-type 'single-float :initial-element 0f0))
         (identity (sgeo.math:identity-mat4)) (offset 0)
         (material (or (getf entry :pbr) (list :base-color #(1d0 1d0 1d0 1d0)
                                                   :metallic 0d0 :roughness 0.5d0 :occlusion 1d0
                                                   :receives-shadow-p nil :emissive #(0d0 0d0 0d0))))
         (light (getf snapshot :light)))
    (flet ((put (vector)
             (map nil (lambda (value) (setf (aref result offset) (coerce value 'single-float))
                                       (incf offset)) vector)))
      (put (or (getf entry :model-matrix) identity))
      (put (or (getf entry :normal-matrix) identity))
      (put (getf snapshot :view-projection))
      (put (getf snapshot :light-view-projection))
      (put (concatenate 'vector (getf snapshot :camera-eye) #(1d0)))
      (put (concatenate 'vector (sgeo.math:v* (getf light :direction) -1d0)
                                (vector (getf light :intensity))))
      (put (concatenate 'vector (getf light :color) #(1d0)))
      (put (getf material :base-color))
      (put (vector (getf material :metallic) (getf material :roughness)
                   (getf material :occlusion) (if (getf material :receives-shadow-p) 1d0 0d0)))
      (put (concatenate 'vector (getf material :emissive) #(0d0)))
      (put (getf snapshot :environment))
      (put (vector (getf snapshot :exposure) (getf light :shadow-bias)
                   (/ 1d0 (getf snapshot :shadow-size)) 0d0)))
    result))

(defun interleave-render-mesh (entry)
  "Empacota posições e normais derivadas; a topologia editável continua na CPU."
  (let* ((positions (getf entry :positions)) (normals (getf entry :normals))
         (count (/ (length positions) 3))
         (vertices (make-array (* count 6) :element-type 'single-float)))
    (dotimes (vertex count vertices)
      (dotimes (axis 3)
        (setf (aref vertices (+ (* vertex 6) axis))
              (coerce (aref positions (+ (* vertex 3) axis)) 'single-float)
              (aref vertices (+ (* vertex 6) 3 axis))
              (coerce (aref normals (+ (* vertex 3) axis)) 'single-float))))))
