(in-package #:sgeo.scene)

(defun %material-number (value context &optional (minimum 0d0) (maximum most-positive-double-float))
  "Valida um número finito antes de publicar qualquer alteração."
  (unless (and (realp value)
               (handler-case (and (= value value) (<= minimum value maximum))
                 (error () nil)))
    (error 'validation-error :context context :message "Valor fora do intervalo ou não finito."))
  (coerce value 'double-float))

(defun %material-vector (value count context &optional (maximum most-positive-double-float))
  (unless (and (typep value 'sequence) (= (length value) count))
    (error 'validation-error :context context :message "Número incorreto de componentes."))
  (map 'vector (lambda (v) (%material-number v context 0d0 maximum)) value))

(defclass pbr-material (simple-material)
  ((alpha :initform 1d0 :reader %pbr-alpha)
   (metallic :initform 0d0 :reader pbr-material-metallic)
   (roughness :initform 0.5d0 :reader pbr-material-roughness)
   (occlusion :initform 1d0 :reader pbr-material-occlusion)
   (emissive :initform #(0d0 0d0 0d0) :reader %pbr-emissive)
   (casts-shadow-p :initform t :reader %pbr-casts-shadow-p)
   (receives-shadow-p :initform t :reader %pbr-receives-shadow-p)
   (lock :initform (bt:make-recursive-lock "sgeo material PBR") :reader %pbr-lock))
  (:documentation "Material metálico/rugosidade; seus parâmetros pertencem à cena Lisp."))

(defun pbr-material-base-color (material)
  (bt:with-recursive-lock-held ((%pbr-lock material))
    (concatenate 'vector (simple-material-color material) (vector (%pbr-alpha material)))))

(defun pbr-material-emissive (material)
  (copy-seq (%pbr-emissive material)))

(defun pbr-material-data (material)
  "Extrai parâmetros copiados, sem referências a recursos da GPU."
  (bt:with-recursive-lock-held ((%pbr-lock material))
    (list :base-color (pbr-material-base-color material)
          :metallic (pbr-material-metallic material)
          :roughness (pbr-material-roughness material)
          :occlusion (pbr-material-occlusion material)
          :emissive (pbr-material-emissive material)
          :casts-shadow-p (%pbr-casts-shadow-p material)
          :receives-shadow-p (%pbr-receives-shadow-p material))))

(defmethod (setf simple-material-color) (color (material pbr-material))
  "Mantém a validação PBR e o canal alfa ao usar a operação RGB compartilhada."
  (let ((rgb (%material-vector color 3 "cor PBR" 1d0)))
    (bt:with-recursive-lock-held ((%pbr-lock material))
      (set-pbr-material material :base-color (concatenate 'vector rgb (vector (%pbr-alpha material)))))
    rgb))

(defun set-pbr-material (material &key (base-color nil color-p) (metallic nil metal-p)
                       (roughness nil rough-p) (occlusion nil ao-p) (emissive nil emission-p)
                       (casts-shadow-p nil casts-p) (receives-shadow-p nil receives-p))
  "Valida todos os parâmetros e os publica como uma única edição."
  (unless (typep material 'pbr-material)
    (error 'validation-error :context "material PBR" :message "Esperava um material PBR."))
  (let ((color (and color-p (%material-vector base-color 4 "cor PBR" 1d0)))
        (metal (and metal-p (%material-number metallic "metalicidade" 0d0 1d0)))
        (rough (and rough-p (%material-number roughness "rugosidade" 0d0 1d0)))
        (ao (and ao-p (%material-number occlusion "oclusão" 0d0 1d0)))
        (emission (and emission-p (%material-vector emissive 3 "emissão"))))
    (dolist (pair (list (cons casts-p casts-shadow-p) (cons receives-p receives-shadow-p)))
      (when (and (car pair) (not (member (cdr pair) '(t nil))))
        (error 'validation-error :context "sombras PBR" :message "Esperava T ou NIL.")))
    (bt:with-recursive-lock-held ((%pbr-lock material))
      (when color-p
        (setf (slot-value material 'color) (subseq color 0 3)
              (slot-value material 'alpha) (aref color 3)))
      (when metal-p (setf (slot-value material 'metallic) metal))
      (when rough-p (setf (slot-value material 'roughness) rough))
      (when ao-p (setf (slot-value material 'occlusion) ao))
      (when emission-p (setf (slot-value material 'emissive) emission))
      (when casts-p (setf (slot-value material 'casts-shadow-p) casts-shadow-p))
      (when receives-p (setf (slot-value material 'receives-shadow-p) receives-shadow-p))
      (touch-object material :pbr-parameters)))
  material)

(defun make-pbr-material (&key (name "PBR") (base-color #(0.8d0 0.8d0 0.85d0 1d0))
                         (metallic 0d0) (roughness 0.5d0) (occlusion 1d0)
                         (emissive #(0d0 0d0 0d0)) (casts-shadow-p t) (receives-shadow-p t))
  "Cria um material PBR opaco com cor linear e emissão HDR."
  (set-pbr-material (make-instance 'pbr-material :name name)
                    :base-color base-color :metallic metallic :roughness roughness
                    :occlusion occlusion :emissive emissive :casts-shadow-p casts-shadow-p
                    :receives-shadow-p receives-shadow-p))

(defclass directional-light (scene-object)
  ((direction :initform #(-0.4d0 -1d0 -0.3d0))
   (color :initform #(1d0 0.97d0 0.9d0))
   (intensity :initform 3d0)
   (shadow-extent :initform 8d0)
   (shadow-bias :initform 0.002d0))
  (:documentation "Luz direcional; DIRECTION indica o trajeto dos raios."))

(defun set-directional-light (light &key (direction nil direction-p) (color nil color-p)
                             (intensity nil intensity-p) (shadow-extent nil extent-p)
                             (shadow-bias nil bias-p))
  "Altera a luz atomicamente, usando o bloqueio do mundo proprietário."
  (unless (typep light 'directional-light)
    (error 'validation-error :context "luz" :message "Esperava uma luz direcional."))
  (let ((dir (and direction-p (%vec3-copy direction "direção da luz")))
        (rgb (and color-p (%material-vector color 3 "cor da luz")))
        (power (and intensity-p (%material-number intensity "intensidade")))
        (extent (and extent-p (%material-number shadow-extent "extensão da sombra" 0.01d0)))
        (bias (and bias-p (%material-number shadow-bias "viés da sombra" 0d0 0.1d0))))
    (when (and dir (<= (vector-length dir) 1d-12))
      (error 'validation-error :context "luz" :message "A direção não pode ser nula."))
    (flet ((publish ()
             (when direction-p (setf (slot-value light 'direction) (normalize dir)))
             (when color-p (setf (slot-value light 'color) rgb))
             (when intensity-p (setf (slot-value light 'intensity) power))
             (when extent-p (setf (slot-value light 'shadow-extent) extent))
             (when bias-p (setf (slot-value light 'shadow-bias) bias))
             (touch-object light :light-parameters)))
      (let ((world (scene-object-world light)))
        (if world (with-world-lock (world) (publish)) (publish)))))
  light)

(defun make-directional-light (&key (name "Sun") (direction #(-0.4d0 -1d0 -0.3d0))
                              (color #(1d0 0.97d0 0.9d0)) (intensity 3d0)
                              (shadow-extent 8d0) (shadow-bias 0.002d0))
  (set-directional-light (make-instance 'directional-light :name name)
                         :direction direction :color color :intensity intensity
                         :shadow-extent shadow-extent :shadow-bias shadow-bias))

(defun directional-light-data (light)
  "Extrai direção mundial e parâmetros fotométricos da luz."
  (list :direction (normalize (transform-direction (world-transform light)
                                                    (slot-value light 'direction)))
        :color (copy-seq (slot-value light 'color)) :intensity (slot-value light 'intensity)
        :shadow-extent (slot-value light 'shadow-extent) :shadow-bias (slot-value light 'shadow-bias)))
