(in-package #:sgeo.gltf)

(defstruct (gltf-asset (:constructor %make-gltf-asset))
  (world nil :read-only t) (scenes #() :read-only t) (nodes #() :read-only t)
  (meshes #() :read-only t) (materials #() :read-only t) (textures #() :read-only t)
  (images #() :read-only t) (skeletons #() :read-only t) (clips #() :read-only t)
  (metadata nil :read-only t))

(defun gltf-world (asset) (gltf-asset-world asset))
(defun gltf-scenes (asset) (copy-seq (gltf-asset-scenes asset)))
(defun gltf-nodes (asset) (copy-seq (gltf-asset-nodes asset)))
(defun gltf-meshes (asset) (copy-seq (gltf-asset-meshes asset)))
(defun gltf-materials (asset) (copy-seq (gltf-asset-materials asset)))
(defun gltf-textures (asset) (copy-seq (gltf-asset-textures asset)))
(defun gltf-images (asset) (copy-seq (gltf-asset-images asset)))
(defun gltf-skeletons (asset) (copy-seq (gltf-asset-skeletons asset)))
(defun gltf-clips (asset) (copy-seq (gltf-asset-clips asset)))
(defun gltf-metadata (asset) (gltf-asset-metadata asset))

(defun %obj (&rest pairs)
  (let ((result (make-hash-table :test #'equal)))
    (loop for (key value) on pairs by #'cddr do (setf (gethash key result) value))
    result))
(defun %get (object key &optional default)
  (if (hash-table-p object) (gethash key object default) default))
(defun %arr (value) (if (and (vectorp value) (not (stringp value))) value #()))
(defun %fail (format-control &rest arguments)
  (error "glTF inválido: ~?" format-control arguments))
(defun %required (object key context)
  (multiple-value-bind (value found) (gethash key object)
    (unless found (%fail "campo obrigatório ~a ausente em ~a." key context)) value))
(defun %integer-field (object key context &optional minimum)
  (let ((value (%required object key context)))
    (unless (and (integerp value) (or (null minimum) (>= value minimum)))
      (%fail "~a em ~a deve ser inteiro válido." key context)) value))
(defun %index (index vector context)
  (unless (and (integerp index) (<= 0 index) (< index (length vector)))
    (%fail "índice ~s fora dos limites em ~a." index context))
  (aref vector index))
(defun %json-safe (value)
  "Converte valores JSON em listas imprimíveis pelo serializador de cenas."
  (cond ((hash-table-p value)
         (cons :json-object
               (loop for key being the hash-keys of value using (hash-value item)
                     collect (list key (%json-safe item)))))
        ((and (vectorp value) (not (stringp value)))
         (cons :json-array (map 'list #'%json-safe value)))
        ((or (eq value :null) (eq value 'yason:null)) :json-null)
        ((or (eq value t) (eq value 'yason:true)) :json-true)
        ((or (null value) (eq value 'yason:false)) :json-false)
        ((listp value) (cons :json-array (mapcar #'%json-safe value)))
        ((or (stringp value) (keywordp value) (numberp value)) value)
        (t (princ-to-string value))))
(defun %safe-images (images)
  (map 'list (lambda (image)
               (list :name (getf image :name)
                     :mime-type (getf image :mime-type)
                     :data-uri (format nil "data:~a;base64,~a"
                                       (or (getf image :mime-type) "application/octet-stream")
                                       (%base64-encode (getf image :bytes)))
                     :source (%json-safe (getf image :source)))) images))

(defun %image-mime-type (image bytes)
  "Reconhece os formatos de imagem do núcleo glTF sem decodificar pixels."
  (or (%get image "mimeType")
      (cond ((and (>= (length bytes) 8) (equalp (subseq bytes 0 8) #(137 80 78 71 13 10 26 10))) "image/png")
            ((and (>= (length bytes) 2) (= (aref bytes 0) 255) (= (aref bytes 1) 216)) "image/jpeg")
            (t (%fail "formato de imagem não reconhecido.")))))
(defun %safe-attributes (attributes)
  (loop for key being the hash-keys of attributes using (hash-value entry)
        collect (list key :components (getf entry :components)
                      :values (coerce (getf entry :values) 'list))))

(defun %finite (number context)
  (unless (and (realp number) (handler-case (= number number) (error () nil))
               (handler-case (<= (abs number) most-positive-double-float) (error () nil)))
    (%fail "número não finito em ~a." context))
  (coerce number 'double-float))

(defun %read-bytes (pathname)
  (with-open-file (stream pathname :direction :input :element-type '(unsigned-byte 8))
    (let* ((length (file-length stream)) (bytes (make-array length :element-type '(unsigned-byte 8))))
      (unless (= (read-sequence bytes stream) length) (%fail "leitura incompleta de ~a." pathname)) bytes)))
(defun %u32 (bytes offset)
  (unless (<= (+ offset 4) (length bytes)) (%fail "cabeçalho GLB truncado."))
  (+ (aref bytes offset) (ash (aref bytes (+ offset 1)) 8)
     (ash (aref bytes (+ offset 2)) 16) (ash (aref bytes (+ offset 3)) 24)))
(defun %glb-document (bytes)
  (unless (and (>= (length bytes) 20) (= (%u32 bytes 0) #x46546c67)
               (= (%u32 bytes 4) 2) (= (%u32 bytes 8) (length bytes)))
    (%fail "cabeçalho ou comprimento GLB inválido."))
  (let ((offset 12) (json nil) (binary nil) (first-chunk t))
    (loop while (< offset (length bytes)) do
      (when (> (+ offset 8) (length bytes)) (%fail "descritor de bloco GLB truncado."))
      (let* ((length (%u32 bytes offset)) (type (%u32 bytes (+ offset 4)))
             (start (+ offset 8)) (end (+ start length)))
        (when (or (not (zerop (mod length 4))) (> end (length bytes)))
          (%fail "comprimento de bloco GLB inválido."))
        (cond ((= type #x4e4f534a)
               (unless (and first-chunk (null json)) (%fail "bloco JSON GLB repetido ou fora de ordem."))
               (setf json (sb-ext:octets-to-string (subseq bytes start end) :external-format :utf-8)))
              ((= type #x004e4942)
               (when binary (%fail "bloco BIN GLB repetido."))
               (setf binary (subseq bytes start end)))
              (t (%fail "tipo de bloco GLB desconhecido ~x." type)))
        (setf first-chunk nil offset end)))
    (unless json (%fail "bloco JSON GLB ausente."))
    (values (yason:parse (string-trim '(#\Space #\Tab #\Return #\Newline #\Null) json)
                        :json-arrays-as-vectors t :json-booleans-as-symbols t :json-nulls-as-keyword t) binary)))

(defun %hex-value (char)
  (digit-char-p char 16))
(defun %percent-decode (text)
  (with-output-to-string (out)
    (loop for i from 0 below (length text) do
      (let ((c (char text i)))
        (if (char= c #\%)
            (progn
              (when (>= (+ i 2) (length text)) (%fail "escape URI percentual incompleto."))
              (let ((a (%hex-value (char text (1+ i)))) (b (%hex-value (char text (+ i 2)))))
                (unless (and a b) (%fail "escape URI percentual inválido."))
                (let ((decoded (+ (* 16 a) b)))
                  (when (or (= decoded 0) (> decoded 127)) (%fail "URI contém byte não suportado."))
                  (write-char (code-char decoded) out))
                (incf i 2)))
            (write-char c out))))))
(defun %base64-decode (text)
  (let* ((alphabet "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/")
         (clean (remove-if (lambda (c) (find c '(#\Space #\Tab #\Return #\Newline))) text))
         (padding (loop for i downfrom (1- (length clean)) to 0 while (char= (char clean i) #\=) count t))
         (output (make-array (max 0 (* 3 (/ (length clean) 4))) :element-type '(unsigned-byte 8)))
         (out 0) (acc 0) (bits 0))
    (unless (and (zerop (mod (length clean) 4)) (<= padding 2)) (%fail "base64 inválido."))
    (loop for i below (- (length clean) padding) for ch = (char clean i) do
      (let ((digit (position ch alphabet)))
        (unless digit (%fail "caractere base64 inválido."))
        (setf acc (+ (ash acc 6) digit) bits (+ bits 6))
        (when (>= bits 8) (decf bits 8) (setf (aref output out) (ldb (byte 8 bits) acc)) (incf out))))
    (subseq output 0 out)))
(defun %base64-encode (bytes)
  (let ((alphabet "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"))
    (with-output-to-string (out)
      (loop for i from 0 below (length bytes) by 3
            for remaining = (- (length bytes) i)
            for n = (+ (ash (aref bytes i) 16)
                       (if (> remaining 1) (ash (aref bytes (1+ i)) 8) 0)
                       (if (> remaining 2) (aref bytes (+ i 2)) 0)) do
              (write-char (char alphabet (ldb (byte 6 18) n)) out)
              (write-char (char alphabet (ldb (byte 6 12) n)) out)
              (write-char (if (> remaining 1) (char alphabet (ldb (byte 6 6) n)) #\=) out)
              (write-char (if (> remaining 2) (char alphabet (ldb (byte 6 0) n)) #\=) out)))))

(defun %inside-directory-p (child directory)
  (let* ((child-name (namestring (truename child)))
         (dir-name (namestring (truename directory)))
         (prefix (if (and (> (length dir-name) 0)
                          (char= (char dir-name (1- (length dir-name))) #\/)) dir-name
                     (concatenate 'string dir-name "/"))))
    (and (>= (length child-name) (length prefix))
         (string= prefix child-name :end2 (length prefix)))))
(defun %resource-bytes (uri source-directory)
  (cond
    ((and (>= (length uri) 5) (string-equal "data:" uri :end2 5))
     (let ((comma (position #\, uri)))
       (unless comma (%fail "data URI sem vírgula."))
       (let* ((header (subseq uri 5 comma)) (payload (subseq uri (1+ comma))))
         (if (search ";base64" header :from-end t) (%base64-decode payload)
             (map '(vector (unsigned-byte 8)) #'char-code (%percent-decode payload))))))
    (t
     (let* ((decoded (%percent-decode uri))
            (relative (pathname decoded)))
       (when (or (uiop:absolute-pathname-p relative)
                 (some (lambda (part) (member part '(:up "..") :test #'equal))
                       (pathname-directory relative)))
         (%fail "URI externa escapa da pasta do ativo."))
       (let ((path (merge-pathnames relative source-directory)))
         (unless (and (probe-file path) (%inside-directory-p path source-directory))
           (%fail "recurso externo ausente ou fora da pasta do ativo: ~a." uri))
         (%read-bytes path))))))

(defun %load-document (pathname)
  (let ((bytes (%read-bytes pathname)))
    (if (and (>= (length bytes) 4) (= (%u32 bytes 0) #x46546c67))
        (%glb-document bytes)
        (values (with-open-file (in pathname :direction :input :external-format :utf-8)
                  (yason:parse in :json-arrays-as-vectors t
                               :json-booleans-as-symbols t :json-nulls-as-keyword t)) nil))))

(defun %component-size (type)
  (case type (5120 1) (5121 1) (5122 2) (5123 2) (5125 4) (5126 4)
    (otherwise (%fail "tipo de componente de accessor desconhecido ~s." type))))
(defun %read-scalar (bytes offset type)
  (let ((size (%component-size type)))
    (unless (<= (+ offset size) (length bytes)) (%fail "accessor além do fim do buffer."))
    (let ((raw (loop for i below size sum (ash (aref bytes (+ offset i)) (* i 8)))))
      (case type
        (5120 (let ((v (if (logbitp 7 raw) (- raw 256) raw))) v))
        (5121 raw)
        (5122 (if (logbitp 15 raw) (- raw 65536) raw))
        (5123 raw)
        (5125 raw)
        (5126 (let* ((bits (if (logbitp 31 raw) (- raw #x100000000) raw)))
                (sb-kernel:make-single-float bits)))))))
(defun %normalized-value (value type)
  (case type
    (5120 (max -1d0 (/ value 127d0))) (5121 (/ value 255d0))
    (5122 (max -1d0 (/ value 32767d0))) (5123 (/ value 65535d0)) (otherwise value)))
(defun %shape-size (shape)
  (cond ((string= shape "SCALAR") 1) ((string= shape "VEC2") 2)
        ((string= shape "VEC3") 3) ((string= shape "VEC4") 4)
        ((string= shape "MAT2") 4) ((string= shape "MAT3") 9)
        ((string= shape "MAT4") 16) (t (%fail "tipo de accessor desconhecido ~s." shape))))
(defun %accessor-values (index accessors views buffers &optional (expected-type nil))
  (let* ((accessor (%index index accessors "accessor"))
         (count (%integer-field accessor "count" "accessor" 1))
         (component (%integer-field accessor "componentType" "accessor" 0))
         (shape (%required accessor "type" "accessor"))
         (width (%shape-size shape)) (size (%component-size component))
         (normalized (member (%get accessor "normalized") (list t 'yason:true)))
         (data (make-array (* count width) :initial-element 0d0)))
    (when (and expected-type (not (string= expected-type shape))) (%fail "esperado accessor ~a, veio ~a." expected-type shape))
    (when (and normalized (member component '(5125 5126))) (%fail "normalized não permitido para componentType ~a." component))
    (flet ((read-elements (view-index byte-offset stride element-count component-type target-width destination-index)
             (let* ((view (%index view-index views "bufferView"))
                    (buffer-index (%integer-field view "buffer" "bufferView" 0))
                    (buffer (%index buffer-index buffers "buffer"))
                    (view-offset (%get view "byteOffset" 0))
                    (view-length (%integer-field view "byteLength" "bufferView" 0))
                    (view-end (+ view-offset view-length))
                    (effective-stride (or stride (* target-width (%component-size component-type))))
                    (absolute (+ view-offset byte-offset)))
               (when (or (> (+ absolute (* (1- element-count) effective-stride)
                                     (* target-width (%component-size component-type))) view-end)
                         (> view-end (length buffer)))
                 (%fail "bufferView/accessor excede o buffer declarado."))
               (loop for element below element-count do
                 (loop for component-offset below target-width
                       for at = (+ absolute (* element effective-stride)
                                   (* component-offset (%component-size component-type)))
                       for v = (%read-scalar buffer at component-type)
                       do (setf (aref data (+ destination-index (* element target-width) component-offset))
                                (if normalized (%normalized-value v component-type) v)))))))
      (when (gethash "bufferView" accessor)
        (let* ((view (%index (gethash "bufferView" accessor) views "bufferView"))
               (stride (%get view "byteStride"))
               (offset (%get accessor "byteOffset" 0)))
          (unless (and (integerp offset) (>= offset 0)) (%fail "byteOffset inválido."))
          (when (and stride (or (< stride (* width size)) (> stride 252) (not (zerop (mod stride 4)))))
            (%fail "byteStride inválido."))
          (read-elements (gethash "bufferView" accessor) offset stride count component width 0)))
      (when (gethash "sparse" accessor)
        (let* ((sparse (gethash "sparse" accessor))
               (sparse-count (%integer-field sparse "count" "sparse" 1))
               (indices (%required sparse "indices" "sparse"))
               (values-object (%required sparse "values" "sparse"))
               (index-type (%integer-field indices "componentType" "sparse.indices" 0))
               (index-view (%integer-field indices "bufferView" "sparse.indices" 0))
               (value-view (%integer-field values-object "bufferView" "sparse.values" 0))
               (index-buffer (%index (%integer-field (%index index-view views "sparse index view") "buffer" "sparse index view" 0) buffers "buffer"))
               (value-buffer (%index (%integer-field (%index value-view views "sparse value view") "buffer" "sparse value view" 0) buffers "buffer"))
               (iv (%index index-view views "sparse index view")) (vv (%index value-view views "sparse value view"))
               (indices-start (+ (%get iv "byteOffset" 0) (%get indices "byteOffset" 0)))
               (values-start (+ (%get vv "byteOffset" 0) (%get values-object "byteOffset" 0))))
          (unless (member index-type '(5121 5123 5125)) (%fail "sparse index componentType inválido."))
          (unless (and (<= sparse-count count)
                       (integerp indices-start) (>= indices-start (%get iv "byteOffset" 0))
                       (integerp values-start) (>= values-start (%get vv "byteOffset" 0)))
            (%fail "offset ou contagem sparse inválidos."))
          (when (or (> (+ indices-start (* sparse-count (%component-size index-type)))
                       (+ (%get iv "byteOffset" 0) (%get iv "byteLength")))
                    (> (+ values-start (* sparse-count width size))
                       (+ (%get vv "byteOffset" 0) (%get vv "byteLength"))))
            (%fail "dados sparse além do buffer."))
          (loop for i below sparse-count for index = (%read-scalar index-buffer (+ indices-start (* i (%component-size index-type))) index-type) do
            (unless (and (< index count) (or (zerop i) (> index (%read-scalar index-buffer (+ indices-start (* (1- i) (%component-size index-type))) index-type))))
              (%fail "índices sparse fora da faixa ou não crescentes."))
            (loop for c below width do
              (setf (aref data (+ (* index width) c))
                    (let ((v (%read-scalar value-buffer (+ values-start (* (+ (* i width) c) size)) component)))
                      (if normalized (%normalized-value v component) v)))))))
      (when (and (not (gethash "bufferView" accessor)) (not (gethash "sparse" accessor)))
        (%fail "accessor sem bufferView nem sparse."))
      (loop for value across data do (%finite value "accessor"))
      (dolist (bound-key '("min" "max"))
        (when (gethash bound-key accessor)
          (let ((bound (%arr (gethash bound-key accessor))))
            (unless (= (length bound) width) (%fail "accessor ~a com dimensão incorreta." bound-key))
            (loop for c below width
                  for actual = (loop for i below count collect (aref data (+ (* i width) c)))
                  for expected = (elt bound c)
                  do (unless (%finite expected "accessor bounds") (%fail "limite inválido."))
                     (setf expected (if normalized (%normalized-value expected component)
                                        (if (= component 5126) (coerce expected 'single-float) expected)))
                     (if (string= bound-key "min")
                         (when (> expected (reduce #'min actual)) (%fail "accessor min excede os dados."))
                         (when (< expected (reduce #'max actual)) (%fail "accessor max está abaixo dos dados.")))))))
      (values data count width shape))))

(defun %vector3 (values)
  (unless (= (length values) 3) (%fail "vec3 precisa conter três componentes."))
  (make-array 3 :element-type 'double-float
              :initial-contents (loop for i below 3 collect (%finite (elt values i) "vec3"))))
(defun %matrix-components (matrix)
  ;; Matriz coluna-major, decomposta em TRS; shear não é representável no nó do motor.
  (unless (= (length matrix) 16) (%fail "node.matrix precisa ter 16 componentes."))
  (let* ((m (map 'vector (lambda (x) (%finite x "node.matrix")) matrix))
         (sx (sqrt (+ (expt (aref m 0) 2) (expt (aref m 1) 2) (expt (aref m 2) 2))))
         (sy (sqrt (+ (expt (aref m 4) 2) (expt (aref m 5) 2) (expt (aref m 6) 2))))
         (sz (sqrt (+ (expt (aref m 8) 2) (expt (aref m 9) 2) (expt (aref m 10) 2))))
         (sx (if (< (- (* (aref m 0) (- (* (aref m 5) (aref m 10)) (* (aref m 9) (aref m 6))))
                         (* (aref m 4) (- (* (aref m 1) (aref m 10)) (* (aref m 9) (aref m 2))))
                         (* (aref m 8) (- (* (aref m 1) (aref m 6)) (* (aref m 5) (aref m 2))))) 0d0)
                    (- sx) sx))
         (r00 (/ (aref m 0) sx)) (r10 (/ (aref m 1) sx)) (r20 (/ (aref m 2) sx))
         (r01 (/ (aref m 4) sy)) (r11 (/ (aref m 5) sy)) (r21 (/ (aref m 6) sy))
         (r02 (/ (aref m 8) sz)) (r12 (/ (aref m 9) sz)) (r22 (/ (aref m 10) sz))
         (trace (+ r00 r11 r22)) (q nil))
    (when (or (< (abs sx) 1d-12) (< (abs sy) 1d-12) (< (abs sz) 1d-12))
      (%fail "node.matrix singular não pode virar TRS."))
    (when (or (> (abs (+ (* r00 r01) (* r10 r11) (* r20 r21))) 1d-5)
              (> (abs (+ (* r00 r02) (* r10 r12) (* r20 r22))) 1d-5)
              (> (abs (+ (* r01 r02) (* r11 r12) (* r21 r22))) 1d-5))
      (%fail "node.matrix contém shear, indisponível na hierarquia do motor."))
    (setf q
          (cond ((plusp trace)
                 (let* ((s (* 2d0 (sqrt (+ trace 1d0))))
                        (w (/ s 4d0)) (x (/ (- r21 r12) s))
                        (y (/ (- r02 r20) s)) (z (/ (- r10 r01) s)))
                   (sgeo.math:make-quaternion x y z w)))
                ((and (> r00 r11) (> r00 r22))
                 (let* ((s (* 2d0 (sqrt (max 0d0 (+ 1d0 r00 (- r11) (- r22))))))
                        (x (/ s 4d0)) (y (/ (+ r01 r10) s))
                        (z (/ (+ r02 r20) s)) (w (/ (- r21 r12) s)))
                   (sgeo.math:make-quaternion x y z w)))
                ((> r11 r22)
                 (let* ((s (* 2d0 (sqrt (max 0d0 (+ 1d0 r11 (- r00) (- r22))))))
                        (x (/ (+ r01 r10) s)) (y (/ s 4d0))
                        (z (/ (+ r12 r21) s)) (w (/ (- r02 r20) s)))
                   (sgeo.math:make-quaternion x y z w)))
                (t (let* ((s (* 2d0 (sqrt (max 0d0 (+ 1d0 r22 (- r00) (- r11))))))
                          (x (/ (+ r02 r20) s)) (y (/ (+ r12 r21) s))
                          (z (/ s 4d0)) (w (/ (- r10 r01) s)))
                     (sgeo.math:make-quaternion x y z w)))))
    (values (%vector3 (list (aref m 12) (aref m 13) (aref m 14))) q
            (%vector3 (list sx sy sz)))))

(defun %triangle-indices (mode vertices indices)
  (let* ((source (or indices (coerce (loop for i below vertices collect i) 'vector)))
         (triangles (make-array 0 :adjustable t :fill-pointer 0)))
    (labels ((tri (a b c) (vector-push-extend a triangles)
               (vector-push-extend b triangles) (vector-push-extend c triangles)))
      (case mode
        (4 (unless (zerop (mod (length source) 3)) (%fail "mode TRIANGLES exige três índices por triângulo."))
           (loop for i from 0 below (length source) by 3 do (tri (aref source i) (aref source (1+ i)) (aref source (+ i 2)))))
        (5 (loop for i from 2 below (length source) do
               (if (evenp i) (tri (aref source (- i 2)) (aref source (1- i)) (aref source i))
                   (tri (aref source (1- i)) (aref source (- i 2)) (aref source i)))))
        (6 (loop for i from 2 below (length source) do (tri (aref source 0) (aref source (1- i)) (aref source i))))
        (otherwise (%fail "mode de primitiva ~s não suportado; apenas triângulos, strip e fan." mode)))
      (coerce triangles 'vector))))

(defun %image-data (image buffers views source-directory)
  (cond ((gethash "uri" image) (%resource-bytes (gethash "uri" image) source-directory))
        ((gethash "bufferView" image)
         (let* ((view (%index (gethash "bufferView" image) views "image.bufferView"))
                (buffer (%index (%get view "buffer") buffers "image buffer"))
                (offset (%get view "byteOffset" 0)) (length (%get view "byteLength")))
           (unless (<= (+ offset length) (length buffer)) (%fail "imagem excede bufferView."))
           (subseq buffer offset (+ offset length))))
        (t (%fail "imagem sem uri ou bufferView."))))

(defun %load-materials (document buffers views source-directory)
  (let* ((raw-images (%arr (%get document "images")))
         (images (map 'vector (lambda (image)
                               (let ((bytes (%image-data image buffers views source-directory)))
                                (list :name (%get image "name") :mime-type (%image-mime-type image bytes)
                                      :bytes bytes :source image))) raw-images))
         (textures (%arr (%get document "textures")))
         (materials (%arr (%get document "materials")))
         (result (make-array (length materials))))
    (loop for texture across textures do
      (%index (%required texture "source" "texture") images "texture.source")
      (when (%get texture "sampler")
        (%index (%get texture "sampler") (%arr (%get document "samplers")) "texture.sampler")))
    (dotimes (i (length materials))
      (let* ((raw (aref materials i))
             (pbr (%get raw "pbrMetallicRoughness"))
             (base (%arr (%get pbr "baseColorFactor" #(1d0 1d0 1d0 1d0))))
             (emissive (%arr (%get raw "emissiveFactor" #(0d0 0d0 0d0))))
             (material (make-pbr-material :name (or (%get raw "name") (format nil "Material ~d" i))
                                          :base-color base
                                          :metallic (%get pbr "metallicFactor" 1d0)
                                          :roughness (%get pbr "roughnessFactor" 1d0)
                                          :emissive emissive)))
        (dolist (pair (list (list pbr "baseColorTexture") (list pbr "metallicRoughnessTexture")
                           (list raw "normalTexture") (list raw "occlusionTexture") (list raw "emissiveTexture")))
          (let ((info (%get (first pair) (second pair))))
            (when info (%index (%required info "index" "textureInfo") textures "textureInfo.index"))))
        (setf (gethash :gltf-material (object-metadata material))
              (list :definition (%json-safe raw) :textures (%json-safe textures)
                    :samplers (%json-safe (%arr (%get document "samplers")))
                    :images (%safe-images images)
                    :alpha-mode (%get raw "alphaMode" "OPAQUE")
                    :alpha-cutoff (%get raw "alphaCutoff" 0.5d0)
                    :double-sided (not (null (member (%get raw "doubleSided") (list t 'yason:true))))))
        (setf (aref result i) material)))
    (values result textures images)))

(defun %load-primitives (mesh-index gltf-mesh meshes accessors views buffers materials)
  (let ((primitives (%arr (%get gltf-mesh "primitives"))))
    (when (zerop (length primitives)) (%fail "mesh ~d não possui primitives." mesh-index))
    (loop for primitive across primitives for pindex from 0 collect
      (let* ((attributes (%required primitive "attributes" "primitive"))
             (position-index (%get attributes "POSITION"))
             (position-values nil) (vertex-count nil))
        (unless position-index (%fail "primitive sem POSITION."))
        (multiple-value-setq (position-values vertex-count) (%accessor-values position-index accessors views buffers "VEC3"))
        (let* ((normals (when (gethash "NORMAL" attributes)
                          (multiple-value-bind (v n) (%accessor-values (gethash "NORMAL" attributes) accessors views buffers "VEC3")
                            (unless (= n vertex-count) (%fail "NORMAL e POSITION com contagens diferentes.")) v)))
               (index-values (when (gethash "indices" primitive)
                               (multiple-value-bind (v n width shape)
                                   (%accessor-values (gethash "indices" primitive) accessors views buffers "SCALAR")
                                 (declare (ignore width shape))
                                 (let ((accessor (%index (gethash "indices" primitive) accessors "indices")))
                                   (unless (member (%get accessor "componentType") '(5121 5123 5125))
                                     (%fail "índice de primitive precisa ser unsigned integer.")))
                                 (subseq v 0 n))))
               (mode (%get primitive "mode" 4))
               (triangles (%triangle-indices mode vertex-count index-values))
               (vertex-attributes (make-hash-table :test #'equal)))
          (when (or (zerop (length triangles)) (some (lambda (i) (or (not (integerp i)) (< i 0) (>= i vertex-count))) triangles))
            (%fail "triângulo vazio ou índice fora do número de vértices."))
          (maphash (lambda (semantic accessor-index)
                     (unless (member semantic '("POSITION" "NORMAL") :test #'string=)
                       (multiple-value-bind (values count width shape)
                           (%accessor-values accessor-index accessors views buffers)
                         (declare (ignore shape))
                         (unless (= count vertex-count) (%fail "atributo ~a com contagem incompatível." semantic))
                         (setf (gethash semantic vertex-attributes) (list :components width :values values)))))
                   attributes)
          (let* ((meta (make-hash-table :test #'equal))
                 (geometry (make-triangle-mesh :positions position-values :indices triangles
                                               :normals normals
                                               :name (format nil "~a / primitiva ~d" (or (%get gltf-mesh "name") mesh-index) pindex)
                                               :metadata meta))
                 (material-index (%get primitive "material"))
                 (material (if material-index (%index material-index materials "material")
                               (make-material :name "Default glTF"))))
            (setf (gethash :gltf-attributes (object-metadata geometry)) (%safe-attributes vertex-attributes)
                  (gethash :gltf-primitive (object-metadata geometry))
                  (list :mode mode :index-data (coerce index-values 'list)
                        :morph-targets (%json-safe (%arr (%get primitive "targets")))))
            (make-mesh-object geometry :material material
                              :name (format nil "~a / primitiva ~d" (or (%get gltf-mesh "name") mesh-index) pindex))))))))

(defun %validate-core-extensions (document)
  (let ((required (%arr (%get document "extensionsRequired"))))
    (when (plusp (length required))
      (%fail "extensões obrigatórias não suportadas: ~{~a~^, ~}." (coerce required 'list))))
  (unless (string= (%get (%get document "asset") "version" "") "2.0")
    (%fail "asset.version precisa ser 2.0.")))

(defun %check-graph (nodes)
  (let ((parents (make-array (length nodes) :initial-element nil)))
    (dotimes (i (length nodes))
      (let ((children (%arr (%get (aref nodes i) "children"))))
        (unless (= (length children) (length (remove-duplicates (coerce children 'list))))
          (%fail "node ~d repete um filho." i))
        (loop for child across children do
          (%index child nodes "node.children")
          (when (aref parents child) (%fail "node ~d possui mais de um pai." child))
          (setf (aref parents child) i))))
    (let ((state (make-array (length nodes) :initial-element 0)))
      (labels ((visit (i)
                 (when (= (aref state i) 1) (%fail "ciclo na hierarquia de nodes."))
                 (unless (= (aref state i) 2)
                   (setf (aref state i) 1)
                   (loop for child across (%arr (%get (aref nodes i) "children")) do (visit child))
                   (setf (aref state i) 2))))
        (dotimes (i (length nodes)) (visit i))))
    parents))

(defun %node-root (node)
  (loop for current = node then (scene-object-parent current)
        while (scene-object-parent current) finally (return current)))
(defun %ancestor-list (node)
  (loop for current = node then (scene-object-parent current) while current collect current))
(defun %common-ancestor (nodes)
  (let ((first-chain (%ancestor-list (first nodes))))
    (or (find-if (lambda (candidate)
                   (every (lambda (node) (member candidate (%ancestor-list node) :test #'eq))
                          (rest nodes))) first-chain)
        (first nodes))))
(defun %matrices-from-accessor (accessor-index accessors views buffers count)
  (multiple-value-bind (values matrix-count width shape)
      (%accessor-values accessor-index accessors views buffers "MAT4")
    (declare (ignore width))
    (unless (and (string= shape "MAT4") (= matrix-count count))
      (%fail "inverseBindMatrices precisa de uma MAT4 por joint."))
    (loop for i below count collect
      (sgeo.math:make-mat4 (subseq values (* i 16) (* (1+ i) 16))))))
(defun %make-skeletons (document node-objects parent-index accessors views buffers)
  (let* ((skins (%arr (%get document "skins"))) (result (make-array (length skins))))
    (dotimes (i (length skins))
      (let* ((skin (aref skins i)) (joint-indexes (%arr (%required skin "joints" "skin")))
             (joints (map 'vector (lambda (index) (%index index node-objects "skin.joints")) joint-indexes))
             (roots (map 'list #'%node-root joints))
             (root (if (gethash "skeleton" skin)
                       (%index (gethash "skeleton" skin) node-objects "skin.skeleton")
                       (%common-ancestor (coerce joints 'list))))
             (matrices (if (gethash "inverseBindMatrices" skin)
                           (%matrices-from-accessor (gethash "inverseBindMatrices" skin)
                                                     accessors views buffers (length joints))
                           (make-list (length joints) :initial-element (sgeo.math:identity-mat4))))
             (skeleton (sgeo.animation:make-skeleton :name (or (%get skin "name") (format nil "Skin ~d" i))
                                                     :joints joints :inverse-bind-matrices matrices :root root)))
        (unless (and roots (every (lambda (candidate) (eq candidate (first roots))) (rest roots)))
          (%fail "joints de skin ~d não compartilham uma hierarquia." i))
        (unless (every (lambda (joint) (member root (%ancestor-list joint) :test #'eq)) (coerce joints 'list))
          (%fail "skin.skeleton não é ancestral dos joints."))
        (setf (aref result i) skeleton)))
    result))
(defun %primitive-morph-targets (primitive accessors views buffers vertex-count)
  (let ((targets (%arr (%get primitive "targets"))))
    (map 'vector
         (lambda (target)
           (maphash (lambda (semantic accessor)
                      (declare (ignore accessor))
                      (unless (member semantic '("POSITION" "NORMAL" "TANGENT") :test #'string=)
                        (%fail "atributo morfológico ~a não é suportado sem perda." semantic)))
                    target)
           (let ((positions (if (gethash "POSITION" target)
                                (multiple-value-bind (values count)
                                    (%accessor-values (gethash "POSITION" target) accessors views buffers "VEC3")
                                  (unless (= count vertex-count) (%fail "morph POSITION com contagem incorreta.")) values)
                                (make-array (* 3 vertex-count) :initial-element 0d0)))
                 (normals (when (gethash "NORMAL" target)
                            (multiple-value-bind (values count)
                                (%accessor-values (gethash "NORMAL" target) accessors views buffers "VEC3")
                              (unless (= count vertex-count) (%fail "morph NORMAL com contagem incorreta.")) values))))
             (sgeo.animation:make-morph-target :positions positions :normals normals))) targets)))
(defun %node-influences (primitive accessors views buffers vertex-count joint-count)
  "Reúne todos os conjuntos JOINTS_n/WEIGHTS_n sem descartar influências."
  (let* ((attributes (%get primitive "attributes"))
         (sets (sort (loop for semantic being the hash-keys of attributes
                           when (and (>= (length semantic) 7) (string= semantic "JOINTS_" :end1 7))
                           collect (or (parse-integer semantic :start 7 :junk-allowed nil)
                                       (%fail "semântica de junta inválida."))) #'<))
         (weight-count (loop for semantic being the hash-keys of attributes
                             count (and (>= (length semantic) 8) (string= semantic "WEIGHTS_" :end1 8))))
         (index-rows (make-array vertex-count :initial-element nil))
         (weight-rows (make-array vertex-count :initial-element nil)))
    (unless (= (length sets) weight-count) (%fail "JOINTS_n e WEIGHTS_n precisam aparecer em pares."))
    (when (null sets) (return-from %node-influences (values nil nil)))
    (loop for set in sets for expected from 0 do
      (unless (= set expected) (%fail "conjuntos de influência precisam ter índices consecutivos."))
      (let* ((joints (%required attributes (format nil "JOINTS_~D" set) "primitive"))
             (weights (%required attributes (format nil "WEIGHTS_~D" set) "primitive"))
             (joint-decl (%index joints accessors "JOINTS"))
             (weight-decl (%index weights accessors "WEIGHTS"))
             (weight-component (%get weight-decl "componentType")))
        (unless (and (member (%get joint-decl "componentType") '(5121 5123))
                     (not (member (%get joint-decl "normalized") (list t 'yason:true))))
          (%fail "JOINTS precisa usar unsigned byte/short não normalizado."))
        (unless (or (= weight-component 5126)
                    (and (member weight-component '(5121 5123))
                         (member (%get weight-decl "normalized") (list t 'yason:true))))
          (%fail "WEIGHTS precisa usar FLOAT ou unsigned byte/short normalizado."))
        (multiple-value-bind (values count) (%accessor-values joints accessors views buffers "VEC4")
          (unless (= count vertex-count) (%fail "JOINTS com contagem incorreta."))
          (dotimes (i vertex-count)
            (setf (aref index-rows i) (append (aref index-rows i) (coerce (subseq values (* i 4) (* (1+ i) 4)) 'list)))))
        (multiple-value-bind (values count) (%accessor-values weights accessors views buffers "VEC4")
          (unless (= count vertex-count) (%fail "WEIGHTS com contagem incorreta."))
          (dotimes (i vertex-count)
            (setf (aref weight-rows i) (append (aref weight-rows i) (coerce (subseq values (* i 4) (* (1+ i) 4)) 'list)))))))
    (dotimes (i vertex-count)
      (let ((seen nil))
        (loop for joint in (aref index-rows i) for weight in (aref weight-rows i) do
          (unless (and (integerp joint) (<= 0 joint) (< joint joint-count) (>= weight 0))
            (%fail "índice/peso de junta inválido."))
          (when (plusp weight)
            (when (member joint seen) (%fail "influência não nula repetida para uma junta."))
            (push joint seen)))
        (unless (plusp (reduce #'+ (aref weight-rows i))) (%fail "vértice de skin sem peso positivo."))))
    (values (coerce index-rows 'list) (coerce weight-rows 'list))))
(defun %replace-node-meshes-with-deformables (document node-objects primitive-meshes skins skeletons accessors views buffers)
  (declare (ignore primitive-meshes skins))
  (let ((nodes (%arr (%get document "nodes"))) (meshes (%arr (%get document "meshes"))))
    (dotimes (i (length nodes))
      (let* ((decl (aref nodes i)) (mesh-index (%get decl "mesh"))
             (skin-index (%get decl "skin")))
        (when mesh-index
          (let* ((mesh-decl (%index mesh-index meshes "node.mesh"))
                 (primitive-decls (%arr (%get mesh-decl "primitives")))
                 (objects (scene-object-children (aref node-objects i)))
                 (has-morphs (plusp (length (%arr (%get (aref primitive-decls 0) "targets"))))))
            (when (or skin-index has-morphs)
              (when (and has-morphs (some (lambda (primitive)
                                           (/= (length (%arr (%get primitive "targets")))
                                               (length (%arr (%get (aref primitive-decls 0) "targets")))))
                                         primitive-decls))
                (%fail "primitives de uma mesh precisam ter quantidades iguais de morph targets."))
              (loop for object in objects for primitive across primitive-decls do
                (let* ((geometry (mesh-object-geometry object))
                       (positions (sgeo.geometry:mesh-positions geometry))
                       (vertex-count (/ (length positions) 3))
                       (skeleton (when skin-index (%index skin-index skeletons "node.skin")))
                       (joint-count (if skeleton (length (sgeo.animation:skeleton-joints skeleton)) 0))
                       (morph-targets (%primitive-morph-targets primitive accessors views buffers vertex-count))
                       (morph-weights (%arr (or (%get decl "weights") (%get mesh-decl "weights"))))
                       (influences nil) (weights nil) (deformable nil))
                  (when (and (plusp (length morph-weights)) (/= (length morph-weights) (length morph-targets)))
                    (%fail "node/mesh weights incompatíveis com morph target count."))
                  (multiple-value-setq (influences weights)
                    (%node-influences primitive accessors views buffers vertex-count joint-count))
                  (when (and skin-index (not influences)) (%fail "skinned primitive exige JOINTS_0 e WEIGHTS_0."))
                  (setf deformable
                        (sgeo.animation:make-deformable-mesh-object
                         :name (object-name object) :geometry geometry :material (mesh-object-material object)
                         :skeleton skeleton :joint-indices influences :joint-weights weights
                         :morph-targets (coerce morph-targets 'list)
                         :morph-weights (if (plusp (length morph-weights)) morph-weights
                                            (make-array (length morph-targets) :initial-element 0d0))))
                  (when influences
                    (let* ((per-vertex-width (length (first influences)))
                           (joint-attributes
                             (loop for set from 0 below (/ per-vertex-width 4) append
                               (list (list (format nil "JOINTS_~d" set) :components 4
                                           :values (loop for row in influences append (subseq row (* set 4) (* (1+ set) 4))))
                                     (list (format nil "WEIGHTS_~d" set) :components 4
                                           :values (loop for row in weights append (subseq row (* set 4) (* (1+ set) 4))))))))
                      (setf (gethash :gltf-attributes (object-metadata geometry))
                            (append (gethash :gltf-attributes (object-metadata geometry)) joint-attributes))))
                  (setf (gethash :gltf-morph-data (object-metadata geometry))
                        (list :target-count (length morph-targets)
                              :target-source (%json-safe (%arr (%get primitive "targets")))))
                  (setf (gethash :gltf-morph-tangents (object-metadata geometry))
                        (map 'list (lambda (target)
                                     (when (%get target "TANGENT")
                                       (multiple-value-bind (values count)
                                           (%accessor-values (%get target "TANGENT") accessors views buffers "VEC3")
                                         (unless (= count vertex-count) (%fail "morph TANGENT com contagem incorreta."))
                                         (coerce values 'list)))) (%arr (%get primitive "targets"))))
                  (remove-child (aref node-objects i) object)
                  (add-child (aref node-objects i) deformable))))))))))

(defun %animation-value (values key-index width)
  (let ((components (subseq values (* key-index width) (* (1+ key-index) width))))
    (if (= width 1) (aref components 0) components)))
(defun %animation-keys (times values width interpolation)
  (let ((count (length times)))
    (unless (and (plusp count) (or (not (eq interpolation :cubic-spline)) (> count 1)))
      (%fail "curva de animação vazia ou cúbica com menos de duas chaves."))
    (loop for i below count collect
      (let ((time (%finite (aref times i) "animation input")))
        (when (minusp time) (%fail "tempos de animação precisam ser não negativos."))
        (if (eq interpolation :cubic-spline)
            (list time (%animation-value values (+ (* i 3) 1) width)
                  (%animation-value values (* i 3) width)
                  (%animation-value values (+ (* i 3) 2) width))
            (list time (%animation-value values i width)))))))
(defun %weights-animation-keys (times values width interpolation)
  (let ((count (length times)))
    (unless (and (plusp count) (or (not (eq interpolation :cubic-spline)) (> count 1)))
      (%fail "curva de weights vazia ou cúbica com menos de duas chaves."))
    (loop for i below count collect
      (let* ((time (%finite (aref times i) "animation input"))
             (base (* i width (if (eq interpolation :cubic-spline) 3 1)))
             (in (when (eq interpolation :cubic-spline) (subseq values base (+ base width))))
             (value-start (if (eq interpolation :cubic-spline) (+ base width) base))
             (value (subseq values value-start (+ value-start width)))
             (out-start (when (eq interpolation :cubic-spline) (+ base (* 2 width))))
             (out (when out-start (subseq values out-start (+ out-start width)))))
        (when (minusp time) (%fail "tempos de animação precisam ser não negativos."))
        (if out (list time value in out) (list time value))))))
(defun %make-clips (document node-objects primitive-meshes accessors views buffers)
  (declare (ignore primitive-meshes))
  (let* ((animations (%arr (%get document "animations")))
         (result (make-array (length animations)))
         (nodes (%arr (%get document "nodes")))
         (meshes (%arr (%get document "meshes"))))
    (dotimes (animation-index (length animations))
      (let* ((animation (aref animations animation-index))
             (samplers (%arr (%get animation "samplers")))
             (tracks nil)
             (seen (make-hash-table :test #'equal)))
        (loop for channel across (%arr (%get animation "channels")) do
          (let* ((target (%required channel "target" "animation channel"))
                 (node-index (%integer-field target "node" "animation target" 0))
                 (node (%index node-index node-objects "animation target node"))
                 (path (%required target "path" "animation target"))
                 (sampler (%index (%integer-field channel "sampler" "animation channel" 0)
                                  samplers "animation sampler"))
                 (mode (let ((name (%get sampler "interpolation" "LINEAR")))
                         (cond ((string= name "LINEAR") :linear)
                               ((string= name "STEP") :step)
                               ((string= name "CUBICSPLINE") :cubic-spline)
                               (t (%fail "interpolação não suportada: ~a." name)))))
                 (input (%integer-field sampler "input" "animation sampler" 0))
                 (output (%integer-field sampler "output" "animation sampler" 0))
                 (input-decl (%index input accessors "animation input"))
                 (times nil) (time-count nil) (time-width nil) (time-shape nil)
                 (values nil) (value-count nil) (width nil) (shape nil))
            (multiple-value-setq (times time-count time-width time-shape)
              (%accessor-values input accessors views buffers "SCALAR"))
            (unless (and (= (%get input-decl "componentType") 5126) (= time-width 1)
                         (gethash "min" input-decl) (gethash "max" input-decl))
              (%fail "animation input deve ser FLOAT SCALAR e declarar min/max."))
            (multiple-value-setq (values value-count width shape)
              (%accessor-values output accessors views buffers))
            (unless (member path '("translation" "rotation" "scale" "weights") :test #'string=)
              (%fail "animation target path inválido: ~a." path))
            (loop for key-index from 1 below time-count do
              (unless (> (aref times key-index) (aref times (1- key-index)))
                (%fail "timestamps precisam crescer estritamente.")))
            (let* ((factor (if (eq mode :cubic-spline) 3 1))
                   (weightp (string= path "weights"))
                   (morph-count nil)
                   (expected-width (cond ((string= path "translation") 3)
                                         ((string= path "scale") 3)
                                         ((string= path "rotation") 4)
                                         (t nil))))
              (if expected-width
                  (unless (and (= width expected-width) (= value-count (* time-count factor))
                               (string= shape (format nil "VEC~d" width)))
                    (%fail "accessor de saída incompatível com ~a." path))
                  (let* ((node-decl (%index node-index nodes "animation node"))
                         (mesh-index (%get node-decl "mesh"))
                         (mesh (and mesh-index (%index mesh-index meshes "animation mesh")))
                         (first-primitive (and mesh (%index 0 (%arr (%get mesh "primitives")) "mesh primitive"))))
                    (setf morph-count (or (and mesh (length (%arr (%get mesh "weights"))))
                                          (length (%arr (%get first-primitive "targets")))))
                    (unless (and (plusp morph-count) (= width 1) (string= shape "SCALAR")
                                 (= value-count (* morph-count time-count factor)))
                      (%fail "accessor de weights incompatível com os morph targets."))))
              (let* ((identity (list node-index path))
                     (targets (if weightp
                                  (remove-if-not (lambda (child)
                                                   (and (typep child 'sgeo.animation:deformable-mesh-object)
                                                        (plusp (length (sgeo.animation:mesh-morph-targets child)))))
                                                 (scene-object-children node))
                                  (list node))))
                (when (gethash identity seen) (%fail "canal duplicado para node/path."))
                (setf (gethash identity seen) t)
                (when (null targets) (%fail "weights target sem malha morfológica."))
                (dolist (track-target targets)
                  (let* ((property (cond ((string= path "translation") :position)
                                         ((string= path "rotation") :rotation)
                                         ((string= path "scale") :scale)
                                         (t :weights)))
                         (keys (if weightp (%weights-animation-keys times values morph-count mode)
                                   (%animation-keys times values width mode))))
                    (when (string= path "rotation")
                      (dolist (key keys)
                        (setf (second key) (apply #'sgeo.math:make-quaternion
                                                 (coerce (second key) 'list)))))
                    (push (sgeo.animation:make-property-track track-target (list property) keys
                                                              :interpolation mode
                                                              :name (or (%get animation "name") path))
                          tracks)))))))
        (setf (aref result animation-index)
              (sgeo.animation:make-animation-clip
               :name (or (%get animation "name") (format nil "Animation ~d" animation-index))
               :tracks (nreverse tracks)))))
    result))

(defun %source-snapshot (document buffers)
  (list :document (%json-safe document)
        :buffers (loop for buffer across buffers collect (%base64-encode buffer))))

(defun import-gltf (pathname &key world scene)
  "Importa glTF/GLB validando referências e buffers antes de alterar WORLD."
  (let* ((pathname (truename pathname))
         (source-directory (make-pathname :name nil :type nil :defaults pathname))
         (document nil) (glb-binary nil))
    (multiple-value-setq (document glb-binary) (%load-document pathname))
    (%validate-core-extensions document)
    (let* ((buffers-decl (%arr (%get document "buffers")))
           (buffers (make-array (length buffers-decl)))
           (views (%arr (%get document "bufferViews")))
           (accessors (%arr (%get document "accessors")))
           (gltf-meshes (%arr (%get document "meshes")))
           (nodes-decl (%arr (%get document "nodes")))
           (scenes-decl (%arr (%get document "scenes")))
           (parent-index (%check-graph nodes-decl))
           (scene-index (or scene (%get document "scene" 0)))
           (materials nil) (textures nil) (images nil) (primitive-meshes nil) (skeletons #()) (clips #())
           (node-objects (make-array (length nodes-decl)))
           (world-value (or world (make-world))) (import-roots nil))
      (dotimes (i (length buffers-decl))
        (let* ((decl (aref buffers-decl i))
               (declared (%integer-field decl "byteLength" "buffer" 0))
               (uri (%get decl "uri"))
               (bytes (cond (uri (%resource-bytes uri source-directory))
                            ((and (zerop i) glb-binary) glb-binary)
                            (t (%fail "buffer ~d sem URI e sem bloco BIN." i)))))
          (when (< (length bytes) declared) (%fail "buffer ~d menor que byteLength declarado." i))
          (setf (aref buffers i) (subseq bytes 0 declared))))
      (loop for view across views for i from 0 do
        (let* ((buffer (%index (%integer-field view "buffer" "bufferView" 0) buffers "bufferView.buffer"))
               (offset (%get view "byteOffset" 0))
               (length (%integer-field view "byteLength" "bufferView" 0)))
          (unless (and (integerp offset) (>= offset 0) (<= (+ offset length) (length buffer)))
            (%fail "bufferView ~d excede seu buffer." i))))
          (multiple-value-setq (materials textures images) (%load-materials document buffers views source-directory))
      (setf primitive-meshes
            (coerce (loop for mesh across gltf-meshes for i from 0
                          collect (%load-primitives i mesh gltf-meshes accessors views buffers materials))
                    'vector))
      ;; Monta uma hierarquia isolada; somente raízes validadas serão publicadas no mundo.
      (dotimes (i (length nodes-decl))
        (let* ((decl (aref nodes-decl i))
               (node (make-scene-object :name (or (%get decl "name") (format nil "Node ~d" i))))
               (mesh-index (%get decl "mesh")))
          (when mesh-index
            (let ((primitives (%index mesh-index primitive-meshes "node.mesh")))
              ;; Cada node glTF instancia a malha; os buffers de geometria e material permanecem compartilhados.
              (dolist (primitive primitives)
                (add-child node
                           (make-mesh-object (mesh-object-geometry primitive)
                                             :material (mesh-object-material primitive)
                                             :name (object-name primitive))))))
          (cond
            ((gethash "matrix" decl)
             (when (or (gethash "translation" decl) (gethash "rotation" decl) (gethash "scale" decl))
               (%fail "node não pode definir matrix e TRS simultaneamente."))
             (multiple-value-bind (position rotation scale) (%matrix-components (%arr (gethash "matrix" decl)))
               (set-position node position) (set-rotation node rotation) (set-scale node scale)))
            (t
             (when (gethash "translation" decl) (set-position node (%vector3 (%arr (gethash "translation" decl)))))
             (when (gethash "rotation" decl)
               (let ((q (%arr (gethash "rotation" decl))))
                 (unless (= (length q) 4) (%fail "rotation precisa conter quatro números."))
                 (set-rotation node (apply #'sgeo.math:make-quaternion (map 'list (lambda (x) (%finite x "rotation")) q)))))
             (when (gethash "scale" decl) (set-scale node (%vector3 (%arr (gethash "scale" decl)))))))
          (setf (aref node-objects i) node)))
      (dotimes (i (length nodes-decl))
        (loop for child across (%arr (%get (aref nodes-decl i) "children"))
              do (add-child (aref node-objects i) (aref node-objects child))))
      (setf skeletons (%make-skeletons document node-objects parent-index accessors views buffers))
      (%replace-node-meshes-with-deformables document node-objects primitive-meshes
                                             (%arr (%get document "skins")) skeletons
                                             accessors views buffers)
      (setf clips (%make-clips document node-objects primitive-meshes accessors views buffers))
      (unless (zerop (length scenes-decl))
        (%index scene-index scenes-decl "scene"))
      (setf import-roots
            (if (plusp (length scenes-decl))
                (loop for index across (%arr (%get (aref scenes-decl scene-index) "nodes"))
                      collect (%index index node-objects "scene.nodes"))
                (loop for i below (length node-objects) when (null (aref parent-index i)) collect (aref node-objects i))))
      ;; Validar todas as referências restantes que alterariam a cena após montagem.
      (unless (= (length import-roots) (length (remove-duplicates import-roots :test #'eq)))
        (%fail "scene.nodes contém raízes repetidas."))
      (dolist (root import-roots)
        (when (scene-object-parent root) (%fail "scene.nodes precisa referenciar raízes da hierarquia.")))
      (loop for decl across nodes-decl do
        (when (gethash "camera" decl) (%index (gethash "camera" decl) (%arr (%get document "cameras")) "node.camera"))
        (when (gethash "skin" decl) (%index (gethash "skin" decl) (%arr (%get document "skins")) "node.skin")))
      (dolist (root import-roots) (add-to-world world-value root))
      (dolist (clip (reverse (coerce clips 'list))) (sgeo.animation:add-animation-clip world-value clip))
      (setf (gethash :gltf-sources (object-metadata (world-root world-value)))
            (append (gethash :gltf-sources (object-metadata (world-root world-value)))
                    (list (%source-snapshot document buffers))))
      (let ((asset (%make-gltf-asset :world world-value :scenes import-roots :nodes node-objects
                                     :meshes (coerce (loop for node across node-objects
                                                           append (remove-if-not (lambda (child)
                                                                                   (typep child 'sgeo.scene:mesh-object))
                                                                                 (scene-object-children node)))
                                                      'vector)
                                     :materials materials :textures textures :images images
                                     :skeletons skeletons :clips clips
                                     :metadata (list :document document :source pathname))))
        asset))))

(defun %json-unsafe (value)
  (cond ((and (consp value) (eq (first value) :json-object))
         (let ((table (make-hash-table :test #'equal)))
           (dolist (entry (rest value)) (setf (gethash (first entry) table) (%json-unsafe (second entry)))) table))
        ((and (consp value) (eq (first value) :json-array))
         (map 'vector #'%json-unsafe (rest value)))
        ((eq value :json-true) 'yason:true) ((eq value :json-false) 'yason:false) ((eq value :json-null) 'yason:null)
        (t value)))
(defun %object-children (object)
  (scene-object-children object))
(defun %world-objects (world)
  (let ((out nil))
    (labels ((walk (object)
               (push object out)
               (dolist (child (%object-children object)) (walk child))))
      (walk (world-root world)))
    (nreverse out)))
(defun %u32-append (builder integer)
  (dotimes (i 4) (vector-push-extend (ldb (byte 8 (* i 8)) integer) builder)))
(defun %append-float (builder number)
  (%u32-append builder (sb-kernel:single-float-bits (coerce number 'single-float))))
(defun %pad-builder (builder &optional (alignment 4))
  (loop while (not (zerop (mod (length builder) alignment))) do (vector-push-extend 0 builder)))
(defun %append-floats (builder values)
  (let ((offset (length builder)))
    (%pad-builder builder)
    (setf offset (length builder))
    (loop for value in values do (%append-float builder value))
    (values offset (- (length builder) offset))))
(defun %append-indices (builder indices)
  (let* ((maximum (reduce #'max indices :initial-value 0))
         (component-type (if (<= maximum #xffff) 5123 5125))
         (offset nil) (length nil))
    (%pad-builder builder)
    (setf offset (length builder))
    (dolist (index indices)
      (if (= component-type 5123)
          (progn (vector-push-extend (ldb (byte 8 0) index) builder)
                 (vector-push-extend (ldb (byte 8 8) index) builder))
          (%u32-append builder index)))
    (setf length (- (length builder) offset))
    (values offset length component-type)))
(defun %accessor-entry (doc view-index component-type count shape &key minimum maximum normalized)
  (let* ((accessors (or (gethash "accessors" doc) #()))
         (entry (%obj "bufferView" view-index "componentType" component-type
                      "count" count "type" shape)))
    (when normalized (setf (gethash "normalized" entry) t))
    (when minimum (setf (gethash "min" entry) (coerce minimum 'vector)))
    (when maximum (setf (gethash "max" entry) (coerce maximum 'vector)))
    (setf (gethash "accessors" doc) (concatenate 'vector accessors (vector entry)))
    (1- (length (gethash "accessors" doc)))))
(defun %buffer-view-entry (doc offset length &optional target)
  (let* ((views (or (gethash "bufferViews" doc) #()))
         (entry (%obj "buffer" 0 "byteOffset" offset "byteLength" length)))
    (when target (setf (gethash "target" entry) target))
    (setf (gethash "bufferViews" doc) (concatenate 'vector views (vector entry)))
    (1- (length (gethash "bufferViews" doc)))))
(defun %position-bounds (values)
  (let ((minima (make-array 3 :initial-element most-positive-double-float))
        (maxima (make-array 3 :initial-element most-negative-double-float)))
    (loop for i from 0 below (length values) by 3 do
      (dotimes (j 3)
        (setf (aref minima j) (min (aref minima j) (aref values (+ i j)))
              (aref maxima j) (max (aref maxima j) (aref values (+ i j))))))
    (values minima maxima)))
(defun %export-texture-library (meta doc textures images)
  "Mescla bibliotecas importadas e remapeia índices de imagens e samplers."
  (let* ((library (list (getf meta :textures) (getf meta :images) (getf meta :samplers)))
         (cache (or (gethash "__sgeo_texture_libraries" doc)
                    (setf (gethash "__sgeo_texture_libraries" doc) (make-hash-table :test #'equal)))))
    (multiple-value-bind (base found) (gethash library cache)
      (when found (return-from %export-texture-library (values base textures images))))
    (let* ((base (length textures))
           (image-base (length images))
           (samplers (or (gethash "samplers" doc) #()))
           (sampler-base (length samplers))
           (source-textures (or (%json-unsafe (getf meta :textures)) #()))
           (source-samplers (or (%json-unsafe (getf meta :samplers)) #()))
           (new-images
             (map 'vector (lambda (image)
                            (let ((entry (or (%json-unsafe (getf image :source)) (%obj))))
                              (remhash "bufferView" entry)
                              (setf (gethash "uri" entry) (getf image :data-uri))
                              (when (getf image :mime-type)
                                (setf (gethash "mimeType" entry) (getf image :mime-type)))
                              entry)) (getf meta :images))))
      (setf images (concatenate 'vector images new-images))
      (when (plusp (length source-samplers))
        (setf (gethash "samplers" doc) (concatenate 'vector samplers source-samplers)))
      (loop for texture across source-textures do
        (when (gethash "source" texture) (incf (gethash "source" texture) image-base))
        (when (gethash "sampler" texture) (incf (gethash "sampler" texture) sampler-base)))
      (setf textures (concatenate 'vector textures source-textures)
            (gethash library cache) base)
      (values base textures images))))

(defun %export-material (material doc textures images)
  "Atualiza fatores vivos e preserva mapas com índices válidos após mesclar ativos."
  (let* ((materials (or (gethash "materials" doc) #()))
         (meta (gethash :gltf-material (object-metadata material)))
         (entry (or (and meta (%json-unsafe (getf meta :definition))) (%obj)))
         (index (length materials)))
    (when meta
      (multiple-value-bind (base new-textures new-images)
          (%export-texture-library meta doc textures images)
        (setf textures new-textures images new-images)
        (flet ((remap (owner key)
                 (let ((info (%get owner key)))
                   (when (and info (gethash "index" info)) (incf (gethash "index" info) base)))))
          (remap (%get entry "pbrMetallicRoughness") "baseColorTexture")
          (remap (%get entry "pbrMetallicRoughness") "metallicRoughnessTexture")
          (dolist (key '("normalTexture" "occlusionTexture" "emissiveTexture")) (remap entry key)))))
    (setf (gethash "name" entry) (object-name material))
    (when (typep material 'sgeo.scene:pbr-material)
      (let* ((data (pbr-material-data material))
             (pbr (or (%get entry "pbrMetallicRoughness") (%obj))))
        (setf (gethash "baseColorFactor" pbr) (getf data :base-color)
              (gethash "metallicFactor" pbr) (getf data :metallic)
              (gethash "roughnessFactor" pbr) (getf data :roughness)
              (gethash "pbrMetallicRoughness" entry) pbr
              (gethash "emissiveFactor" entry) (getf data :emissive))))
    (unless (typep material 'sgeo.scene:pbr-material)
      (setf (gethash "pbrMetallicRoughness" entry)
            (%obj "baseColorFactor" (concatenate 'vector (sgeo.scene:simple-material-color material) #(1d0))
                  "metallicFactor" 0d0 "roughnessFactor" 1d0)))
    (setf (gethash "materials" doc) (concatenate 'vector materials (vector entry)))
    (values index textures images)))

(defun %append-u16s (builder values)
  (%pad-builder builder)
  (let ((offset (length builder)))
    (dolist (value values)
      (unless (and (integerp value) (<= 0 value #xffff)) (%fail "índice de articulação fora de UNSIGNED_SHORT."))
      (vector-push-extend (ldb (byte 8 0) value) builder)
      (vector-push-extend (ldb (byte 8 8) value) builder))
    (values offset (- (length builder) offset))))
(defun %rows-flat (rows)
  (loop for row across rows append (coerce row 'list)))
(defun %float-accessor (doc builder values count shape &optional target)
  (multiple-value-bind (offset length) (%append-floats builder values)
    (%accessor-entry doc (%buffer-view-entry doc offset length target) 5126 count shape)))
(defun %export-primitive (object doc builder materials textures images)
  "Exporta a geometria fonte e os dados autoritativos da instância."
  (let* ((geometry (mesh-object-geometry object))
         (data (sgeo.core:compile-render-data geometry))
         (positions (sgeo.geometry:render-mesh-positions data))
         (normals (sgeo.geometry:render-mesh-normals data))
         (indices (coerce (sgeo.geometry:render-mesh-indices data) 'list))
         (attrs (%obj)) (targets (make-array 0 :adjustable t :fill-pointer 0))
         (primitive (%obj)) (metadata (object-metadata geometry)))
    (multiple-value-bind (minimum maximum) (%position-bounds positions)
      (multiple-value-bind (offset length) (%append-floats builder (coerce positions 'list))
        (setf (gethash "POSITION" attrs)
              (%accessor-entry doc (%buffer-view-entry doc offset length 34962) 5126
                               (/ (length positions) 3) "VEC3" :minimum minimum :maximum maximum))))
    (when normals
      (setf (gethash "NORMAL" attrs)
            (%float-accessor doc builder (coerce normals 'list) (/ (length normals) 3) "VEC3" 34962)))
    (dolist (attribute (gethash :gltf-attributes metadata))
      (when (and (consp attribute) (stringp (first attribute))
                 (not (member (first attribute) '("JOINTS_0" "JOINTS_1" "WEIGHTS_0" "WEIGHTS_1") :test #'string=)))
        (let* ((semantic (first attribute)) (width (getf (rest attribute) :components))
               (values (getf (rest attribute) :values)))
          (when (and (integerp width) (member width '(1 2 3 4))
                     (= (length values) (* (/ (length positions) 3) width)))
            (setf (gethash semantic attrs)
                  (%float-accessor doc builder values (/ (length values) width)
                                   (if (= width 1) "SCALAR" (format nil "VEC~d" width)) 34962))))))
    (when (typep object 'sgeo.animation:deformable-mesh-object)
      (when (sgeo.animation:mesh-skeleton object)
        (let* ((joint-rows (sgeo.animation:mesh-joint-indices object))
               (weight-rows (sgeo.animation:mesh-joint-weights object))
               (width (loop for row across joint-rows maximize (length row)))
               (set-count (ceiling width 4)))
          (loop for set below set-count do
            (let ((joint-values (loop for row across joint-rows append
                                 (loop for c from (* set 4) below (* (1+ set) 4)
                                       collect (if (< c (length row)) (aref row c) 0))))
                  (weight-values (loop for row across weight-rows append
                                  (loop for c from (* set 4) below (* (1+ set) 4)
                                        collect (if (< c (length row)) (aref row c) 0d0)))))
              (multiple-value-bind (offset length) (%append-u16s builder joint-values)
                (setf (gethash (format nil "JOINTS_~d" set) attrs)
                      (%accessor-entry doc (%buffer-view-entry doc offset length 34962) 5123
                                       (/ (length joint-values) 4) "VEC4")))
              (setf (gethash (format nil "WEIGHTS_~d" set) attrs)
                    (%float-accessor doc builder weight-values (/ (length weight-values) 4) "VEC4" 34962))))))
      (loop for target across (sgeo.animation:mesh-morph-targets object) for target-index from 0 do
        (let ((entry (%obj)) (target-positions (sgeo.animation:morph-target-positions target))
              (target-normals (sgeo.animation:morph-target-normals target)))
          (multiple-value-bind (minimum maximum) (%position-bounds target-positions)
            (multiple-value-bind (offset length) (%append-floats builder (coerce target-positions 'list))
              (setf (gethash "POSITION" entry)
                    (%accessor-entry doc (%buffer-view-entry doc offset length 34962) 5126
                                     (/ (length target-positions) 3) "VEC3" :minimum minimum :maximum maximum))))
          (when target-normals
            (setf (gethash "NORMAL" entry)
                  (%float-accessor doc builder (coerce target-normals 'list)
                                   (/ (length target-normals) 3) "VEC3" 34962)))
          (let ((tangents (nth target-index (gethash :gltf-morph-tangents metadata))))
            (when tangents
              (unless (= (length tangents) (length target-positions)) (%fail "morph TANGENT incompatível com a fonte."))
              (setf (gethash "TANGENT" entry)
                    (%float-accessor doc builder tangents (/ (length tangents) 3) "VEC3" 34962))))
          (vector-push-extend entry targets)))
      (when (plusp (length targets)) (setf (gethash "targets" primitive) (coerce targets 'vector))))
    (multiple-value-bind (offset length component) (%append-indices builder indices)
      (setf (gethash "indices" primitive)
            (%accessor-entry doc (%buffer-view-entry doc offset length 34963) component (length indices) "SCALAR")))
    (setf (gethash "attributes" primitive) attrs)
    (let ((material (mesh-object-material object)))
      (when material
        (let ((material-index (position material materials :test #'eq)))
          (unless material-index
            (multiple-value-bind (new-index new-textures new-images)
                (%export-material material doc textures images)
              (setf material-index new-index textures new-textures images new-images
                    materials (concatenate 'vector materials (vector material)))))
          (setf (gethash "material" primitive) material-index))))
    (values primitive materials textures images)))
(defun %node-definition (object node-map mesh-index skin-index)
  (let* ((transform (scene-object-local-transform object))
         (position (sgeo.math:transform-position transform))
         (rotation (sgeo.math::quaternion-data (sgeo.math:transform-rotation transform)))
         (scale (sgeo.math:transform-scale transform))
         (entry (%obj "name" (object-name object)
                      "translation" (copy-seq position)
                      "rotation" (copy-seq rotation)
                      "scale" (copy-seq scale)))
         (children (scene-object-children object)))
    (when mesh-index (setf (gethash "mesh" entry) mesh-index))
    (when skin-index (setf (gethash "skin" entry) skin-index))
    (when (and mesh-index (typep object 'sgeo.animation:deformable-mesh-object)
               (plusp (length (sgeo.animation:mesh-morph-weights object))))
      (setf (gethash "weights" entry) (sgeo.animation:mesh-morph-weights object)))
    (when children
      (setf (gethash "children" entry)
            (map 'vector (lambda (child) (gethash child node-map)) children)))
    entry))
(defun %write-glb (pathname json-bytes binary)
  (let* ((json-padding (mod (- 4 (mod (length json-bytes) 4)) 4))
         (bin-padding (mod (- 4 (mod (length binary) 4)) 4))
         (total (+ 12 8 (+ (length json-bytes) json-padding) 8 (+ (length binary) bin-padding))))
    (with-open-file (out pathname :direction :output :if-exists :supersede
                         :element-type '(unsigned-byte 8))
      ;; Escreve o cabeçalho little-endian diretamente no fluxo binário.
      (file-position out 0)
      (write-sequence (vector #x67 #x6c #x54 #x46 2 0 0 0
                              (ldb (byte 8 0) total) (ldb (byte 8 8) total)
                              (ldb (byte 8 16) total) (ldb (byte 8 24) total)) out)
      (let ((length (+ (length json-bytes) json-padding)))
        (write-sequence (vector (ldb (byte 8 0) length) (ldb (byte 8 8) length)
                                (ldb (byte 8 16) length) (ldb (byte 8 24) length)
                                #x4a #x53 #x4f #x4e) out))
      (write-sequence json-bytes out)
      (dotimes (i json-padding) (declare (ignore i)) (write-byte #x20 out))
      (let ((length (+ (length binary) bin-padding)))
        (write-sequence (vector (ldb (byte 8 0) length) (ldb (byte 8 8) length)
                                (ldb (byte 8 16) length) (ldb (byte 8 24) length)
                                #x42 #x49 #x4e #x00) out))
      (write-sequence binary out)
      (dotimes (i bin-padding) (declare (ignore i)) (write-byte 0 out)))))
(defun %key-components (value)
  (cond ((sgeo.math::quaternion-p value) (coerce (sgeo.math::quaternion-data value) 'list))
        ((and (vectorp value) (not (stringp value))) (coerce value 'list))
        ((numberp value) (list value))
        ((listp value) value)
        (t (%fail "valor de animação não exportável: ~s." value))))
(defun %export-track (track node-map doc builder)
  (unless (typep track 'sgeo.animation:property-track)
    (%fail "trilhas de evento não são representáveis por glTF."))
  (let* ((target (sgeo.animation:track-target track))
         (node-index (gethash target node-map))
         (head (first (sgeo.animation:track-path track)))
         (path (cond ((member head '(:position :translation)) "translation")
                     ((eq head :rotation) "rotation") ((eq head :scale) "scale")
                     ((eq head :weights) "weights")
                     (t (%fail "caminho de animação não representável: ~s." head))))
         (keys (sgeo.animation:track-keys track))
         (interpolation (sgeo.animation:track-interpolation track))
         (cubic (eq interpolation :cubic-spline))
         (times (mapcar #'first keys))
         (weightp (string= path "weights"))
         (width (if weightp (length (second (first keys))) (length (%key-components (second (first keys))))))
         (values-flat nil) (shape (if (and weightp (plusp width)) "SCALAR" (format nil "VEC~d" width)))
         (animation-sampler nil) (animation-channel nil))
    (unless node-index (%fail "alvo de animação fora da hierarquia exportada."))
    (unless (= (length (sgeo.animation:track-path track)) 1)
      (%fail "glTF exige um canal completo de transformação ou de pesos."))
    (when (some (lambda (easing) (not (member easing '(nil :linear))))
                (sgeo.animation:track-easings track))
      (%fail "easing Lisp precisa ser amostrado antes de exportar para glTF."))
    (unless (and (plusp (length keys)) (member interpolation '(:step :linear :cubic-spline)))
      (%fail "trilha de animação sem chaves ou com interpolação inválida."))
    (when (and weightp (not (typep target 'sgeo.animation:deformable-mesh-object)))
      (%fail "alvo de morph weights não é uma malha deformável."))
    (setf values-flat
          (loop for key in keys append
                (if cubic
                    (append (%key-components (third key)) (%key-components (second key))
                            (%key-components (fourth key)))
                    (%key-components (second key)))))
    (let* ((time-min (reduce #'min times)) (time-max (reduce #'max times))
           (time-accessor (multiple-value-bind (offset length) (%append-floats builder times)
                            (%accessor-entry doc (%buffer-view-entry doc offset length) 5126
                                             (length times) "SCALAR" :minimum (list time-min) :maximum (list time-max))))
           (output-count (if weightp (* (length times) width (if cubic 3 1))
                             (* (length times) (if cubic 3 1))))
           (output-accessor (%float-accessor doc builder values-flat output-count shape)))
      (setf animation-sampler (%obj "input" time-accessor
                                    "output" output-accessor
                                    "interpolation" (case interpolation
                                                      (:step "STEP") (:linear "LINEAR")
                                                      (:cubic-spline "CUBICSPLINE")))
            animation-channel (%obj "sampler" 0 "target" (%obj "node" node-index "path" path)))
      (values animation-sampler animation-channel))))
(defun %export-animations (world node-map doc builder)
  (let* ((state (sgeo.scene:world-animation-state world))
         (clips (and state (sgeo.animation:animation-state-clips state)))
         (animations (make-array 0 :adjustable t :fill-pointer 0)))
    (dolist (clip clips)
      (let ((samplers (make-array 0 :adjustable t :fill-pointer 0))
            (channels (make-array 0 :adjustable t :fill-pointer 0)))
        (dolist (track (sgeo.animation:clip-tracks clip))
          (multiple-value-bind (sampler channel) (%export-track track node-map doc builder)
            (setf (gethash "sampler" channel) (length samplers))
            (vector-push-extend sampler samplers)
            (vector-push-extend channel channels)))
        (when (plusp (length channels))
          (vector-push-extend (%obj "name" (or (sgeo.animation::%clip-name clip) "Animation")
                                    "samplers" (coerce samplers 'vector)
                                    "channels" (coerce channels 'vector)) animations))))
    (when (plusp (length animations)) (setf (gethash "animations" doc) (coerce animations 'vector)))))
(defun %encode-json (document stream)
  "Escapa todos os controles C0, inclusive em versões antigas do YASON."
  (let ((yason::*char-replacements* (let ((copy (make-hash-table)))
                                      (maphash (lambda (key value) (setf (gethash key copy) value))
                                               yason::*char-replacements*) copy)))
    (dotimes (code 32)
      (setf (gethash (code-char code) yason::*char-replacements*)
            (format nil "\\u~4,'0X" code)))
    (yason:encode document stream)))

(defun export-gltf (world pathname &key binary)
  "Exporta o mundo para glTF JSON com buffer externo ou para GLB binário."
  (let* ((objects (remove (world-root world) (%world-objects world) :test #'eq))
         (mesh-objects (remove-if-not (lambda (object) (typep object 'sgeo.scene:mesh-object)) objects))
         (node-map (make-hash-table :test #'eq))
         (doc (%obj "asset" (%obj "version" "2.0" "generator" "S-Geometry/CL")))
         (builder (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
         (materials #()) (textures #()) (images #()) (mesh-index-map (make-hash-table :test #'eq))
         (skin-index-map (make-hash-table :test #'eq)) (skeletons nil)
         (meshes (make-array 0 :adjustable t :fill-pointer 0)) (nodes nil))
    (loop for object in objects for i from 0 do (setf (gethash object node-map) i))
    (dolist (object mesh-objects)
      (when (and (typep object 'sgeo.animation:deformable-mesh-object)
                 (sgeo.animation:mesh-skeleton object))
        (let ((skeleton (sgeo.animation:mesh-skeleton object)))
          (unless (gethash skeleton skin-index-map)
            (setf (gethash skeleton skin-index-map) (length skeletons))
            (push skeleton skeletons)))))
    (setf skeletons (nreverse skeletons))
    (loop for object in skeletons for index from 0 do (setf (gethash object skin-index-map) index))
    (loop for object in mesh-objects for index from 0 do
      (multiple-value-bind (primitive new-materials new-textures new-images)
          (%export-primitive object doc builder materials textures images)
        (setf materials new-materials textures new-textures images new-images
              (gethash object mesh-index-map) index)
        (let ((mesh (%obj "name" (object-name object) "primitives" (vector primitive))))
          (when (and (typep object 'sgeo.animation:deformable-mesh-object)
                     (plusp (length (sgeo.animation:mesh-morph-weights object))))
            (setf (gethash "weights" mesh) (sgeo.animation:mesh-morph-weights object)))
          (vector-push-extend mesh meshes))))
    (setf nodes
          (map 'vector (lambda (object)
                         (%node-definition object node-map (gethash object mesh-index-map)
                           (when (and (typep object 'sgeo.animation:deformable-mesh-object)
                                      (sgeo.animation:mesh-skeleton object))
                             (gethash (sgeo.animation:mesh-skeleton object) skin-index-map)))) objects))
    (setf (gethash "nodes" doc) nodes
          (gethash "scenes" doc) (vector (%obj "nodes"
                                                (coerce (loop for object in (%object-children (world-root world))
                                                              collect (gethash object node-map)) 'vector)))
          (gethash "scene" doc) 0
          (gethash "meshes" doc) (coerce meshes 'vector)
          (gethash "buffers" doc) (vector (%obj "byteLength" (length builder))))
    (when (plusp (length skeletons))
      (setf (gethash "skins" doc)
            (map 'vector
                 (lambda (skeleton)
                   (let* ((joints (sgeo.animation:skeleton-joints skeleton))
                          (matrices (sgeo.animation:skeleton-inverse-bind-matrices skeleton))
                          (flat (loop for matrix across matrices append (coerce matrix 'list)))
                          (accessor (%float-accessor doc builder flat (length joints) "MAT4")))
                     (%obj "name" "Skin" "joints" (map 'vector (lambda (joint)
                                                                        (or (gethash joint node-map)
                                                                            (%fail "articulação do skin fora do mundo exportado."))) joints)
                           "inverseBindMatrices" accessor
                           "skeleton" (or (gethash (sgeo.animation:skeleton-root skeleton) node-map)
                                          (gethash (aref joints 0) node-map))))) skeletons)))
    (%export-animations world node-map doc builder)
    (setf (gethash "byteLength" (aref (gethash "buffers" doc) 0)) (length builder))
    (when (plusp (length textures)) (setf (gethash "textures" doc) textures))
    (when (plusp (length images)) (setf (gethash "images" doc) images))
    (remhash "__sgeo_texture_libraries" doc)
    (when binary
      (remhash "uri" (aref (gethash "buffers" doc) 0)))
    (if binary
        (let* ((json-string (with-output-to-string (out) (%encode-json doc out)))
               (json-bytes (sb-ext:string-to-octets json-string :external-format :utf-8)))
          (%write-glb pathname json-bytes builder))
        (let* ((bin-path (make-pathname :type "bin" :defaults pathname))
               (uri (file-namestring bin-path))
               (json-path (if (equal (pathname-type pathname) "gltf") pathname
                              (make-pathname :type "gltf" :defaults pathname))))
          (setf (gethash "uri" (aref (gethash "buffers" doc) 0)) uri)
          (with-open-file (out bin-path :direction :output :if-exists :supersede
                               :element-type '(unsigned-byte 8))
            (write-sequence builder out))
          (with-open-file (out json-path :direction :output :if-exists :supersede
                               :external-format :utf-8)
            (%encode-json doc out))))
    pathname))
