(in-package #:sgeo.math)

(deftype vec2 () '(simple-array double-float (2)))
(deftype vec3 () '(simple-array double-float (3)))
(deftype vec4 () '(simple-array double-float (4)))
(deftype mat4 () '(simple-array double-float (16)))

(defun %number (value context)
  (unless (realp value)
    (error 'validation-error :context context
           :message (format nil "Esperava um número real, mas recebeu ~S." value)))
  (coerce value 'double-float))

(defun %vec (value size context)
  (unless (and (typep value 'array) (= (array-rank value) 1)
               (= (length value) size))
    (error 'validation-error :context context
           :message (format nil "Esperava um vetor com ~D componentes." size)))
  (make-array size :element-type 'double-float
              :initial-contents (loop for i below size collect (%number (aref value i) context))))

(defun %vector-p (value size)
  (and (typep value 'array) (= (array-rank value) 1) (= (length value) size)
       (loop for component across value always (realp component))))

(defun %make-vector (size values context)
  (make-array size :element-type 'double-float
              :initial-contents (loop for value in values collect (%number value context))))

(defun make-vec2 (&optional (x 0d0) (y 0d0))
  "Cria um vetor bidimensional em precisão dupla."
  (%make-vector 2 (list x y) "vec2"))
(defun make-vec3 (&optional (x 0d0) (y 0d0) (z 0d0))
  "Cria um vetor tridimensional em precisão dupla."
  (%make-vector 3 (list x y z) "vec3"))
(defun make-vec4 (&optional (x 0d0) (y 0d0) (z 0d0) (w 0d0))
  "Cria um vetor de quatro componentes em precisão dupla."
  (%make-vector 4 (list x y z w) "vec4"))
(defun vec2 (&optional (x 0d0) (y 0d0)) "Cria um vec2 a partir de duas componentes." (make-vec2 x y))
(defun vec3 (&optional (x 0d0) (y 0d0) (z 0d0)) "Cria um vec3 a partir de três componentes." (make-vec3 x y z))
(defun vec4 (&optional (x 0d0) (y 0d0) (z 0d0) (w 0d0)) "Cria um vec4 a partir de quatro componentes." (make-vec4 x y z w))

(defun vx (vector) "Retorna a primeira componente de um vetor." (aref vector 0))
(defun vy (vector) "Retorna a segunda componente de um vetor." (aref vector 1))
(defun vz (vector) "Retorna a terceira componente de um vetor." (aref vector 2))
(defun vw (vector) "Retorna a quarta componente de um vetor." (aref vector 3))

(defun %check-same-size (a b operation)
  (unless (and (typep a 'array) (= (array-rank a) 1)
               (typep b 'array) (= (array-rank b) 1)
               (= (length a) (length b)) (member (length a) '(2 3 4))
               (loop for component across a always (realp component))
               (loop for component across b always (realp component)))
    (error 'validation-error :context operation
           :message "Os argumentos precisam ser vetores do mesmo tamanho (2, 3 ou 4).")))

(defun v+ (a b)
  "Soma componente a componente dois vetores do mesmo tamanho."
  (%check-same-size a b "v+")
  (%make-vector (length a) (loop for i below (length a) collect (+ (aref a i) (aref b i))) "v+"))
(defun v- (a b)
  "Subtrai componente a componente dois vetores do mesmo tamanho."
  (%check-same-size a b "v-")
  (%make-vector (length a) (loop for i below (length a) collect (- (aref a i) (aref b i))) "v-"))
(defun v* (a b)
  "Multiplica vetores componente a componente ou um vetor por escalar."
  (cond ((and (numberp a) (typep b 'array) (= (array-rank b) 1) (member (length b) '(2 3 4)))
         (%make-vector (length b) (loop for x across b collect (* (%number a "v*") x)) "v*"))
        ((and (numberp b) (typep a 'array) (= (array-rank a) 1))
         (%make-vector (length a) (loop for x across a collect (* x (%number b "v*"))) "v*"))
        (t (%check-same-size a b "v*")
           (%make-vector (length a) (loop for i below (length a) collect (* (aref a i) (aref b i))) "v*"))))
(defun %write-vector (destination result operation)
  (%check-same-size destination result operation)
  (dotimes (i (length destination) destination) (setf (aref destination i) (aref result i))))
(defun v+! (destination a b) "Soma vetores e grava o resultado no vetor de destino." (%write-vector destination (v+ a b) "v+!"))
(defun v-! (destination a b) "Subtrai vetores e grava o resultado no vetor de destino." (%write-vector destination (v- a b) "v-!"))
(defun v*! (destination a b) "Multiplica vetores e grava o resultado no vetor de destino." (%write-vector destination (v* a b) "v*!"))

(defun dot (a b)
  "Retorna o produto escalar de dois vetores."
  (%check-same-size a b "dot")
  (loop for i below (length a) sum (* (aref a i) (aref b i)) double-float))
(defun cross (a b)
  "Retorna o produto vetorial de dois vec3."
  (unless (and (%vector-p a 3) (%vector-p b 3))
    (error 'validation-error :context "cross" :message "O produto vetorial exige dois vec3."))
  (make-vec3 (- (* (vy a) (vz b)) (* (vz a) (vy b)))
             (- (* (vz a) (vx b)) (* (vx a) (vz b)))
             (- (* (vx a) (vy b)) (* (vy a) (vx b)))))
(defun vector-length (vector)
  "Retorna o comprimento euclidiano de um vetor."
  (unless (and (typep vector 'array) (= (array-rank vector) 1) (member (length vector) '(2 3 4)))
    (error 'validation-error :context "vector-length" :message "Esperava vec2, vec3 ou vec4."))
  (sqrt (dot vector vector)))
(defun normalize (vector)
  "Retorna uma cópia unitária do vetor; sinaliza erro para o vetor nulo."
  (let ((length (vector-length vector)))
    (when (<= length 1d-15)
      (error 'math-error :context "normalize" :message "Não é possível normalizar o vetor nulo."))
    (v* vector (/ 1d0 length))))

(defun make-mat4 (&optional values)
  "Cria uma matriz 4x4 em coluna-major; aceita 16 valores lineares."
  (let ((values (or values (make-array 16 :initial-element 0d0))))
    (unless (and (typep values 'array) (= (array-rank values) 1) (= (length values) 16))
      (error 'validation-error :context "mat4" :message "A matriz precisa conter 16 valores."))
    (%vec values 16 "mat4")))
(defun mat4 (values) "Cria uma matriz 4x4 coluna-major a partir de 16 valores." (make-mat4 values))
(defun identity-mat4 ()
  "Cria a matriz identidade 4x4."
  (let ((m (make-mat4))) (dotimes (i 4 m) (setf (aref m (+ i (* i 4))) 1d0))))
(defun translation-mat4 (&optional (x (make-vec3)) y z)
  "Cria uma matriz de translação a partir de vec3 ou de três componentes."
  (let ((translation
          (cond ((and (null y) (null z) (%vector-p x 3)) x)
                ((and (realp x) (realp y) (realp z)) (make-vec3 x y z))
                (t (error 'validation-error :context "translation-mat4"
                          :message "Esperava vec3 ou três componentes reais.")))))
    (let ((m (identity-mat4)))
      (dotimes (i 3 m) (setf (aref m (+ 12 i)) (aref translation i))))))
(defun scaling-mat4 (&optional (x 1d0) y z)
  "Cria uma matriz de escala a partir de vec3, escalar ou três componentes."
  (let ((v (cond ((and (null y) (null z) (%vector-p x 3)) x)
                 ((and (realp x) (null y) (null z)) (make-vec3 x x x))
                 ((and (realp x) (realp y) (realp z)) (make-vec3 x y z))
                 (t (error 'validation-error :context "scaling-mat4"
                           :message "Esperava vec3, escalar ou três componentes reais.")))))
    (let ((m (identity-mat4)))
      (dotimes (i 3 m) (setf (aref m (+ i (* i 4))) (%number (aref v i) "scaling-mat4"))))))

(defstruct (quaternion (:constructor %make-quaternion (data))) (data #() :type (simple-array double-float (4))))
(defun make-quaternion (&optional (x 0d0) (y 0d0) (z 0d0) (w 1d0))
  "Cria um quaternion na ordem x, y, z, w."
  (%make-quaternion (%make-vector 4 (list x y z w) "quaternion")))
(defun %qdata (q)
  (unless (quaternion-p q) (error 'validation-error :context "quaternion" :message "Esperava um quaternion."))
  (quaternion-data q))
(defun quaternion-from-axis-angle (axis angle)
  "Cria rotação a partir de eixo vec3 e ângulo em radianos."
  (unless (%vector-p axis 3) (error 'validation-error :context "quaternion-from-axis-angle" :message "O eixo precisa ser vec3."))
  (let* ((unit (normalize axis)) (half (/ (%number angle "ângulo") 2d0)) (s (sin half)))
    (make-quaternion (* (vx unit) s) (* (vy unit) s) (* (vz unit) s) (cos half))))
(defun quaternion-multiply (a b)
  "Compõe dois quaternions com produto de Hamilton, aplicando b antes de a."
  (let* ((x1 (aref (%qdata a) 0)) (y1 (aref (%qdata a) 1)) (z1 (aref (%qdata a) 2)) (w1 (aref (%qdata a) 3))
         (x2 (aref (%qdata b) 0)) (y2 (aref (%qdata b) 1)) (z2 (aref (%qdata b) 2)) (w2 (aref (%qdata b) 3)))
    (make-quaternion (+ (* w1 x2) (* x1 w2) (* y1 z2) (- (* z1 y2)))
                     (+ (* w1 y2) (- (* x1 z2)) (* y1 w2) (* z1 x2))
                     (+ (* w1 z2) (* x1 y2) (- (* y1 x2)) (* z1 w2))
                     (- (* w1 w2) (* x1 x2) (* y1 y2) (* z1 z2)))))
(defun quaternion-normalize (q)
  "Retorna uma cópia unitária do quaternion."
  (let* ((v (%qdata q)) (length (sqrt (loop for x across v sum (* x x) double-float))))
    (when (<= length 1d-15) (error 'math-error :context "quaternion-normalize" :message "Não é possível normalizar o quaternion nulo."))
    (apply #'make-quaternion (loop for x across v collect (/ x length)))))
(defun quaternion->mat4 (q)
  "Converte quaternion para matriz de rotação coluna-major."
  (let* ((q (quaternion-normalize q)) (x (aref (%qdata q) 0)) (y (aref (%qdata q) 1))
         (z (aref (%qdata q) 2)) (w (aref (%qdata q) 3)) (m (identity-mat4)))
    (setf (aref m 0) (- 1d0 (* 2d0 (+ (* y y) (* z z))))
          (aref m 1) (* 2d0 (+ (* x y) (* z w)))
          (aref m 2) (* 2d0 (- (* x z) (* y w)))
          (aref m 4) (* 2d0 (- (* x y) (* z w)))
          (aref m 5) (- 1d0 (* 2d0 (+ (* x x) (* z z))))
          (aref m 6) (* 2d0 (+ (* y z) (* x w)))
          (aref m 8) (* 2d0 (+ (* x z) (* y w)))
          (aref m 9) (* 2d0 (- (* y z) (* x w)))
          (aref m 10) (- 1d0 (* 2d0 (+ (* x x) (* y y)))))
    m))
(defun %rotation-mat4 (axis angle)
  (let ((c (cos (%number angle "ângulo"))) (s (sin (%number angle "ângulo"))) (m (identity-mat4)))
    (ecase axis
      (:x (setf (aref m 5) c (aref m 6) s (aref m 9) (- s) (aref m 10) c))
      (:y (setf (aref m 0) c (aref m 2) (- s) (aref m 8) s (aref m 10) c))
      (:z (setf (aref m 0) c (aref m 1) s (aref m 4) (- s) (aref m 5) c)))
    m))
(defun rotation-x-mat4 (angle) "Cria rotação em torno do eixo X, em radianos." (%rotation-mat4 :x angle))
(defun rotation-y-mat4 (angle) "Cria rotação em torno do eixo Y, em radianos." (%rotation-mat4 :y angle))
(defun rotation-z-mat4 (angle) "Cria rotação em torno do eixo Z, em radianos." (%rotation-mat4 :z angle))

(defun %mat (matrix context)
  (unless (and (typep matrix 'array) (= (array-rank matrix) 1) (= (length matrix) 16)
               (loop for component across matrix always (realp component)))
    (error 'validation-error :context context :message "Esperava mat4 com 16 valores reais."))
  matrix)
(defun mat* (a b)
  "Multiplica mat4 por mat4 ou transforma vec4, usando vetores-coluna."
  (%mat a "mat*")
  (cond ((and (typep b 'array) (= (array-rank b) 1) (= (length b) 16))
         (let ((out (make-mat4)))
           (dotimes (col 4 out)
             (dotimes (row 4)
               (setf (aref out (+ row (* col 4)))
                     (loop for k below 4 sum (* (aref a (+ row (* k 4))) (aref b (+ k (* col 4)))) double-float))))))
        ((%vector-p b 4)
         (apply #'make-vec4
                (loop for row below 4 collect (loop for k below 4 sum (* (aref a (+ row (* k 4))) (aref b k)) double-float))))
        (t (error 'validation-error :context "mat*" :message "O segundo argumento precisa ser mat4 ou vec4."))))
(defun inverse-mat4 (matrix)
  "Inverte mat4 por eliminação de Gauss-Jordan; sinaliza matrizes singulares."
  (%mat matrix "inverse-mat4")
  (let ((a (make-array '(4 8) :element-type 'double-float :initial-element 0d0)))
    (dotimes (row 4)
      (dotimes (col 4) (setf (aref a row col) (aref matrix (+ row (* col 4)))))
      (setf (aref a row (+ 4 row)) 1d0))
    (dotimes (col 4)
      (let ((pivot-row (loop with best = col with best-value = (abs (aref a col col))
                             for row from (1+ col) below 4
                             when (> (abs (aref a row col)) best-value)
                               do (setf best row best-value (abs (aref a row col)))
                             finally (return best))))
        (when (zerop (aref a pivot-row col))
          (error 'math-error :context "inverse-mat4" :message "A matriz é singular e não possui inversa."))
        (unless (= pivot-row col)
          (dotimes (j 8) (rotatef (aref a pivot-row j) (aref a col j))))
        (let ((pivot (aref a col col)))
          (dotimes (j 8) (setf (aref a col j) (/ (aref a col j) pivot))))
        (dotimes (row 4)
          (unless (= row col)
            (let ((factor (aref a row col)))
              (dotimes (j 8) (decf (aref a row j) (* factor (aref a col j)))))))))
    (let ((out (make-mat4)))
      (dotimes (row 4 out) (dotimes (col 4) (setf (aref out (+ row (* col 4))) (aref a row (+ 4 col))))))))
(defun transform-point (matrix point)
  "Transforma vec3 como ponto e divide pelas coordenadas homogêneas."
  (%mat matrix "transform-point")
  (unless (%vector-p point 3) (error 'validation-error :context "transform-point" :message "Esperava vec3."))
  (let ((out (mat* matrix (make-vec4 (vx point) (vy point) (vz point) 1d0))))
    (when (<= (abs (vw out)) 1d-15) (error 'math-error :context "transform-point" :message "O ponto foi transformado para w igual a zero."))
    (make-vec3 (/ (vx out) (vw out)) (/ (vy out) (vw out)) (/ (vz out) (vw out)))))
(defun transform-direction (matrix direction)
  "Transforma vec3 como direção, ignorando translação."
  (%mat matrix "transform-direction")
  (unless (%vector-p direction 3) (error 'validation-error :context "transform-direction" :message "Esperava vec3."))
  (let ((out (mat* matrix (make-vec4 (vx direction) (vy direction) (vz direction) 0d0))))
    (make-vec3 (vx out) (vy out) (vz out))))
(defun perspective-mat4 (fov-y aspect near far)
  "Cria projeção perspectiva RH com câmera voltada para -Z e NDC OpenGL."
  (let ((fov (%number fov-y "perspective-mat4")) (aspect (%number aspect "perspective-mat4"))
        (near (%number near "perspective-mat4")) (far (%number far "perspective-mat4")))
    (unless (and (> fov 0d0) (< fov pi) (> aspect 0d0) (> near 0d0) (> far near))
      (error 'math-error :context "perspective-mat4" :message "Exige 0 < fov < pi, aspecto positivo e 0 < near < far."))
    (let* ((f (/ 1d0 (tan (/ fov 2d0)))) (m (make-mat4)))
      (setf (aref m 0) (/ f aspect) (aref m 5) f
            (aref m 10) (/ (+ far near) (- near far))
            (aref m 11) -1d0
            (aref m 14) (/ (* 2d0 far near) (- near far)))
      m)))
(defun orthographic-mat4 (left right bottom top near far)
  "Cria uma projeção ortográfica RH com planos perto e longe positivos."
  (let ((left (%number left "orthographic-mat4"))
        (right (%number right "orthographic-mat4"))
        (bottom (%number bottom "orthographic-mat4"))
        (top (%number top "orthographic-mat4"))
        (near (%number near "orthographic-mat4"))
        (far (%number far "orthographic-mat4")))
    (unless (and (< left right) (< bottom top) (>= near 0d0) (> far near))
      (error 'math-error :context "orthographic-mat4"
             :message "Os limites precisam ser ordenados e satisfazer 0 <= perto < longe."))
    (let ((matrix (make-mat4)))
      (setf (aref matrix 0) (/ 2d0 (- right left))
            (aref matrix 5) (/ 2d0 (- top bottom))
            (aref matrix 10) (/ -2d0 (- far near))
            (aref matrix 12) (- (/ (+ right left) (- right left)))
            (aref matrix 13) (- (/ (+ top bottom) (- top bottom)))
            (aref matrix 14) (- (/ (+ far near) (- far near)))
            (aref matrix 15) 1d0)
      matrix)))
(defun look-at-mat4 (eye target up)
  "Cria view matrix RH para câmera em eye olhando target, com up aproximado."
  (unless (and (%vector-p eye 3) (%vector-p target 3) (%vector-p up 3))
    (error 'validation-error :context "look-at-mat4" :message "eye, target e up precisam ser vec3."))
  (let* ((forward (normalize (v- target eye)))
         (side (normalize (cross forward up)))
         (actual-up (cross side forward))
         (m (identity-mat4)))
    (setf (aref m 0) (vx side) (aref m 4) (vy side) (aref m 8) (vz side)
          (aref m 1) (vx actual-up) (aref m 5) (vy actual-up) (aref m 9) (vz actual-up)
          (aref m 2) (- (vx forward)) (aref m 6) (- (vy forward)) (aref m 10) (- (vz forward))
          (aref m 12) (- (dot side eye)) (aref m 13) (- (dot actual-up eye))
          (aref m 14) (dot forward eye))
    m))

(defstruct (transform (:constructor %make-transform (position rotation scale)))
  (position (make-vec3) :type (simple-array double-float (3)))
  (rotation (make-quaternion) :type quaternion)
  (scale (make-vec3 1d0 1d0 1d0) :type (simple-array double-float (3))))
(defun make-transform (&key (position (make-vec3)) (rotation (make-quaternion)) (scale (make-vec3 1d0 1d0 1d0)))
  "Cria transformação afim; a matriz resultante aplica escala, rotação e translação."
  (unless (%vector-p position 3) (error 'validation-error :context "make-transform" :message "position precisa ser vec3."))
  (unless (quaternion-p rotation) (error 'validation-error :context "make-transform" :message "rotation precisa ser quaternion."))
  (unless (%vector-p scale 3) (error 'validation-error :context "make-transform" :message "scale precisa ser vec3."))
  (%make-transform (%vec position 3 "posição") (quaternion-normalize rotation) (%vec scale 3 "escala")))
(defun transform-matrix (transform)
  "Retorna a matriz coluna-major da transformação afim."
  (unless (transform-p transform) (error 'validation-error :context "transform-matrix" :message "Esperava transform."))
  (mat* (translation-mat4 (transform-position transform))
        (mat* (quaternion->mat4 (transform-rotation transform)) (scaling-mat4 (transform-scale transform)))))

(defstruct (ray (:constructor %make-ray (origin direction)))
  (origin (make-vec3) :type (simple-array double-float (3)))
  (direction (make-vec3 0d0 0d0 -1d0) :type (simple-array double-float (3))))
(defun make-ray (origin direction)
  "Cria raio com direção normalizada, para que parâmetros t sejam distâncias."
  (unless (and (%vector-p origin 3) (%vector-p direction 3))
    (error 'validation-error :context "make-ray" :message "Origem e direção precisam ser vec3."))
  (%make-ray (%vec origin 3 "raio") (normalize direction)))

(defstruct (aabb (:constructor %make-aabb (min max)))
  (min (make-vec3) :type (simple-array double-float (3)))
  (max (make-vec3) :type (simple-array double-float (3))))
(defun make-aabb (min max)
  "Cria caixa alinhada aos eixos e valida que min não exceda max."
  (unless (and (%vector-p min 3) (%vector-p max 3))
    (error 'validation-error :context "make-aabb" :message "min e max precisam ser vec3."))
  (dotimes (i 3)
    (when (> (aref min i) (aref max i))
      (error 'validation-error :context "make-aabb" :message "Cada componente de min deve ser menor ou igual à de max.")))
  (%make-aabb (%vec min 3 "aabb") (%vec max 3 "aabb")))
(defun aabb-union (a b)
  "Retorna a menor caixa alinhada que contém as duas caixas."
  (unless (and (aabb-p a) (aabb-p b)) (error 'validation-error :context "aabb-union" :message "Esperava duas caixas AABB."))
  (make-aabb (make-vec3 (min (vx (aabb-min a)) (vx (aabb-min b))) (min (vy (aabb-min a)) (vy (aabb-min b))) (min (vz (aabb-min a)) (vz (aabb-min b))))
             (make-vec3 (max (vx (aabb-max a)) (vx (aabb-max b))) (max (vy (aabb-max a)) (vy (aabb-max b))) (max (vz (aabb-max a)) (vz (aabb-max b))))))
(defun transform-aabb (box matrix-or-transform)
  "Transforma os oito cantos da caixa e retorna seus novos limites alinhados."
  (unless (aabb-p box) (error 'validation-error :context "transform-aabb" :message "Esperava AABB."))
  (let ((matrix (if (transform-p matrix-or-transform) (transform-matrix matrix-or-transform) matrix-or-transform))
        (minimum (make-vec3 most-positive-double-float most-positive-double-float most-positive-double-float))
        (maximum (make-vec3 most-negative-double-float most-negative-double-float most-negative-double-float)))
    (%mat matrix "transform-aabb")
    (dotimes (mask 8)
      (let* ((point (make-vec3 (if (logbitp 0 mask) (vx (aabb-max box)) (vx (aabb-min box)))
                               (if (logbitp 1 mask) (vy (aabb-max box)) (vy (aabb-min box)))
                               (if (logbitp 2 mask) (vz (aabb-max box)) (vz (aabb-min box)))))
             (result (transform-point matrix point)))
        (dotimes (i 3) (setf (aref minimum i) (min (aref minimum i) (aref result i))
                             (aref maximum i) (max (aref maximum i) (aref result i))))))
    (make-aabb minimum maximum)))
(defun ray-aabb-intersection (ray box)
  "Retorna a distância de entrada do raio na caixa ou NIL quando não há acerto."
  (unless (and (ray-p ray) (aabb-p box)) (error 'validation-error :context "ray-aabb-intersection" :message "Esperava raio e AABB."))
  (let ((near 0d0) (far most-positive-double-float))
    (dotimes (axis 3)
      (let ((origin (aref (ray-origin ray) axis)) (direction (aref (ray-direction ray) axis))
            (minimum (aref (aabb-min box) axis)) (maximum (aref (aabb-max box) axis)))
        (if (<= (abs direction) 1d-15)
            (when (or (< origin minimum) (> origin maximum)) (return-from ray-aabb-intersection nil))
            (let* ((t1 (/ (- minimum origin) direction)) (t2 (/ (- maximum origin) direction))
                   (entry (min t1 t2)) (exit (max t1 t2)))
              (setf near (max near entry) far (min far exit))
              (when (> near far) (return-from ray-aabb-intersection nil))))))
    near))
(defun ray-triangle-intersection (ray v0 v1 v2)
  "Retorna distância de interseção Möller–Trumbore, em duas faces, ou NIL."
  (unless (and (ray-p ray) (%vector-p v0 3) (%vector-p v1 3) (%vector-p v2 3))
    (error 'validation-error :context "ray-triangle-intersection" :message "Esperava raio e três vec3."))
  (let* ((edge1 (v- v1 v0)) (edge2 (v- v2 v0)) (p (cross (ray-direction ray) edge2))
         (det (dot edge1 p)))
    (when (<= (abs det) (* 1d-15 (vector-length edge1) (vector-length edge2)))
      (return-from ray-triangle-intersection nil))
    (let* ((inverse (/ 1d0 det)) (offset (v- (ray-origin ray) v0))
           (u (* inverse (dot offset p))))
      (when (or (< u 0d0) (> u 1d0)) (return-from ray-triangle-intersection nil))
      (let* ((q (cross offset edge1)) (v (* inverse (dot (ray-direction ray) q))))
        (when (or (< v 0d0) (> (+ u v) 1d0)) (return-from ray-triangle-intersection nil))
        (let ((distance (* inverse (dot edge2 q))))
          (when (>= distance 0d0) distance))))))
