(in-package #:sgeo.animation)

;;; Clipes, estado de reprodução, mistura em camadas e avanço de eventos.

(defclass animation-clip ()
  ((name :initarg :name :initform nil :accessor %clip-name)
   (tracks :initarg :tracks :initform nil :accessor clip-tracks)
   (duration :initarg :duration :initform nil :reader clip-duration)))
(defclass animation-state ()
  ((world :initarg :world :reader %state-world)
   (clips :initform nil :accessor animation-state-clips)
   (players :initform nil :accessor animation-state-players)
   (time :initform 0d0 :accessor animation-state-time)
   (references :initform (make-hash-table :test 'equal) :reader %state-references)))
(defclass animation-player ()
  ((world :initarg :world :reader %player-world)
   (clip :initarg :clip :reader player-clip)
   (time :initarg :time :initform 0d0 :reader player-time)
   (weight :initarg :weight :initform 1d0 :reader player-weight)
   (speed :initarg :speed :initform 1d0 :reader player-speed)
   (looping-p :initarg :looping-p :initform t :accessor player-looping-p)
   (playing-p :initform t :accessor player-playing-p)
   (enabled-p :initform t :accessor %player-enabled-p)
   (seeking-p :initform nil :accessor %player-seeking-p)
   (additive-p :initarg :additive-p :initform nil :accessor player-additive-p)
   (mask :initarg :mask :initform nil :accessor player-mask)
   (root-motion-target :initarg :root-motion-target :initform nil :reader %player-root-target)
   (root-motion-joint :initarg :root-motion-joint :initform nil :reader %player-root-joint)))

(defun (setf clip-duration) (value clip)
  (unless (and (%finite-real-p value) (not (minusp value)))
    (error "Duração do clipe precisa ser finita e não negativa."))
  (setf (slot-value clip 'duration) (coerce value 'double-float)))

(defun (setf player-weight) (value player)
  (unless (and (%finite-real-p value) (not (minusp value)))
    (error "Peso do player precisa ser finito e não negativo."))
  (setf (slot-value player 'weight) (coerce value 'double-float)))
(defun (setf player-speed) (value player)
  (unless (%finite-real-p value) (error "Velocidade do player precisa ser finita."))
  (setf (slot-value player 'speed) (coerce value 'double-float)))
(defun (setf player-time) (value player)
  (unless (and (%finite-real-p value) (not (minusp value)))
    (error "Tempo do player precisa ser finito e não negativo."))
  (setf (slot-value player 'time) (coerce value 'double-float)))

(defvar *animation-event-handler* nil
  "Função dinâmica opcional chamada para eventos sem handler próprio.")
(defvar *pending-animation-events* :disabled)

(defun make-animation-clip (&key name tracks duration)
  "Cria um clipe inspecionável; a duração padrão cobre todas as trilhas."
  (unless (every (lambda (track) (or (typep track 'property-track)
                                     (typep track 'event-track))) tracks)
    (error "Clipes só aceitam trilhas de propriedade ou de eventos."))
    (let* ((derived (loop for track in tracks
                        maximize (cond ((typep track 'property-track)
                                        (first (car (last (track-keys track)))))
                                       ((typep track 'event-track)
                                        (if (%event-track-events track)
                                            (first (car (last (%event-track-events track))))
                                            0d0))
                                       (t 0d0)) into maximum
                        finally (return (or maximum 0d0)))))
    (unless (or (null duration)
                (and (%finite-real-p duration) (not (minusp duration))))
      (error "Duração do clipe precisa ser finita e não negativa."))
    (make-instance 'animation-clip :name name :tracks (copy-list tracks)
                   :duration (coerce (or duration derived) 'double-float))))

(defun ensure-animation-state (world)
  "Retorna o estado de animação pertencente ao mundo."
  (sgeo.scene:with-world-lock (world)
    (or (sgeo.scene:world-animation-state world)
        (setf (sgeo.scene:world-animation-state world)
              (make-instance 'animation-state :world world)))))

(defun add-animation-clip (world clip)
  "Anexa um clipe ao mundo e devolve o mesmo clipe."
  (unless (typep clip 'animation-clip) (error "Esperava um animation-clip."))
  (let ((state (ensure-animation-state world)))
    (sgeo.scene:with-world-lock (world)
      (pushnew clip (animation-state-clips state) :test #'eq)))
  clip)

(defun play-animation (world clip &key (weight 1d0) (speed 1d0) (looping-p t)
                                      additive-p mask root-motion-target root-motion-joint
                                      (evaluate-p t))
  "Inicia um clipe no estado do mundo."
  (unless (typep clip 'animation-clip) (error "Esperava um animation-clip."))
  (unless (and (%finite-real-p weight) (not (minusp weight))
               (%finite-real-p speed))
    (error "Peso e velocidade precisam ser números finitos; peso não pode ser negativo."))
  (let* ((state (ensure-animation-state world))
         (player (make-instance 'animation-player :world world :clip clip
                                :weight (coerce weight 'double-float)
                                :speed (coerce speed 'double-float)
                                :looping-p (not (null looping-p))
                                :additive-p (not (null additive-p)) :mask mask
                                :root-motion-target root-motion-target
                                :root-motion-joint root-motion-joint)))
    (sgeo.scene:with-world-lock (world)
      (let ((references (%copy-state-references state))
            (old-clips (copy-list (animation-state-clips state))))
        (push player (animation-state-players state))
        (pushnew clip (animation-state-clips state) :test #'eq)
        (when evaluate-p
          (handler-case (evaluate-animation-state state)
            (error (condition)
              (setf (animation-state-players state)
                    (remove player (animation-state-players state) :test #'eq))
              (setf (animation-state-clips state) old-clips)
              (%restore-state-references state references)
              (error condition))))))
    player))

(defun stop-animation (player)
  "Interrompe a reprodução sem destruir o clipe ou o player."
  (let ((world (%player-world player)))
    (let ((was-playing (player-playing-p player))
          (was-enabled (%player-enabled-p player)))
      (setf (player-playing-p player) nil (%player-enabled-p player) nil)
    (sgeo.scene:with-world-lock (world)
      (let ((state (sgeo.scene:world-animation-state world)))
        (when state
          (handler-case (evaluate-animation-state state)
            (error (condition)
              (setf (player-playing-p player) was-playing
                    (%player-enabled-p player) was-enabled)
              (error condition)))))))
  player))

(defun seek-animation (player time &key fire-events)
  "Move o cursor e avalia a pose; eventos são silenciosos por padrão."
  (unless (%finite-real-p time) (error "O instante precisa ser finito."))
  (let* ((world (%player-world player)) (duration (clip-duration (player-clip player)))
         (new-time (max 0d0 (min duration (coerce time 'double-float)))))
    (sgeo.scene:with-world-lock (world)
      (let* ((state (ensure-animation-state world))
             (old (player-time player))
             (references (%copy-state-references state))
             (*pending-animation-events* (and fire-events nil)))
        (handler-case
            (progn
              (setf (player-time player) new-time)
              (when fire-events (%dispatch-events (player-clip player) old new-time player))
              (setf (%player-seeking-p player) t)
              (unwind-protect (evaluate-animation-state state)
                (setf (%player-seeking-p player) nil)))
          (error (condition)
            (setf (player-time player) old (%player-seeking-p player) nil)
            (%restore-state-references state references)
            (error condition)))
        (dolist (pending (nreverse *pending-animation-events*))
          (destructuring-bind (track event pending-player) pending
            (let ((handler (or (%event-track-handler track) *animation-event-handler*)))
              (when handler
                (funcall handler (second event) pending-player track (first event)))))))
    player)))

(defun %mask-allows-p (player track)
  (let ((mask (player-mask player)))
    (or (null mask)
        (cond ((hash-table-p mask)
               (or (gethash (list (track-target track) (track-path track)) mask)
                   (gethash (track-path track) mask)
                   (gethash (first (track-path track)) mask)))
              ((functionp mask) (funcall mask (track-target track) (track-path track)))
              ((listp mask)
               (or (member (track-path track) mask :test #'equal)
                   (member (first (track-path track)) mask :test #'equal)
                   (member (second (track-path track)) mask :test #'equal)))
              (t nil)))))

(defun %event-call (track event player)
  (if (not (eq *pending-animation-events* :disabled))
      (push (list track event player) *pending-animation-events*)
      (let ((handler (or (%event-track-handler track) *animation-event-handler*)))
        (when handler (funcall handler (second event) player track (first event))))))

(defun %dispatch-events (clip from to player)
  (dolist (track (clip-tracks clip))
    (when (typep track 'event-track)
      (dolist (event (if (>= to from)
                         (%event-track-events track)
                         (reverse (%event-track-events track))))
        (if (>= to from)
            (when (and (> (first event) from) (<= (first event) to))
              (%event-call track event player))
            (when (and (< (first event) from) (>= (first event) to))
              (%event-call track event player)))))))

(defun %dispatch-looped-events (clip old-unwrapped new-unwrapped player)
  (let ((duration (clip-duration clip)))
    (when (> duration 0d0)
      (if (> new-unwrapped old-unwrapped)
          (loop for cycle from (floor old-unwrapped duration) to (floor new-unwrapped duration)
                for from = (if (= cycle (floor old-unwrapped duration))
                               (mod old-unwrapped duration) -1d-15)
                for to = (if (= cycle (floor new-unwrapped duration))
                             (mod new-unwrapped duration) duration)
                do (%dispatch-events clip from to player))
          (loop for cycle downfrom (floor old-unwrapped duration) to (floor new-unwrapped duration)
                for from = (if (= cycle (floor old-unwrapped duration))
                               (mod old-unwrapped duration) (+ duration 1d-15))
                for to = (if (= cycle (floor new-unwrapped duration))
                             (mod new-unwrapped duration) 0d0)
                do (%dispatch-events clip from to player))))))

(defun %root-motion-track (player)
  (let ((joint (%player-root-joint player)))
    (and joint
         (find-if (lambda (track)
                    (and (typep track 'property-track)
                         (eq (track-target track) joint)
                         (member (first (track-path track)) '(:position :translation))))
                  (clip-tracks (player-clip player))))))

(defun %root-motion-track-p (player track)
  (and (%player-root-target player) (eq track (%root-motion-track player))))

(defun %apply-root-motion (player previous current looping-p)
  (let ((target (%player-root-target player)) (track (%root-motion-track player)))
    (when (and target track (fboundp 'extract-root-motion))
      (let* ((duration (clip-duration (player-clip player)))
             (delta (extract-root-motion
                     (lambda (time) (sample-track track time))
                     previous current :looping-p looping-p :duration duration)))
        (sgeo.scene:set-position target
          (sgeo.math:v+ (sgeo.math:transform-position
                         (sgeo.scene:scene-object-local-transform target)) delta))))))

(defun %advance-player (player dt)
  (when (and (%player-enabled-p player) (player-playing-p player))
    (let* ((clip (player-clip player)) (duration (clip-duration clip))
           (delta (* dt (player-speed player))) (old (player-time player))
           (raw (+ old delta)))
      (unless (and (%finite-real-p delta) (%finite-real-p raw))
        (error "Avanço de player excedeu a faixa numérica finita."))
      (cond
        ((player-looping-p player)
         (if (plusp duration)
             (progn (%dispatch-looped-events clip old raw player)
                    (%apply-root-motion player old raw t)
                    (setf (player-time player) (mod raw duration)))
             (setf (player-time player) 0d0)))
        (t
         (let ((new (max 0d0 (min duration raw))))
           (%dispatch-events clip old new player)
           (%apply-root-motion player old new nil)
           (setf (player-time player) new)
           (when (or (and (plusp delta) (>= raw duration))
                     (and (minusp delta) (<= raw 0d0)))
             (setf (player-playing-p player) nil))))))))

(defun %root-target-snapshot (player)
  (let ((target (%player-root-target player)))
    (when target
      (list target (sgeo.math:transform-position
                    (sgeo.scene:scene-object-local-transform target))))))

(defun advance-animation-state (state dt)
  "Avança todos os players e aplica a pose enquanto o lock do mundo está ativo."
  (unless (and (%finite-real-p dt) (not (minusp dt)))
    (error "O passo de animação precisa ser finito e não negativo."))
  (let ((world (%state-world state)) (dt (coerce dt 'double-float)))
    (sgeo.scene:with-world-lock (world)
      (let* ((old-clock (animation-state-time state))
             (player-snapshots (mapcar (lambda (player)
                                         (list player (player-time player)
                                               (player-playing-p player)))
                                       (animation-state-players state)))
             (reference-snapshot (%copy-state-references state))
             (root-snapshots (remove nil (mapcar #'%root-target-snapshot
                                                 (animation-state-players state))))
             (*pending-animation-events* nil))
        (handler-case
            (progn
              (unless (%finite-real-p (+ old-clock dt))
                (error "Relógio de animação excedeu a faixa numérica finita."))
              (incf (animation-state-time state) dt)
              (dolist (player (animation-state-players state)) (%advance-player player dt))
              (evaluate-animation-state state))
          (error (condition)
            (setf (animation-state-time state) old-clock)
            (dolist (snapshot player-snapshots)
              (setf (player-time (first snapshot)) (second snapshot)
                    (player-playing-p (first snapshot)) (third snapshot)))
            (%restore-state-references state reference-snapshot)
            (dolist (snapshot root-snapshots)
              (ignore-errors (sgeo.scene:set-position (first snapshot) (second snapshot))))
            (error condition)))
        (dolist (pending (nreverse *pending-animation-events*))
          (destructuring-bind (track event player) pending
            (let ((handler (or (%event-track-handler track) *animation-event-handler*)))
              (when handler
                (funcall handler (second event) player track (first event))))))))
  state))

(defun %property-key (track)
  (list (track-target track) (track-path track)))
(defun %copy-state-references (state)
  (let ((copy (make-hash-table :test 'equal)))
    (maphash (lambda (key value)
               (setf (gethash key copy) (%copy-animation-value value)))
             (%state-references state))
    copy))
(defun %restore-state-references (state snapshot)
  (clrhash (%state-references state))
  (maphash (lambda (key value) (setf (gethash key (%state-references state)) value)) snapshot))
(defun %reference-value (state track)
  (let* ((key (%property-key track)) (entry (gethash key (%state-references state))))
    (or entry
        (setf (gethash key (%state-references state))
              (%copy-animation-value (read-track-value track))))))

(defun %weighted-combine (base contributions)
  (let* ((total (loop for (value weight) in contributions sum weight double-float))
         (all (append (when (< total 1d0) (list (list base (- 1d0 total))))
                      contributions)))
    (when (> total 1d0)
      (setf all (mapcar (lambda (entry) (list (first entry) (/ (second entry) total))) contributions)))
    (let ((result (first (first all))) (sum (second (first all))))
      (dolist (entry (rest all) result)
        (let ((weight (second entry)))
          (setf result (%linear-value result (first entry) (/ weight (+ sum weight)))
                sum (+ sum weight)))))))

(defun %quaternion-conjugate (q)
  (let ((d (sgeo.math::quaternion-data q)))
    (sgeo.math:make-quaternion (- (aref d 0)) (- (aref d 1)) (- (aref d 2)) (aref d 3))))

(defun %additive-value (base reference sample weight)
  (cond ((and (sgeo.math::quaternion-p base) (sgeo.math::quaternion-p reference)
              (sgeo.math::quaternion-p sample))
         (let* ((delta (sgeo.math:quaternion-multiply sample (%quaternion-conjugate reference)))
                (weighted (%linear-value (sgeo.math:make-quaternion) delta weight)))
           (sgeo.math:quaternion-normalize (sgeo.math:quaternion-multiply weighted base))))
        ((and (%finite-real-p base) (%finite-real-p reference) (%finite-real-p sample))
         (+ base (* weight (- sample reference))))
        ((and (%value-components base) (%value-components reference) (%value-components sample))
         (map 'vector (lambda (b r s) (+ b (* weight (- s r))))
              (%value-components base) (%value-components reference) (%value-components sample)))
        (t base)))

(defun %collect-pose-updates (state)
  (let ((groups (make-hash-table :test 'equal)))
    (dolist (player (animation-state-players state))
      (dolist (track (clip-tracks (player-clip player)))
        (when (and (typep track 'property-track) (%player-enabled-p player)
                   (plusp (player-weight player)) (%mask-allows-p player track))
          (unless (%root-motion-track-p player track)
            (let ((entry (or (gethash (%property-key track) groups)
                             (setf (gethash (%property-key track) groups)
                                   (list track nil nil)))))
              (let ((sample (sample-track track (player-time player)))
                    (weight (player-weight player)))
                (if (player-additive-p player)
                    (push (list sample weight
                                (%copy-animation-value (second (first (track-keys track)))))
                          (third entry))
                    (push (list sample weight) (second entry)))))))))
    (let ((updates nil) (orphaned-references nil))
      (maphash
       (lambda (key entry)
         (declare (ignore key))
         (let* ((track (first entry)) (current (%reference-value state track))
                (base (if (second entry) (%weighted-combine current (nreverse (second entry))) current))
                (value base))
           (dolist (additive (nreverse (third entry)))
             (setf value (%additive-value value (third additive) (first additive) (second additive))))
           (push (list track value (read-track-value track)) updates)))
       groups)
      ;; Uma chave removida ou um player parado deixa a referência sem trilha
      ;; ativa. Restaura o valor capturado uma vez e descarta a referência.
      (maphash
       (lambda (key reference)
         (unless (gethash key groups)
           (let* ((target (first key)) (path (second key))
                  (track (make-property-track target path (list (list 0d0 reference)))))
             (push (list track reference (read-track-value track)) updates)
             (push key orphaned-references))))
       (%state-references state))
      (values (nreverse updates) orphaned-references))))

(defun evaluate-animation-state (state)
  "Mistura camadas e publica todos os valores com restauração em caso de erro."
  (let ((world (%state-world state)))
    (sgeo.scene:with-world-lock (world)
      (let ((references (%copy-state-references state)) (applied nil))
        (handler-case
            (multiple-value-bind (updates orphaned-references)
                (%collect-pose-updates state)
              (progn
                (dolist (update updates)
                  (push update applied)
                  (write-track-value (first update) (second update)))
                (dolist (key orphaned-references)
                  (remhash key (%state-references state)))))
          (error (condition)
            (dolist (update applied)
              (ignore-errors (write-track-value (first update) (third update))))
            (%restore-state-references state references)
            (error condition)))))
    state))

(defmethod sgeo.scene:update-world-animations :after ((world sgeo.scene:world) dt)
  (let ((state (sgeo.scene:world-animation-state world)))
    (when state (advance-animation-state state dt))))

(defun animate (target path &key from to keys duration (interpolation :linear) name)
  "Forma curta que retorna um clipe normal de uma trilha de propriedade."
  (let* ((track-keys (or keys (and duration
                                   (list (list 0d0 from) (list duration to)))))
         (track (make-property-track target path track-keys
                                     :interpolation interpolation :name name)))
    (make-animation-clip :name name :tracks (list track) :duration duration)))

(defun %compile-animation-track-form (form)
  (destructuring-bind (tag target path &rest key-forms) form
    (unless (and (symbolp tag) (string-equal (symbol-name tag) "TRACK"))
      (error "Forma DSL desconhecida: ~S" form))
    (let ((path (if (and (consp path) (eq (first path) 'quote))
                    (second path) path)))
      `(sgeo.animation:make-property-track
        ,target ',path
        (list ,@(mapcar (lambda (key)
                          (destructuring-bind (time value &rest options) key
                            (declare (ignore options)) `(list ,time ,value)))
                        key-forms))
        :easings ',(mapcar (lambda (key) (getf (cddr key) :ease)) key-forms)))))

(defmacro defanimation (name options &body forms)
  "Define um clipe global a partir de formas TRACK legíveis."
  (let ((duration (getf options :duration)))
    `(defparameter ,name
       (sgeo.animation:make-animation-clip
        :name (string-downcase (symbol-name ',name)) :duration ,duration
        :tracks (list ,@(mapcar #'%compile-animation-track-form forms))))))
