(in-package #:sgeo.animation)

;;; Dados de animação e compilação de caminhos de propriedades.

(defclass property-track ()
  ((target :initarg :target :reader track-target)
   (path :initarg :path :reader track-path)
   (keys :initarg :keys :reader track-keys)
   (interpolation :initarg :interpolation :reader track-interpolation)
   (easings :initarg :easings :initform nil :reader %track-easings)
   (name :initarg :name :initform nil :reader %track-name)
   (accessors :initform nil :accessor %track-accessors)))
(defclass transform-track (property-track) ())
(defclass skeletal-track (property-track) ())
(defclass event-track ()
  ((events :initarg :events :reader %event-track-events)
   (handler :initarg :handler :initform nil :reader %event-track-handler)))

(defun %finite-real-p (x)
  (and (realp x)
       (handler-case (and (<= x most-positive-double-float)
                          (>= x most-negative-double-float))
         (error () nil))))

(defun %copy-animation-value (value)
  (cond ((sgeo.math::quaternion-p value)
         (apply #'sgeo.math:make-quaternion
                (coerce (sgeo.math::quaternion-data value) 'list)))
        ((and (typep value 'array) (= (array-rank value) 1)) (copy-seq value))
        (t value)))

(defun %validate-animation-value (value context)
  (cond
    ((%finite-real-p value) (coerce value 'double-float))
    ((numberp value) (error "~A: números precisam ser reais e finitos." context))
    ((sgeo.math::quaternion-p value)
     (let ((data (sgeo.math::quaternion-data value)))
       (unless (every #'%finite-real-p data)
         (error "~A: componentes de quaternion precisam ser finitas." context))
       (sgeo.math:quaternion-normalize value)))
    ((and (typep value 'array) (= (array-rank value) 1)
          (plusp (length value)) (every #'%finite-real-p value))
     (map 'vector (lambda (x) (coerce x 'double-float)) value))
    ((and (typep value 'array) (= (array-rank value) 1)
          (some #'numberp value))
     (error "~A: vetores numéricos precisam conter apenas valores finitos." context))
    (t value)))

(defun %normalize-key (key previous)
  (unless (and (consp key) (>= (length key) 2) (<= (length key) 4)
               (%finite-real-p (first key)))
    (error "Chave de animação inválida: ~S" key))
  (let ((time (coerce (first key) 'double-float))
        (value (%validate-animation-value (second key) "valor da chave")))
    (when (and previous (<= time previous))
      (error "Os tempos das chaves precisam crescer estritamente."))
    (let ((in (third key)) (out (fourth key)))
      (when (or in out)
        (unless (and in out) (error "Chaves cúbicas precisam de duas tangentes."))
        (setf in (%validate-tangent in "tangente de entrada")
              out (%validate-tangent out "tangente de saída")))
      (list time value in out))))

(defun %validate-tangent (value context)
  (cond ((%finite-real-p value) (coerce value 'double-float))
        ((sgeo.math::quaternion-p value)
         (let ((data (sgeo.math::quaternion-data value)))
           (unless (every #'%finite-real-p data) (error "~A precisa ser finita." context))
           (copy-seq data)))
        ((and (typep value 'array) (= (array-rank value) 1)
              (plusp (length value)) (every #'%finite-real-p value))
         (map 'vector (lambda (x) (coerce x 'double-float)) value))
        (t (error "~A incompatível: ~S" context value))))

(defun (setf track-keys) (keys track)
  "Valida e substitui as chaves sem deixar estado parcialmente atualizado."
  (unless (and (listp keys) keys) (error "Uma trilha precisa de ao menos uma chave."))
  (let ((normalized nil) (previous nil))
    (dolist (key keys)
      (let ((entry (%normalize-key key previous)))
        (setf previous (first entry))
      (push entry normalized)))
    (setf normalized (nreverse normalized))
    (unless (eq (track-interpolation track) :step)
      (let ((first-value (second (first normalized))))
        (dolist (entry normalized)
          (let ((value (second entry)))
            (unless (or (and (%finite-real-p first-value) (%finite-real-p value))
                        (and (sgeo.math::quaternion-p first-value)
                             (sgeo.math::quaternion-p value))
                        (and (%value-components first-value) (%value-components value)
                             (= (length (%value-components first-value))
                                (length (%value-components value)))))
              (error "Valores incompatíveis em trilha interpolada: ~S e ~S."
                     first-value value))
            (when (eq (track-interpolation track) :cubic-spline)
              (dolist (tangent (list (third entry) (fourth entry)))
                (unless (or (and (%finite-real-p first-value) (%finite-real-p tangent))
                            (and (%value-components first-value) (%value-components tangent)
                                 (= (length (%value-components first-value))
                                    (length (%value-components tangent)))))
                  (error "Tangente cúbica incompatível com valor da chave."))))))))
    (setf (slot-value track 'keys) normalized
          (slot-value track 'easings)
          (loop for index below (length normalized)
                collect (nth index (%track-easings track))))))

(defun track-easings (track)
  "Retorna uma cópia dos modos de easing associados a cada segmento."
  (copy-list (%track-easings track)))

(defun set-track-keys (track keys)
  "Substitui as chaves de uma trilha após validar toda a nova sequência."
  (setf (track-keys track) keys)
  track)

(defun make-property-track (target path keys &key (interpolation :linear) name easings)
  "Cria trilha de propriedade e compila uma vez seu caminho de acesso."
  (unless (member interpolation '(:step :linear :cubic-spline))
    (error "Interpolação inválida: ~S" interpolation))
  (when (and easings
             (not (every (lambda (easing)
                           (member easing '(nil :linear :in :out :in-out))) easings)))
    (error "A lista de easing contém um modo desconhecido."))
  (let* ((path (%normalize-animation-path path))
         (track (make-instance (if (member (first path) '(:position :translation :rotation :scale))
                                  'transform-track 'property-track)
                               :target target :path path
                               :keys nil :interpolation interpolation :name name
                               :easings easings)))
    (setf (track-keys track) keys)
    (multiple-value-bind (getter setter) (animation-property-accessors target (track-path track))
      (setf (%track-accessors track) (cons getter setter)))
    track))

(defun make-event-track (events &key handler)
  "Cria trilha de eventos com pares (tempo valor)."
  (let ((normalized nil) (previous nil))
    (dolist (event events)
      (unless (and (consp event) (>= (length event) 2) (%finite-real-p (first event)))
        (error "Evento inválido: ~S" event))
      (let ((time (coerce (first event) 'double-float)))
        (when (and previous (< time previous)) (error "Eventos precisam estar ordenados."))
        (setf previous time)
        (push (list time (second event)) normalized)))
    (make-instance 'event-track :events (nreverse normalized) :handler handler)))

(defun %component-index (component)
  (position component '(:x :y :z :w x y z w)))

(defun %read-segment (object segment)
  (cond
    ((and (consp segment) (eq (first segment) 'aref)) (aref object (second segment)))
    ((and (consp segment) (eq (first segment) 'nth) (listp object)) (nth (second segment) object))
    ((and (consp segment) (eq (first segment) 'slot)) (slot-value object (second segment)))
    ((and (consp segment) (eq (first segment) 'funcall)) (funcall (second segment) object))
    ((%component-index segment)
     (let ((index (%component-index segment)))
       (if (sgeo.math::quaternion-p object)
           (aref (sgeo.math::quaternion-data object) index)
           (aref object index))))
    ((and (symbolp segment) (slot-exists-p object segment)) (slot-value object segment))
    ((and (symbolp segment) (fboundp segment)) (funcall segment object))
    (t (error "Segmento de caminho não reconhecido: ~S" segment))))

(defun %write-segment (object segment value)
  (cond
    ((and (consp segment) (eq (first segment) 'aref)) (setf (aref object (second segment)) value))
    ((and (consp segment) (eq (first segment) 'nth)) (setf (nth (second segment) object) value))
    ((and (consp segment) (eq (first segment) 'slot)) (setf (slot-value object (second segment)) value))
    ((and (consp segment) (eq (first segment) 'funcall))
     (funcall (third segment) value object))
    ((%component-index segment)
     (let ((index (%component-index segment)))
       (if (sgeo.math::quaternion-p object)
           (setf (aref (sgeo.math::quaternion-data object) index) value)
           (setf (aref object index) value))))
    ((and (symbolp segment) (slot-exists-p object segment)) (setf (slot-value object segment) value))
    ((and (symbolp segment) (fboundp `(setf ,segment))) (funcall (fdefinition `(setf ,segment)) value object))
    (t (error "Segmento de caminho sem escrita: ~S" segment))))

(defun %normalize-animation-path (path)
  (let* ((segments (if (listp path) (copy-tree path) (list path)))
         (head (first segments)))
    (when (symbolp head)
      (let ((name (string-upcase (symbol-name head))))
        (when (member name '("POSITION" "TRANSLATION" "ROTATION" "SCALE" "WEIGHTS")
                      :test #'string=)
          (setf (first segments) (intern name "KEYWORD")))))
    (when (and (second segments) (symbolp (second segments)))
      (let ((name (string-upcase (symbol-name (second segments)))))
        (when (member name '("X" "Y" "Z" "W") :test #'string=)
          (setf (second segments) (intern name "KEYWORD")))))
    segments))

(defun %compile-read-step (segment)
  (cond
    ((and (consp segment) (eq (first segment) 'aref))
     (let ((index (second segment))) (lambda (object) (aref object index))))
    ((and (consp segment) (eq (first segment) 'nth))
     (let ((index (second segment))) (lambda (object) (nth index object))))
    ((and (consp segment) (eq (first segment) 'slot))
     (let ((slot (second segment))) (lambda (object) (slot-value object slot))))
    ((and (consp segment) (eq (first segment) 'funcall))
     (let ((reader (second segment))) (lambda (object) (funcall reader object))))
    ((%component-index segment)
     (let ((index (%component-index segment)))
       (lambda (object)
         (if (sgeo.math::quaternion-p object)
             (aref (sgeo.math::quaternion-data object) index)
             (aref object index)))))
    ((symbolp segment)
     (lambda (object)
       (cond ((and (typep object 'standard-object)
                   (slot-exists-p object segment)) (slot-value object segment))
             ((fboundp segment) (funcall segment object))
             (t (error "Propriedade ~S não encontrada em ~S." segment object)))))
    (t (error "Segmento de caminho não reconhecido: ~S" segment))))

(defun %compile-write-step (segment)
  (cond
    ((and (consp segment) (eq (first segment) 'aref))
     (let ((index (second segment))) (lambda (object value) (setf (aref object index) value))))
    ((and (consp segment) (eq (first segment) 'nth))
     (let ((index (second segment))) (lambda (object value) (setf (nth index object) value))))
    ((and (consp segment) (eq (first segment) 'slot))
     (let ((slot (second segment))) (lambda (object value) (setf (slot-value object slot) value))))
    ((and (consp segment) (eq (first segment) 'funcall))
     (let ((writer (third segment))) (lambda (object value) (funcall writer value object))))
    ((%component-index segment)
     (let ((index (%component-index segment)))
       (lambda (object value)
         (if (sgeo.math::quaternion-p object)
             (setf (aref (sgeo.math::quaternion-data object) index) value)
             (setf (aref object index) value)))))
    ((and (symbolp segment) (fboundp `(setf ,segment)))
     (lambda (object value)
       (funcall (fdefinition `(setf ,segment)) value object)))
    ((symbolp segment)
     (lambda (object value) (setf (slot-value object segment) value)))
    (t (error "Segmento de caminho sem escrita: ~S" segment))))

(defgeneric animation-property-accessors (target path)
  (:documentation "Retorna getter e setter compilados para uma propriedade animável."))

(defun %rotation-euler (target)
  (let* ((d (sgeo.math::quaternion-data
             (sgeo.math:transform-rotation (sgeo.scene:scene-object-local-transform target))))
         (x (aref d 0)) (y (aref d 1)) (z (aref d 2)) (w (aref d 3)))
    (vector (atan (* 2d0 (+ (* w x) (* y z)))
                  (- 1d0 (* 2d0 (+ (* x x) (* y y)))))
            (asin (max -1d0 (min 1d0 (* 2d0 (- (* w y) (* z x))))))
            (atan (* 2d0 (+ (* w z) (* x y)))
                  (- 1d0 (* 2d0 (+ (* y y) (* z z))))))))

(defun %scene-path-accessors (target head component)
  (case head
    ((:position :translation)
     (values (lambda ()
               (let ((value (sgeo.math:transform-position
                             (sgeo.scene:scene-object-local-transform target))))
                 (if component (aref value (%component-index component)) value)))
             (lambda (value)
               (if component
                   (let ((vector (sgeo.math:transform-position
                                  (sgeo.scene:scene-object-local-transform target))))
                     (setf (aref vector (%component-index component)) (coerce value 'double-float))
                   (sgeo.scene:set-position target vector))
                   (sgeo.scene:set-position target value)))))
    (:rotation
     (values (lambda ()
               (if component (aref (%rotation-euler target) (%component-index component))
                   (sgeo.math:transform-rotation
                    (sgeo.scene:scene-object-local-transform target))))
             (lambda (value)
               (if component
                   (let ((angles (%rotation-euler target)))
                     (setf (aref angles (%component-index component)) (coerce value 'double-float))
                     (sgeo.scene:set-rotation target (sgeo.scene::%coerce-rotation angles)))
                   (sgeo.scene:set-rotation target value)))))
    (:scale
     (values (lambda ()
               (let ((value (sgeo.math:transform-scale
                             (sgeo.scene:scene-object-local-transform target))))
                 (if component (aref value (%component-index component)) value)))
             (lambda (value)
               (if component
                   (let ((vector (sgeo.math:transform-scale
                                  (sgeo.scene:scene-object-local-transform target))))
                     (setf (aref vector (%component-index component)) (coerce value 'double-float))
                     (sgeo.scene:set-scale target vector))
                   (sgeo.scene:set-scale target value)))))))

(defmethod animation-property-accessors ((target t) path)
  "Retorna funções de leitura e escrita compiladas para um caminho."
  (let* ((segments (%normalize-animation-path path))
         (head (first segments)))
    (when (and (typep target 'sgeo.scene:scene-object)
               (member head '(:position :translation :rotation :scale)))
      (return-from animation-property-accessors
        (%scene-path-accessors target head (second segments))))
    (unless segments (error "O caminho de animação não pode ser vazio."))
    (let* ((readers (mapcar #'%compile-read-step segments))
           (writer (%compile-write-step (car (last segments))))
           (parents (butlast readers))
           (parent-getter
             (if parents
                 (reduce (lambda (outer inner)
                           (lambda () (funcall inner (funcall outer))))
                         (rest parents)
                         :initial-value (lambda () (funcall (first parents) target)))
                 (lambda () target)))
           (getter
             (if (cdr segments)
                 (let ((last-reader (car (last readers))))
                   (lambda () (funcall last-reader (funcall parent-getter))))
                 (let ((first-reader (first readers)))
                   (lambda () (funcall first-reader target)))))
           (setter (if (cdr segments)
                       (lambda (value) (funcall writer (funcall parent-getter) value))
                       (lambda (value) (funcall writer target value)))))
      (values getter setter))))

(defmethod animation-property-accessors
    ((target deformable-mesh-object) path)
  "Compila acesso a pesos morfológicos sem refletir slots internos."
  (let* ((segments (%normalize-animation-path path))
         (component (second segments)))
    (unless (and (eq (first segments) :weights) (<= (length segments) 2)
                 (or (= (length segments) 1) (integerp component)))
      (return-from animation-property-accessors
        (call-next-method)))
    (if component
        (values (lambda () (aref (mesh-morph-weights target) component))
                (lambda (value)
                  (let ((weights (mesh-morph-weights target)))
                    (setf (aref weights component) (coerce value 'double-float))
                    (set-morph-weights target weights))))
        (values (lambda () (mesh-morph-weights target))
                (lambda (value) (set-morph-weights target value))))))

(defun read-track-value (track)
  (funcall (car (%track-accessors track))))
(defun write-track-value (track value)
  (funcall (cdr (%track-accessors track)) value))

(defun %value-components (value)
  (cond ((sgeo.math::quaternion-p value) (sgeo.math::quaternion-data value))
        ((and (typep value 'array) (= (array-rank value) 1)
              (every #'%finite-real-p value)) value)
        (t nil)))
(defun %linear-value (a b t-value)
  (cond
    ((and (sgeo.math::quaternion-p a) (sgeo.math::quaternion-p b))
     (let* ((qa (sgeo.math:quaternion-normalize a))
            (qb (sgeo.math:quaternion-normalize b))
            (da (sgeo.math::quaternion-data qa)) (db (sgeo.math::quaternion-data qb))
            (dot (loop for x across da for y across db sum (* x y) double-float)))
       (when (minusp dot) (setf qb (apply #'sgeo.math:make-quaternion
                                         (loop for x across db collect (- x)))
                            db (sgeo.math::quaternion-data qb) dot (- dot)))
       (if (> dot 0.9995d0)
           (sgeo.math:quaternion-normalize
            (apply #'sgeo.math:make-quaternion
                   (loop for x across da for y across db collect (+ x (* t-value (- y x))))))
           (let* ((theta (acos (max -1d0 (min 1d0 dot))))
                  (denom (sin theta))
                  (wa (/ (sin (* (- 1d0 t-value) theta)) denom))
                  (wb (/ (sin (* t-value theta)) denom)))
             (sgeo.math:quaternion-normalize
              (apply #'sgeo.math:make-quaternion
                     (loop for x across da for y across db collect (+ (* wa x) (* wb y)))))))))
    ((and (%finite-real-p a) (%finite-real-p b)) (+ a (* t-value (- b a))))
    ((and (%value-components a) (%value-components b)
          (= (length (%value-components a)) (length (%value-components b))))
     (map 'vector (lambda (x y) (+ x (* t-value (- y x)))) (%value-components a) (%value-components b)))
    (t (if (< t-value 1d0) a b))))

(defun %cubic-value (a out-tangent b in-tangent amount span)
  (let* ((t2 (* amount amount)) (t3 (* t2 amount))
         (h00 (+ (* 2d0 t3) (* -3d0 t2) 1d0))
         (h10 (+ t3 (* -2d0 t2) amount))
         (h01 (+ (* -2d0 t3) (* 3d0 t2)))
         (h11 (- t3 t2)))
    (labels ((component (x out y in)
               (+ (* h00 x) (* h10 span (or out 0d0))
                  (* h01 y) (* h11 span (or in 0d0))))
             (hermite (x out y in)
               (component x out y in)))
      (cond
        ((and (%finite-real-p a) (%finite-real-p b))
         (hermite a out-tangent b in-tangent))
        ((and (sgeo.math::quaternion-p a) (sgeo.math::quaternion-p b))
         (let* ((q0 (sgeo.math::quaternion-data a))
                (q1 (copy-seq (sgeo.math::quaternion-data b)))
                (m0 (and out-tangent (%value-components out-tangent)))
                (m1 (and in-tangent (%value-components in-tangent)))
                (dot (loop for x across q0 for y across q1 sum (* x y) double-float)))
           (when (minusp dot)
             (setf q1 (map 'vector #'- q1)
                   m1 (and m1 (map 'vector #'- m1))))
           (sgeo.math:quaternion-normalize
            (apply #'sgeo.math:make-quaternion
                   (loop for x across q0 for y across q1 for i from 0
                         collect (hermite x (and m0 (aref m0 i)) y (and m1 (aref m1 i))))))))
        ((and (%value-components a) (%value-components b))
         (map 'vector (lambda (x out y in) (hermite x out y in))
              (%value-components a) (%value-components out-tangent)
              (%value-components b) (%value-components in-tangent)))
        (t (%linear-value a b amount))))))

(defun sample-track (track time)
  "Amostra trilha por interpolação step, linear ou Hermite glTF."
  (unless (%finite-real-p time) (error "O instante precisa ser finito."))
  (let* ((keys (track-keys track)) (t0 (first (first keys))) (last (car (last keys))))
    (cond ((<= time t0) (%copy-animation-value (second (first keys))))
          ((>= time (first last)) (%copy-animation-value (second last)))
          (t (let ((left (first keys)) (right (second keys)))
               (loop for rest on keys while (second rest)
                     for a = (first rest) for b = (second rest)
                     when (< time (first b))
                       do (setf left a right b) (return))
               (if (eq (track-interpolation track) :step)
                   (%copy-animation-value (second left))
                   (let* ((span (- (first right) (first left)))
                          (u (/ (- time (first left)) span))
                          (easing (nth (position left keys :test #'eq)
                                       (%track-easings track)))
                          (u (case easing
                               (:in (* u u))
                               (:out (- 1d0 (* (- 1d0 u) (- 1d0 u))))
                               (:in-out (* u u (- 3d0 (* 2d0 u))))
                               (otherwise u))))
                     (%copy-animation-value
                      (if (eq (track-interpolation track) :cubic-spline)
                          (%cubic-value (second left) (fourth left) (second right)
                                        (third right) u span)
                          (%linear-value (second left) (second right) u))))))))))
