;;;; Verifica a interação dos gizmos diretamente no estado CPU do editor.
(load (merge-pathnames "bootstrap.lisp" (or *load-truename* *compile-file-truename*)))
(asdf:load-system :sgeo/examples)
(asdf:load-system :sgeo/editor/opengl)

(defun gizmo-check (condition description)
  "Interrompe a verificação quando um contrato do gizmo falha."
  (unless condition (error "Verificação do gizmo falhou: ~A" description))
  t)

(defun gizmo-pose (object)
  "Copia a pose local para comparações independentes do objeto."
  (let ((transform (sgeo.scene:scene-object-local-transform object)))
    (list (copy-seq (sgeo.math:transform-position transform))
          (copy-seq (sgeo.math::quaternion-data
                     (sgeo.math:transform-rotation transform)))
          (copy-seq (sgeo.math:transform-scale transform)))))

(defun gizmo-context (&key parent-p)
  "Cria mundo, objeto selecionado e estado interno sem abrir uma janela."
  (let* ((world (sgeo.examples:make-kernel-world))
         (editor (sgeo.editor:make-editor :world world))
         (object (sgeo.scene:find-object world "EditableBox")))
    (when parent-p
      (let ((parent (sgeo.scene:make-mesh-object
                     (sgeo.geometry:make-half-edge-box :size 0.5d0)
                     :name "Parent" :position '(0.3d0 0.2d0 0d0)
                     :rotation '(0d0 0.61d0 0.17d0) :scale '(2d0 0.65d0 1.35d0))))
        (sgeo.scene:add-to-world world parent)
        (sgeo.scene:reparent object parent)
        (sgeo.scene:set-position object '(0.1d0 0.15d0 0.05d0))
        (sgeo.scene:set-rotation object '(0.12d0 -0.2d0 0.08d0))
        (sgeo.scene:set-scale object '(0.8d0 1.1d0 0.9d0))))
    (sgeo.editor:editor-select editor object)
    (values editor object
            (sgeo.editor.opengl::%make-editor-ui
             :editor editor :width 800 :height 600 :viewport-rect '(0 0 800 600)))))

(defun gizmo-axis-drag-target (state object axis &optional (fraction 0.45d0))
  "Escolhe pixels ao longo do eixo projetado de verdade na viewport."
  (multiple-value-bind (x1 y1 x2 y2)
      (sgeo.editor.opengl::%gizmo-axis-points state object axis)
    (gizmo-check (and x1 y1 x2 y2
                      (> (sqrt (+ (expt (- x2 x1) 2) (expt (- y2 y1) 2))) 8d0))
                 (format nil "o eixo ~S possui projeção utilizável" axis))
    (values x1 y1 (+ x1 (* fraction (- x2 x1)))
            (+ y1 (* fraction (- y2 y1))) x2 y2)))

(defun gizmo-drag (state object axis tool &key (preview-p t) (release-p t))
  "Inicia e atualiza um arraste usando coordenadas projetadas do eixo."
  (setf (sgeo.editor:editor-tool (sgeo.editor.opengl::editor-ui-editor state)) tool)
  (multiple-value-bind (x1 y1 x2 y2)
      (gizmo-axis-drag-target state object axis)
    (sgeo.editor.opengl::%begin-gizmo-drag state object axis x1 y1)
    (sgeo.editor.opengl::%cursor-moved state x2 y2)
    (when preview-p (sgeo.editor.opengl::%preview-gizmo-drag state))
    (when release-p (sgeo.editor.opengl::%finish-gizmo-drag state))))

(defun gizmo-check-operation (tool axis)
  "Confere prévia, histórico e restauração integral para uma ferramenta."
  (multiple-value-bind (editor object state) (gizmo-context)
    (let ((before (gizmo-pose object))
          (history-before (length (sgeo.editor:editor-history editor))))
      (gizmo-drag state object axis tool)
      (let ((after (gizmo-pose object)))
        (gizmo-check (not (equalp before after))
                     (format nil "~A atualiza a pose antes da liberação" tool))
        (gizmo-check (= (length (sgeo.editor:editor-history editor))
                        (1+ history-before))
                     (format nil "~A registra exatamente um passo ao liberar" tool))
        (sgeo.editor:undo-edit editor)
        (gizmo-check (equalp before (gizmo-pose object))
                     (format nil "Undo de ~A restaura a pose inteira" tool))
        (sgeo.editor:redo-edit editor)
        (gizmo-check (equalp after (gizmo-pose object))
                     (format nil "Redo de ~A restaura a pose inteira" tool))))))

(defun gizmo-check-cancel-and-zero-drag (tool)
  "Confere cancelamento e liberação sem movimento para uma ferramenta."
  (multiple-value-bind (editor object state) (gizmo-context)
    (setf (sgeo.editor:editor-tool editor) tool)
    (let ((before (gizmo-pose object))
          (history-before (length (sgeo.editor:editor-history editor))))
      (multiple-value-bind (x1 y1 x2 y2)
          (gizmo-axis-drag-target state object :x)
        (declare (ignore x2 y2))
        (sgeo.editor.opengl::%begin-gizmo-drag state object :x x1 y1)
        (sgeo.editor.opengl::%cursor-moved state (+ x1 23d0) (+ y1 11d0))
        (sgeo.editor.opengl::%preview-gizmo-drag state))
      (gizmo-check (not (equalp before (gizmo-pose object)))
                   (format nil "prévia de ~A muda antes de cancelar" tool))
      (sgeo.editor.opengl::%cancel-gizmo-drag state)
      (gizmo-check (equalp before (gizmo-pose object))
                   (format nil "cancelamento de ~A restaura a pose" tool))
      (gizmo-check (= history-before (length (sgeo.editor:editor-history editor)))
                   (format nil "cancelamento de ~A não cria histórico" tool))
      (multiple-value-bind (x1 y1 x2 y2)
          (gizmo-axis-drag-target state object :x)
        (declare (ignore x2 y2))
        (sgeo.editor.opengl::%begin-gizmo-drag state object :x x1 y1)
        (sgeo.editor.opengl::%finish-gizmo-drag state))
      (gizmo-check (equalp before (gizmo-pose object))
                   (format nil "arraste zero de ~A mantém a pose" tool))
      (gizmo-check (= history-before (length (sgeo.editor:editor-history editor)))
                   (format nil "arraste zero de ~A não cria comando" tool)))))

(defun gizmo-check-parent-axis-direction ()
  "Confere que a translação segue no mundo o eixo mostrado sob um pai transformado."
  (multiple-value-bind (editor object state) (gizmo-context :parent-p t)
    (let* ((world (sgeo.editor:editor-world editor))
           (start (sgeo.editor.opengl::%world-origin object))
           (before-history (length (sgeo.editor:editor-history editor))))
      (multiple-value-bind (x1 y1 x2 y2 world-x2 world-y2)
          (gizmo-axis-drag-target state object :x)
        (declare (ignore world-x2 world-y2))
        (setf (sgeo.editor:editor-tool editor) :translate)
        (sgeo.editor.opengl::%begin-gizmo-drag state object :x x1 y1)
        (sgeo.editor.opengl::%cursor-moved state x2 y2)
        (sgeo.editor.opengl::%preview-gizmo-drag state)
        (let* ((preview (sgeo.editor.opengl::%world-origin object))
               (delta (sgeo.math:v- preview start))
               (shown (sgeo.math:transform-direction
                       (sgeo.scene:world-transform (sgeo.scene:scene-object-parent object))
                       #(1d0 0d0 0d0)))
               (delta-length (sgeo.math:vector-length delta))
               (shown-length (sgeo.math:vector-length shown)))
          (gizmo-check (> delta-length 1d-7) "o arraste do filho atualiza sua posição mundial")
          (gizmo-check (> shown-length 1d-7) "o eixo mostrado não colapsa sob o pai")
          (let ((alignment (/ (sgeo.math:dot delta shown)
                              (* delta-length shown-length))))
            (gizmo-check (> alignment 0.999d0)
                         "a translação do filho segue a direção mundial do eixo mostrado")))
        (sgeo.editor.opengl::%finish-gizmo-drag state)
        (gizmo-check (= (length (sgeo.editor:editor-history editor))
                        (1+ before-history))
                     "a translação hierárquica vira um comando ao liberar")))))

(defun gizmo-check-scene-object-types ()
  "Confere os eixos em grupos de cena e malhas de triângulos."
  (dolist (kind '(:group :triangle))
    (multiple-value-bind (editor ignored state) (gizmo-context)
      (declare (ignore ignored))
      (let ((object (ecase kind
                      (:group (sgeo.scene:make-scene-object :name "Group"))
                      (:triangle (sgeo.scene:make-mesh-object (sgeo.geometry:make-box))))))
        (sgeo.scene:add-to-world (sgeo.editor:editor-world editor) object)
        (sgeo.editor:editor-select editor object)
        (setf (sgeo.editor:editor-tool editor) :translate)
        (multiple-value-bind (x y target-x target-y)
            (gizmo-axis-drag-target state object :x)
          (declare (ignore x y))
          (gizmo-check (sgeo.editor.opengl::%hit-gizmo-axis state object target-x target-y)
                       "o gizmo de qualquer objeto de cena responde ao eixo visível"))
        (let ((before (gizmo-pose object)))
          (gizmo-drag state object :x :translate)
          (gizmo-check (not (equalp before (gizmo-pose object)))
                       "o gizmo transforma grupos e triângulos")
          (sgeo.editor:undo-edit editor)
          (gizmo-check (equalp before (gizmo-pose object)) "Undo restaura qualquer objeto"))))))

(defun gizmo-check-retired-selection ()
  "Confere que uma edição pública pode aposentar a seleção sem quebrar as vistas."
  (multiple-value-bind (editor object state) (gizmo-context)
    (let* ((mesh (sgeo.scene:mesh-object-geometry object))
           (edge (first (sgeo.geometry:mesh-edges mesh))))
      (sgeo.editor:editor-select editor object (list edge))
      (sgeo.editor:inspect-editor editor (list :element mesh edge))
      (sgeo.geometry:split-edge mesh edge)
      (gizmo-check (not (sgeo.editor.opengl::%live-element-p mesh edge))
                   "a aresta original foi aposentada")
      (sgeo.editor.opengl::%refresh-element-selection state)
      (gizmo-check (null (sgeo.editor:editor-elements editor))
                   "a seleção aposentada é descartada")
      (gizmo-check (eq object (sgeo.editor:editor-inspected editor))
                   "o inspetor retorna ao objeto que continua vivo")
      (gizmo-check (sgeo.geometry:validate-mesh mesh) "a geometria editada continua válida"))))

(defun run-editor-gizmo-checks ()
  "Executa checagens de interação sem iniciar o backend gráfico."
  (let ((failures nil))
    (labels ((run-case (label function)
               (handler-case
                   (progn (funcall function) (format t "GIZMO_CASE_OK ~A~%" label))
                 (error (condition)
                   (push (cons label condition) failures)
                   (format t "GIZMO_CASE_FAILED ~A: ~A~%" label condition)))))
      (dolist (tool-axis '((:translate :x) (:rotate :y) (:scale :z)))
        (run-case (first tool-axis)
                  (lambda () (gizmo-check-operation (first tool-axis) (second tool-axis)))))
      (dolist (tool '(:translate :rotate :scale))
        (run-case (list :cancel-and-zero tool)
                  (lambda () (gizmo-check-cancel-and-zero-drag tool))))
      (run-case :parent-axis #'gizmo-check-parent-axis-direction)
      (run-case :object-types #'gizmo-check-scene-object-types)
      (run-case :retired-selection #'gizmo-check-retired-selection))
    (when failures
      (error "~D verificação(ões) de gizmo falharam." (length failures)))
    (format t "EDITOR_GIZMO_CHECKS_OK translate/rotate/scale, cancelamento, arraste zero e hierarquia~%")
    t))

(handler-case
    (progn (run-editor-gizmo-checks) (uiop:quit 0))
  (error (condition)
    (format *error-output* "Falha nos gizmos do editor: ~A~%" condition)
    (uiop:quit 1)))
