;;;; Editor nativo; geometria, listener e histórico compartilham a mesma imagem.
(load (merge-pathnames "bootstrap.lisp" (or *load-truename* *compile-file-truename*)))
(asdf:load-system :sgeo/editor/opengl)
(asdf:load-system :sgeo/examples)

(defun parse-editor-options (arguments)
  "Interpreta opções simples do lançador sem avaliar formulários externos."
  (let ((frames nil) (visible t) (repl t) (capture nil) (open nil)
        (scene-path "scene.sgeo") (width 1280) (height 800))
    (labels ((argument (option)
               (or (pop arguments) (error "~A exige um argumento." option)))
             (positive-integer (option)
               (let ((value (parse-integer (argument option))))
                 (unless (plusp value) (error "~A exige um inteiro positivo." option)) value)))
      (loop while arguments for option = (pop arguments)
            do (cond ((string= option "--frames") (setf frames (positive-integer option)))
                     ((string= option "--width") (setf width (positive-integer option)))
                     ((string= option "--height") (setf height (positive-integer option)))
                     ((string= option "--hidden") (setf visible nil))
                     ((string= option "--no-repl") (setf repl nil))
                     ((string= option "--capture") (setf capture (argument option)))
                     ((string= option "--open") (setf open (argument option) scene-path open))
                     ((string= option "--scene") (setf scene-path (argument option)))
                     ((string= option "--help")
                      (format t "sbcl --script tools/editor.lisp [--open arquivo.sgeo] [--scene arquivo.sgeo] [--width N] [--height N] [--frames N] [--hidden] [--no-repl] [--capture arquivo.ppm]~%")
                      (uiop:quit 0))
                     (t (error "Opção desconhecida: ~A" option)))))
    (values frames visible repl capture open scene-path width height)))

(handler-case
    (multiple-value-bind (frames visible repl capture open scene-path width height)
        (parse-editor-options (uiop:command-line-arguments))
      (let* ((world (if open (sgeo.serialization:load-world open) (sgeo.examples:make-kernel-world)))
             (editor (sgeo.editor:make-editor :world world :scene-path scene-path)))
        (format t "~&S-Geometry/CL — M3 editor~%")
        (format t "LMB: selecionar | RMB: menu | Alt+LMB: orbitar | MMB: deslocar | roda: zoom | Ctrl+Enter: avaliar listener~%")
        (multiple-value-bind (returned report)
            (sgeo.editor.opengl:run-editor editor :width width :height height
              :max-frames frames :visible visible :repl repl :capture-path capture)
          (declare (ignore returned))
          (format t "~&Editor concluído: ~D quadros, ~D envios de malha à GPU.~%"
                  (sgeo.runtime:runtime-report-frames report) (sgeo.runtime:runtime-report-uploads report))
          (let ((failure (or (sgeo.runtime:runtime-report-platform-error report)
                             (sgeo.runtime:runtime-report-render-error report))))
            (when failure (error failure))))))
  (error (condition)
    (format *error-output* "~&Falha ao executar o editor: ~A~%" condition)
    (uiop:quit 1)))
