;;;; Demonstra M4 na GPU real; falhas deixam a demonstração com código de saída não zero.
(load (merge-pathnames "bootstrap.lisp" (or *load-truename* *compile-file-truename*)))
(asdf:load-system :sgeo/examples/pbr)
(load (merge-pathnames "m4-acceptance-common.lisp" (uiop:pathname-directory-pathname *load-truename*)))

(defun m4-pixels (renderer)
  (copy-seq (sgeo.backend.vulkan::%last-frame-pixels renderer)))

(defun m4-changed-pixels (a b)
  (if (/= (length a) (length b)) (max (length a) (length b))
      (loop for offset from 0 below (length a) by 4
            count (loop for channel from 0 below 3
                        thereis (/= (aref a (+ offset channel)) (aref b (+ offset channel)))))))

(defun run-m4-acceptance ()
  "Verifica trocas reais de pipeline, efeitos visuais, edições e persistência."
  (let* ((world (sgeo.examples.pbr:make-pbr-world))
         (box (sg:find-object world "EditableBox")) (mesh (sg:mesh-object-geometry box))
         (phase :baseline) (requested nil) (installed nil) (baseline nil) (tinted nil)
         (active nil) (installed-binary nil) (uploads nil) (edited nil) (finished nil)
         (transient nil) (gpu-count nil) (retained-program nil)
         (compiler nil) (compile-started (bt:make-semaphore))
         (compile-release (bt:make-semaphore))
         (caster-materials
           (remove-duplicates
            (mapcar (lambda (entry) (getf entry :material))
                    (getf (sgeo.scene:render-snapshot world) :objects)) :test #'eq))
         (scene-path (merge-pathnames "artifacts/m4-acceptance.sgeo" *project-root*))
         (expected-path (merge-pathnames "artifacts/m4-acceptance.expected.lisp" *project-root*)))
    (ensure-directories-exist scene-path)
    (multiple-value-bind (returned renderer report)
        (sgeo.examples.pbr:run-pbr-viewer
         :world world :width 640 :height 420 :visible nil :repl nil :validation t :max-frames 200
         :frame-hook
         (lambda (current window renderer frame)
           (handler-bind ((error (lambda (condition)
                                  (format *error-output* "~&M4 quadro ~D, etapa ~S: ~A~%" frame phase condition)
                                  (bt:signal-semaphore compile-release)
                                  (sgeo.platform:request-window-close window))))
           (m4-check (eq current world) "mesma instância do mundo")
           (m4-check (eq mesh (sg:mesh-object-geometry box)) "mesma malha editável")
           (let* ((info (sgeo.render:renderer-info renderer))
                  (program (sgeo.backend.vulkan::%pbr-program renderer))
                  (generation (sgeo.render:shader-program-generation program))
                  (failure (sgeo.render:shader-program-last-error program)))
             (m4-check (getf info :validation) "camada de validação habilitada")
             (m4-check (null (getf info :validation-messages))
                       (format nil "mensagens de validação Vulkan: ~S" (getf info :validation-messages)))
             (case phase
               (:baseline
                (when (>= frame 1)
                  (setf baseline (m4-pixels renderer))
                  (m4-check (> (length (remove-duplicates baseline)) 32) "imagem PBR contém variação de iluminação")
                  (sgeo.render:capture-frame renderer window (merge-pathnames "artifacts/m4-baseline.ppm" *project-root*))
                  ;; Falha no primeiro UBO após a aquisição: pool parcial e semáforo
                  ;; precisam ser recuperados antes do próximo quadro normal.
                  (let ((original (symbol-function 'sgeo.backend.vulkan:make-buffer)) (failed nil))
                    (unwind-protect
                         (progn
                           (setf (symbol-function 'sgeo.backend.vulkan:make-buffer)
                                 (lambda (&rest arguments)
                                   (declare (ignore arguments))
                                   (error "Falha de UBO simulada.")))
                           (handler-case (sgeo.render:render-frame renderer world 640 420)
                             (error () (setf failed t))))
                      (setf (symbol-function 'sgeo.backend.vulkan:make-buffer) original))
                    (m4-check failed "falha após adquirir imagem exercitada")
                    (m4-check (sgeo.backend.vulkan::%needs-recovery-p renderer)
                              "aquisição interrompida marcada para recuperação")
                    (m4-check (null (sgeo.backend.vulkan::%descriptor-pool renderer))
                              "pool parcial liberado"))
                  (dolist (material caster-materials) (sg:set-pbr-material material :casts-shadow-p nil))
                  (setf phase :without-shadows)))
               (:without-shadows
                (m4-check (not (sgeo.backend.vulkan::%needs-recovery-p renderer)) "sincronização recuperada")
                (m4-check (> (m4-changed-pixels baseline (m4-pixels renderer)) 50)
                          "mapa de sombras altera pixels reais")
                (sgeo.render:capture-frame renderer window (merge-pathnames "artifacts/m4-without-shadows.ppm" *project-root*))
                (dolist (material caster-materials) (sg:set-pbr-material material :casts-shadow-p t))
                (setf phase :restore-shadows))
               (:restore-shadows
                (m4-check (equalp baseline (m4-pixels renderer)) "sombras restauradas produzem a imagem original")
                (setf requested (sgeo.render:reload-renderer-shaders renderer :source (m4-fragment-source :tinted))
                      phase :reload))
               (:reload
                (when (= generation requested)
                  (setf tinted (m4-pixels renderer) active (sgeo.render:shader-program-active program) installed generation)
                  (setf installed-binary (copy-seq (getf (sgeo.render:shader-program-compiled program) :fragment)))
                  (m4-check (> (m4-changed-pixels baseline tinted) 100) "novo shader alterou pixels reais")
                  (sgeo.render:capture-frame renderer window (merge-pathnames "artifacts/m4-tinted.ppm" *project-root*))
                  (setf requested (sgeo.render:reload-renderer-shaders renderer :source (m4-fragment-source :bad-source))
                        phase :bad-source)))
               (:bad-source
                (when failure
                  (m4-check (= generation installed) "falha de compilação preservou geração")
                  (m4-check (eq active (sgeo.render:shader-program-active program)) "falha preservou pipeline GPU")
                  (m4-check (equalp tinted (m4-pixels renderer)) "falha preservou imagem anterior")
                  (setf requested (sgeo.render:reload-renderer-shaders renderer :source (m4-fragment-source :bad-layout))
                        phase :bad-layout)))
               (:bad-layout
                (when (and failure (not (sgeo.render:shader-program-pending-p program)))
                  (m4-check (= generation installed) "falha no construtor preservou geração")
                  (m4-check (eq active (sgeo.render:shader-program-active program)) "construtor preservou pipeline GPU")
                  (setf requested (sgeo.render:reload-renderer-shaders renderer :source (m4-fragment-source :bad-stage))
                        phase :bad-stage)))
               (:bad-stage
                (when (and failure (not (sgeo.render:shader-program-pending-p program)))
                  (m4-check (= generation installed) "shader sem fragmento preservou geração")
                  (m4-check (eq active (sgeo.render:shader-program-active program)) "shader incompleto preservou pipeline GPU")
                  (m4-check (equalp tinted (m4-pixels renderer)) "shader incompleto preservou a imagem")
                  (setf uploads (sgeo.render:renderer-upload-count renderer))
                  (let ((vertex (first (sg:mesh-vertices mesh))))
                    (sg:set-vertex-position mesh vertex (sg:v+ (sg:vertex-position mesh vertex) #(0d0 0.25d0 0d0))))
                  (sg:split-edge mesh (first (sg:mesh-edges mesh)))
                  (let* ((face (first (sg:mesh-faces mesh))) (neighbor (first (sg:face-neighbors mesh face))))
                    (sg:extrude-face-region mesh (list face neighbor) :distance 0.12d0))
                  (sg:set-pbr-material (sg:mesh-object-material box) :metallic 0.7d0 :roughness 0.2d0)
                  (let ((before (copy-seq (sg:render-mesh-positions (sg:compile-render-data mesh))))
                        (revision (sg:object-revision mesh)) (failed nil))
                    (handler-case (sg:extrude-face mesh (first (sg:mesh-faces mesh)) :distance :invalid)
                      (error () (setf failed t)))
                    (m4-check failed "edição inválida rejeitada")
                    (m4-check (= revision (sg:object-revision mesh)) "falha preservou revisão")
                    (m4-check (equalp before (sg:render-mesh-positions (sg:compile-render-data mesh))) "falha preservou vértices"))
                  (m4-check (sg:validate-mesh mesh) "topologia editada válida")
                  (setf phase :geometry)))
               (:geometry
                (when (> (sgeo.render:renderer-upload-count renderer) uploads)
                  (setf edited (m4-pixels renderer))
                  (m4-check (> (m4-changed-pixels tinted edited) 50) "geometria/material alteraram a imagem")
                  (sgeo.render:capture-frame renderer window (merge-pathnames "artifacts/m4-edited.ppm" *project-root*))
                  (setf gpu-count (getf info :gpu-meshes)
                        transient (sg:make-mesh-object (sg:make-half-edge-box :size 0.25d0)
                                                      :name "Transient" :position #(0d0 2d0 0d0)
                                                      :material (sg:make-pbr-material)))
                  (sg:add-to-world world transient)
                  (setf phase :cache-added)))
               (:cache-added
                (when (= (1+ gpu-count) (getf info :gpu-meshes))
                  (sg:remove-from-world world transient)
                  (setf phase :cache-removed)))
               (:cache-removed
                (when (= gpu-count (getf info :gpu-meshes))
                  (m4-check (= installed generation) "remoção de objeto preserva shader")
                  ;; Uma falha no segundo alvo deixa os recursos atuais intactos.
                  (let* ((original (symbol-function 'sgeo.backend.vulkan:make-image))
                         (calls 0) (failed nil)
                         (old-target (sgeo.backend.vulkan::%hdr-image renderer)))
                    (unwind-protect
                         (progn
                           (setf (symbol-function 'sgeo.backend.vulkan:make-image)
                                 (lambda (&rest arguments)
                                   (when (= (incf calls) 2) (error "Falha de alocação simulada."))
                                   (apply original arguments)))
                           (handler-case (sgeo.backend.vulkan::%ensure-render-targets renderer 708 470)
                             (error () (setf failed t))))
                      (setf (symbol-function 'sgeo.backend.vulkan:make-image) original))
                    (m4-check failed "falha parcial dos alvos exercitada")
                    (m4-check (eq old-target (sgeo.backend.vulkan::%hdr-image renderer))
                              "falha de redimensionamento preserva o alvo ativo")
                    (m4-check (equal '(640 420) (getf (sgeo.render:renderer-info renderer) :extent))
                              "falha preserva tamanho ativo"))
                  ;; Segura uma compilação para verificar o resize enquanto ela está pendente.
                  (setf retained-program program compiler (sgeo.render::%program-compiler program)
                        (slot-value program 'sgeo.render::compiler)
                        (lambda (source)
                          (bt:signal-semaphore compile-started)
                          (bt:wait-on-semaphore compile-release)
                          (funcall compiler source))
                        requested (sgeo.render:reload-renderer-shaders renderer :source (m4-fragment-source :tinted)))
                  (bt:wait-on-semaphore compile-started)
                  (glfw:set-window-size 760 480 (sgeo.backend.vulkan:vulkan-window-native window))
                  (setf phase :resize)))
               (:resize
                (when (equal '(760 480) (getf info :extent))
                  (m4-check (= (* 760 480 4) (length (m4-pixels renderer))) "alvos redimensionados")
                  (m4-check (= installed generation) "redimensionamento preserva geração do shader")
                  (m4-check (equalp installed-binary (getf (sgeo.render:shader-program-compiled program) :fragment))
                            "redimensionamento preserva código recompilado")
                  (m4-check (eq retained-program program) "redimensionamento preserva o programa Lisp")
                  (m4-check (sgeo.render:shader-program-pending-p program) "recarga continua pendente após resize")
                  (m4-check (eq active (sgeo.render:shader-program-active program)) "resize preserva pipeline GPU")
                  (setf (slot-value program 'sgeo.render::compiler) compiler phase :resize-reload)
                  (bt:signal-semaphore compile-release)))
               (:resize-reload
                (when (= requested generation)
                  (m4-check (eq retained-program program) "recarga instala no programa retido")
                  (m4-check (not (eq active (sgeo.render:shader-program-active program))) "pipeline pendente substituiu o anterior")
                  (m4-check (null failure) "recarga pendente concluiu sem falha")
                  (sgeo.render:capture-frame renderer window (merge-pathnames "artifacts/m4-resized.ppm" *project-root*))
                  (sgeo.serialization:save-world world scene-path)
                  (m4-write-data expected-path (sgeo.serialization:scene-data world))
                  (setf finished t phase :done)
                  (sgeo.platform:request-window-close window)))
               (:done nil))))))
      (m4-check (eq returned world) "mundo retornado preservado")
      (m4-check (null (sgeo.runtime:runtime-report-platform-error report))
                (format nil "falha de callback: ~A" (sgeo.runtime:runtime-report-platform-error report)))
      (m4-check (null (sgeo.runtime:runtime-report-render-error report))
                (format nil "falha de renderização: ~A" (sgeo.runtime:runtime-report-render-error report)))
      (m4-check finished (format nil "demonstração terminou na etapa ~S" phase))
      (m4-check (zerop (getf (sgeo.render:renderer-info renderer) :gpu-meshes))
                "cache de malhas vazio após encerramento")
      (m4-check (null (getf (sgeo.render:renderer-info renderer) :validation-messages))
                "encerramento sem recursos Vulkan pendentes")
      (format t "M4: ~D quadros, ~D envios; sombras verificadas, shader substituído, três falhas de shader recuperadas, malha editada, cache liberado, falhas de alocação e aquisição recuperadas e janela redimensionada com recarga pendente.~%"
              (sgeo.runtime:runtime-report-frames report) (sgeo.runtime:runtime-report-uploads report)))
    (multiple-value-bind (output error-output status)
        (uiop:run-program (list "sbcl" "--dynamic-space-size" "4096" "--script"
                                (namestring (merge-pathnames "tools/m4-reopen-check.lisp" *project-root*))
                                (namestring scene-path) (namestring expected-path))
                          :output :string :error-output :string :ignore-error-status t)
      (m4-check (zerop status) (format nil "processo novo (~D): ~A~%~A" status output error-output))
      (write-string output))
    t))

(handler-case (run-m4-acceptance)
  (error (condition) (format *error-output* "~&~A~%" condition) (uiop:quit 1)))
