;;;; Reabre a animação em outro processo e verifica suas fontes e sua pose renderizada.
(load (merge-pathnames "bootstrap.lisp" (or *load-truename* *compile-file-truename*)))
(asdf:load-system :sgeo/editor/opengl)
(load (merge-pathnames "m5-acceptance-common.lisp" (uiop:pathname-directory-pathname *load-truename*)))
(handler-case
    (destructuring-bind (scene expected) (uiop:command-line-arguments)
      (let* ((world (sgeo.serialization:load-world scene))
             (reference (m5-read-evidence expected))
             (editor (sgeo.editor:make-editor :world world)))
        (m5-check (m5-close-enough-p reference (m5-world-evidence world)) "fontes, pose, clipes e players reabertos")
        (multiple-value-bind (returned report)
            (sgeo.editor.opengl:run-editor editor :width 1280 :height 800 :visible nil :repl nil :max-frames 3
              :capture-path (merge-pathnames "artifacts/m5-reopened.ppm" *project-root*))
          (declare (ignore returned))
          (m5-check (null (sgeo.runtime:runtime-report-render-error report)) "renderização da cena reaberta")
          (m5-check (null (sgeo.runtime:runtime-report-platform-error report)) "janela da cena reaberta"))
        (let* ((player (first (sg:animation-state-players (sg:world-animation-state world))))
               (before (getf (m5-world-evidence world) :meshes)))
          (setf (sg:player-playing-p player) t)
          (sg:update-world world 0.1d0)
          (m5-check (not (m5-close-enough-p before (getf (m5-world-evidence world) :meshes))) "reprodução retomada na imagem nova"))
        (sgeo.gltf:export-gltf world (merge-pathnames "artifacts/m5-reopened-export.glb" *project-root*) :binary t)
        (format t "~&M5 reopen: fontes e animações comparadas; 3 quadros e reprodução em SBCL novo verificados.~%"))
      (uiop:quit 0))
  (error (condition) (format *error-output* "~&Falha na reabertura M5: ~A~%" condition) (uiop:quit 1)))
