;;;; O laço gráfico permanece na thread principal; o REPL usa a mesma imagem Lisp.
(load (merge-pathnames "bootstrap.lisp" (or *load-truename* *compile-file-truename*)))
(asdf:load-system :sgeo/examples)

(defun parse-launch-options (arguments)
  "Interpreta as opções do lançador sem executar conteúdo fornecido como argumento."
  (let ((triangle nil) (kernel nil) (frames nil) (visible t) (repl t) (capture nil))
    (loop while arguments
          for argument = (pop arguments)
          do (cond
               ((string= argument "--triangle") (setf triangle t))
               ((string= argument "--kernel") (setf kernel t))
               ((string= argument "--hidden") (setf visible nil))
               ((string= argument "--no-repl") (setf repl nil))
               ((string= argument "--frames")
                (unless arguments (error "--frames exige uma quantidade."))
                (setf frames (parse-integer (pop arguments)))
                (unless (plusp frames) (error "--frames precisa ser positivo.")))
               ((string= argument "--capture")
                (unless arguments (error "--capture exige um caminho."))
                (setf capture (pop arguments)))
               ((string= argument "--help")
                (format t "sbcl --script tools/run.lisp [--triangle | --kernel] [--frames N] [--hidden] [--no-repl] [--capture arquivo.ppm]~%")
                (uiop:quit 0))
               (t (error "Opção desconhecida: ~A" argument))))
    (when (and triangle kernel) (error "Escolha --triangle ou --kernel."))
    (values triangle frames visible repl capture kernel)))

(handler-case
    (multiple-value-bind (triangle frames visible repl capture kernel)
        (parse-launch-options (uiop:command-line-arguments))
      (let ((world (cond (triangle (sgeo.examples:make-triangle-world))
                         (kernel (sgeo.examples:make-kernel-world))
                         (t (sgeo.examples:make-live-world)))))
        (format t "~&S-Geometry/CL — ~A~%" (cond (triangle "M0 triangle")
                                                (kernel "M2 geometry kernel")
                                                (t "M1 live scene")))
        (format t "LMB: selecionar | RMB: orbitar | MMB: deslocar | roda: zoom | W: arame | Esc: sair~%")
        (multiple-value-bind (returned renderer report)
            (sg:run world :max-frames frames :visible visible :repl repl :capture-path capture)
          (declare (ignore returned renderer))
          (format t "~&Execução concluída: ~D quadros, ~D envios de malha à GPU.~%"
                  (sg:runtime-report-frames report) (sg:runtime-report-uploads report))
          (let ((failure (or (sg:runtime-report-platform-error report)
                             (sg:runtime-report-render-error report))))
            (when failure (error failure))))))
  (error (condition)
    (format *error-output* "~&Falha ao executar: ~A~%" condition)
    (uiop:quit 1)))
