(in-package #:sgeo.examples.simulation)

(defclass boid (sgeo.scene:mesh-object)
  ((velocity :initarg :velocity :accessor boid-velocity)
   (max-speed :initform 3d0 :accessor boid-max-speed)))
(defclass flock ()
  ((world :initarg :world :reader %flock-world)
   (boids :initarg :boids :reader flock-boids)
   (mode :initarg :mode :reader flock-mode)
   (positions :initarg :positions :reader %flock-positions)
   (velocities :initarg :velocities :reader %flock-velocities)
   (separation :initform 1.6d0 :accessor flock-separation)
   (alignment :initform 0.7d0 :accessor flock-alignment)
   (cohesion :initform 0.35d0 :accessor flock-cohesion)
   (neighbor-radius :initform 2.5d0 :accessor flock-neighbor-radius)))
(defvar *flock* nil)
(defun %flock-point (array index)
  (sgeo.math:make-vec3 (aref array (* index 3)) (aref array (+ (* index 3) 1)) (aref array (+ (* index 3) 2))))
(defun %store-flock-point (array index vector)
  (dotimes (axis 3) (setf (aref array (+ (* index 3) axis)) (aref vector axis))))
(defun %boid-position (object)
  (sgeo.math:transform-point (sgeo.scene:world-transform object) #(0d0 0d0 0d0)))
(defun %limit-velocity (velocity maximum)
  (let ((speed (sgeo.math:vector-length velocity)))
    (if (> speed maximum) (sgeo.math:v* velocity (/ maximum speed)) velocity)))
(defun update-flock (flock dt)
  "Calcula o próximo bando a partir de um snapshot, sem dependência da ordem dos objetos."
  (let* ((boids (flock-boids flock)) (count (length boids))
         (positions (%flock-positions flock)) (velocities (%flock-velocities flock))
         (next (make-array (* count 3) :element-type 'double-float)))
    (when (eq (flock-mode flock) :objects)
      (loop for object across boids for i from 0 do
        (%store-flock-point positions i (%boid-position object))
        (%store-flock-point velocities i (boid-velocity object))))
    (dotimes (i count)
      (let ((p (%flock-point positions i)) (v (%flock-point velocities i))
            (separation (sgeo.math:make-vec3)) (alignment (sgeo.math:make-vec3))
            (center (sgeo.math:make-vec3)) (neighbors 0))
        (dotimes (j count)
          (unless (= i j)
            (let* ((other (%flock-point positions j)) (difference (sgeo.math:v- p other))
                   (distance (sgeo.math:vector-length difference)))
              (when (< distance (flock-neighbor-radius flock))
                (incf neighbors)
                (setf center (sgeo.math:v+ center other)
                      alignment (sgeo.math:v+ alignment (%flock-point velocities j)))
                (when (> distance 1d-6)
                  (setf separation (sgeo.math:v+ separation (sgeo.math:v* difference (/ 1d0 (* distance distance))))))))))
        (let* ((steer (if (plusp neighbors)
                          (sgeo.math:v+ (sgeo.math:v* separation (flock-separation flock))
                            (sgeo.math:v+ (sgeo.math:v* (sgeo.math:v- (sgeo.math:v* alignment (/ 1d0 neighbors)) v)
                                                       (flock-alignment flock))
                                         (sgeo.math:v* (sgeo.math:v- (sgeo.math:v* center (/ 1d0 neighbors)) p)
                                                       (flock-cohesion flock)))) (sgeo.math:make-vec3)))
               (boundary (sgeo.math:v* p -0.12d0))
               (velocity (%limit-velocity (sgeo.math:v+ v (sgeo.math:v* (sgeo.math:v+ steer boundary) dt))
                                          (boid-max-speed (aref boids i)))))
          (%store-flock-point next i velocity))))
    (dotimes (i count)
      (let* ((object (aref boids i)) (velocity (%flock-point next i))
             (position (sgeo.math:v+ (%flock-point positions i) (sgeo.math:v* velocity dt))))
        (%store-flock-point positions i position) (%store-flock-point velocities i velocity)
        (setf (boid-velocity object) velocity)
        (sgeo.scene:set-position object position)
        (sgeo.scene:set-rotation object (sgeo.math:quaternion-from-axis-angle #(0d0 1d0 0d0)
                                           (atan (sgeo.math:vx velocity) (sgeo.math:vz velocity))))))) flock)

(defun make-boids-world (&key (count 48) (mode :objects))
  "Constrói Boids em objetos Lisp ou vetores numéricos empacotados, com a mesma cena."
  (unless (and (integerp count) (<= 1 count 10000) (member mode '(:objects :packed)))
    (error "Quantidade ou modo de Boids inválido."))
  (let* ((world (sgeo.scene:make-world :camera (sgeo.scene:make-camera :eye #(0d0 13d0 13d0) :target #(0d0 0d0 0d0))))
         (geometry (sgeo.geometry:make-triangle-mesh :positions #(-0.13d0 0d0 -0.2d0 0.13d0 0d0 -0.2d0 0d0 0d0 0.3d0)
                                                    :indices #(0 1 2)))
         (material (sgeo.scene:make-material :color #(0.2d0 0.85d0 0.65d0)))
         (boids (make-array count))
         (positions (make-array (* count 3) :element-type 'double-float))
         (velocities (make-array (* count 3) :element-type 'double-float)))
    (dotimes (i count)
      (let* ((angle (* i 2.399963229728653d0)) (radius (* 0.65d0 (sqrt (1+ i))))
             (position (sgeo.math:make-vec3 (* radius (cos angle)) 0d0 (* radius (sin angle))))
             (velocity (sgeo.math:make-vec3 (* 1.5d0 (- (sin angle))) 0d0 (* 1.5d0 (cos angle))))
             (object (make-instance 'boid :name (format nil "Boid ~D" i) :geometry geometry :material material :velocity velocity)))
        (setf (aref boids i) object)
        (sgeo.scene:set-position object position) (sgeo.scene:add-to-world world object)
        (%store-flock-point positions i position) (%store-flock-point velocities i velocity)))
    (let* ((flock (make-instance 'flock :world world :boids boids :mode mode :positions positions :velocities velocities))
           (simulation (sgeo.simulation:attach-simulation world)))
      (sgeo.simulation:add-phase-hook simulation :fixed-update
        (lambda (world state dt) (declare (ignore world state)) (update-flock flock dt)))
      (sgeo.simulation:add-phase-hook simulation :post-update
        (lambda (world state dt) (declare (ignore state dt))
          (sgeo.debug:debug-text world #(-5d0 3d0 -3d0) (format nil "BOIDS ~D ~A" count mode) :height 0.4d0)))
      (setf *flock* flock) (values world flock))))
(defun run-boids (&key (count 48) (mode :objects) (visible t) max-frames capture-path frame-hook repl)
  "Abre o bando e mantém a referência pública para experimentos no REPL."
  (multiple-value-bind (world flock) (make-boids-world :count count :mode mode)
    (declare (ignore flock))
    (uiop:symbol-call :sgeo.runtime :run-world world :title "S-Geometry — Boids" :visible visible :max-frames max-frames
      :capture-path capture-path :frame-hook frame-hook :repl repl)))
