(in-package #:sgeo.platform)

(defmethod set-focus-handler ((window platform-window) function)
  (declare (ignore window function)) nil)
(defmethod window-gamepad-state ((window platform-window)) (declare (ignore window)) nil)

(defmacro with-native-graphics-environment (() &body body)
  "Mascara armadilhas numéricas dos drivers e restaura o ambiente Lisp."
  #+sbcl
  `(let ((saved-modes (sb-int:get-floating-point-modes)))
     (unwind-protect (progn (sb-int:set-floating-point-modes :traps nil) ,@body)
       (apply #'sb-int:set-floating-point-modes saved-modes)))
  #-sbcl `(progn ,@body))

(defmethod make-window (&key (width 1024) (height 768) (title "S-Geometry")
                            (visible t) (backend :opengl))
  (create-platform-window backend :width width :height height :title title :visible visible))

(defmethod create-platform-window (backend &key width height title visible)
  (declare (ignore width height title visible))
  (error 'sgeo.core:platform-error :context "janela"
         :message (format nil "Backend não carregado: ~S." backend)))

(defmethod poll-events ((window platform-window))
  (declare (ignore window))
  (error 'sgeo.core:platform-error :context "eventos"
         :message "Nenhuma implementação de plataforma foi carregada."))

(defmethod window-size ((window platform-window))
  (declare (ignore window))
  (values 0 0))
(defmethod framebuffer-size ((window platform-window))
  (declare (ignore window))
  (values 0 0))
(defmethod window-should-close-p ((window platform-window))
  (declare (ignore window)) t)
(defmethod request-window-close ((window platform-window)) window)
(defmethod swap-buffers ((window platform-window)) window)
(defmethod close-window ((window platform-window)) window)
(defmethod set-window-title ((window platform-window) title)
  (declare (ignore title)) window)
(defmethod set-key-handler ((window platform-window) function)
  (declare (ignore function)) window)
(defmethod set-cursor-handler ((window platform-window) function)
  (declare (ignore function)) window)
(defmethod set-scroll-handler ((window platform-window) function)
  (declare (ignore function)) window)
(defmethod set-mouse-button-handler ((window platform-window) function)
  (declare (ignore function)) window)
(defmethod set-close-handler ((window platform-window) function)
  (declare (ignore function)) window)
(defmethod set-character-handler ((window platform-window) function)
  (declare (ignore function)) window)
(defmethod window-time ((window platform-window))
  (declare (ignore window)) 0d0)
(defmethod window-cursor-position ((window platform-window))
  (declare (ignore window)) (values 0d0 0d0))
